### PR TITLE
Add bash script to create debian package for Carla

### PR DESCRIPTION
**Pull request by himanshugoswami**
#### Description
Added bash script file, which creates Debian packages Carla.

#### Where has this been tested?

  * **Platform(s):** 18.04

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/2506)

### CODE REVIEW

**Comment by marcgpuig** [comment]
Could this be integrated with the Makefile to have the same methodology for all our installation processes?

**Comment by himanshugoswami** [comment]
> Could this be integrated with the Makefile to have the same methodology for all our installation processes regardless of the operating system?

**Comment by himanshugoswami** [comment]
> Well, this script will run only on Ubuntu machines. Maybe we can add a 'make debian' command for Ubuntus only that will call this script.
> 
> > _[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/2506#-:-M1BvomlEMd720rbyd1l:bp9s0y4)_ status: 0 of 1 files reviewed, all discussions resolved (waiting on @fpasch, @germanros1987, and @johannesquast)

There is no need to have "make debian" command. This is just a bash file, and everyone knows how to run it?

**Comment by himanshugoswami** [comment]
> Well, this script will run only on Ubuntu machines. Maybe we can add a 'make debian' command for Ubuntus only that will call this script.
> 
> > _[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/2506#-:-M1BvomlEMd720rbyd1l:bp9s0y4)_ status: 0 of 1 files reviewed, all discussions resolved (waiting on @fpasch, @germanros1987, and @johannesquast)

I have made changes in the file accordingly and tested on Ubuntu 14.04, 16.04, 18.04 and 19.10
It is working as expected. Thanks for the comment.

**Comment by himanshugoswami** [comment]
> Could this be integrated with the Makefile to have the same methodology for all our installation processes regardless of the operating system?

I have made changes in the file accordingly and tested on Ubuntu 14.04, 16.04, 18.04 and 19.10
It is working as expected. Thanks for the comment.

**Pull request merged**
