### PR TITLE
[NO_BUILD] Docker and rendering docs updates

### PR DESCRIPTION
**Pull request by corkyw10**
Docker and Rendering Docs updates

- Rendering documentation specifies that Vulkan is the only graphics API for carla 0.9.12/ue4.26
- Instructions for rendering in off screen mode are divided into >=0.9.12 and <0.9.12.
- Instructions have been added on how to set up the x-server to allow headless rendering in versions <0.9.12 and vulkan
- Instructions for building the official docker image are divided into >=0.9.12 and <0.9.12.
- New page added for how to build unreal and carla in docker for import purposes
- Expanded how to export a package using docker in the "Create standalone" section
- Docker build updated with most recent fork of UE information

Warnings

- I have shared a new dockerfile with @bernatx that gets rid of the x-server set up for the new version of carla, since it comes with offscreen rendering, but this needs to be tested in jenkins

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4407)

### CODE REVIEW

**Review by bernatx — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4407)* status: all files reviewed, 4 unresolved discussions (waiting on @corkyw10)

___
*[Docs/build_docker_unreal.md, line 47 at r2](https://reviewable.io/reviews/carla-simulator/carla/4407#-MfZglso2Mpu6_L5ruUS:-MfZglspBT7k45W2Jz1p:blhds6g) ([raw file](https://github.com/carla-simulator/carla/blob/584f03548125af699a95b86c603de93b1cb5dc32/Docs/build_docker_unreal.md#L47)):*
> ```
> __ue4-docker:__
> _ue4-docker_ is a Python package that contains Dockerfiles and build infrastructure to facilitate the building of Docker images for Unreal Engine 4. You can find more information and documentation [here](https://docs.adamrehn.com/ue4-docker/read-these-first/introduction-to-ue4-docker).
> To install _ue4-docker_, run the following command:
> ```sh
> pip3 install ue4-docker
> ```
> Access to port 9876 is required during the build of the Unreal Engine image. If the host system is running an active firewall that blocks that port, you can run the following command to automatically configure access:
> ```sh
> ue4-docker setup
> ```
> ```

We don't need anymore the ue4-docker, because now we need to use our UE4.26 fork, and that tool does not support that.
What is required is that the user has a **user/password** from Epic account to be able to download the fork. He will need to supply those values when calling the docker later.
___
*[Docs/build_docker_unreal.md, line 73 at r2](https://reviewable.io/reviews/carla-simulator/carla/4407#-MfZhSps98UZaahmtXga:-MfZhSps98UZaahmtXgb:b-afwxa6) ([raw file](https://github.com/carla-simulator/carla/blob/584f03548125af699a95b86c603de93b1cb5dc32/Docs/build_docker_unreal.md#L73)):*
> ```
> __1. Build Unreal Engine.__
> Run the following command to create a Docker image containing a compiled version of Unreal Engine 4.24.3. Change the version if needed:
> ```sh
> cd Util/Docker
> ue4-docker build 4.24.3 --no-engine --no-minimal
> ```
We can remove this step.
___
*[Docs/build_docker_unreal.md, line 78 at r2](https://reviewable.io/reviews/carla-simulator/carla/4407#-MfZhfMh0YYFDYYvKURB:-MfZhfMh0YYFDYYvKURC:bpospxv) ([raw file](https://github.com/carla-simulator/carla/blob/584f03548125af699a95b86c603de93b1cb5dc32/Docs/build_docker_unreal.md#L78)):*
> ```Markdown
> 
> The following command will build an image called `carla-prerequisites` using `Prerequisites.Dockerfile`:
> ```

We can say that here we will install the compiler and tools needed, and then will download the UE4.26 fork and compile it. To download the UE4.26 we need the user to provide with an user/password to access Epic. Those values need to be provided in the command line with the arguments:

* --build-arg EPIC_USER=[user]
* --build-arg EPIC_PASS=[password]

So, for user **John** and pass **1234** the commandline will be like:

```docker build --build-arg EPIC_USER=John --build-arg EPIC_PASS=1234 -t carla-prerequisites -f Prerequisites.Dockerfile .```
___
*[Docs/build_docker_unreal.md, line 103 at r2](https://reviewable.io/reviews/carla-simulator/carla/4407#-MfZizRBBRkXa1iHrk0q:-MfZizRC4Nawoa9861pe:b-mkskid) ([raw file](https://github.com/carla-simulator/carla/blob/584f03548125af699a95b86c603de93b1cb5dc32/Docs/build_docker_unreal.md#L103)):*
> ```
> __4. Clean up intermediate build images.__
> Run the following command to remove intermediate images left over from the Unreal Engine build process:
> ```sh
> ue4-docker clean
> ```
> ```
This step can be removed, we don't use the ue4-docker thing

**Review by corkyw10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4407)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @bernatx)

___
*[Docs/build_docker_unreal.md, line 47 at r2](https://reviewable.io/reviews/carla-simulator/carla/4407#-MfZglso2Mpu6_L5ruUS:-Mfcd1Vd7mQLiIlmaGLu:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/584f03548125af699a95b86c603de93b1cb5dc32/Docs/build_docker_unreal.md#L47)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
> __ue4-docker:__
> _ue4-docker_ is a Python package that contains Dockerfiles and build infrastructure to facilitate the building of Docker images for Unreal Engine 4. You can find more information and documentation [here](https://docs.adamrehn.com/ue4-docker/read-these-first/introduction-to-ue4-docker).
> To install _ue4-docker_, run the following command:
> ```sh
> pip3 install ue4-docker
> ```
> Access to port 9876 is required during the build of the Unreal Engine image. If the host system is running an active firewall that blocks that port, you can run the following command to automatically configure access:
> ```sh
> ue4-docker setup
> ```
> ```

We don't need anymore the ue4-docker, because now we need to use our UE4.26 fork, and that tool does not support that.
What is required is that the user has a **user/password** from Epic account to be able to download the fork. He will need to supply those values when calling the docker later.
</blockquote></details>

Done.
___
*[Docs/build_docker_unreal.md, line 73 at r2](https://reviewable.io/reviews/carla-simulator/carla/4407#-MfZhSps98UZaahmtXga:-Mfcd8E-B0LBY9aanKjX:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/584f03548125af699a95b86c603de93b1cb5dc32/Docs/build_docker_unreal.md#L73)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
> __1. Build Unreal Engine.__
> Run the following command to create a Docker image containing a compiled version of Unreal Engine 4.24.3. Change the version if needed:
> ```sh
> cd Util/Docker
> ue4-docker build 4.24.3 --no-engine --no-minimal
> ```
We can remove this step.
</blockquote></details>

Done.
___
*[Docs/build_docker_unreal.md, line 78 at r2](https://reviewable.io/reviews/carla-simulator/carla/4407#-MfZhfMh0YYFDYYvKURB:-Mfce-xF3Yv1b7v_HV_o:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/584f03548125af699a95b86c603de93b1cb5dc32/Docs/build_docker_unreal.md#L78)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

We can say that here we will install the compiler and tools needed, and then will download the UE4.26 fork and compile it. To download the UE4.26 we need the user to provide with an user/password to access Epic. Those values need to be provided in the command line with the arguments:

* --build-arg EPIC_USER=[user]
* --build-arg EPIC_PASS=[password]

So, for user **John** and pass **1234** the commandline will be like:

```docker build --build-arg EPIC_USER=John --build-arg EPIC_PASS=1234 -t carla-prerequisites -f Prerequisites.Dockerfile .```

</blockquote></details>

Done.
___
*[Docs/build_docker_unreal.md, line 103 at r2](https://reviewable.io/reviews/carla-simulator/carla/4407#-MfZizRBBRkXa1iHrk0q:-Mfcerig88XjEBSplBkZ:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/584f03548125af699a95b86c603de93b1cb5dc32/Docs/build_docker_unreal.md#L103)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
> __4. Clean up intermediate build images.__
> Run the following command to remove intermediate images left over from the Unreal Engine build process:
> ```sh
> ue4-docker clean
> ```
> ```
This step can be removed, we don't use the ue4-docker thing
</blockquote></details>

Done.

**Review by bernatx — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4407)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corkyw10)

**Review by bernatx — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4407)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corkyw10)

**Pull request merged**
