### PR TITLE
sergi-e/update-deb-installation

### PR DESCRIPTION
**Pull request by sergi-e**
#### Description

- Quickstart installation (deb instructions) updated. 
- ROS bridge installation (deb instructions) updated. 

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04.4
  * **Python version(s):** 3.6.9
  * **Unreal Engine version(s):** 4.24

#### Possible Drawbacks

- ROS bridge docs nee d to be revisited.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3241)

### CODE REVIEW

**Review by joel-mb — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3241)* status: 0 of 2 files reviewed, 11 unresolved discussions (waiting on @joel-mb and @sergi-e)

___
*[Docs/ros_installation.md, line 5 at r1](https://reviewable.io/reviews/carla-simulator/carla/3241#-MG7vm890fDWrKF8mFUM:-MG7vm890fDWrKF8mFUN:b-ot8n9v) ([raw file](https://github.com/carla-simulator/carla/blob/be72bd9b5ad3804216bc0dea72ee756b08398bae/Docs/ros_installation.md#L5)):*
> ```
> A. Using deb repository](#a-using-deb-repository)
> ```
Instead of `deb` I would use the whole word `debian`
___
*[Docs/ros_installation.md, line 27 at r1](https://reviewable.io/reviews/carla-simulator/carla/3241#-MG7w0_sDYtRRQW6YeSh:-MG7w0_sDYtRRQW6YeSi:b-ez9wix) ([raw file](https://github.com/carla-simulator/carla/blob/be72bd9b5ad3804216bc0dea72ee756b08398bae/Docs/ros_installation.md#L27)):*
> ```
> Set up the deb repository in the system.
> ```
Same as above. I would say:
Set up the debian repository in your system.
___
*[Docs/ros_installation.md, line 32 at r1](https://reviewable.io/reviews/carla-simulator/carla/3241#-MG7wC3OCX8hf3SiDNLB:-MG7wC3P9SbBwvQbU6Wf:b-usxaxq) ([raw file](https://github.com/carla-simulator/carla/blob/be72bd9b5ad3804216bc0dea72ee756b08398bae/Docs/ros_installation.md#L32)):*
> ```
> Install CARLA and check for the installation in the `/opt/` folder.
> ```
I would remove or rewrite this sentence. Substitute `CARLA` by `ROS bridge`.
___
*[Docs/ros_installation.md, line 34 at r1](https://reviewable.io/reviews/carla-simulator/carla/3241#-MG7wb4oEUJJeXUWM5MW:-MG7wb4oEUJJeXUWM5MX:byiolfg) ([raw file](https://github.com/carla-simulator/carla/blob/be72bd9b5ad3804216bc0dea72ee756b08398bae/Docs/ros_installation.md#L34)):*
> ```
> # Update the repository
> ```
I would say: Update your Debian package index
___
*[Docs/ros_installation.md, line 40 at r1](https://reviewable.io/reviews/carla-simulator/carla/3241#-MG7xAs7EC9GtIMBbNBv:-MG7xAs7EC9GtIMBbNBw:b-kwtzm7) ([raw file](https://github.com/carla-simulator/carla/blob/be72bd9b5ad3804216bc0dea72ee756b08398bae/Docs/ros_installation.md#L40)):*
> ```
> carla-ros-bridge==0.9.10-1
> ```
Only one equal (i.e., `carla-ros-bridge=0.9.10-1`)
___
*[Docs/ros_installation.md, line 40 at r1](https://reviewable.io/reviews/carla-simulator/carla/3241#-MG7xOSc53xL4nA0-RMt:-MG7xOSd6FZG8QJx3_Bm:b-qt6h14) ([raw file](https://github.com/carla-simulator/carla/blob/be72bd9b5ad3804216bc0dea72ee756b08398bae/Docs/ros_installation.md#L40)):*
> ```
> and "-1" to a deb tag, which usually will always be the same
> ```
I would rewrite this sentence in the following way:

and "1" to the debian revision. (skipping the last part of the sentence).
___
*[Docs/start_quickstart.md, line 6 at r1](https://reviewable.io/reviews/carla-simulator/carla/3241#-MG7xitI9F6R2sOd_wgc:-MG7xitI9F6R2sOd_wgd:bkatx2c) ([raw file](https://github.com/carla-simulator/carla/blob/be72bd9b5ad3804216bc0dea72ee756b08398bae/Docs/start_quickstart.md#L6)):*
> ```
> deb CARLA installation
> ```
Same as above. I would use `Debian` instead of just `deb`
___
*[Docs/start_quickstart.md, line 35 at r1](https://reviewable.io/reviews/carla-simulator/carla/3241#-MG7yimY97qibG6cQp79:-MG7yimZ957vS5EOWCku:b-7n03k0) ([raw file](https://github.com/carla-simulator/carla/blob/be72bd9b5ad3804216bc0dea72ee756b08398bae/Docs/start_quickstart.md#L35)):*
> ```
> cd /opt/carla-simulator/bin
> ```
The `bin` folder has been removed. Use instead: `cd /opt/carla-simulator`
___
*[Docs/start_quickstart.md, line 85 at r1](https://reviewable.io/reviews/carla-simulator/carla/3241#-MG7yA5M0uf2ILIIaAGB:-MG7yA5M0uf2ILIIaAGC:b-fkukc3) ([raw file](https://github.com/carla-simulator/carla/blob/be72bd9b5ad3804216bc0dea72ee756b08398bae/Docs/start_quickstart.md#L85)):*
> ```
> # Update the repository
> ```
Same as above. I would say: Update your Debian package index
___
*[Docs/start_quickstart.md, line 92 at r1](https://reviewable.io/reviews/carla-simulator/carla/3241#-MG7yP1y3V5VNyKa7mqf:-MG7yP1y3V5VNyKa7mqg:be1a61c) ([raw file](https://github.com/carla-simulator/carla/blob/be72bd9b5ad3804216bc0dea72ee756b08398bae/Docs/start_quickstart.md#L92)):*
> ```
> carla-simulator==0.9.10-1
> ```
Only one equal (i.e., `carla-simulator=0.9.10-1`
___
*[Docs/start_quickstart.md, line 92 at r1](https://reviewable.io/reviews/carla-simulator/carla/3241#-MG7yVkq8ZBzyzAb4sKa:-MG7yVkq8ZBzyzAb4sKb:b-juimzv) ([raw file](https://github.com/carla-simulator/carla/blob/be72bd9b5ad3804216bc0dea72ee756b08398bae/Docs/start_quickstart.md#L92)):*
> ```
> and "-1" to a deb tag, which usually will always be the same.··
> ```
Same as above.

**Review by sergi-e — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3241)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @joel-mb and @sergi-e)

___
*[Docs/ros_installation.md, line 5 at r1](https://reviewable.io/reviews/carla-simulator/carla/3241#-MG7vm890fDWrKF8mFUM:-MGD2oBKBp40CSXmucm-:b-896fja) ([raw file](https://github.com/carla-simulator/carla/blob/be72bd9b5ad3804216bc0dea72ee756b08398bae/Docs/ros_installation.md#L5)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> A. Using deb repository](#a-using-deb-repository)
> ```
Instead of `deb` I would use the whole word `debian`
</blockquote></details>

Done!
___
*[Docs/ros_installation.md, line 27 at r1](https://reviewable.io/reviews/carla-simulator/carla/3241#-MG7w0_sDYtRRQW6YeSh:-MGD2qEq38n8uhL0ZZW4:b-896fja) ([raw file](https://github.com/carla-simulator/carla/blob/be72bd9b5ad3804216bc0dea72ee756b08398bae/Docs/ros_installation.md#L27)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> Set up the deb repository in the system.
> ```
Same as above. I would say:
Set up the debian repository in your system.
</blockquote></details>

Done!
___
*[Docs/ros_installation.md, line 32 at r1](https://reviewable.io/reviews/carla-simulator/carla/3241#-MG7wC3OCX8hf3SiDNLB:-MGD3CUj9MRnh3KQhp-Y:b-kt4686) ([raw file](https://github.com/carla-simulator/carla/blob/be72bd9b5ad3804216bc0dea72ee756b08398bae/Docs/ros_installation.md#L32)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> Install CARLA and check for the installation in the `/opt/` folder.
> ```
I would remove or rewrite this sentence. Substitute `CARLA` by `ROS bridge`.
</blockquote></details>

Keeping it at least for now. 
___
*[Docs/ros_installation.md, line 40 at r1](https://reviewable.io/reviews/carla-simulator/carla/3241#-MG7xAs7EC9GtIMBbNBv:-MGD3wtV1L8alt2POB6Q:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/be72bd9b5ad3804216bc0dea72ee756b08398bae/Docs/ros_installation.md#L40)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> carla-ros-bridge==0.9.10-1
> ```
Only one equal (i.e., `carla-ros-bridge=0.9.10-1`)
</blockquote></details>

Done.
___
*[Docs/start_quickstart.md, line 35 at r1](https://reviewable.io/reviews/carla-simulator/carla/3241#-MG7yimY97qibG6cQp79:-MGD4p0g8bR_Ck-s74d4:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/be72bd9b5ad3804216bc0dea72ee756b08398bae/Docs/start_quickstart.md#L35)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> cd /opt/carla-simulator/bin
> ```
The `bin` folder has been removed. Use instead: `cd /opt/carla-simulator`
</blockquote></details>

Done.
___
*[Docs/start_quickstart.md, line 92 at r1](https://reviewable.io/reviews/carla-simulator/carla/3241#-MG7yP1y3V5VNyKa7mqf:-MGD54946-bNsZoGQ2uf:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/be72bd9b5ad3804216bc0dea72ee756b08398bae/Docs/start_quickstart.md#L92)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> carla-simulator==0.9.10-1
> ```
Only one equal (i.e., `carla-simulator=0.9.10-1`
</blockquote></details>

Done.

**Review by joel-mb — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3241)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @sergi-e)

___
*[Docs/start_quickstart.md, line 35 at r1](https://reviewable.io/reviews/carla-simulator/carla/3241#-MG7yimY97qibG6cQp79:-MGIgaBXCFUu1iajUs4W:b-t8xfvu) ([raw file](https://github.com/carla-simulator/carla/blob/be72bd9b5ad3804216bc0dea72ee756b08398bae/Docs/start_quickstart.md#L35)):*
<details><summary><i>Previously, sergi-e (sergi.e) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not updated! ;)

**Review by joel-mb — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3241)* status: all files reviewed, 3 unresolved discussions (waiting on @sergi-e)

___
*[Docs/ros_installation.md, line 76 at r2](https://reviewable.io/reviews/carla-simulator/carla/3241#-MGIkoc_-fGdlWKxRV50:-MGIkoc_-fGdlWKxRV51:b-co01ka) ([raw file](https://github.com/carla-simulator/carla/blob/443e70a427640ebfc6a059e6f1cdf5f9b2c55ec1/Docs/ros_installation.md#L76)):*
> ```
> apt installation
> ```
Use `Debian installation` instead
___
*[Docs/ros_installation.md, line 76 at r2](https://reviewable.io/reviews/carla-simulator/carla/3241#-MGIksQI-BjUFg5KpMr_:-MGIksQI-BjUFg5KpMra:bdte4qs) ([raw file](https://github.com/carla-simulator/carla/blob/443e70a427640ebfc6a059e6f1cdf5f9b2c55ec1/Docs/ros_installation.md#L76)):*
> ```
> opt/carla/bin/
> ```
This should be `/opt/carla-simulator`

**Review by sergi-e — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3241)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @joel-mb)

___
*[Docs/ros_installation.md, line 76 at r2](https://reviewable.io/reviews/carla-simulator/carla/3241#-MGIkoc_-fGdlWKxRV50:-MGcCjo6C6Y1SUsmXYHY:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/443e70a427640ebfc6a059e6f1cdf5f9b2c55ec1/Docs/ros_installation.md#L76)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> apt installation
> ```
Use `Debian installation` instead
</blockquote></details>

Done.
___
*[Docs/ros_installation.md, line 76 at r2](https://reviewable.io/reviews/carla-simulator/carla/3241#-MGIksQI-BjUFg5KpMr_:-MGcCq9Y6KbXyp1T6SzL:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/443e70a427640ebfc6a059e6f1cdf5f9b2c55ec1/Docs/ros_installation.md#L76)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> opt/carla/bin/
> ```
This should be `/opt/carla-simulator`
</blockquote></details>

Done.
___
*[Docs/start_quickstart.md, line 35 at r1](https://reviewable.io/reviews/carla-simulator/carla/3241#-MG7yimY97qibG6cQp79:-MGcBxFR0RRtCrta1vA8:b-z8cs29) ([raw file](https://github.com/carla-simulator/carla/blob/be72bd9b5ad3804216bc0dea72ee756b08398bae/Docs/start_quickstart.md#L35)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

Not updated! ;)
</blockquote></details>

Touché

**Review by joel-mb — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3241)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
