### PR TITLE
Level change in runtime

### PR DESCRIPTION
**Pull request by juaxix**
This pull request is just to be able to change the current map to another (should exist in the list of maps), 

Checklist:

  - [x] Pass @felipecode tests 
  - [x] Changes in the settings files and python files to be able to load maps
  - [x] Code compiles correctly

#### Description
Related to #65 and #358 
Child of #438
Requires #445

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/482)

### CODE REVIEW

**Comment by nsubiron** [comment]
Includes some changes from the spectator branch, it crashes when pressing E

---

Review status: 0 of 25 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/482#-:-LEPtSdq5toLwz5w_Egd:b-5jj6n7)*

**Comment by juaxix** [comment]
Oh, it needs the last changes from carla spectator :dagger: 

---

Review status: 0 of 25 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/482#-:-LEQkD0y7ENVdGEo9Byj:b56c1xa)*

**Comment by juaxix** [comment]
this is the reason why it crashes, an assertion in C++ that expected the default spectator of the game mode to be CarlaSpectator subclass. It is fixed in the latest change of the carla_spectator branch that i'm mergind now.  

---

Review status: 0 of 25 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/482#-:-LETEBx9-niFr25mHJY0:bskre16)*

**Comment by felipecode** [comment]
Another failure I found. When changing city after a bit of time, four episodes, 2 on 
each map.
I have the following error : 
[2018.06.16-14.53.42:497][ 91]LogCarla: Error: The map in CarlaSettings is not the current one: Town02 !

**Pull request closed without merging**
