### PR TITLE
Corkyw10/traffic sim gateway

### PR DESCRIPTION
**Pull request by corkyw10**
#### Description

I have added an overview of the options available to CARLA users to simulate traffic. 

There are four sections:
- Scenario Runner and OpenSCENARIO
- Traffic Manager
- Scenic
- SUMO

Each section explains briefly what each feature is and what the main useful points are along with a link to the relevant docs

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4023)

### CODE REVIEW

**Review by jackbart94 — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4023)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @glopezdiest and @joel-mb)

**Review by glopezdiest — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4023)* status: all files reviewed, 2 unresolved discussions (waiting on @corkyw10 and @joel-mb)

___
*[Docs/ts_traffic_simulation_overview.md, line 16 at r1](https://reviewable.io/reviews/carla-simulator/carla/4023#-MWdWOE73wgr47NrMRqd:-MWdWOE73wgr47NrMRqe:b-2answx) ([raw file](https://github.com/carla-simulator/carla/blob/492a618ce1a1f89ee1812c08b7b6c64a250db6b4/Docs/ts_traffic_simulation_overview.md#L16)):*
> ```
> maneuver
> ```
include Maneuvers, Actions ...
___
*[Docs/ts_traffic_simulation_overview.md, line 18 at r1](https://reviewable.io/reviews/carla-simulator/carla/4023#-MWdWSQV4uUMfN-2RYac:-MWdWSQV4uUMfN-2RYad:b-dmgb0n) ([raw file](https://github.com/carla-simulator/carla/blob/492a618ce1a1f89ee1812c08b7b6c64a250db6b4/Docs/ts_traffic_simulation_overview.md#L18)):*
> ```
>  needs to be installed
> ```
maybe use `has to be installed`, instead of `needs to be installed`

**Review by corkyw10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4023)* status: all files reviewed, 2 unresolved discussions (waiting on @glopezdiest and @joel-mb)

___
*[Docs/ts_traffic_simulation_overview.md, line 16 at r1](https://reviewable.io/reviews/carla-simulator/carla/4023#-MWdWOE73wgr47NrMRqd:-MWdcUkZ3fLa6O1foD7K:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/492a618ce1a1f89ee1812c08b7b6c64a250db6b4/Docs/ts_traffic_simulation_overview.md#L16)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> maneuver
> ```
include Maneuvers, Actions ...
</blockquote></details>

Done.
___
*[Docs/ts_traffic_simulation_overview.md, line 18 at r1](https://reviewable.io/reviews/carla-simulator/carla/4023#-MWdWSQV4uUMfN-2RYac:-MWdcV-p-qXGZRVevMuU:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/492a618ce1a1f89ee1812c08b7b6c64a250db6b4/Docs/ts_traffic_simulation_overview.md#L18)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
>  needs to be installed
> ```
maybe use `has to be installed`, instead of `needs to be installed`
</blockquote></details>

Done.

**Review by glopezdiest — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4023)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @jackbart94 and @joel-mb)

**Review by joel-mb — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4023)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corkyw10)

**Pull request merged**
