### PR TITLE
Changing the resolution of the cached map in Traffic Manager

### PR DESCRIPTION
**Pull request by jackbart94**
#### Description

Changing the resolution of the cached map from 0.1 to 5 in Traffic Manager, and other values for stages that needed to work with this. This will improve the performance of Traffic Manager and its usage of the Waypoint API.

#### Where has this been tested?

  * **Platform(s):**  Ubuntu 18
  * **Python version(s):** Python 3.7
  * **Unreal Engine version(s):** 4.26 

#### Possible Drawbacks

Needs to be heavily tested to make sure it's as stable as the 0.1 map.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4169)

### CODE REVIEW

**Review by bernatx — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4169)* status: all files reviewed, 1 unresolved discussion (waiting on @glopezdiest, @jackbart94, and @joel-mb)

___
*[LibCarla/source/carla/trafficmanager/CollisionStage.cpp, line 350 at r1](https://reviewable.io/reviews/carla-simulator/carla/4169#-MZlS88K5G16T-DgxjlZ:-MZlS88K5G16T-Dgxjl_:b-picqv) ([raw file](https://github.com/carla-simulator/carla/blob/8e9cd0fd859daf024f660cd8877b115346ce533e/LibCarla/source/carla/trafficmanager/CollisionStage.cpp#L350)):*
> ```cpp
> 
>     // Conditions for collision negotiation.
>     bool geodesic_path_bbox_touching = geometry_comparison.inter_geodesic_distance < OVERLAP_THERESHOLD;
> ```

Which is the intended name: Thereshold or Threshold ? :)

**Review by jackbart94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4169)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @bernatx, @glopezdiest, and @joel-mb)

___
*[LibCarla/source/carla/trafficmanager/CollisionStage.cpp, line 350 at r1](https://reviewable.io/reviews/carla-simulator/carla/4169#-MZlS88K5G16T-DgxjlZ:-MZlTQXq39IWj1W57t6X:b-622n1d) ([raw file](https://github.com/carla-simulator/carla/blob/8e9cd0fd859daf024f660cd8877b115346ce533e/LibCarla/source/carla/trafficmanager/CollisionStage.cpp#L350)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

Which is the intended name: Thereshold or Threshold ? :)
</blockquote></details>

My bad! Fixed

**Review by glopezdiest — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4169)* status: 1 of 11 files reviewed, 2 unresolved discussions (waiting on @bernatx, @jackbart94, and @joel-mb)

___
*[LibCarla/source/carla/trafficmanager/InMemoryMap.cpp, line 164 at r2](https://reviewable.io/reviews/carla-simulator/carla/4169#-M_fcP0L8rFa2QqtFbah:-M_fcP0L8rFa2QqtFbai:bjwlhe0) ([raw file](https://github.com/carla-simulator/carla/blob/04b5da3529996b5fc6ccc0217d172cb0a5b5963f/LibCarla/source/carla/trafficmanager/InMemoryMap.cpp#L164)):*
> ```
> 0.12f
> ```
Make it a constant

**Review by jackbart94 — COMMENTED** [review]
> Dismissed @bernatx from a discussion.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4169)* status: 1 of 14 files reviewed, 2 unresolved discussions (waiting on @bernatx, @glopezdiest, and @joel-mb)

**Review by jackbart94 — COMMENTED** [review]
> Dismissed @glopezdiest from a discussion.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4169)* status: 1 of 14 files reviewed, all discussions resolved (waiting on @bernatx and @joel-mb)

**Review by joel-mb — APPROVED** [review]
> Reviewed 8 of 10 files at r2, 5 of 5 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4169)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jackbart94)

**Review by glopezdiest — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 8 of 10 files at r2, 5 of 5 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4169)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jackbart94)

**Pull request merged**
