### PR TITLE
Fix rss sensor

### PR DESCRIPTION
**Pull request by berndgassmann**
#### Description

Fixes #  

#### Where has this been tested?

  * **Platform(s):** Ubunut 18.04
  * **Python version(s):** 2.7 and 3.6
  * **Unreal Engine version(s):** ...

#### Possible Drawbacks

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3388)

### CODE REVIEW

**Review by fpasch — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3388)* status: all files reviewed, 2 unresolved discussions (waiting on @bernatx, @berndgassmann, and @sergi-e)

___
*[CHANGELOG.md, line 7 at r1](https://reviewable.io/reviews/carla-simulator/carla/3388#-MIrilu_4WZnp3N8glqL:-MIrilu_4WZnp3N8glqM:b-jfttza) ([raw file](https://github.com/carla-simulator/carla/blob/3969cedc3c91f964cff0ab6d7717e4d8701b8787/CHANGELOG.md#L7)):*
> ```Markdown
>   * Added support in Traffic Manager for dead-end roads
>   * Upgraded CARLA Docker image to Ubuntu 18.04
>   * Upgraded to AD RSS v4.2.0 supporting unstructured scenes and pedestrians, and fixed spdlog to v1.7.0
> ```

as 0.9.10 was released, I doubt, that you should change it here.
___
*[Util/BuildTools/BuildLibCarla.sh, line 132 at r1](https://reviewable.io/reviews/carla-simulator/carla/3388#-MIrjUOp7sTQe0ZvMLPK:-MIrjUOp7sTQe0ZvMLPL:b2dx2xk) ([raw file](https://github.com/carla-simulator/carla/blob/3969cedc3c91f964cff0ab6d7717e4d8701b8787/Util/BuildTools/BuildLibCarla.sh#L132)):*
> ```
> ad-rss-4.2.0
> ```
can be get rid of the version here? Someone could forget it next time.

**Review by berndgassmann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3388)* status: all files reviewed, 2 unresolved discussions (waiting on @bernatx, @fpasch, and @sergi-e)

___
*[CHANGELOG.md, line 7 at r1](https://reviewable.io/reviews/carla-simulator/carla/3388#-MIrilu_4WZnp3N8glqL:-MIsIDWl2uzoKgFdPSCw:b-e3hfu2) ([raw file](https://github.com/carla-simulator/carla/blob/3969cedc3c91f964cff0ab6d7717e4d8701b8787/CHANGELOG.md#L7)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

as 0.9.10 was released, I doubt, that you should change it here.
</blockquote></details>

As I don't see changelog entries for sub-releases, I don't know where else to place. But you are right. Starting a a latest changes section that becomes then at some point in time 0.9.10.2 might be an option. How should I proceed?
___
*[Util/BuildTools/BuildLibCarla.sh, line 132 at r1](https://reviewable.io/reviews/carla-simulator/carla/3388#-MIrjUOp7sTQe0ZvMLPK:-MIsJ2gj6F8tvEAt9Op4:b-vjignh) ([raw file](https://github.com/carla-simulator/carla/blob/3969cedc3c91f964cff0ab6d7717e4d8701b8787/Util/BuildTools/BuildLibCarla.sh#L132)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

> ```
> ad-rss-4.2.0
> ```
can be get rid of the version here? Someone could forget it next time.
</blockquote></details>

I believe this cannot be forgotten, otherwise it won't compile. As the other dependencies under the Build folder are checked out in folders with their actual version, I thought it makes sense to keep this format also for ad-rss. For sure one could omit the version number; but in the end it doesn't change that often.

**Review by bernatx — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3388)* status: all files reviewed, 2 unresolved discussions (waiting on @fpasch and @sergi-e)

___
*[CHANGELOG.md, line 7 at r1](https://reviewable.io/reviews/carla-simulator/carla/3388#-MIrilu_4WZnp3N8glqL:-MItIhR_5kEWejQiy_29:b9n9poo) ([raw file](https://github.com/carla-simulator/carla/blob/3969cedc3c91f964cff0ab6d7717e4d8701b8787/CHANGELOG.md#L7)):*
<details><summary><i>Previously, berndgassmann wrote…</i></summary><blockquote>

As I don't see changelog entries for sub-releases, I don't know where else to place. But you are right. Starting a a latest changes section that becomes then at some point in time 0.9.10.2 might be an option. How should I proceed?
</blockquote></details>

Usually we add at the beginning of the changelod.md file a section called **## Latest** that is the one that will go as a new release. As we have released a few days ago, we don't have it yet. You can create it. Something like:
```
## Latest
   * Upgraded to AD RSS v4.2.0 supporting unstructured scenes and pedestrians, and fixed spdlog to v1.7.0
```

**Review by berndgassmann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3388)* status: 14 of 16 files reviewed, 2 unresolved discussions (waiting on @fpasch and @sergi-e)

___
*[CHANGELOG.md, line 7 at r1](https://reviewable.io/reviews/carla-simulator/carla/3388#-MIrilu_4WZnp3N8glqL:-MIwh-OQ-TbneylEpdAo:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/3969cedc3c91f964cff0ab6d7717e4d8701b8787/CHANGELOG.md#L7)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

Usually we add at the beginning of the changelod.md file a section called **## Latest** that is the one that will go as a new release. As we have released a few days ago, we don't have it yet. You can create it. Something like:
```
## Latest
   * Upgraded to AD RSS v4.2.0 supporting unstructured scenes and pedestrians, and fixed spdlog to v1.7.0
```
</blockquote></details>

Done.
___
*[Util/BuildTools/BuildLibCarla.sh, line 132 at r1](https://reviewable.io/reviews/carla-simulator/carla/3388#-MIrjUOp7sTQe0ZvMLPK:-MIwhDoV51bHDATta75v:bg2ab0t) ([raw file](https://github.com/carla-simulator/carla/blob/3969cedc3c91f964cff0ab6d7717e4d8701b8787/Util/BuildTools/BuildLibCarla.sh#L132)):*
<details><summary><i>Previously, berndgassmann wrote…</i></summary><blockquote>

I believe this cannot be forgotten, otherwise it won't compile. As the other dependencies under the Build folder are checked out in folders with their actual version, I thought it makes sense to keep this format also for ad-rss. For sure one could omit the version number; but in the end it doesn't change that often.
</blockquote></details>

But you're right, I've updated the Ad-rss.sh to ensure that the actual version number of the folder in the script file is only present once. Folder name and tag name to be checked out use the same variable. Like this the change to forget something goes down to zero.

**Review by bernatx — DISMISSED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3388)* status: all files reviewed, 2 unresolved discussions (waiting on @fpasch and @sergi-e)

**Review by fpasch — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3388)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sergi-e)

**Review by bernatx — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3388)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sergi-e)

**Review by fpasch — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3388)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sergi-e)

**Review by fpasch — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3388)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sergi-e)

**Review by berndgassmann — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3388)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sergi-e)

**Review by bernatx — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3388)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sergi-e)

**Pull request merged**
