### PR TITLE
Added wheel control

### PR DESCRIPTION
**Pull request by algababr**
#### Description

Added two new functions to the PythonAPI in order to change the direction (or rotation) of a vehicle wheel by using an index and also get the steer angle of any wheel of the vehicle.

Fixes # 

#### Where has this been tested?

  * **Platform(s):**  Windows
  * **Python version(s):** 3.7
  * **Unreal Engine version(s):** 4.24

#### Possible Drawbacks

When the user asks for the steer angle of any vehicle wheel, it returns the steer angle calculated by the PhysX engine.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3868)

### CODE REVIEW

**Review by doterop — CHANGES_REQUESTED** [review]
> Reviewed 6 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3868)* status: 6 of 13 files reviewed, 11 unresolved discussions (waiting on @algababr)

___
*[LibCarla/source/carla/client/Vehicle.cpp, line 62 at r1](https://reviewable.io/reviews/carla-simulator/carla/3868#-MTgyngd6VqGoO-KDy55:-MTgyngd6VqGoO-KDy56:b-qhvecs) ([raw file](https://github.com/carla-simulator/carla/blob/e59e80b43281c2157b041691634915499009cc8c/LibCarla/source/carla/client/Vehicle.cpp#L62)):*
> ```
> g){
> ```
Minor notation just to keep the same convention.
Add a space between the `)` and the `{`
___
*[LibCarla/source/carla/client/Vehicle.cpp, line 68 at r1](https://reviewable.io/reviews/carla-simulator/carla/3868#-MTgz1Bm5dh3m3WhKFG-:-MTgz1Bm5dh3m3WhKFG0:bo4olnb) ([raw file](https://github.com/carla-simulator/carla/blob/e59e80b43281c2157b041691634915499009cc8c/LibCarla/source/carla/client/Vehicle.cpp#L68)):*
> ```
> ){
> ```
Same
___
*[LibCarla/source/carla/client/detail/Simulator.h, line 449 at r1](https://reviewable.io/reviews/carla-simulator/carla/3868#-MTgzEsg3VUEoNbVfnD3:-MTgzEsg3VUEoNbVfnD4:b-xasmq3) ([raw file](https://github.com/carla-simulator/carla/blob/e59e80b43281c2157b041691634915499009cc8c/LibCarla/source/carla/client/detail/Simulator.h#L449)):*
> ```
> ){
> ```
Space
___
*[LibCarla/source/carla/client/detail/Simulator.h, line 454 at r1](https://reviewable.io/reviews/carla-simulator/carla/3868#-MTgzGQI4XGz629ENX63:-MTgzGQI4XGz629ENX64:b-xasmq3) ([raw file](https://github.com/carla-simulator/carla/blob/e59e80b43281c2157b041691634915499009cc8c/LibCarla/source/carla/client/detail/Simulator.h#L454)):*
> ```
> ){
> ```
Space
___
*[PythonAPI/carla/source/libcarla/Actor.cpp, line 136 at r1](https://reviewable.io/reviews/carla-simulator/carla/3868#-MTh6rw_6WgpbYjCsYBr:-MTh6rw_6WgpbYjCsYBs:bv9fipc) ([raw file](https://github.com/carla-simulator/carla/blob/e59e80b43281c2157b041691634915499009cc8c/PythonAPI/carla/source/libcarla/Actor.cpp#L136)):*
> ```
>       .def("set_wheel_steer_direction", &cc::Vehicle::SetWheelSteerDirection, (arg("wheel_location")), (arg("angle_in_deg")))
>       .def("get_wheel_steer_angle", &cc::Vehicle::GetWheelSteerAngle, (arg("wheel_location")))
> ```
I think it would be better to include the enum of the wheel location here too
___
*[PythonAPI/examples/tutorial.py, line 39 at r1](https://reviewable.io/reviews/carla-simulator/carla/3868#-MTgzedxAIodIECACov8:-MTgzedxAIodIECACov9:b8vqzu6) ([raw file](https://github.com/carla-simulator/carla/blob/e59e80b43281c2157b041691634915499009cc8c/PythonAPI/examples/tutorial.py#L39)):*
> ```Python
>         # requests in the localhost at port 2000.
>         client = carla.Client('localhost', 2000)
>         client.set_timeout(5.0)
> ```

Remove this file from the PR
___
*[Unreal/CarlaUE4/CarlaUE4.uproject, line 3 at r1](https://reviewable.io/reviews/carla-simulator/carla/3868#-MTgzVTV5iWVz5wyU_L9:-MTgzVTV5iWVz5wyU_LA:b8vqzu6) ([raw file](https://github.com/carla-simulator/carla/blob/e59e80b43281c2157b041691634915499009cc8c/Unreal/CarlaUE4/CarlaUE4.uproject#L3)):*
> ```
> {
> 	"FileVersion": 3,
> 	"EngineAssociation": "{AFEA611D-4870-D6FA-3535-97AE4FF017A2}",
> ```

Remove this file from the PR
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/EnvironmentObject.h, line 8 at r1](https://reviewable.io/reviews/carla-simulator/carla/3868#-MTgzyVf7Gch4T6vjYnc:-MTgzyVgC53Mty5UNK7F:b-xouxpc) ([raw file](https://github.com/carla-simulator/carla/blob/e59e80b43281c2157b041691634915499009cc8c/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/EnvironmentObject.h#L8)):*
> ```objc
> #pragma once
> 
> #include "Carla/Util/BoundingBox.h"
> ```

Why did you need this include here?
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.h, line 276 at r1](https://reviewable.io/reviews/carla-simulator/carla/3868#-MTh26bl7V3aZQLJbbKC:-MTh26bl7V3aZQLJbbKD:bmxtoa2) ([raw file](https://github.com/carla-simulator/carla/blob/e59e80b43281c2157b041691634915499009cc8c/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.h#L276)):*
> ```
> /// An enum could be used, but this is something situational. An uint8 does the trick just fine
> ```
I think you can remove this comment
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp, line 460 at r1](https://reviewable.io/reviews/carla-simulator/carla/3868#-MTh3BuP3WZirSZiCmNA:-MTh3BuP3WZirSZiCmNB:b1tli4n) ([raw file](https://github.com/carla-simulator/carla/blob/e59e80b43281c2157b041691634915499009cc8c/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp#L460)):*
> ```
> this->
> ```
Can be removed
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp, line 468 at r1](https://reviewable.io/reviews/carla-simulator/carla/3868#-MTh3VUR1n0cIVWrZRGm:-MTh3VUS67COV7XcnVVH:b1tli4n) ([raw file](https://github.com/carla-simulator/carla/blob/e59e80b43281c2157b041691634915499009cc8c/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp#L468)):*
> ```
> this->
> ```
Can be removed

**Comment by algababr** [comment]
The include in EnvironmentObject.h was used because it was giving compile errors, not recognizing a certain class (FBoundingBox). I removed tutorial.py and the .uproject files from the commit.

**Review by algababr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3868)* status: 0 of 14 files reviewed, 10 unresolved discussions (waiting on @algababr and @doterop)

___
*[LibCarla/source/carla/client/Vehicle.cpp, line 62 at r1](https://reviewable.io/reviews/carla-simulator/carla/3868#-MTgyngd6VqGoO-KDy55:-MUyKLml7wFhWItzStFc:bb6un1j) ([raw file](https://github.com/carla-simulator/carla/blob/e59e80b43281c2157b041691634915499009cc8c/LibCarla/source/carla/client/Vehicle.cpp#L62)):*
<details><summary><i>Previously, doterop wrote…</i></summary><blockquote>

> ```
> g){
> ```
Minor notation just to keep the same convention.
Add a space between the `)` and the `{`
</blockquote></details>

Done
___
*[LibCarla/source/carla/client/Vehicle.cpp, line 68 at r1](https://reviewable.io/reviews/carla-simulator/carla/3868#-MTgz1Bm5dh3m3WhKFG-:-MUyKL3mBIKnpx8plmJ6:bb6un1j) ([raw file](https://github.com/carla-simulator/carla/blob/e59e80b43281c2157b041691634915499009cc8c/LibCarla/source/carla/client/Vehicle.cpp#L68)):*
<details><summary><i>Previously, doterop wrote…</i></summary><blockquote>

> ```
> ){
> ```
Same
</blockquote></details>

Done
___
*[LibCarla/source/carla/client/detail/Simulator.h, line 449 at r1](https://reviewable.io/reviews/carla-simulator/carla/3868#-MTgzEsg3VUEoNbVfnD3:-MUyKJL0Dr9MY1FPJzEh:bb6un1j) ([raw file](https://github.com/carla-simulator/carla/blob/e59e80b43281c2157b041691634915499009cc8c/LibCarla/source/carla/client/detail/Simulator.h#L449)):*
<details><summary><i>Previously, doterop wrote…</i></summary><blockquote>

> ```
> ){
> ```
Space
</blockquote></details>

Done
___
*[LibCarla/source/carla/client/detail/Simulator.h, line 454 at r1](https://reviewable.io/reviews/carla-simulator/carla/3868#-MTgzGQI4XGz629ENX63:-MUyKIg3B2vFA-wfyrQz:bb6un1j) ([raw file](https://github.com/carla-simulator/carla/blob/e59e80b43281c2157b041691634915499009cc8c/LibCarla/source/carla/client/detail/Simulator.h#L454)):*
<details><summary><i>Previously, doterop wrote…</i></summary><blockquote>

> ```
> ){
> ```
Space
</blockquote></details>

Done
___
*[PythonAPI/carla/source/libcarla/Actor.cpp, line 136 at r1](https://reviewable.io/reviews/carla-simulator/carla/3868#-MTh6rw_6WgpbYjCsYBr:-MUyKAjP1bKM-3k-ONUn:b2secjg) ([raw file](https://github.com/carla-simulator/carla/blob/e59e80b43281c2157b041691634915499009cc8c/PythonAPI/carla/source/libcarla/Actor.cpp#L136)):*
<details><summary><i>Previously, doterop wrote…</i></summary><blockquote>

> ```
>       .def("set_wheel_steer_direction", &cc::Vehicle::SetWheelSteerDirection, (arg("wheel_location")), (arg("angle_in_deg")))
>       .def("get_wheel_steer_angle", &cc::Vehicle::GetWheelSteerAngle, (arg("wheel_location")))
> ```
I think it would be better to include the enum of the wheel location here too
</blockquote></details>

Added the new enum called VehicleWheelLocation
___
*[PythonAPI/examples/tutorial.py, line 39 at r1](https://reviewable.io/reviews/carla-simulator/carla/3868#-MTgzedxAIodIECACov8:-MUyK9Pp3lYSACaq1hcd:bb6un1j) ([raw file](https://github.com/carla-simulator/carla/blob/e59e80b43281c2157b041691634915499009cc8c/PythonAPI/examples/tutorial.py#L39)):*
<details><summary><i>Previously, doterop wrote…</i></summary><blockquote>

Remove this file from the PR
</blockquote></details>

Done
___
*[Unreal/CarlaUE4/CarlaUE4.uproject, line 3 at r1](https://reviewable.io/reviews/carla-simulator/carla/3868#-MTgzVTV5iWVz5wyU_L9:-MUyJyZk0ySVIGwS2SKa:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/e59e80b43281c2157b041691634915499009cc8c/Unreal/CarlaUE4/CarlaUE4.uproject#L3)):*
<details><summary><i>Previously, doterop wrote…</i></summary><blockquote>

Remove this file from the PR
</blockquote></details>

Done.
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/EnvironmentObject.h, line 8 at r1](https://reviewable.io/reviews/carla-simulator/carla/3868#-MTgzyVf7Gch4T6vjYnc:-MUyKRZO1cfRzVHkKzn9:bpeb4iy) ([raw file](https://github.com/carla-simulator/carla/blob/e59e80b43281c2157b041691634915499009cc8c/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/EnvironmentObject.h#L8)):*
<details><summary><i>Previously, doterop wrote…</i></summary><blockquote>

Why did you need this include here?
</blockquote></details>

Had to add it since it was giving compile errors not recognizing the struct FBoundingBox
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.h, line 276 at r1](https://reviewable.io/reviews/carla-simulator/carla/3868#-MTh26bl7V3aZQLJbbKC:-MUyKQD7ADA5pBWET74N:bb6un1j) ([raw file](https://github.com/carla-simulator/carla/blob/e59e80b43281c2157b041691634915499009cc8c/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.h#L276)):*
<details><summary><i>Previously, doterop wrote…</i></summary><blockquote>

> ```
> /// An enum could be used, but this is something situational. An uint8 does the trick just fine
> ```
I think you can remove this comment
</blockquote></details>

Done
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp, line 460 at r1](https://reviewable.io/reviews/carla-simulator/carla/3868#-MTh3BuP3WZirSZiCmNA:-MUyKOFj4GX6xcTHQK6f:bb6un1j) ([raw file](https://github.com/carla-simulator/carla/blob/e59e80b43281c2157b041691634915499009cc8c/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp#L460)):*
<details><summary><i>Previously, doterop wrote…</i></summary><blockquote>

> ```
> this->
> ```
Can be removed
</blockquote></details>

Done
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp, line 468 at r1](https://reviewable.io/reviews/carla-simulator/carla/3868#-MTh3VUR1n0cIVWrZRGm:-MUyKPKS3r8LZ-wx-Z0M:bb6un1j) ([raw file](https://github.com/carla-simulator/carla/blob/e59e80b43281c2157b041691634915499009cc8c/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp#L468)):*
<details><summary><i>Previously, doterop wrote…</i></summary><blockquote>

> ```
> this->
> ```
Can be removed
</blockquote></details>

Done

**Review by algababr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3868)* status: 0 of 14 files reviewed, 13 unresolved discussions (waiting on @algababr and @doterop)

___
*[LibCarla/source/carla/client/detail/Client.h, line 236 at r4](https://reviewable.io/reviews/carla-simulator/carla/3868#-MUyMi4zEVUVOeid-aJT:-MUyMi4zEVUVOeid-aJU:blj8cba) ([raw file](https://github.com/carla-simulator/carla/blob/d193d243d608ccfbf8c2ceba5066a98575ebfe68/LibCarla/source/carla/client/detail/Client.h#L236)):*
> ```objc
>     void EnableChronoPhysics(
>         rpc::ActorId vehicle,
>         uint64_t MaxSubsteps,
> ```

Merge update
___
*[LibCarla/source/carla/client/detail/Simulator.h, line 27 at r4](https://reviewable.io/reviews/carla-simulator/carla/3868#-MUyMmp52jL1VvCmaSoN:-MUyMmp66bhwd_JaWaYq:b-g2z6zi) ([raw file](https://github.com/carla-simulator/carla/blob/d193d243d608ccfbf8c2ceba5066a98575ebfe68/LibCarla/source/carla/client/detail/Simulator.h#L27)):*
> ```objc
> #include "carla/rpc/VehicleLightStateList.h"
> #include "carla/rpc/LabelledPoint.h"
> #include "carla/rpc/VehicleWheels.h"
> ```

Added included for using the new enum
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.h, line 42 at r4](https://reviewable.io/reviews/carla-simulator/carla/3868#-MUyMaJs8HQN8FjJv14J:-MUyMaJs8HQN8FjJv14K:b-yr295e) ([raw file](https://github.com/carla-simulator/carla/blob/d193d243d608ccfbf8c2ceba5066a98575ebfe68/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.h#L42)):*
> ```objc
>   //Use for bikes and bicycles
>   Front_Wheel = 0,
>   Back_Wheel = 1,
> ```

Update

**Review by algababr — COMMENTED** [review]
> Reviewed 1 of 13 files at r1, 1 of 10 files at r2, 2 of 2 files at r3, 2 of 10 files at r4, 8 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3868)* status: all files reviewed, 11 unresolved discussions (waiting on @doterop)

**Review by doterop — COMMENTED** [review]
> Reviewed 1 of 10 files at r2, 8 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3868)* status: all files reviewed, 4 unresolved discussions (waiting on @doterop)

**Review by doterop — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 10 files at r4, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3868#-:-MVHH8Oc4ZBPeBRs0NB5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @algababr)

**Comment by algababr** [comment]
___
*[CHANGELOG.md, line 19 at r7](https://reviewable.io/reviews/carla-simulator/carla/3868#-MVqHaio1gGNASb-U2HJ:-MVqHaio1gGNASb-U2HK:b-9i6pzd) ([raw file](https://github.com/carla-simulator/carla/blob/417f23b7d09dea9fa253d8e85a31a9e69cbe7fb0/CHANGELOG.md#L19)):*
> ```Markdown
>   * API extensions:
>   - Added `set_wheel_steer_direction()` function to change the bone angle of each wheel of a vehicle
> 	- Added `get_wheel_steer_angle()` function to get the steer angle of a vehicle whee
> ```

Fixed conflict with Changelog

**Review by algababr — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3868)* status: all files reviewed, 2 unresolved discussions (waiting on @algababr)

**Review by bernatx — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3868)* status: 11 of 12 files reviewed, 3 unresolved discussions (waiting on @algababr)

___
*[CHANGELOG.md, line 19 at r7](https://reviewable.io/reviews/carla-simulator/carla/3868#-MVqIT6y0TiIB-zxwJ3K:-MVqIT6y0TiIB-zxwJ3L:b-49y5mt) ([raw file](https://github.com/carla-simulator/carla/blob/417f23b7d09dea9fa253d8e85a31a9e69cbe7fb0/CHANGELOG.md#L19)):*
> ```Markdown
>   * API extensions:
>   - Added `set_wheel_steer_direction()` function to change the bone angle of each wheel of a vehicle
> 	- Added `get_wheel_steer_angle()` function to get the steer angle of a vehicle whee
> ```

Is there a TAB code?

**Comment by algababr** [comment]
___
*[CHANGELOG.md, line 19 at r7](https://reviewable.io/reviews/carla-simulator/carla/3868#-MVqIT6y0TiIB-zxwJ3K:-MVqJENU45HbZ5EQFotJ:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/417f23b7d09dea9fa253d8e85a31a9e69cbe7fb0/CHANGELOG.md#L19)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

Is there a TAB code?
</blockquote></details>

Done.

**Review by algababr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3868)* status: 11 of 12 files reviewed, 4 unresolved discussions (waiting on @algababr and @bernatx)

___
*[CHANGELOG.md, line 19 at r8](https://reviewable.io/reviews/carla-simulator/carla/3868#-MVqJH306hx2Inx1KKtd:-MVqJH306hx2Inx1KKte:buyyl44) ([raw file](https://github.com/carla-simulator/carla/blob/cc3b715299530e2e1654da5b9fd6817b9ce1a12f/CHANGELOG.md#L19)):*
> ```Markdown
>   * API extensions:
>   - Added `set_wheel_steer_direction()` function to change the bone angle of each wheel of a vehicle
>   - Added `get_wheel_steer_angle()` function to get the steer angle of a vehicle whee
> ```

Fixed tab

**Review by algababr — COMMENTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3868)* status: all files reviewed, 4 unresolved discussions (waiting on @algababr and @bernatx)

**Review by bernatx — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3868)* status: all files reviewed, 3 unresolved discussions (waiting on @algababr)

**Comment by aufkeinenfallvergessen** [comment]
Hello @algababr, @bernatx, @doterop & @DSantosO,
I want to apply individually torque to the wheels.
Unfortunately it doesnt work the way I did hope for, as seen in my Post [#5215 ](https://github.com/carla-simulator/carla/discussions/5215).

Now I want to use the Function [SetBrakeTorque](https://docs.unrealengine.com/4.27/en-US/API/Plugins/PhysXVehicles/USimpleWheeledVehicleMovementCom-/SetBrakeTorque/) from [USimpleWheeledVehicleMovementComponent](https://docs.unrealengine.com/4.27/en-US/API/Plugins/PhysXVehicles/USimpleWheeledVehicleMovementCom-/).

Are you able to possibly add this Function as well, or could describe to me how you have done it?
Currently I am using a Debian Package install of Carla (no build from Source Code).

Thank you very much :)

**Pull request merged**
