### PR TITLE
Add OccupancyGrid to ros-bridge

### PR DESCRIPTION
**Pull request by danil-tolkachev**
#### Description

screenshot from 2018-06-27 11-05-09
screenshot from 2018-06-27 11-06-02

#### Where has this been tested?

  * **Platform(s):** Ubuntu 16.04
  * **Python version(s):** Python 2.7
  * **Unreal Engine version(s):** ...

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/537)

### CODE REVIEW

**Comment by danil-tolkachev** [comment]
Should I need to do some works on PR? There's some FIXME comments, but they are related to other parts of CARLA, so I'm not sure how to fix them.

**Comment by laurent-george** [comment]
Review status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @danil-tolkachev)

---

*[carla_ros_bridge/src/carla_ros_bridge/map.py, line 55 at r1](https://reviewable.io/reviews/carla-simulator/carla/537#-LG0sS19EjYo0F0brTa-:-LG0sS1B6aUSW1DlTkq5:boqxtl) ([raw file](https://github.com/carla-simulator/carla/blob/d67a67c47f2c4e150b5bcba9d60a536b42864620/carla_ros_bridge/src/carla_ros_bridge/map.py#L55)):*
> ```
>        # FIXME: height for Town01 is still in centimeters
> ```
Maybe create an issue on carla board ?

---

*[carla_ros_bridge/src/carla_ros_bridge/map.py, line 60 at r1](https://reviewable.io/reviews/carla-simulator/carla/537#-LG0szGmBB-Hmw_5QGB-:-LG0szGmBB-Hmw_5QGB0:b-vua02m) ([raw file](https://github.com/carla-simulator/carla/blob/d67a67c47f2c4e150b5bcba9d60a536b42864620/carla_ros_bridge/src/carla_ros_bridge/map.py#L60)):*
> ```Python
> 
>     def send_map(self):
>         self.map_pub.publish(self.map_msg)
> ```

Here the map will not be saved in the rosbag.  Do we need to add a way to save a kind of latch topic in the rosbag (i.e only once), or should we keep the map only for real time processing/not replay.
 The user can still use rosbag record -a , to create a rosbag, but it introduce unsynch behavior..

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/537)*

**Comment by danil-tolkachev** [comment]
Review status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @danil-tolkachev)

---

*[carla_ros_bridge/src/carla_ros_bridge/map.py, line 55 at r1](https://reviewable.io/reviews/carla-simulator/carla/537#-LG0sS19EjYo0F0brTa-:-LG4-eFWDcnfCVnqAam_:b-lz7gja) ([raw file](https://github.com/carla-simulator/carla/blob/d67a67c47f2c4e150b5bcba9d60a536b42864620/carla_ros_bridge/src/carla_ros_bridge/map.py#L55)):*
<details><summary><i>Previously, laurent-george (George Laurent) wrote…</i></summary><blockquote>

> ```
>        # FIXME: height for Town01 is still in centimeters
> ```
Maybe create an issue on carla board ?
</blockquote></details>

I opened #541

---

*[carla_ros_bridge/src/carla_ros_bridge/map.py, line 60 at r1](https://reviewable.io/reviews/carla-simulator/carla/537#-LG0szGmBB-Hmw_5QGB-:-LG40lQG29nUQEPJlctg:b-oja8mn) ([raw file](https://github.com/carla-simulator/carla/blob/d67a67c47f2c4e150b5bcba9d60a536b42864620/carla_ros_bridge/src/carla_ros_bridge/map.py#L60)):*
<details><summary><i>Previously, laurent-george (George Laurent) wrote…</i></summary><blockquote>

Here the map will not be saved in the rosbag.  Do we need to add a way to save a kind of latch topic in the rosbag (i.e only once), or should we keep the map only for real time processing/not replay.
 The user can still use rosbag record -a , to create a rosbag, but it introduce unsynch behavior..

</blockquote></details>

I didn't work with `CarlaRosBridgeWithBag` yet. @laurent-george, by unsynch behavior do you mean that it is possible that not all messages will be сought in a bag file? In that case I think that it would be nice to support map in the bridge with bag too.

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/537)*

**Comment by danil-tolkachev** [comment]
@laurent-george could you get some advices how to add map into bridge with bag?

**Comment by laurent-george** [comment]
@danil-tolkachev yeah sure, I am looking into it. We can also merge your code without this feature and add a new pull request later. Give me some hours I try to figure out an approach.

**Comment by laurent-george** [comment]
@danil-tolkachev I tried to test it on my computer, but I get issue with the map name scene.map_name return an empty string here, thus the .txt is not found.
Have you other change like new settings.yaml not in the pull request ?

**Comment by danil-tolkachev** [comment]
Hi @laurent-george. Probably I haven't. I'm not sure, but it seems that you use not the latest version (0.8.4) of Carla. Can you check this?

**Comment by laurent-george** [comment]
@nsubiron I didn't understand why the travis build failed here, could you help me on that ?

**Comment by marcgpuig** [comment]
For some reason, `PythonClient/carla/planner/city_track` have trailing newlines. I don't know how @felipecode managed to overpass the travis, but it's there 😂
Maybe he can fix it!

**Comment by laurent-george** [comment]
@danil-tolkachev can you rebase your branch so it can be merged ?

**Comment by danil-tolkachev** [comment]
@laurent-george I've added some changes. Could you review them?

**Comment by xuwenqian66** [comment]
> @nsubiron, @marcgpuig
> Should I need to do some works on PR? There's some FIXME comments, but they are related to other parts of CARLA, so I'm not sure how to fix them.

Hi, I am a beginner from carla. I just want to integrate a self defined Lidar in Carla system. But the release and rosbridge conbined not correctly. So I failed to establish with  https://github.com/carla-simulator/ros-bridge. So I just wonder if you could send me a example for the combination from carla UE4 to Rviz without .sh file, that would be more great for me to learn the combination.

**Comment by JackRen88** [comment]
Hello,everyone!
How to modify the name of the map coordinate (/map)?

**Pull request merged**
