### PR TITLE
Fix a typo error in changing the lateral args 

### LINKED ISSUE #6037: Typo error in controller.py
Hi there,

CARLA version: 0.9.13
Platform/OS: Ubuntu 20.04
Problem you have experienced: Small typo error found in https://github.com/carla-simulator/carla/blob/master/PythonAPI/carla/agents/navigation/controller.py
```
def change_lateral_PID(self, args_lateral):
    """Changes the parameters of the PIDLongitudinalController"""
    self._lon_controller.change_parameters(**args_lateral)
```
I think it should be: `self._lat_controller.change_parameters(**args_lateral)`

Best

### PR DESCRIPTION
**Pull request by apgeorg**
#### Description

Fix a typo error in changing the lateral args in controller.py

Fixes #6037 

#### Where has this been tested?

  * **Platform(s):** Ubuntu 20.04
  * **Python version(s):** Python 3.8.10

- - -
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/6046)

### CODE REVIEW

**Comment by glopezdiest** [comment]
Hey, yes indeed, that is a typo, sorry about that. However, can you please do the PR to `dev`?

**Comment by apgeorg** [comment]
> Hey, yes indeed, that is a typo, sorry about that. However, can you please do the PR to `dev`?

@glopezdiest alright!

**Comment by glopezdiest** [comment]
Please resolve the conflicts that came from swtiching to dev. You can always just remake the branch (and the PR if needed)

**Comment by apgeorg** [comment]
> Please resolve the conflicts that came from swtiching to dev. You can always just remake the branch (and the PR if needed)

@glopezdiest FYI I remake it in #6080

**Pull request closed without merging**
