### PR TITLE
Enabled overlap events on static meshes and log error messages when meshes in world are empty

### PR DESCRIPTION
**Pull request by algababr**
#### Description

Enabled overlap events on all meshes in the world so CarSim and Chrono detect collisions correctly. Also added error messages to log if there are empty meshes detected in the world.

Fixes #  

#### Where has this been tested?

  * **Platform(s):** Windows
  * **Python version(s):** 3.7.9
  * **Unreal Engine version(s):** 4.24

#### Possible Drawbacks

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4088)

### CODE REVIEW

**Review by bernatx — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4088)* status: all files reviewed, 2 unresolved discussions (waiting on @algababr)

___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp, line 176 at r1](https://reviewable.io/reviews/carla-simulator/carla/4088#-MYdA8OOBya46QaASxXb:-MYdA8OOBya46QaASxXc:b5so4rj) ([raw file](https://github.com/carla-simulator/carla/blob/3676f55e84a4b31130580abd00d91459549973f4/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp#L176)):*
> ```cpp
>   }
>   
>   EnableCarSimChronoOverlapEvents();
> ```

I think we can just remove the Carsim and Chrono from the function name, so it is like   EnableOverlapEvents();. Then it will be a more general use, not just for them.
Also, remove the double space in a new line above.
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp, line 268 at r1](https://reviewable.io/reviews/carla-simulator/carla/4088#-MYdAQf0AdDv_6109JZE:-MYdAQf0AdDv_6109JZF:b-uuahol) ([raw file](https://github.com/carla-simulator/carla/blob/3676f55e84a4b31130580abd00d91459549973f4/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp#L268)):*
> ```cpp
>   for(AActor *Actor : WorldActors)
>   {
>   	AStaticMeshActor *MeshActor = CastChecked<AStaticMeshActor>(Actor);
> ```

Avoid using TAB's and use spaces instead.
Also, there is a double space in two new lines, please remove that also.

**Review by bernatx — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4088)* status: all files reviewed, 2 unresolved discussions (waiting on @algababr)

**Comment by algababr** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp, line 268 at r1](https://reviewable.io/reviews/carla-simulator/carla/4088#-MYdAQf0AdDv_6109JZE:-Mfc8TgE7pzBZcOjRuH1:bsauh39) ([raw file](https://github.com/carla-simulator/carla/blob/3676f55e84a4b31130580abd00d91459549973f4/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp#L268)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

Avoid using TAB's and use spaces instead.
Also, there is a double space in two new lines, please remove that also.
</blockquote></details>

I can't see through reviewable if it still has the tabs, but I think it's fine now. I double checked with visual studio 2019 just to be sure.

**Comment by algababr** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp, line 176 at r1](https://reviewable.io/reviews/carla-simulator/carla/4088#-MYdA8OOBya46QaASxXb:-Mfc8pxqDKoY9X81etXi:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/3676f55e84a4b31130580abd00d91459549973f4/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp#L176)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

I think we can just remove the Carsim and Chrono from the function name, so it is like   EnableOverlapEvents();. Then it will be a more general use, not just for them.
Also, remove the double space in a new line above.
</blockquote></details>

Done.

**Review by bernatx — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4088)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @algababr)

**Pull request merged**
