### PR TITLE
Add a minimal ros bridge: camera, lidar, control

### LINKED ISSUE #12: ROS integration
Hi!

Is there any plan of integrating Carla with ROS?
In specific this would allow us to retrieve the state information, sensor data and to send control command to the car.

Probably the easiest way would be to write a ROS node that uses the CARLA client API in python? 

Thanks!

### PR DESCRIPTION
**Pull request by laurent-george**
#### Description

A simple ros bridge written in python. Inspired by the work of WenchaoDing (https://gist.github.com/WenchaoDing/8bdf2b6753f0cc6cb1c4019529a79c9f).

Fixes #12  

rviz

#### Where has this been tested?

  * **Platform(s):** Linux (ubuntu  16.04 with ros lunar)
  * **Python version(s):** python2.7
  * **Unreal Engine version(s):** 4.18

#### Possible Drawbacks

None (new code)

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/301)

### CODE REVIEW

**Comment by laurent-george** [comment]
I still have some problem with transforms (I don't really understand the coordinate system of carla, it seems that there is something strange with the lidar point). In my understanding carla transforms and unreal engine use left-handed coordinate system. But does the lidar points respect this convention ? What is the difference between get_transform and get_unreal_transform ?

**Comment by laurent-george** [comment]
Ok all major problem with transform are now fixed (it would be nice if a carla developer could recheck that, I had to do pointcloud modification in order to get it right). 
For now only markers for vehicles are handled (I will add the pedestrians/traffic light in a near future)

Demonstration video with lidar/depth/camera/depth_cloud in rviz available here: [carla_ros_bridge](https://www.youtube.com/watch?v=S_NoN2GBtdY&feature=youtu.be)

**Comment by felipecode** [comment]
Hey, we haven't forgot your pull request. It seems super nice. 
We are right now testing it and deciding where we are going to place it.

**Comment by laurent-george** [comment]
@felipecode any update ? (I am just back from holidays, so don't hesitate if you required some information/refactor etc)

**Comment by laurent-george** [comment]
Thanks for the review, I am working on the modification requested.

**Comment by laurent-george** [comment]
@nsubiron I have updated the code based on your review.

**Comment by germanros1987** [comment]
This looks great. Could you address my last comment? After that, this is ready to get merged!

---

Review status: all files reviewed at latest revision, 22 unresolved discussions, some commit checks failed.

---

*[carla_ros_bridge/src/carla_ros_bridge/bridge_with_rosbag.py, line 18 at r4](https://reviewable.io/reviews/carla-simulator/carla/301#-LEKhZjH7cOavVDxBTj9:-LEKhZjH7cOavVDxBTjA:btzdh8z) ([raw file](https://github.com/carla-simulator/carla/blob/d319785501599e4729d6227356b9d1ef0c4c6136/carla_ros_bridge/src/carla_ros_bridge/bridge_with_rosbag.py#L18)):*
> ```Python
>         super(CarlaRosBridgeWithBag, self).__init__(*args, **kwargs)
>         timestr = time.strftime("%Y%m%d-%H%M%S")
>         self.bag = rosbag.Bag('/tmp/output_{}.bag'.format(timestr), mode='w')
> ```

Why hardcoding this?

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/301#-:-LEKi0Q6EK5zACuesyiz:b72lpfi)*

**Comment by germanros1987** [comment]
+@germanros1987 as feature reviewer (since I think I was never officially added!)

---

Review status: all files reviewed at latest revision, 23 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/301#-:-LELQyazAzOrT4b5JJmS:b-mzpbbl)*

**Comment by laurent-george** [comment]
@germanros1987 Thanks again for your review, I updated the code to remove the hardcoded path for rosbag (now we can provide the wanted path as a parameter when launching the node).

**Comment by germanros1987** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 23 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/301#-:-LEVK5BE7yCxkyCRwvm3:bnfp4nl)*

**Comment by germanros1987** [comment]
@laurent-george you need to resolve all the discussions before to get the review accepted. So basically you should not see any red in reviewable. Go to the top right part and click there. Reviewable will take you to the different sections that require your attention (you have to reply / acept / ok). 

---

Review status: all files reviewed at latest revision, 23 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/301#-:-LEVKCkY78JJYCGpa2F3:b-z131k4)*

**Comment by laurent-george** [comment]
Review status: all files reviewed at latest revision, 23 unresolved discussions, some commit checks failed.

---

*[carla_ros_bridge/Readme.md, line 31 at r2](https://reviewable.io/reviews/carla-simulator/carla/301#-LD0UKO3Bf1-AV1XiF-w:-LE_md5969PpNvx2uWtH:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/2931dabc5f699d8e472f5b40703ee2348f54d213/carla_ros_bridge/Readme.md#L31)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

This would need to be changed right before the PR is merged. 
</blockquote></details>

Done.

---

*[carla_ros_bridge/config/settings.yaml, line 53 at r2](https://reviewable.io/reviews/carla-simulator/carla/301#-LD0VQ3hC6BG3evyhGkl:-LE_mh1r8g_EQcg89NDy:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/2931dabc5f699d8e472f5b40703ee2348f54d213/carla_ros_bridge/config/settings.yaml#L53)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

Perhaps remove these comments or make an explicit comment to tell people to uncomment them in case they want to switch on additional sensors?
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/carla_ros_bridge/bridge_with_rosbag.py, line 18 at r4](https://reviewable.io/reviews/carla-simulator/carla/301#-LEKhZjH7cOavVDxBTj9:-LE_mlHb-ohvgt-Ttx6G:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/d319785501599e4729d6227356b9d1ef0c4c6136/carla_ros_bridge/src/carla_ros_bridge/bridge_with_rosbag.py#L18)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

Why hardcoding this?
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/client.py, line 1 at r2](https://reviewable.io/reviews/carla-simulator/carla/301#-LD0WntS42npZ0Xf3ptX:-LE_mrQiAofoZkwSh2TX:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/2931dabc5f699d8e472f5b40703ee2348f54d213/carla_ros_bridge/src/client.py#L1)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

This file is huge and hard to review. I would recommend to split it into modules. You have several classes, so I would recommend to have those classes as independent files. 
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/client.py, line 37 at r2](https://reviewable.io/reviews/carla-simulator/carla/301#-LD0Vm5I-BPzkFXKuDun:-LE_mpJY6zOHQeGweELZ:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/2931dabc5f699d8e472f5b40703ee2348f54d213/carla_ros_bridge/src/client.py#L37)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

Please, follow this standard for imports: https://www.python.org/dev/peps/pep-0008/#imports
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/client.py, line 39 at r2](https://reviewable.io/reviews/carla-simulator/carla/301#-LD0XOdkAdISiG5sdKs9:-LE_mw_L-AGNutStjPg9:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/2931dabc5f699d8e472f5b40703ee2348f54d213/carla_ros_bridge/src/client.py#L39)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

please, add docstring
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/client.py, line 66 at r2](https://reviewable.io/reviews/carla-simulator/carla/301#-LD0XNY5EHqrXz9FoGe_:-LE_mvhU8ZfLyXGXILK1:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/2931dabc5f699d8e472f5b40703ee2348f54d213/carla_ros_bridge/src/client.py#L66)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

please, add docstring
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/client.py, line 84 at r2](https://reviewable.io/reviews/carla-simulator/carla/301#-LD0XMMo4B5Jnei8u2Qa:-LE_mueyEbwkEK0Cxdx0:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/2931dabc5f699d8e472f5b40703ee2348f54d213/carla_ros_bridge/src/client.py#L84)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

please, add docstring
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/client.py, line 97 at r2](https://reviewable.io/reviews/carla-simulator/carla/301#-LD0XF3B7qxVOL4MdwR_:-LE_mtIhERqxagBOvbeV:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/2931dabc5f699d8e472f5b40703ee2348f54d213/carla_ros_bridge/src/client.py#L97)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

please, add docstring
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/client.py, line 107 at r2](https://reviewable.io/reviews/carla-simulator/carla/301#-LD0X9yZB1n8mxkPGMmq:-LE_mrvU5RTGj0SZRmXY:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/2931dabc5f699d8e472f5b40703ee2348f54d213/carla_ros_bridge/src/client.py#L107)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

Please, do it :)
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/client.py, line 145 at r2](https://reviewable.io/reviews/carla-simulator/carla/301#-LD0ZHDP9oly7vY5FSNh:-LE_nA5kBGBKf5m7msPe:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/2931dabc5f699d8e472f5b40703ee2348f54d213/carla_ros_bridge/src/client.py#L145)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

One class, one file? At least in this case, that looks like the right thing to do. 
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/client.py, line 235 at r2](https://reviewable.io/reviews/carla-simulator/carla/301#-LD0XemxBfgmfU74jLZR:-LE_nD2P6Uh1wOACIGaG:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/2931dabc5f699d8e472f5b40703ee2348f54d213/carla_ros_bridge/src/client.py#L235)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

please, add docstring
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/client.py, line 243 at r2](https://reviewable.io/reviews/carla-simulator/carla/301#-LD0XkFp4zTv7WiRzxuc:-LE_nE1W34iNNqEQ_-Of:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/2931dabc5f699d8e472f5b40703ee2348f54d213/carla_ros_bridge/src/client.py#L243)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

 please, add docstring
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/client.py, line 254 at r2](https://reviewable.io/reviews/carla-simulator/carla/301#-LD0XlqIEvGxpbWy-Ovk:-LE_mzX693jRmTgOXMnX:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/2931dabc5f699d8e472f5b40703ee2348f54d213/carla_ros_bridge/src/client.py#L254)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

please, add docstring
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/client.py, line 275 at r2](https://reviewable.io/reviews/carla-simulator/carla/301#-LD0Xsjz1m-7a7mPk7G7:-LE_n-z09vwNaA_IkEVv:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/2931dabc5f699d8e472f5b40703ee2348f54d213/carla_ros_bridge/src/client.py#L275)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

please, add docstring
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/client.py, line 289 at r2](https://reviewable.io/reviews/carla-simulator/carla/301#-LD0Xtzu9-iq8VjK9CHb:-LE_n1hFAYSjPeOb9rNP:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/2931dabc5f699d8e472f5b40703ee2348f54d213/carla_ros_bridge/src/client.py#L289)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

please, add docstring
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/client.py, line 290 at r2](https://reviewable.io/reviews/carla-simulator/carla/301#-LD0YV8g9ixl_l3gF75y:-LE_n8gd43KEB8nGQK86:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/2931dabc5f699d8e472f5b40703ee2348f54d213/carla_ros_bridge/src/client.py#L290)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

Remove this comment. 
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/client.py, line 405 at r2](https://reviewable.io/reviews/carla-simulator/carla/301#-LD0Y7XjDPbAi5PKPD7X:-LE_n2qg3pd_ReZs3Bh4:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/2931dabc5f699d8e472f5b40703ee2348f54d213/carla_ros_bridge/src/client.py#L405)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

please, add docstring
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/client.py, line 434 at r2](https://reviewable.io/reviews/carla-simulator/carla/301#-LD0Y8fb4CJlrYW6FoRb:-LE_n4-k6xdr1OVCDl7V:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/2931dabc5f699d8e472f5b40703ee2348f54d213/carla_ros_bridge/src/client.py#L434)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

please, add docstring
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/client.py, line 453 at r2](https://reviewable.io/reviews/carla-simulator/carla/301#-LD0YB0HAQOZCG9J2AB8:-LE_n5Ms6PcfNbwi-Win:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/2931dabc5f699d8e472f5b40703ee2348f54d213/carla_ros_bridge/src/client.py#L453)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

Please, fix/finish docstring
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/client.py, line 498 at r2](https://reviewable.io/reviews/carla-simulator/carla/301#-LD0YIP7DgJs8aHSyGjy:-LE_nGVZ3i4VjmgUjjYF:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/2931dabc5f699d8e472f5b40703ee2348f54d213/carla_ros_bridge/src/client.py#L498)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

Please, fix/finish docstring
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/client.py, line 512 at r2](https://reviewable.io/reviews/carla-simulator/carla/301#-LD0YLJl5rBYQAxqZYQ1:-LE_n7Qr432v_UtLW75q:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/2931dabc5f699d8e472f5b40703ee2348f54d213/carla_ros_bridge/src/client.py#L512)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

Please, add a docstring to document this class. And please, add it to its own file. It has its own identity. 
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/client.py, line 554 at r2](https://reviewable.io/reviews/carla-simulator/carla/301#-LD0WUy7CtmWlww2cfNh:-LE_mo56CQrpjf3E5Vwv:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/2931dabc5f699d8e472f5b40703ee2348f54d213/carla_ros_bridge/src/client.py#L554)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

Please, use yapf, pylint or auto pep8 on your files
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/301)*

**Comment by laurent-george** [comment]
Reviewed 4 of 11 files at r1, 12 of 18 files at r3, 1 of 4 files at r4, 4 of 4 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 23 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/301)*

**Comment by laurent-george** [comment]
Reviewed 1 of 4 files at r5.
Review status: all files reviewed at latest revision, 23 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/301)*

**Comment by laurent-george** [comment]
Just rebase on master

**Comment by nsubiron** [comment]
Yay! :)

**Pull request merged**
