### PR TITLE
Expose Telemetry Data

### PR DESCRIPTION
**Pull request by joel-mb**
#### Description

This PR exposes the telemetry data to the client:

```py
vehicle.get_telemetry_data()
```

This will return a `VehicleTelemetryData` structure with the following information

```py
VehicleTelemetryData(
    speed  # [m/s]
    steer
    throttle
    brake
    engine_rpm
    gear
    drag  # [N]
    wheels  # list of WheelTelemetryData
)
WheelTelemetryData(
    tire_friction
    lat_slip  # [degrees]
    long_slip
    omega
    tire_load
    normalized_tire_load,
    torque  # [Nm]
    long_force  # [N]
    lat_force  # [N]
    normalized_long_force
    normalized_lat_force
)
```

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04
  * **Python version(s):** 3.7
  * **Unreal Engine version(s):** 4.26

#### Possible Drawbacks

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5153)

### CODE REVIEW

**Review by jackbart94 — DISMISSED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5153)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Axel1092)

___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp, line 787 at r1](https://reviewable.io/reviews/carla-simulator/carla/5153#-MvYlO-G5xMlvSm-4pP1:-MvYlO-G5xMlvSm-4pP2:b2nicts) ([raw file](https://github.com/carla-simulator/carla/blob/956d5e264d3c18563cde20c10ea12aeb8c3f66ad/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp#L787)):*
> ```cpp
>     Wheels.Add(WheelTelemetryData);
>   }
>   
> ```

tab

**Review by joel-mb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5153)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Axel1092)

___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp, line 787 at r1](https://reviewable.io/reviews/carla-simulator/carla/5153#-MvYlO-G5xMlvSm-4pP1:-MvYweuQDC0FC6ZSokME:bb6un1j) ([raw file](https://github.com/carla-simulator/carla/blob/956d5e264d3c18563cde20c10ea12aeb8c3f66ad/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp#L787)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

tab
</blockquote></details>

Done

**Comment by Himverma2012** [comment]
Hi, I was able to implement this code for my project & I'm able to use the command

`telemetry = world.player.get_telemetry_data`

Inside this, I get a structure like you've mentioned & I can access the VehicleTelemetryData using <dot> operator. But when I try to get the WheelTelemetryData using `telemetry.wheels` (I'm a noob, I know), I get an error:

`TypeError: No to_python (by-value) converter found for C++ type: class std::vector<class carla::rpc::WheelTelemetryData,class std::allocator<class carla::rpc::WheelTelemetryData> >`

Can you help me with this issue?

**Comment by Akshay-sudo-ux** [comment]
Hi, is there a plan to merge this PR to dev?  The telemetry info exposed here to the client is pretty useful.

Thanks in advance,
Akshay

**Review by Blyron — APPROVED** [review]

**Review by Blyron — COMMENTED** [review]
> Reviewed 12 of 16 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5153)* status: 4 of 16 files reviewed, all discussions resolved (waiting on @Axel1092 and @jackbart94)

**Review by Blyron — APPROVED** [review]
> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5153)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Axel1092)

**Comment by Hyohyo99** [comment]
> 안녕하세요, 저는 이 코드를 제 프로젝트에 구현할 수 있었고 다음 명령을 사용할 수 있었습니다.
> 
> `telemetry = world.player.get_telemetry_data`
> 
> 이 안에서, 당신이 언급한 것과 같은 구조를 얻고 Operator를 사용하여 VehicleTelemetryData에 액세스할 수 있습니다. 하지만 `telemetry.wheels`(저는 초보자입니다, 알아요) WheelTelemetryData를 가져오려고 하면 오류가 발생합니다.
> 
> `TypeError: No to_python (by-value) converter found for C++ type: class std::vector<class carla::rpc::WheelTelemetryData,class std::allocator<class carla::rpc::WheelTelemetryData> >`
> 
> 이 문제를 해결하는 데 도움을 주실 수 있나요?

I have same problem. Did you solved it?

**Comment by Yandong-Luo** [comment]
Hi, why I can not use get_telemetry_data() to get the data?

`import carla
import random
import time

def main():
    client = carla.Client('127.0.0.1', 2000)
    client.set_timeout(2.0)

    world = client.get_world()
    actors = world.get_actors()
    print([actor.type_id for actor in actors])

    blueprint_library = world.get_blueprint_library()
    vehicle_bp = blueprint_library.filter('vehicle.*')[0]
    spawn_points = world.get_map().get_spawn_points()

    # Spawn vehicle
    vehicle = None
    for spawn_point in spawn_points:
        vehicle = world.try_spawn_actor(vehicle_bp, spawn_point)
        if vehicle is not None:
            print(f"Spawned vehicle at {spawn_point}")
            break

    if vehicle is None:
        print("Failed to spawn vehicle at any spawn point.")
        return

    front_left_wheel  = carla.WheelPhysicsControl(tire_friction=2.0, damping_rate=1.5, max_steer_angle=70.0, long_stiff_value=1000)
    front_right_wheel = carla.WheelPhysicsControl(tire_friction=2.0, damping_rate=1.5, max_steer_angle=70.0, long_stiff_value=1000)
    rear_left_wheel   = carla.WheelPhysicsControl(tire_friction=3.0, damping_rate=1.5, max_steer_angle=0.0,  long_stiff_value=1000)
    rear_right_wheel  = carla.WheelPhysicsControl(tire_friction=3.0, damping_rate=1.5, max_steer_angle=0.0,  long_stiff_value=1000)
    wheels = [front_left_wheel, front_right_wheel, rear_left_wheel, rear_right_wheel]

    physics_control = vehicle.get_physics_control()
    physics_control.torque_curve = [carla.Vector2D(x=0, y=400), carla.Vector2D(x=1300, y=600)]
    physics_control.max_rpm = 10000
    physics_control.moi = 1.0
    physics_control.damping_rate_full_throttle = 0.0
    physics_control.use_gear_autobox = True
    physics_control.gear_switch_time = 0.5
    physics_control.clutch_strength = 10
    physics_control.mass = 10000
    physics_control.drag_coefficient = 0.25
    physics_control.steering_curve = [carla.Vector2D(x=0, y=1), carla.Vector2D(x=100, y=1), carla.Vector2D(x=300, y=1)]
    physics_control.use_sweep_wheel_collision = True
    physics_control.wheels = wheels
    vehicle.apply_physics_control(physics_control)

    time.sleep(1.0)

    if hasattr(vehicle, "get_telemetry_data"):
        telemetry = vehicle.get_telemetry_data()
        print("Engine RPM:", telemetry.engine_rotation_speed)
        for i, wheel in enumerate(telemetry.wheels):
            print(f"Wheel {i}:")
            print(f"  Tire Force: {wheel.tire_force}")
            print(f"  Long Slip: {wheel.longitudinal_slip}")
            print(f"  Lat Slip: {wheel.lateral_slip}")
            print(f"  Steer Angle: {wheel.steer_angle}")
            print(f"  Rotation Speed: {wheel.rotation_speed}")
    else:
        print("there is no telemetry data available for this vehicle.")

if __name__ == '__main__':
    main()
`


10:40:07 in CARLA_0.9.15/PythonAPI/examples via 💻 carla 
➜  python physics_control.py
['vehicle.audi.a2', 'vehicle.audi.a2', 'vehicle.audi.a2', 'traffic.traffic_light', 'traffic.traffic_light', 'traffic.traffic_light', 'traffic.traffic_light', 'traffic.traffic_light', 'traffic.traffic_light', 'traffic.traffic_light', 'traffic.traffic_light', 'traffic.traffic_light', 'traffic.traffic_light', 'traffic.traffic_light', 'traffic.traffic_light', 'traffic.traffic_light', 'traffic.traffic_light', 'traffic.traffic_light', 'traffic.unknown', 'traffic.unknown', 'traffic.unknown', 'traffic.yield', 'traffic.stop', 'traffic.stop', 'traffic.stop', 'spectator']
Spawned vehicle at Transform(Location(x=-84.932762, y=16.474657, z=0.600000), Rotation(pitch=0.000000, yaw=-179.840790, roll=0.000000))
there is no telemetry data available for this vehicle.

**Pull request merged**
