### PR TITLE
Digital Twins Update 26//05

### PR DESCRIPTION
**Pull request by Blyron**
#### Description

Adding vehicles props and terrain. and other kind of stuff to Digital twins project. Also fixed crash when trying to connect with osmrenderer.

Fixes #  

#### Where has this been tested?

  * **Platform(s):** Ubuntu 20.04 Windows 11
  * **Python version(s):**  .3.8
  * **Unreal Engine version(s):** 4.26

#### Possible Drawbacks

- - -
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/6502)

### CODE REVIEW

**Review by Axel1092 — CHANGES_REQUESTED** [review]
> Reviewed 28 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/6502)* status: 28 of 31 files reviewed, 4 unresolved discussions (waiting on @bernatx and @Blyron)

___
*[`Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp` line 217 at r1](https://reviewable.io/reviews/carla-simulator/carla/6502#-NWMQ16h2fzknE2JtuIl:-NWMQ16h2fzknE2JtuIm:b-1o8mji) ([raw file](https://github.com/carla-simulator/carla/blob/7c1743849ffd062e83656921bf3967c1f25278b1/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp#L217)):*
> ```cpp
> //
>   //// Road mask
> 	//int32 Width = RoadMask->SizeX, Height = RoadMask->SizeY;
> ```

Better to remove comented code
___
*[`Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp` line 240 at r1](https://reviewable.io/reviews/carla-simulator/carla/6502#-NWMQ4y51b6yfyM3YPDH:-NWMQ4y51b6yfyM3YPDI:b-7ne4oc) ([raw file](https://github.com/carla-simulator/carla/blob/7c1743849ffd062e83656921bf3967c1f25278b1/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp#L240)):*
> ```cpp
>                                                           (Offset.Y + Y),
>                                                           0));
>       //if( ImageData[CellIndex].R > 0.5 ) // Small Threshold  /* Uncomment to apply road mask */
> ```

commented code
___
*[`Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp` line 255 at r1](https://reviewable.io/reviews/carla-simulator/carla/6502#-NWMQ7GpAG3tfFPdnE2d:-NWMQ7GpAG3tfFPdnE2e:b-7ne4oc) ([raw file](https://github.com/carla-simulator/carla/blob/7c1743849ffd062e83656921bf3967c1f25278b1/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp#L255)):*
> ```cpp
>   Normals.Init(FVector(0.0f, 0.0f, 1.0f), Vertices.Num());
>   //RawHeightmap->Unlock();
>   //RawRoadMask->Unlock();  /* Uncomment to apply road mask */
> ```

commented code
___
*[`Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp` line 854 at r1](https://reviewable.io/reviews/carla-simulator/carla/6502#-NWMQGOF2rMjMLHGsZ8O:-NWMQGOF2rMjMLHGsZ8P:b-dcrvil) ([raw file](https://github.com/carla-simulator/carla/blob/7c1743849ffd062e83656921bf3967c1f25278b1/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp#L854)):*
> ```cpp
>       carla::geom::deformation::GetBumpDeformation(PosX,PosY);
>   }else{
>     return carla::geom::deformation::GetZPosInDeformation(PosX, PosY) + (carla::geom::deformation::GetZPosInDeformation(PosX, PosY) * -0.15f);
> ```

long line

**Review by Blyron — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/6502)* status: 27 of 31 files reviewed, 4 unresolved discussions (waiting on @Axel1092 and @bernatx)

___
*[`Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp` line 217 at r1](https://reviewable.io/reviews/carla-simulator/carla/6502#-NWMQ16h2fzknE2JtuIl:-NWMVMbdAjBUSO74Nu-n:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/7c1743849ffd062e83656921bf3967c1f25278b1/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp#L217)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

Better to remove comented code
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp` line 240 at r1](https://reviewable.io/reviews/carla-simulator/carla/6502#-NWMQ4y51b6yfyM3YPDH:-NWMVMzk7JClXIRnQ8xL:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/7c1743849ffd062e83656921bf3967c1f25278b1/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp#L240)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

commented code
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp` line 255 at r1](https://reviewable.io/reviews/carla-simulator/carla/6502#-NWMQ7GpAG3tfFPdnE2d:-NWMVO1G11-n8b8yiEW4:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/7c1743849ffd062e83656921bf3967c1f25278b1/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp#L255)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

commented code
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp` line 854 at r1](https://reviewable.io/reviews/carla-simulator/carla/6502#-NWMQGOF2rMjMLHGsZ8O:-NWMVR1H7SgMWblPjn-W:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/7c1743849ffd062e83656921bf3967c1f25278b1/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp#L854)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

long line
</blockquote></details>

Done.

**Review by Axel1092 — APPROVED** [review]
> Reviewed 3 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/6502)* status: 30 of 31 files reviewed, all discussions resolved (waiting on @bernatx)

**Review by bernatx — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/6502)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Blyron)

**Pull request merged**
