### PR TITLE
Moved GNSS sensor from client to server

### PR DESCRIPTION
**Pull request by doterop**
#### Description

Moved the GNSS sensor from client to server side.

#### Where has this been tested?

  * **Platform(s):** Linux
  * **Python version(s):** 3.5.2
  * **Unreal Engine version(s):** 4.22

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/2199)

### CODE REVIEW

**Comment by xmyqsh** [comment]
Good job! Can you elaborate on the pros and cons?

**Comment by marcgpuig** [comment]
@xmyqsh we decided to port as much as we can to server so the client is as light as possible.
- **Pros:**
  - Fewer calculations on the client-side.
  - Exactly the same output for different clients listening to the same sensor.
- **Cons:**
  - More calculations on the server-side.
  - More networking traffic.

**Comment by xmyqsh** [comment]
@marcgpuig Do you think it is proper to port `LaneInvasionSensor` to the server-side?
The following is my solution that I just figure out:
Create a `LaneInvasionSensor.*` under `Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor`,
and `#include <carla/road/...>` related functions to calculate the result just as the client-side solution does. All of the others are similar to the normal server-side sensor where the Server-side sensor Guide described.

**Comment by nsubiron** [comment]
> Exactly the same output for different clients listening to the same sensor.

Unfortunately two clients cannot listen to the same sensor...

**Pull request merged**
