### PR TITLE
Building Carla on Ubuntu 20.04 LTS

### PR DESCRIPTION
**Pull request by pravinblaze**
#### Description

Most of the instructions for building Carla on Ubuntu 18.04 works for 20.04 as well except for dropping Python 2.7 related dependencies.
Like so:
```
sudo apt-get install build-essential clang-8 lld-8 g++-7 cmake ninja-build libvulkan1 python3 python3-pip python3-dev libpng-dev libtiff5-dev libjpeg-dev tzdata sed curl unzip autoconf libtool rsync libxml2-dev &&
pip3 install --user setuptools
```

Build scripts are also modified to remove Python 2.7 targets.
One could manually install Python 2.7 and retain support for it but it's probably better to just let go of it.

P.S. No need to add Xenial or Bionic deb repository, which is the first command in the build instructions in the [docs](https://carla.readthedocs.io/en/latest/build_linux/), i.e,
```
sudo apt-get update &&
sudo apt-get install wget software-properties-common &&
sudo add-apt-repository ppa:ubuntu-toolchain-r/test &&
wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add - &&
sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main" &&
sudo apt-get update
```
I was able to build Carla on Ubuntu 20.04 with only Focal Fossa deb repository.

#### Where has this been tested?

  * **Platform(s):** Ubuntu 20.04
  * **Python version(s):** 3.8
  * **Unreal Engine version(s):** 4.24

#### Possible Drawbacks

* To run scripts that use pygame, need to use pygame developent version 2.0.0.dev6 as 1.9.6 can't be installed from pip on Python 3.8.

``` pip3 install pygame==2.0.0.dev6  ```

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/2787)

### CODE REVIEW

**Comment by Roosstef** [comment]
Are there any plans to continue merging? It would be really nice to use carla with ubuntu20.04. Especially because of the new ros distro for python3 support.

**Comment by jeffchen006** [comment]
Could you show us how to replace Xenial deb repo to Focal Fossa deb? 
i.e. How to change the lines in doc:
```
sudo apt-get update &&
sudo apt-get install wget software-properties-common &&
sudo add-apt-repository ppa:ubuntu-toolchain-r/test &&
wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add - &&
sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main" &&
sudo apt-get update

```

**Comment by pravinblaze** [comment]
> Could you show us how to replace Xenial deb repo to Focal Fossa deb?
> i.e. How to change the lines in doc:
> 
> ```
> sudo apt-get update &&
> sudo apt-get install wget software-properties-common &&
> sudo add-apt-repository ppa:ubuntu-toolchain-r/test &&
> wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add - &&
> sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main" &&
> sudo apt-get update
> ```

Hi @jeffchen006, I didn't try adding Focal Fossa deb. I was able to build only using default repositories that come with Focal Fossa.

**Comment by tlobig** [comment]
I am, too, interested in building for Ubuntu 20.04 - Python2 is EOL for a while now, I'd appreciate depcrication. Seems like Travis and Jenkis jobs insist on building for python2 and thus won't go through.
Any plans on support of Ubuntu 20.04 in master soon?

**Comment by pravinblaze** [comment]
Deleting branch as building for Python 3.8 on Ubuntu 20.04 is now supported in the master branch.

**Pull request closed without merging**
