### PR TITLE
Update boost setup

### LINKED ISSUE #875: Error when  'make LibCarla'
Hi,

I'm using Ubuntu 18.04.1 LTS.
And I got this list of errors shown below: (Full log attached.) 
[log.txt](https://github.com/carla-simulator/carla/files/2481649/log.txt)

BuildLibCarla.sh: Building LibCarla "Server" configuration.
[1/51] Building CXX object LibCarla/cm.../__/__/source/carla/client/Image.cpp.o
FAILED: LibCarla/cmake/server/CMakeFiles/carla_server.dir/__/__/source/carla/client/Image.cpp.o 
/usr/bin/clang++-5.0  -DBOOST_ERROR_CODE_HEADER_ONLY -I../../LibCarla/cmake/../source -I../boost-1.67.0-install/include -I../rpclib-2.2.1-libcxx-install/include -std=c++14 -pthread -fPIC -Werror -Wall -Wextra -Wno-missing-braces -stdlib=libc++ -I/home/ic/UnrealEngine_4.19/carla/Build/llvm-5.0-install/include/c++/v1 -std=c++14 -pthread -fPIC -Werror -Wall -Wextra -Wno-missing-braces -stdlib=libc++ -I/home/ic/UnrealEngine_4.19/carla/Build/llvm-5.0-install/include/c++/v1   -O3 -DNDEBUG -MD -MT LibCarla/cmake/server/CMakeFiles/carla_server.dir/__/__/source/carla/client/Image.cpp.o -MF LibCarla/cmake/server/CMakeFiles/carla_server.dir/__/__/source/carla/client/Image.cpp.o.d -o LibCarla/cmake/server/CMakeFiles/carla_server.dir/__/__/source/carla/client/Image.cpp.o -c ../../LibCarla/source/carla/client/Image.cpp
In file included from ../../LibCarla/source/carla/client/Image.cpp:8:
In file included from ../../LibCarla/cmake/../source/carla/client/Image.h:9:
../../LibCarla/cmake/../source/carla/Buffer.h:204:42: error: no member named 'is_const_buffer_sequence' in namespace 'boost::asio'
    typename std::enable_if<boost::asio::is_const_buffer_sequence<T>::value>::type
                            ~~~~~~~~~~~~~^
../../LibCarla/cmake/../source/carla/Buffer.h:204:67: error: 'T' does not refer to a value
    typename std::enable_if<boost::asio::is_const_buffer_sequence<T>::value>::type
                                                                  ^
../../LibCarla/cmake/../source/carla/Buffer.h:203:24: note: declared here
    template <typename T>
                       ^
../../LibCarla/cmake/../source/carla/Buffer.h:204:71: error: member 'value' declared as a template
    typename std::enable_if<boost::asio::is_const_buffer_sequence<T>::value>::type
                                                                      ^
../../LibCarla/cmake/../source/carla/Buffer.h:204:76: error: expected ';' at end of declaration list
    typename std::enable_if<boost::asio::is_const_buffer_sequence<T>::value>::type
                                                                           ^
                                                                           ;
../../LibCarla/cmake/../source/carla/Buffer.h:97:9: error: use of undeclared identifier 'ReuseThisBuffer'
        ReuseThisBuffer();
        ^
5 errors generated.

Thank you for your help.

### PR DESCRIPTION
**Pull request by praveen-palanisamy**
#### Description

- Updated the `Setup.sh` script to define the boost version in one place and use it appropriately in all other places
- Upgraded the boost version to 1.68.0 as 1.67.0 has been reported to have build issues
- Fixes #875, #881 

#### Where has this been tested?

  * **Platform(s):** Ubuntu 16.04
  * **Python version(s):** 3.6, 2.7
  * **Unreal Engine version(s):**

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/947)

### CODE REVIEW

**Comment by praveen-palanisamy** [comment]
The Boost 1.68.0 release may have some issues with the IO extensions (see [here](https://github.com/freeorion/freeorion/issues/2211)). This has been already fixed in Boost's master. It seems to be an issue for PythonAPI's JPEG/ PNG/ TIFF extensions (as reported by the CI error in https://travis-ci.org/carla-simulator/carla/jobs/452018876).

The issue is due to : `error: use of undeclared identifier 'bits8'` in Boost 1.68 image IO.

I see 3 options:
1. Wait for Boost release 1.69.0 to be available
2. Build off of Boost's master 
3. Patch the Boost headers by adding:
  ```c++
  namespace boost { namespace gil {
  typedef uint8_t  bits8;
  typedef uint16_t bits16;
  typedef uint32_t bits32;
  typedef int8_t   bits8s;
  typedef int16_t  bits16s;
  typedef int32_t  bits32s;
  typedef float32_t bits32f;
  }}
  ``` 
 to `/usr/include/boost/gil/extension/io/tiff_io.hpp`, `/usr/include/boost/gil/extension/io/png_io_private.hpp` and `/usr/include/boost/gil/extension/io/jpeg_io_private.hpp`

**Comment by nsubiron** [comment]
Boost 1.69 beta is out, maybe we can start testing and see if it also fixes #949.

**Comment by praveen-palanisamy** [comment]
Building with Boost 1.69 Beta goes fine for me locally. But, I do not think it is a good idea to build this master branch against the beta release.  What do you think?

For #949 , I have pushed an update that may satisfy Travis.

Once we have the Boost 1.69.0 release, these issues will likely be resolved.

**Comment by nsubiron** [comment]
Closing this one, we'll continue the work in #1117.

**Pull request closed without merging**
