### PR TITLE
Retrieve BBs of all the elements of the level

### PR DESCRIPTION
**Pull request by doterop**
#### Description

Continuation of PR #3272 .

A new method has been added to the PythonAPI to get all the BBs of the level:
```
bbs = world.get_level_bbs()
``` 
A new enum to  categorize the object types has been added too, so we can filter the call to a specific object type:
```
bbs = world.get_level_bbs(carla.CityObjectLabel.TrafficLight)
``` 

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04
  * **Python version(s):** 3
  * **Unreal Engine version(s):** 4.24

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3301)

### CODE REVIEW

**Review by bernatx — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3301)* status: all files reviewed, 3 unresolved discussions (waiting on @Axel1092, @doterop, @DSantosO, and @marcgpuig)

___
*[LibCarla/source/carla/rpc/ObjectLabel.h, line 18 at r1](https://reviewable.io/reviews/carla-simulator/carla/3301#-MHVVx7V4clbiAbkMFqu:-MHVVx7V4clbiAbkMFqv:b9ettwi) ([raw file](https://github.com/carla-simulator/carla/blob/054fcd42af55c829f5aeeef1114a12bc1e840ffd/LibCarla/source/carla/rpc/ObjectLabel.h#L18)):*
> ```
> Buildings
> ```
Can be the tags in singular?
___
*[PythonAPI/carla/source/libcarla/World.cpp, line 140 at r1](https://reviewable.io/reviews/carla-simulator/carla/3301#-MHVVegc4-4DrHkSSzjV:-MHVVegfE7mDtvhfkWc1:b10822g) ([raw file](https://github.com/carla-simulator/carla/blob/054fcd42af55c829f5aeeef1114a12bc1e840ffd/PythonAPI/carla/source/libcarla/World.cpp#L140)):*
> ```
> value("None", cr::CityObjectLabel::None)
> ```
Maybe using **Any** in this case is more understable? So you want Any tag you find, instead of None
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.h, line 56 at r1](https://reviewable.io/reviews/carla-simulator/carla/3301#-MHVWB_u0S8XHDeTENlL:-MHVWB_u0S8XHDeTENlM:b-7xctdv) ([raw file](https://github.com/carla-simulator/carla/blob/054fcd42af55c829f5aeeef1114a12bc1e840ffd/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.h#L56)):*
> ```
> =  0
> ```
Could we use the TAG constant instead of the value?

**Review by doterop — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3301)* status: all files reviewed, 3 unresolved discussions (waiting on @Axel1092, @bernatx, @DSantosO, and @marcgpuig)

___
*[LibCarla/source/carla/rpc/ObjectLabel.h, line 18 at r1](https://reviewable.io/reviews/carla-simulator/carla/3301#-MHVVx7V4clbiAbkMFqu:-MHVz0Xm4vHCtMEsAn7L:bpwhmjd) ([raw file](https://github.com/carla-simulator/carla/blob/054fcd42af55c829f5aeeef1114a12bc1e840ffd/LibCarla/source/carla/rpc/ObjectLabel.h#L18)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
> Buildings
> ```
Can be the tags in singular?
</blockquote></details>

They are in singular on the string conversion and it's pending to be changed on the future on the enum.
___
*[PythonAPI/carla/source/libcarla/World.cpp, line 140 at r1](https://reviewable.io/reviews/carla-simulator/carla/3301#-MHVVegc4-4DrHkSSzjV:-MHVsCVI4dg4kzSTEKes:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/054fcd42af55c829f5aeeef1114a12bc1e840ffd/PythonAPI/carla/source/libcarla/World.cpp#L140)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
> value("None", cr::CityObjectLabel::None)
> ```
Maybe using **Any** in this case is more understable? So you want Any tag you find, instead of None
</blockquote></details>

Done.
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.h, line 56 at r1](https://reviewable.io/reviews/carla-simulator/carla/3301#-MHVWB_u0S8XHDeTENlL:-MHVrk4p8bvuQKS0WE_O:b-dzwqnf) ([raw file](https://github.com/carla-simulator/carla/blob/054fcd42af55c829f5aeeef1114a12bc1e840ffd/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.h#L56)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
> =  0
> ```
Could we use the TAG constant instead of the value?
</blockquote></details>

Do you mean the enum CityObjectLabel? We can't do this due to the UFUNCTION macro. The enum should be marked as a UENUM so UE can identify it internally but this makes it incompatible with the client part.

**Review by bernatx — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3301)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Axel1092, @DSantosO, and @marcgpuig)

___
*[LibCarla/source/carla/rpc/ObjectLabel.h, line 18 at r1](https://reviewable.io/reviews/carla-simulator/carla/3301#-MHVVx7V4clbiAbkMFqu:-MHWApQT5S7fDi8dEquU:b32wtd) ([raw file](https://github.com/carla-simulator/carla/blob/054fcd42af55c829f5aeeef1114a12bc1e840ffd/LibCarla/source/carla/rpc/ObjectLabel.h#L18)):*
<details><summary><i>Previously, doterop wrote…</i></summary><blockquote>

They are in singular on the string conversion and it's pending to be changed on the future on the enum.
</blockquote></details>

ok
___
*[PythonAPI/carla/source/libcarla/World.cpp, line 140 at r1](https://reviewable.io/reviews/carla-simulator/carla/3301#-MHVVegc4-4DrHkSSzjV:-MHWAEKN98Go0M5SAQw-:b-7lj75h) ([raw file](https://github.com/carla-simulator/carla/blob/054fcd42af55c829f5aeeef1114a12bc1e840ffd/PythonAPI/carla/source/libcarla/World.cpp#L140)):*
<details><summary><i>Previously, doterop wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ok, I see then that the situation where a user wants to get the BB of all objects that does not have a TAG assigned (None) is not possible (probably of not use also).
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.h, line 56 at r1](https://reviewable.io/reviews/carla-simulator/carla/3301#-MHVWB_u0S8XHDeTENlL:-MHW9erR9p1a07xyS2ed:b-r57as) ([raw file](https://github.com/carla-simulator/carla/blob/054fcd42af55c829f5aeeef1114a12bc1e840ffd/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.h#L56)):*
<details><summary><i>Previously, doterop wrote…</i></summary><blockquote>

Do you mean the enum CityObjectLabel? We can't do this due to the UFUNCTION macro. The enum should be marked as a UENUM so UE can identify it internally but this makes it incompatible with the client part.
</blockquote></details>

ok, I see, no problem then.

**Review by bernatx — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3301#-:-MHjsGrw0Zxvt2v6q6Kx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Axel1092, @DSantosO, and @marcgpuig)

**Review by bernatx — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3301#-:-MHlSvwe2Abpeq6hnKYS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Axel1092, @DSantosO, and @marcgpuig)

**Pull request merged**
