### PR TITLE
update python __str__ wrapper

### PR DESCRIPTION
**Pull request by xmyqsh**
Solve the problem of `RuntimeError: std::bad_cast` described here: https://github.com/carla-simulator/carla/issues/1125#issuecomment-500085292

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/1730)

### CODE REVIEW

**Comment by xmyqsh** [comment]
@germanros1987 Please review and approve this PR for 
https://github.com/carla-simulator/scenario_runner/commit/d2858373eeffe24eb59ec82b1f36aa513095888b

**Comment by xmyqsh** [comment]
@nsubiron 
I seems that this line
```
.L.str.1:
        .asciz  "%d"
```
in assembly language which is generated by `std::to_string` in necessary.

And the `std::ostringstream` provides lots of condition checking into the assembly language.

-------
The following is the regression test: 
Case 1: the original code snip
```
 19   std::ostream &operator<<(std::ostream &out, const Color &color) {
 20     out << "Color(" << int(color.r)
 21         << ',' << int(color.g)
 22         << ',' << int(color.b)
 23         << ',' << int(color.a) << ')';
 24     return out;
 25   }
```
```
>>> import networkx
>>> import sys, os, glob
>>> sys.path.append(glob.glob('../carla/dist/carla-0.9.5-py2.7-linux-x86_64.egg')[0])
>>> import carla
>>> print carla.Color()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: std::bad_cast
>>>
```
Case 2: with `std::ostringstream` without `std::to_string`
```
   19   std::ostream &operator<<(std::ostream &out, const Color &color) {
~  20     std::ostringstream oss;
+  21     oss << "Color(" << int(color.r)
   22         << ',' << int(color.g)
   23         << ',' << int(color.b)
   24         << ',' << int(color.a) << ')';
~  25     return out << oss.str();
   26   }
```
```
>>> import networkx
>>> import sys, os, glob
>>> sys.path.append(glob.glob('../carla/dist/carla-0.9.5-py2.7-linux-x86_64.egg')[0])
>>> import carla
>>> print carla.Color()
Color(
>>>
```
Case 3: with `std::ostringstream` with `std::to_string`
```
   19   std::ostream &operator<<(std::ostream &out, const Color &color) {
~  20     std::ostringstream oss;
~  21     oss << "Color(" << std::to_string(int(color.r))
~  22         << ',' << std::to_string(int(color.g))
~  23         << ',' << std::to_string(int(color.b))
~  24         << ',' << std::to_string(int(color.a)) << ')';
+  25     return out << oss.str();
   26   }
```
```
>>> import networkx
>>> import sys, os, glob
>>> sys.path.append(glob.glob('../carla/dist/carla-0.9.5-py2.7-linux-x86_64.egg')[0])
>>> import carla
>>> print carla.Color()
Color(0,0,0,255)
>>>
```

**Comment by xmyqsh** [comment]
@nsubiron
I have got another solution. I will double check it and make a new PR.

**Comment by nsubiron** [comment]
@xmyqsh I'm also investigating this now, for me `networkx` works fine, but importing `tensorflow` breaks the ostream. [This SO question](https://stackoverflow.com/q/4362402) seems the same problem, it could be what they suggest, when the dynamic library is loaded is not properly initializing the streams to format numbers.

**Comment by nsubiron** [comment]
So if the problem is parsing numbers, we can use `std::to_string` when parsing numbers, only with that should do it.

**Comment by xmyqsh** [comment]
@nsubiron You are right. It is a problem with parsing numbers on stream which appears in Boost.Python in 2012 as described in the [SO question](https://stackoverflow.com/questions/4362402/what-is-wrong-with-c-streams-when-using-boost-python). And this problem has been fixed in Boost.Python later in 2012 as `Neil G` said finally. Although we don't know what is the problem exactly and how Boost.Python fixed it.

Now, let's move on our carla PythonAPI. It works well when stands alone. But, when importing some package or loading some dynamic library, eg. networkx, tensorflow, before it, the old parsing numbers on stream problem appears again which same as in 2012.

As far as I know tensorflow us SWIG and ctypes instead of Boost.Python. So this problem cannot be fixed even we update the tensorflow to latest version. This is a very lower level feature which loaded dynamically that only Boost.Python uses it and others do not support.

The solution should be: 1. make others support this feature(not possible); 2. enhance the parsing numbers on stream patch in Boost.Python(do not know it is possible or not)

So, the best solution is to support the function of parsing numbers on stream by ourselves explicitly.
And `std::string` should be the minimum part necessary and best solution currently. Although it also generates about 4x more code https://godbolt.org/z/OqPuzu.

**Comment by nsubiron** [comment]
Great, yes it's a good compromise. In any case, printing is inherently slow, it's not critical to have this part a bit less optimal.

**Pull request merged**
