### PR TITLE
Fix typo in updating lateral controller

### LINKED ISSUE #6037: Typo error in controller.py
Hi there,

CARLA version: 0.9.13
Platform/OS: Ubuntu 20.04
Problem you have experienced: Small typo error found in https://github.com/carla-simulator/carla/blob/master/PythonAPI/carla/agents/navigation/controller.py
```
def change_lateral_PID(self, args_lateral):
    """Changes the parameters of the PIDLongitudinalController"""
    self._lon_controller.change_parameters(**args_lateral)
```
I think it should be: `self._lat_controller.change_parameters(**args_lateral)`

Best

### PR DESCRIPTION
**Pull request by apgeorg**
#### Description

Fix typo in updating lateral controller

Fixes #6037 

#### Where has this been tested?

  * **Platform(s):** Ubuntu 20.04
  * **Python version(s):** 3.8
  * **Unreal Engine version(s):** CARLA's

- - -
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/6080)

### CODE REVIEW

**Review by glopezdiest — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/6080)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @apgeorg)

**Comment by glopezdiest** [comment]
Hey, thanks for the PR. Everything looks good. Waiting for Jenkins to do the tests, then we can merge it.

**Comment by apgeorg** [comment]
> Hey, thanks for the PR. Everything looks good. Waiting for Jenkins to do the tests, then we can merge it.

Hi, thank you for your quick response!

**Comment by apgeorg** [comment]
@glopezdiest I think you can merge it ;)

**Pull request merged**
