### PR TITLE
[NO_BUILD] Agents scripts docs

### PR DESCRIPTION
**Pull request by corkyw10**
# Agents scripts documentation

Documentation explaining:
- the different roles of the scripts
- how to implement an agent
- differences betweens basic and behavior
- how to create a behavior profile.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4352)

### CODE REVIEW

**Review by glopezdiest — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4352)* status: 0 of 3 files reviewed, 9 unresolved discussions (waiting on @corkyw10)

___
*[Docs/adv_agents.md, line 3 at r1](https://reviewable.io/reviews/carla-simulator/carla/4352#-MdaCGgbAew897OE_-KG:-MdaCGgbAew897OE_-KH:blxpk66) ([raw file](https://github.com/carla-simulator/carla/blob/8840134e4af27a30b30b79d0f35c115f21776a26/Docs/adv_agents.md#L3)):*
> ```
> CARLA Agent scripts allow a vehicle to follow either a random, endless route or to take the shortest route to a given destination.  Agents obey traffic lights and react to other obstacles in the road. There are three agent types available. Parameters such as target speed, braking distance, overtaking behavior, tailgating behavior, and more can be modified.
> ```
Not sure, but feels like the fact that users can easily create their own agents is missing
___
*[Docs/adv_agents.md, line 16 at r1](https://reviewable.io/reviews/carla-simulator/carla/4352#-MdaA-hR7ewzCvXdK9zm:-MdaA-hR7ewzCvXdK9zn:bp38c5w) ([raw file](https://github.com/carla-simulator/carla/blob/8840134e4af27a30b30b79d0f35c115f21776a26/Docs/adv_agents.md#L16)):*
> ```
> All scripts involved in the CARLA Agents are found in `PythonAPI/carla/agents/navigation`.
> ```
There are also some help scripts at `PythonAPI/carla/agents/tools`, to ease some calculus. Not sure it worth mentioning though 
___
*[Docs/adv_agents.md, line 21 at r1](https://reviewable.io/reviews/carla-simulator/carla/4352#-Mda9i84630Pox98ZaRM:-Mda9i84630Pox98ZaRN:b-2xk6o) ([raw file](https://github.com/carla-simulator/carla/blob/8840134e4af27a30b30b79d0f35c115f21776a26/Docs/adv_agents.md#L21)):*
> ```
> - __`global_route_planner.py`:__ Gets detailed topology from the CARLA server to build a graph representation of the world map, providing waypoint and road option information for the __Local Planner__.
> - __`global_route_planner_dao.py`:__ Accesses the information from the server-side instance of the __Global Route Planner__.
> ```
These two will have to be changed to adapt to the new ad map library, but I'll explain more in detail when that is finished
___
*[Docs/adv_agents.md, line 23 at r1](https://reviewable.io/reviews/carla-simulator/carla/4352#-Mda8HIN49qU0Ix-qZ1P:-Mda8HIN49qU0Ix-qZ1Q:bnu6a8x) ([raw file](https://github.com/carla-simulator/carla/blob/8840134e4af27a30b30b79d0f35c115f21776a26/Docs/adv_agents.md#L23)):*
> ```
> - __`local_planner.py`:__ Follows waypoints provided by the __Global Route Planner__ based on control inputs from the __VehiclePIDController__.
> ```
Not really. While that is the most interesting function of the local planner, what it really does is initialize a lane following control that will ensure a vehicle follows a lane. You can actually just initialize it without the use of the global route planner, and the local planner will work just fine. For this case, the behavior is the same as the TM, choosing randomly at intersections.
___
*[Docs/adv_agents.md, line 28 at r1](https://reviewable.io/reviews/carla-simulator/carla/4352#-MdaAJGZ0dQAzNut4GaD:-MdaAJGZ0dQAzNut4GaE:b-ylxqfe) ([raw file](https://github.com/carla-simulator/carla/blob/8840134e4af27a30b30b79d0f35c115f21776a26/Docs/adv_agents.md#L28)):*
> ```
> This agent roams around the map, avoids other vehicles, and responds to traffic lights.
> ```
Nop, the agent.py does absolutely nothing. It actually has the functions needed to detect vehicles and traffic lights but its run_step is empty, so it doesn't move. One could argue that the base class is really BasicAgent, and I'll do a PR soonmoving everything to it, to be honest.
___
*[Docs/adv_agents.md, line 42 at r1](https://reviewable.io/reviews/carla-simulator/carla/4352#-MdaBX-S3HUIV4CzbBSP:-MdaBX-T-ZXgwsogzm4T:b-3t7s7e) ([raw file](https://github.com/carla-simulator/carla/blob/8840134e4af27a30b30b79d0f35c115f21776a26/Docs/adv_agents.md#L42)):*
> ```
> from agents.navigation.basic_agent import BasicAgent
> from agents.navigation.behavior_agent import BehaviorAgent
> ```
These seems like both agents have to be imported, while it is either one or the other
___
*[Docs/adv_agents.md, line 77 at r1](https://reviewable.io/reviews/carla-simulator/carla/4352#-MdaElgIDRSajuhd5uot:-MdaElgIDRSajuhd5uou:br56ozd) ([raw file](https://github.com/carla-simulator/carla/blob/8840134e4af27a30b30b79d0f35c115f21776a26/Docs/adv_agents.md#L77)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> while True:
>     if agent.done():
>         print("The target has been reached, stopping the simulation")
>         break
>     vehicle.apply_control(agent.run_step())
> ```
</details>

As this seems taken from the automatic_control script, I'd also add how easy it is to just add another route when the first one finishes (https://github.com/carla-simulator/carla/blob/glopez/new_agents_api/PythonAPI/examples/automatic_control.py#L740)
___
*[Docs/adv_agents.md, line 82 at r1](https://reviewable.io/reviews/carla-simulator/carla/4352#-MdaCW06CLraCoDiKbxm:-MdaCW06CLraCoDiKbxn:b-9w22fi) ([raw file](https://github.com/carla-simulator/carla/blob/8840134e4af27a30b30b79d0f35c115f21776a26/Docs/adv_agents.md#L82)):*
> ```Markdown
>     vehicle.apply_control(agent.run_step())
> ```
> ```

Other things you can do with the agents, feel free to add those that feel interesting (and if any feel counterintuitive, feedback is appreciated):
- Dynamically change the target speed (*set_target_speed*)
- Make it ignore Tls, vehicles or stop signs (*ignore_function*)
- Make the vehicle follow the speed limits (*follow_speed_limits*)
- By using *set_destination* with a starting location, the calculated route will be added to the agents path
- Giving a precomputed plan to the agent with *set_global_plan*
- Or create your own with *trace_route*
___
*[Docs/adv_agents.md, line 138 at r1](https://reviewable.io/reviews/carla-simulator/carla/4352#-MdaDZNRBTUuq4XnR9I6:-MdaDZNS42m_b55WBOJY:b-ik3e52) ([raw file](https://github.com/carla-simulator/carla/blob/8840134e4af27a30b30b79d0f35c115f21776a26/Docs/adv_agents.md#L138)):*
> ```
> You can explore the provided agent scripts, expand upon them or use them as a baseline to create your own
> ```
Another section about how to create your own agent would be interesting. It would also help solidify the knowledge about their internal structure (as they just need an initialization and a run step)

**Comment by glopezdiest** [comment]
Last think I forgot, in order to use the agents, they might have to add the `carla/PythonAPI/carla` folder to the PYTHONPATH. This is automatically done for our scripts (as usual):
```py
try:
    sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + '/carla')
except IndexError:
    pass
```
but that's not the case for the rest

**Review by glopezdiest — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4352)* status: 0 of 3 files reviewed, 9 unresolved discussions (waiting on @corkyw10)

___
*[Docs/adv_agents.md, line 28 at r1](https://reviewable.io/reviews/carla-simulator/carla/4352#-MdaAJGZ0dQAzNut4GaD:-MdaQAAe0JwwhjvtDEoa:b-122ae8) ([raw file](https://github.com/carla-simulator/carla/blob/8840134e4af27a30b30b79d0f35c115f21776a26/Docs/adv_agents.md#L28)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> This agent roams around the map, avoids other vehicles, and responds to traffic lights.
> ```
Nop, the agent.py does absolutely nothing. It actually has the functions needed to detect vehicles and traffic lights but its run_step is empty, so it doesn't move. One could argue that the base class is really BasicAgent, and I'll do a PR soonmoving everything to it, to be honest.
</blockquote></details>

Removed the agent.py, now everything is part of BasicAgent

**Review by corkyw10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4352)* status: 0 of 3 files reviewed, 9 unresolved discussions (waiting on @corkyw10 and @glopezdiest)

___
*[Docs/adv_agents.md, line 3 at r1](https://reviewable.io/reviews/carla-simulator/carla/4352#-MdaCGgbAew897OE_-KG:-Me0VvkbDBKE4s3_P5os:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/8840134e4af27a30b30b79d0f35c115f21776a26/Docs/adv_agents.md#L3)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> CARLA Agent scripts allow a vehicle to follow either a random, endless route or to take the shortest route to a given destination.  Agents obey traffic lights and react to other obstacles in the road. There are three agent types available. Parameters such as target speed, braking distance, overtaking behavior, tailgating behavior, and more can be modified.
> ```
Not sure, but feels like the fact that users can easily create their own agents is missing
</blockquote></details>

Done.
___
*[Docs/adv_agents.md, line 16 at r1](https://reviewable.io/reviews/carla-simulator/carla/4352#-MdaA-hR7ewzCvXdK9zm:-Mdv-4ry9O4rCbYArqx5:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/8840134e4af27a30b30b79d0f35c115f21776a26/Docs/adv_agents.md#L16)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> All scripts involved in the CARLA Agents are found in `PythonAPI/carla/agents/navigation`.
> ```
There are also some help scripts at `PythonAPI/carla/agents/tools`, to ease some calculus. Not sure it worth mentioning though 
</blockquote></details>

Done.
___
*[Docs/adv_agents.md, line 23 at r1](https://reviewable.io/reviews/carla-simulator/carla/4352#-Mda8HIN49qU0Ix-qZ1P:-Mdv0clK2FuRhKIVeVRf:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/8840134e4af27a30b30b79d0f35c115f21776a26/Docs/adv_agents.md#L23)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> - __`local_planner.py`:__ Follows waypoints provided by the __Global Route Planner__ based on control inputs from the __VehiclePIDController__.
> ```
Not really. While that is the most interesting function of the local planner, what it really does is initialize a lane following control that will ensure a vehicle follows a lane. You can actually just initialize it without the use of the global route planner, and the local planner will work just fine. For this case, the behavior is the same as the TM, choosing randomly at intersections.
</blockquote></details>

Done.
___
*[Docs/adv_agents.md, line 28 at r1](https://reviewable.io/reviews/carla-simulator/carla/4352#-MdaAJGZ0dQAzNut4GaD:-Mdv0qLJBnaKJnNmtb_O:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/8840134e4af27a30b30b79d0f35c115f21776a26/Docs/adv_agents.md#L28)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Removed the agent.py, now everything is part of BasicAgent
</blockquote></details>

Done.
___
*[Docs/adv_agents.md, line 42 at r1](https://reviewable.io/reviews/carla-simulator/carla/4352#-MdaBX-S3HUIV4CzbBSP:-Mdv12Q3DNUreiAqUlcZ:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/8840134e4af27a30b30b79d0f35c115f21776a26/Docs/adv_agents.md#L42)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> from agents.navigation.basic_agent import BasicAgent
> from agents.navigation.behavior_agent import BehaviorAgent
> ```
These seems like both agents have to be imported, while it is either one or the other
</blockquote></details>

Done.
___
*[Docs/adv_agents.md, line 77 at r1](https://reviewable.io/reviews/carla-simulator/carla/4352#-MdaElgIDRSajuhd5uot:-Mdv2KXm58ZFBpcB6-DF:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/8840134e4af27a30b30b79d0f35c115f21776a26/Docs/adv_agents.md#L77)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> while True:
>     if agent.done():
>         print("The target has been reached, stopping the simulation")
>         break
>     vehicle.apply_control(agent.run_step())
> ```
As this seems taken from the automatic_control script, I'd also add how easy it is to just add another route when the first one finishes (https://github.com/carla-simulator/carla/blob/glopez/new_agents_api/PythonAPI/examples/automatic_control.py#L740)
</blockquote></details>

Done.
___
*[Docs/adv_agents.md, line 82 at r1](https://reviewable.io/reviews/carla-simulator/carla/4352#-MdaCW06CLraCoDiKbxm:-MdwCjACBdxncxffRERT:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/8840134e4af27a30b30b79d0f35c115f21776a26/Docs/adv_agents.md#L82)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Other things you can do with the agents, feel free to add those that feel interesting (and if any feel counterintuitive, feedback is appreciated):
- Dynamically change the target speed (*set_target_speed*)
- Make it ignore Tls, vehicles or stop signs (*ignore_function*)
- Make the vehicle follow the speed limits (*follow_speed_limits*)
- By using *set_destination* with a starting location, the calculated route will be added to the agents path
- Giving a precomputed plan to the agent with *set_global_plan*
- Or create your own with *trace_route*
</blockquote></details>

Done.
___
*[Docs/adv_agents.md, line 138 at r1](https://reviewable.io/reviews/carla-simulator/carla/4352#-MdaDZNRBTUuq4XnR9I6:-Me0Vyuu9iBnuzFC3-zt:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/8840134e4af27a30b30b79d0f35c115f21776a26/Docs/adv_agents.md#L138)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> You can explore the provided agent scripts, expand upon them or use them as a baseline to create your own
> ```
Another section about how to create your own agent would be interesting. It would also help solidify the knowledge about their internal structure (as they just need an initialization and a run step)
</blockquote></details>

Done.

**Review by glopezdiest — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4352)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @corkyw10)

___
*[Docs/adv_agents.md, line 99 at r2](https://reviewable.io/reviews/carla-simulator/carla/4352#-Me3yp7N9uFBlzMNmaz0:-Me3yp7N9uFBlzMNmaz1:b-31oy0e) ([raw file](https://github.com/carla-simulator/carla/blob/f5a3a7c64e8a89c991e631c65d39ff8975f1fed2/Docs/adv_agents.md#L99)):*
> ```
> to ignore
> ```
just to follow the speed limits, not to ignore them
___
*[Docs/adv_agents.md, line 179 at r2](https://reviewable.io/reviews/carla-simulator/carla/4352#-Me3ytqy1LAzEnIIfkN3:-Me3ytqy1LAzEnIIfkN4:b-ngn484) ([raw file](https://github.com/carla-simulator/carla/blob/f5a3a7c64e8a89c991e631c65d39ff8975f1fed2/Docs/adv_agents.md#L179)):*
> ```
> super(BasicAgent)
> ```
I forgot to send you the correct command. Use `super().__init__(target_speed, debug)`
___
*[Docs/adv_agents.md, line 186 at r2](https://reviewable.io/reviews/carla-simulator/carla/4352#-Me3z67E9jyCqGCnwBvW:-Me3z67E9jyCqGCnwBvX:b7v5m8c) ([raw file](https://github.com/carla-simulator/carla/blob/f5a3a7c64e8a89c991e631c65d39ff8975f1fed2/Docs/adv_agents.md#L186)):*
> ```Markdown
>         :return: carla.VehicleControl
>         """
>         # Actions to take during each simulation step
> ```

Same here. Add:
```
control = carla.VehicleControl()
return control
```

**Review by corkyw10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4352)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @corkyw10 and @glopezdiest)

___
*[Docs/adv_agents.md, line 99 at r2](https://reviewable.io/reviews/carla-simulator/carla/4352#-Me3yp7N9uFBlzMNmaz0:-MeOz1UC1vKUzXMgUbTg:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/f5a3a7c64e8a89c991e631c65d39ff8975f1fed2/Docs/adv_agents.md#L99)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> to ignore
> ```
just to follow the speed limits, not to ignore them
</blockquote></details>

Done.
___
*[Docs/adv_agents.md, line 179 at r2](https://reviewable.io/reviews/carla-simulator/carla/4352#-Me3ytqy1LAzEnIIfkN3:-MeOz6zlEcW3ZM3mqr5V:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/f5a3a7c64e8a89c991e631c65d39ff8975f1fed2/Docs/adv_agents.md#L179)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> super(BasicAgent)
> ```
I forgot to send you the correct command. Use `super().__init__(target_speed, debug)`
</blockquote></details>

Done.
___
*[Docs/adv_agents.md, line 186 at r2](https://reviewable.io/reviews/carla-simulator/carla/4352#-Me3z67E9jyCqGCnwBvW:-MeOzC8CCPYt4l_J35j1:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/f5a3a7c64e8a89c991e631c65d39ff8975f1fed2/Docs/adv_agents.md#L186)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Same here. Add:
```
control = carla.VehicleControl()
return control
```
</blockquote></details>

Done.

**Review by glopezdiest — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4352)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @corkyw10)

___
*[Docs/adv_agents.md, line 17 at r3](https://reviewable.io/reviews/carla-simulator/carla/4352#-MfgP-yt-pQiNFudwGbE:-MfgP-yt-pQiNFudwGbF:b-g4mx69) ([raw file](https://github.com/carla-simulator/carla/blob/2f70aec6f048ab08f2bf6dea7b4633d7024dbad0/Docs/adv_agents.md#L17)):*
> ```
> There are also some calculus helper scripts found in `PythonAPI/carla/agents/tools`.
> ```
This is no longer the case, the tools files have been deleted
___
*[Docs/adv_agents.md, line 23 at r3](https://reviewable.io/reviews/carla-simulator/carla/4352#-MfgP6Lf74tQE6fUqAqe:-MfgP6Lf74tQE6fUqAqf:bszigmx) ([raw file](https://github.com/carla-simulator/carla/blob/2f70aec6f048ab08f2bf6dea7b4633d7024dbad0/Docs/adv_agents.md#L23)):*
> ```
>  __`global_route_planner_dao.py`:__ Accesses the information from the server-side instance of the __Global Route Planner__.
> ```
This has been removed

**Review by corkyw10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4352)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @corkyw10 and @glopezdiest)

___
*[Docs/adv_agents.md, line 17 at r3](https://reviewable.io/reviews/carla-simulator/carla/4352#-MfgP-yt-pQiNFudwGbE:-MfhVxqw0NvDFGmKx3YU:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/2f70aec6f048ab08f2bf6dea7b4633d7024dbad0/Docs/adv_agents.md#L17)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> There are also some calculus helper scripts found in `PythonAPI/carla/agents/tools`.
> ```
This is no longer the case, the tools files have been deleted
</blockquote></details>

Done.
___
*[Docs/adv_agents.md, line 23 at r3](https://reviewable.io/reviews/carla-simulator/carla/4352#-MfgP6Lf74tQE6fUqAqe:-MfhW1q12JVRDD7GBdk5:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/2f70aec6f048ab08f2bf6dea7b4633d7024dbad0/Docs/adv_agents.md#L23)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
>  __`global_route_planner_dao.py`:__ Accesses the information from the server-side instance of the __Global Route Planner__.
> ```
This has been removed
</blockquote></details>

Done.

**Review by glopezdiest — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4352)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @corkyw10)

**Review by glopezdiest — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4352)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corkyw10)

**Review by bernatx — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4352)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corkyw10)

**Pull request merged**
