### PR TITLE
Determinism improvements: Sublevel loading + physics control command

### PR DESCRIPTION
**Pull request by DSantosO**
#### Description

Added fixes to increase determinism in CARLA.
 - During the loading of the sublevels, we make sure that we are loading them in the correct order. Minor differences in this were affecting the determinism on the Opt maps
 - Added ApplyVehiclePhysicsControl to allow use it with apply_batch_sync and rewrite of the vehicle smoke test with this to ensure that no commands are lost.

Fixes #  

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04
  * **Python version(s):** 3.6
  * **Unreal Engine version(s):** 4.26

#### Possible Drawbacks

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4341)

### CODE REVIEW

**Review by Axel1092 — APPROVED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4341)* status: all files reviewed, 1 unresolved discussion (waiting on @DSantosO)

___
*[PythonAPI/carla/source/libcarla/Commands.cpp, line 111 at r1](https://reviewable.io/reviews/carla-simulator/carla/4341#-MdaHuF81yxkH0RU2jOe:-MdaHuF81yxkH0RU2jOf:b1fw7yi) ([raw file](https://github.com/carla-simulator/carla/blob/0f366524166f52a2b5865aca09307962fcf7e91c/PythonAPI/carla/source/libcarla/Commands.cpp#L111)):*
> ```cpp
>   ;
> 
>   class_<cr::Command::ApplyVehiclePhysicsControl>("ApplyVehiclePhysicsControl")
> ```

Remember to add the new command to the Python API documentation

**Comment by DSantosO** [comment]
___
*[PythonAPI/carla/source/libcarla/Commands.cpp, line 111 at r1](https://reviewable.io/reviews/carla-simulator/carla/4341#-MdaHuF81yxkH0RU2jOe:-MdaIlHnD2eykvtmyBIX:bvgoeyj) ([raw file](https://github.com/carla-simulator/carla/blob/0f366524166f52a2b5865aca09307962fcf7e91c/PythonAPI/carla/source/libcarla/Commands.cpp#L111)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

Remember to add the new command to the Python API documentation
</blockquote></details>

Sure, I will add it.

**Review by DSantosO — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4341#-:-MdaJI8WEWgF3dow8crG:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Axel1092)

**Review by DSantosO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4341)* status: all files reviewed, 1 unresolved discussion (waiting on @Axel1092)

___
*[PythonAPI/carla/source/libcarla/Commands.cpp, line 111 at r1](https://reviewable.io/reviews/carla-simulator/carla/4341#-MdaHuF81yxkH0RU2jOe:-MdaJSaX-PSXSZl6Kl8H:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/0f366524166f52a2b5865aca09307962fcf7e91c/PythonAPI/carla/source/libcarla/Commands.cpp#L111)):*
<details><summary><i>Previously, DSantosO wrote…</i></summary><blockquote>

Sure, I will add it.
</blockquote></details>

Done.

**Review by Axel1092 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4341)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DSantosO)

**Comment by pavanteja295** [comment]
Hello , 
I am using carla release 0.9.11 with Town01_opt map trying to load and unload map layers. I am then saving these images using sensor synchronization. However, the map layers do not work as expected. An example scenario is the following.

`world = client.load_world(args.map , carla.MapLayer.Ground)`

Following is an example of saved image. 


I also tried specifically unloading layers like:
`    world.unload_map_layer(carla.MapLayer.All)
    world.load_map_layer(carla.MapLayer.Ground)`

This resulted in the following image:


It would be great if someone let me know what is wrong with my code? Do you recommend compiling carla from source?

**Pull request merged**
