### PR TITLE
Update ad-rss-lib to 4.4.0

### PR DESCRIPTION
**Pull request by fpasch**
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3416)

### CODE REVIEW

**Review by berndgassmann — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3416)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by berndgassmann — APPROVED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3416)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by bernatx — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3416)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bernatx)

**Review by bernatx — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3416)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
