### PR TITLE
Prevent adding trigger boxes inside the intersections

### PR DESCRIPTION
**Pull request by joel-mb**
#### Description

This PR modifies the location and shape of the trigger bounding boxes for the procedural traffic signs. It only affects to traffic lights, stops and yields.

The new algorithm prevents adding trigger boxes inside the intersection. It works in the following way:

1. If the landmark is not located inside an intersection, the center of the trigger box corresponds to the position of the landmark.
2. If the landmark is located inside an intersection it gets a previous waypoint (2m) and checks the number of predecessors. If there is only one possible predecessor we use this location as the center of the bounding box. Otherwise the landmark location is used. 

The shape of the trigger box has been also modified. Previously, the trigger box was a cube with dimension 90% of the lane width. To avoid collisions with oncoming traffic, the dimension of the bounding box has been changed to:
* Width: 50% lane width
* Length: 1.5m
* Heigh: 1m.

Also, large maps now supports stops and yields traffic signs.

#### Where has this been tested?

  * **Platform(s):** Windows
  * **Python version(s):** 3.7
  * **Unreal Engine version(s):** 4.26

#### Possible Drawbacks
Testing is required to verify that Town11 is not affected by these changes.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5403)

### CODE REVIEW

**Review by glopezdiest — APPROVED** [review]
> Reviewed 5 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5403)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Axel1092)

**Review by Axel1092 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5403)* status: all files reviewed, 4 unresolved discussions (waiting on @joel-mb)

___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/StopSignComponent.cpp` line 68 at r2](https://reviewable.io/reviews/carla-simulator/carla/5403#-N1I8lx5ASRqLlKAc4A-:-N1I8lx5ASRqLlKAc4A0:bfkdsk2) ([raw file](https://github.com/carla-simulator/carla/blob/bc8d3dedcf3f7bad94cb73c337a44d7a5fcb53fb/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/StopSignComponent.cpp#L68)):*
> ```cpp
>         if(lane < 0)
>         {
>           box_waypoint.s = FMath::Clamp(box_waypoint.s - (BoxLength + 1.5f),
> ```

Magic numbers
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/StopSignComponent.cpp` line 73 at r2](https://reviewable.io/reviews/carla-simulator/carla/5403#-N1I8eRl4w-ZJEG03fbD:-N1I8eRl4w-ZJEG03fbE:bfkdsk2) ([raw file](https://github.com/carla-simulator/carla/blob/bc8d3dedcf3f7bad94cb73c337a44d7a5fcb53fb/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/StopSignComponent.cpp#L73)):*
> ```cpp
>         else
>         {
>           box_waypoint.s = FMath::Clamp(box_waypoint.s + (BoxLength + 1.5f),
> ```

Magic numbers
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficLightComponent.cpp` line 70 at r2](https://reviewable.io/reviews/carla-simulator/carla/5403#-N1I8s-h55YMBDNVyXSC:-N1I8s-h55YMBDNVyXSD:bfkdsk2) ([raw file](https://github.com/carla-simulator/carla/blob/bc8d3dedcf3f7bad94cb73c337a44d7a5fcb53fb/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficLightComponent.cpp#L70)):*
> ```cpp
>         if(lane < 0)
>         {
>           signal_waypoint.s = FMath::Clamp(signal_waypoint.s - (BoxLength + 1.5f),
> ```

Magic numbers
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficLightComponent.cpp` line 75 at r2](https://reviewable.io/reviews/carla-simulator/carla/5403#-N1I8rbQ8uD550ql9tV8:-N1I8rbQ8uD550ql9tV9:bfkdsk2) ([raw file](https://github.com/carla-simulator/carla/blob/bc8d3dedcf3f7bad94cb73c337a44d7a5fcb53fb/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficLightComponent.cpp#L75)):*
> ```cpp
>         else
>         {
>           signal_waypoint.s = FMath::Clamp(signal_waypoint.s + (BoxLength + 1.5f),
> ```

Magic numbers

**Review by joel-mb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5403)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @Axel1092 and @glopezdiest)

___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/StopSignComponent.cpp` line 68 at r2](https://reviewable.io/reviews/carla-simulator/carla/5403#-N1I8lx5ASRqLlKAc4A-:-N1Ig5DT80PgMusdndDN:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/bc8d3dedcf3f7bad94cb73c337a44d7a5fcb53fb/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/StopSignComponent.cpp#L68)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

Magic numbers
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/StopSignComponent.cpp` line 73 at r2](https://reviewable.io/reviews/carla-simulator/carla/5403#-N1I8eRl4w-ZJEG03fbD:-N1Ig5_V6ZSZE0SfgGCq:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/bc8d3dedcf3f7bad94cb73c337a44d7a5fcb53fb/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/StopSignComponent.cpp#L73)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

Magic numbers
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficLightComponent.cpp` line 70 at r2](https://reviewable.io/reviews/carla-simulator/carla/5403#-N1I8s-h55YMBDNVyXSC:-N1Ig61y4x3Xq-QFeqdg:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/bc8d3dedcf3f7bad94cb73c337a44d7a5fcb53fb/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficLightComponent.cpp#L70)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

Magic numbers
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficLightComponent.cpp` line 75 at r2](https://reviewable.io/reviews/carla-simulator/carla/5403#-N1I8rbQ8uD550ql9tV8:-N1Ig6M-51zo-Win9tEe:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/bc8d3dedcf3f7bad94cb73c337a44d7a5fcb53fb/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficLightComponent.cpp#L75)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

Magic numbers
</blockquote></details>

Done.

**Review by glopezdiest — APPROVED** [review]
> Reviewed 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5403)* status: all files reviewed, 4 unresolved discussions (waiting on @Axel1092)

**Review by Axel1092 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5403)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @joel-mb)

**Pull request merged**
