### PR TITLE
[Docs] List Carla versions available in deb repo

### PR DESCRIPTION
**Pull request by s-hillerk**
Extends the quickstart guide to suggest `apt-cache madison carla-simulator` to find out which versions are available in the deb repo.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3819)

### CODE REVIEW

**Comment by corkyw10** [comment]
Hey, thanks for the contribution. 

I ran the command but it wasn't returning anything for me. What is the expected output? Should it be run in a particular directory?

**Comment by s-hillerk** [comment]
The output should look like this:
```
carla-simulator |     0.9.11 | http://dist.carla.org/carla bionic/main amd64 Packages
carla-simulator |   0.9.10-2 | http://dist.carla.org/carla bionic/main amd64 Packages
carla-simulator |   0.9.10-1 | http://dist.carla.org/carla bionic/main amd64 Packages
```
As the command operates on the apt cache, you might have to run `apt update` first. You must also have the Carla deb repository already enabled. (Both of those are covered by the preceding instructions.)

**Comment by corkyw10** [comment]
It seems like the output depends on the version of Ubuntu being used and passed into `$(lsb_release -sc)`. I have `focal` being passed as that variable and was not getting anything returned from `apt-cache madison carla-simulator`. However when I pass `bionic` manually instead of `$(lsb_release -sc)` when initialising the repository, then `apt-cache madison carla-simulator` returns the same as what you see. 

So I am not sure if this command will be useful for everyone depending on their Linux version.

**Comment by s-hillerk** [comment]
The output of the tool in this case is exactly right then: There is simply no release for focal in the repo yet (see http://dist.carla.org/carla/dists). Doing a deb release for focal at all is a different issue, but I have no idea what Carla’s policies are in that regard.

**Review by corkyw10 — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3819)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by corkyw10** [comment]
You're right. Thanks for that!

**Review by joel-mb — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3819)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by joel-mb** [comment]
@s-hillerk Hi! Thank you for your contribution! Can you please change the target branch from `master` to `dev`. Thanks!

**Review by joel-mb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3819#-:-MTABbCO96_wX7mj9riL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
