### PR TITLE
[NO_BUILD] Download section

### PR DESCRIPTION
**Pull request by corkyw10**
Added the latest release as 0.9.12 and URL for docs, which will be ready when the release is built

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4475)

### CODE REVIEW

**Review by bernatx — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4475)* status: all files reviewed, 2 unresolved discussions (waiting on @corkyw10)

___
*[Docs/download.md, line 5 at r2](https://reviewable.io/reviews/carla-simulator/carla/4475#-MfsA1x0BgZnVOtpbj24:-MfsA1x0BgZnVOtpbj25:byqrls) ([raw file](https://github.com/carla-simulator/carla/blob/15c7155085262f892ff2c30e372c6ca2c47dea89/Docs/download.md#L5)):*
> ```
> /0.9.12
> ```
just syntaxy, can we add the last '/' like the others or just remove in all :)
___
*[Docs/download.md, line 20 at r2](https://reviewable.io/reviews/carla-simulator/carla/4475#-MfsA9P96RiXiVT8pltr:-MfsA9P96RiXiVT8plts:b21h52b) ([raw file](https://github.com/carla-simulator/carla/blob/15c7155085262f892ff2c30e372c6ca2c47dea89/Docs/download.md#L20)):*
> ```
> /0.9.11
> ```
same here

**Review by corkyw10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4475)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @bernatx)

___
*[Docs/download.md, line 5 at r2](https://reviewable.io/reviews/carla-simulator/carla/4475#-MfsA1x0BgZnVOtpbj24:-MfsAxlxDev9qHKwnFMq:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/15c7155085262f892ff2c30e372c6ca2c47dea89/Docs/download.md#L5)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
> /0.9.12
> ```
just syntaxy, can we add the last '/' like the others or just remove in all :)
</blockquote></details>

Done.
___
*[Docs/download.md, line 20 at r2](https://reviewable.io/reviews/carla-simulator/carla/4475#-MfsA9P96RiXiVT8pltr:-MfsAy2hA4ns8stZZVXQ:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/15c7155085262f892ff2c30e372c6ca2c47dea89/Docs/download.md#L20)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
> /0.9.11
> ```
same here
</blockquote></details>

Done.

**Review by bernatx — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4475)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @bernatx and @corkyw10)

___
*[Docs/download.md, line 20 at r2](https://reviewable.io/reviews/carla-simulator/carla/4475#-MfsA9P96RiXiVT8pltr:-MfsBc9X93TER2mcGI5o:bqt8508) ([raw file](https://github.com/carla-simulator/carla/blob/15c7155085262f892ff2c30e372c6ca2c47dea89/Docs/download.md#L20)):*
<details><summary><i>Previously, corkyw10 (Corinne) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

what about the ones below :)

**Review by bernatx — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4475)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corkyw10)

**Pull request merged**
