### PR TITLE
Determinism for Traffic Manager

### PR DESCRIPTION
**Pull request by jackbart94**
#### Description

This branch implements a deterministic mode for Traffic Manager, which allows repetition over different runs. This, however, is limited by the computational power of any user's machine, which is currently a drawback we are working to fix after 0.9.10.

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18
  * **Python version(s):** Python 3.6
  * **Unreal Engine version(s):** 4.24
#### Possible Drawbacks

Above a certain threshold, the simulation has discrepancies and isn't deterministic anymore.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3333)

### CODE REVIEW

**Review by bernatx — CHANGES_REQUESTED** [review]
> Reviewed 13 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3333)* status: 13 of 30 files reviewed, 1 unresolved discussion (waiting on @bernatx, @jackbart94, and @pravinblaze)

___
*[LibCarla/source/carla/trafficmanager/Constants.h, line 32 at r1](https://reviewable.io/reviews/carla-simulator/carla/3333#-MHlKstHAUCQKmgMXUIB:-MHlKstIArXn8KdwHCiy:b-8qjr09) ([raw file](https://github.com/carla-simulator/carla/blob/bf1d2217eef3376a969f2495eb7a465d24442470/LibCarla/source/carla/trafficmanager/Constants.h#L32)):*
> ```
> float
> ```
We should change this type also as **dobule**?

**Review by bernatx — COMMENTED** [review]
> Reviewed 17 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3333)* status: all files reviewed, 1 unresolved discussion (waiting on @jackbart94 and @pravinblaze)

**Review by jackbart94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3333)* status: 28 of 31 files reviewed, 1 unresolved discussion (waiting on @bernatx and @pravinblaze)

___
*[LibCarla/source/carla/trafficmanager/Constants.h, line 32 at r1](https://reviewable.io/reviews/carla-simulator/carla/3333#-MHlKstHAUCQKmgMXUIB:-MHpPVhQC1w_CXxDXVAW:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/bf1d2217eef3376a969f2495eb7a465d24442470/LibCarla/source/carla/trafficmanager/Constants.h#L32)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
> float
> ```
We should change this type also as **dobule**?
</blockquote></details>

Done.

**Review by bernatx — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3333)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pravinblaze)

**Review by pravinblaze — APPROVED** [review]

**Pull request merged**
