### PR TITLE
Filter BaseMap and sublevels on GetAvailableMaps()

### PR DESCRIPTION
**Pull request by DSantosO**
#### Description

Added a filter in the GetAvailableMaps method to avoid return the BaseMap and the Sublevels as normal maps.

Fixes # 

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04
  * **Python version(s):** 3.6
  * **Unreal Engine version(s):** 4.24

#### Possible Drawbacks

None

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3486)

### CODE REVIEW

**Review by bernatx — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3486)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @doterop)

**Review by doterop — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3486)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by doterop — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3486#-:-MKYdIUc6GOs107EvTKn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by doterop — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3486#-:-MKdodFI5ERxcZaG7GWb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DSantosO)

**Pull request merged**
