### PR TITLE
Fixed docker prerequisites and removed python 2 default compilation

### PR DESCRIPTION
**Pull request by Axel1092**
#### Description

Fixed prerequisites in dockerfile and removed python 2 default compilation.

#### Where has this been tested?

  * **Platform(s):** ...
  * **Python version(s):** ...
  * **Unreal Engine version(s):** 4.24

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3227)

### CODE REVIEW

**Review by marcgpuig — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3227)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by bernatx — COMMENTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3227)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by bernatx — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3227#-:-MGIzei_DfWdd-oZJjIh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by bernatx — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3227)* status: all files reviewed, 1 unresolved discussion (waiting on @Axel1092)

___
*[Util/Docker/Prerequisites.Dockerfile, line 39 at r2](https://reviewable.io/reviews/carla-simulator/carla/3227#-MGJ-P2c4y0dNYQTbpFT:-MGJ-P2d8R4zyqEzy6Xm:blqfcwj) ([raw file](https://github.com/carla-simulator/carla/blob/e084c14046572880b248a4423f7ef95003f37567/Util/Docker/Prerequisites.Dockerfile#L39)):*
> ```
> pip2 install setuptools
> ```
I think now we can remove all the python 2 stuff in docker requeriments.

**Pull request merged**
