### PR TITLE
Improved enable/disable of environment objects

### PR DESCRIPTION
**Pull request by doterop**
#### Description

This feature has been improved to control each mesh instead of the whole actor. Similar to the BB calculation.
In fact, the BB can also be queried from the EnvironmentObject and the BoundingBoxCalculator has been updated to support this feature and now we can get the components that compose a BB (ie: traffic lights)

The API remains exactly the same.

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04
  * **Python version(s):** 3
  * **Unreal Engine version(s):** 4.24

#### Possible Drawbacks

This feature only works on not spawned actors

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3563)

### CODE REVIEW

**Review by bernatx — COMMENTED** [review]
:lgtm:

> Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3563#-:-MLmgOtFCczzrE9MOk1Z:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @doterop)

___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/ObjectRegister.cpp, line 74 at r2](https://reviewable.io/reviews/carla-simulator/carla/3563#-MLnKBG_7DqhumMsT70n:-MLnKBG_7DqhumMsT70o:b-ypp14a) ([raw file](https://github.com/carla-simulator/carla/blob/fe5cad8520db2124ba0e759a1f0443b5ec11d325/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/ObjectRegister.cpp#L74)):*
> ```cpp
> 
> 
>   FString FilePath = "~/Desktop/RegisteredObjects.txt";
> ```

Probably will fail for windows.  I think it is better to comment any debug file we create, or just remove the code.
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/ObjectRegister.cpp, line 118 at r2](https://reviewable.io/reviews/carla-simulator/carla/3563#-MLoB5u15zCkGTheuRpR:-MLnKmuE3CVDKMEGLJ1O:b-5p2jhk) ([raw file](https://github.com/carla-simulator/carla/blob/fe5cad8520db2124ba0e759a1f0443b5ec11d325/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/ObjectRegister.cpp#L118)):*
> ```cpp
>   EnvironmentObject.ObjectLabel = static_cast<crp::CityObjectLabel>(Tag);
>   EnvironmentObject.Type = Type;
>   EnvironmentObjects.Emplace(EnvironmentObject);
> ```

Why not pass the parameters to Emplace instead of the temporal object?
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/ObjectRegister.cpp, line 383 at r2](https://reviewable.io/reviews/carla-simulator/carla/3563#-MLqK84eD7hEiP68CEws:-MLqK84eD7hEiP68CEwt:b-vuu0ge) ([raw file](https://github.com/carla-simulator/carla/blob/fe5cad8520db2124ba0e759a1f0443b5ec11d325/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/ObjectRegister.cpp#L383)):*
> ```cpp
>   if(!Enable)
>   {
>     InstanceTransform.SetTranslation(FVector(5000000.0f));
> ```

Wondering if UE4 has no problems handling so large distances.

**Review by doterop — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3563)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @bernatx)

___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/ObjectRegister.cpp, line 74 at r2](https://reviewable.io/reviews/carla-simulator/carla/3563#-MLnKBG_7DqhumMsT70n:-MMKWbcDEWFj7QmYdV5z:bw84t91) ([raw file](https://github.com/carla-simulator/carla/blob/fe5cad8520db2124ba0e759a1f0443b5ec11d325/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/ObjectRegister.cpp#L74)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

Probably will fail for windows.  I think it is better to comment any debug file we create, or just remove the code.
</blockquote></details>

Fixed filepath to be platform agnostic. Now it will be saved in the "save" folder.
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/ObjectRegister.cpp, line 118 at r2](https://reviewable.io/reviews/carla-simulator/carla/3563#-MLoB5u15zCkGTheuRpR:-MMKWn4K7gnVCJyen4DB:b-wuwerh) ([raw file](https://github.com/carla-simulator/carla/blob/fe5cad8520db2124ba0e759a1f0443b5ec11d325/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/ObjectRegister.cpp#L118)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

Why not pass the parameters to Emplace instead of the temporal object?
</blockquote></details>

Just to be easier for reading it. Even so, I forced to move the parameter just in case
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/ObjectRegister.cpp, line 383 at r2](https://reviewable.io/reviews/carla-simulator/carla/3563#-MLqK84eD7hEiP68CEws:-MMKY0_U7TOzBs_okHdb:b-nw73l8) ([raw file](https://github.com/carla-simulator/carla/blob/fe5cad8520db2124ba0e759a1f0443b5ec11d325/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/ObjectRegister.cpp#L383)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

Wondering if UE4 has no problems handling so large distances.
</blockquote></details>

I don't think so, but I reduced it just in case
WORLD_MAX is above 2M so 1M will be enough

**Review by bernatx — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3563)* status: 12 of 15 files reviewed, 1 unresolved discussion (waiting on @bernatx and @doterop)

___
*[PythonAPI/carla/source/libcarla/World.cpp, line 274 at r3](https://reviewable.io/reviews/carla-simulator/carla/3563#-MMLZstM2JjI9rMHwEbj:-MMLZstM2JjI9rMHwEbk:befkaw1) ([raw file](https://github.com/carla-simulator/carla/blob/10489e233c89586ebab5c691c1618476a3f2ec12/PythonAPI/carla/source/libcarla/World.cpp#L274)):*
> ```cpp
>     .def("freeze_all_traffic_lights", &cc::World::FreezeAllTrafficLights, (arg("frozen")))
>     .def("get_level_bbs", &GetLevelBBs, (arg("bb_type")=cr::CityObjectLabel::None))
>     .def("get_environment_objects", &GetEnvironmentObjects, (arg("object_type")=cr::CityObjectLabel::None))
> ```

Can we add a new tag as ANY and make it the default one? For me is confusing to use None to mean Any. If we do, we allow to filter all objects without a label, what could be useful.

**Review by doterop — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3563)* status: 12 of 15 files reviewed, 1 unresolved discussion (waiting on @bernatx)

___
*[PythonAPI/carla/source/libcarla/World.cpp, line 274 at r3](https://reviewable.io/reviews/carla-simulator/carla/3563#-MMLZstM2JjI9rMHwEbj:-MMLbCK1B9AiXwRebZK9:bkrzqj2) ([raw file](https://github.com/carla-simulator/carla/blob/10489e233c89586ebab5c691c1618476a3f2ec12/PythonAPI/carla/source/libcarla/World.cpp#L274)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

Can we add a new tag as ANY and make it the default one? For me is confusing to use None to mean Any. If we do, we allow to filter all objects without a label, what could be useful.
</blockquote></details>

This is already done on the python binding of the enum. The c++ enum has not been changed because is used for tagging.
Anyway, the call from python side will be something like: 
```
get_environment_objects(carla.CityObjectLabel.Any)
```

**Review by bernatx — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3563)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @bernatx and @doterop)

___
*[PythonAPI/carla/source/libcarla/World.cpp, line 274 at r3](https://reviewable.io/reviews/carla-simulator/carla/3563#-MMLZstM2JjI9rMHwEbj:-MMLdkmtCKt1wEX2bi4V:b36eg5v) ([raw file](https://github.com/carla-simulator/carla/blob/10489e233c89586ebab5c691c1618476a3f2ec12/PythonAPI/carla/source/libcarla/World.cpp#L274)):*
<details><summary><i>Previously, doterop wrote…</i></summary><blockquote>

This is already done on the python binding of the enum. The c++ enum has not been changed because is used for tagging.
Anyway, the call from python side will be something like: 
```
get_environment_objects(carla.CityObjectLabel.Any)
```
</blockquote></details>

You are right, we agreed on that. Then the user can not filter by objects without label assigned. Maybe it is better to add the Any tag to the enum and use that as the default value. It will be more clear I think.

**Review by doterop — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3563)* status: 8 of 16 files reviewed, 1 unresolved discussion (waiting on @bernatx and @doterop)

___
*[PythonAPI/carla/source/libcarla/World.cpp, line 274 at r3](https://reviewable.io/reviews/carla-simulator/carla/3563#-MMLZstM2JjI9rMHwEbj:-MMVtia36WyiHtQJPQLD:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/10489e233c89586ebab5c691c1618476a3f2ec12/PythonAPI/carla/source/libcarla/World.cpp#L274)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

You are right, we agreed on that. Then the user can not filter by objects without label assigned. Maybe it is better to add the Any tag to the enum and use that as the default value. It will be more clear I think.
</blockquote></details>

Done.

**Review by bernatx — APPROVED** [review]
> Reviewed 7 of 8 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3563)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
