### PR TITLE
Updated Setup script to use env python

### LINKED ISSUE #948: Building PythonAPI for custom python versions
### Description
Currently, the build script (`Setup.sh`) uses the python installed at : `/usr/bin/python` (`/usr/bin/python2` and `/usr/bin/python3`) which may not be desirable always. It makes it hard to build the PythonAPI for another python version. 
For example, using the carla API in a python virtual env (or conda env) is not possible.

Similar issue on windows has also been reported in #867. 

### Version Info:
CARALA version: master, 0.9.0
Platform/OS: Linux/Ubuntu 16.04

### PR DESCRIPTION
**Pull request by praveen-palanisamy**
#### Description

- Updated the build script (`Setup.sh`) to use the current environment's python interpreters instead of the hard-coded python interpreters from `/usr/bin/`

- Fixes #948 

Enables building the PythonAPI for custom versions of python including python under virtual environments/ conda environments
#### Where has this been tested?

  * **Platform(s):** Linux/Ubuntu 16.04
  * **Python version(s):** 2.7, 3.6

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/949)

### CODE REVIEW

**Comment by praveen-palanisamy** [comment]
Hey @nsubiron,

The travis build is failing with:

 `x86_64-linux-gnu-gcc: error: /home/travis/build/carla-simulator/carla/PythonAPI/dependencies/lib/libboost_python34.a: No such file or directory`

which is strange because it should have been created in the previous build step (`make LibCarla > build.log 2>&1`).
Although the travis log says that previous build step was successful (`BuildLibCarla.sh: Success!`), I am suspecting that either a different python3 was used or the step actually had some issues. 

I tried to reproduce the build issue locally but, the build goes through well with a fresh clone of this PR branch. My local build was on Ubuntu 16.04 which is different from what the CI pipeline uses (14.04). I can try to reproduce this in a container with the same env as the CI but I think it will be better to have the full log from the travis builds in general especially for debugging.

**Comment by praveen-palanisamy** [comment]
@nsubiron : Fixed.

**Comment by praveen-palanisamy** [comment]
ping @nsubiron . This is ready for review & merge.

**Comment by planckwu** [comment]
> ping @nsubiron . This is ready for review & merge.

I got the same problem, what is the solution?

**Comment by planckwu** [comment]
@praveen-palanisamy 
I got the same problem, what is the solution?

**Comment by nsubiron** [comment]
Hey @praveen-palanisamy, sorry for taking so long, we were busy with 0.9.1 and then some time out-of-office.

Is there any other way of achieving this without overwriting `${HOME}/user-config.jam`? I don't think many people use it but I don't feel comfortable overwriting user settings without telling them.

**Comment by praveen-palanisamy** [comment]
Hey @nsubiron , No worries. It is understandable given the amount of work that went into 0.9.1. Please keep-up the good work!

Hmmm. Good point. That's a worthwhile consideration. Boost's BJam and bootstrap were too picky when it comes to building Boost.Python so I used the `user-config.jam` which was sure to take the precedence for the build config. But, I also think it is better to leave the user's settings untouched (in case they deliberately want something else).

I have updated the PR with a project level config. Tested with Py 3.4 and 3.6 in addition to the default. The CI runner should most probably report success soon.

**Comment by praveen-palanisamy** [comment]
Hi @planckwu , 

If you are facing the same issue as #948 or the the one listed in [this comment above](https://github.com/carla-simulator/carla/pull/949#issuecomment-437397580), you can use the modifications in this Pull Request (PR) for the solution.

If the tests go well, it may soon be merged into master and so you can then easily use it.

 If you can't wait for the merge and need the solution right now, you can pull this PR, (optionally rebase with the master branch) and use it. You can do something like below from the root directory where you have cloned [carla](https://github.com/carla-simulator/carla.git):

1. `git fetch origin pull/949/head:use_env_python_solution`
2. `git checkout use_env_python_solution`
3. (optional): `git rebase master`
4. Follow the carla build procedure (`make setup`, `make PythonAPI` etc...)

**Comment by praveen-palanisamy** [comment]
@nsubiron Any idea why the `BuildLibCarla.sh` in the Travis build is failing with:

 `../../LibCarla/cmake/../source/carla/Buffer.h:294:42: error: no member named 'is_const_buffer_sequence' in namespace 'boost::asio'`
(Related to #875)
?  

The `Setup.sh` (this PR) seems to return success though as per [this line](https://travis-ci.org/carla-simulator/carla/jobs/461381329#L945) in the build log.

I also tested this PR inside the same container that the Travis CI used (`travisci/ci-garnet:packer-1512502276-986baf0`) and didn't have any issue with the whole build process. I am not able to reproduce this.

**Comment by nsubiron** [comment]
Same here. No idea why this fails now.

**Comment by praveen-palanisamy** [comment]
It may be specific to the Travis build env. Because the CI with the previous commit with the `user-config.jam` was successful, I have pushed an update that uses `user-config.jam` when Travis is building it. I guess this is acceptable since we are not overriding user's settings except travis's.

**Pull request merged**
