### PR TITLE
Include map name in scene description message

### LINKED ISSUE #313: Safe way to know the city name the client is connected
Right now the CARLA simulator does not send, in 
any part of the protocol, which is the current city.
Even when the client chooses the city (after solving issue #65)
it is interesting to receive the city name from the CARLA simulator
to avoid the need to parse the carlasettings file.

### PR DESCRIPTION
**Pull request by nsubiron**
#### Description

Adds an extra string to the scene description message with the current map name. I also updated `view_start_positions.py` and `manual_control.py` to use it.

Fixes #313.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/358)

### CODE REVIEW

**Comment by felipecode** [comment]
*[a discussion](https://reviewable.io/reviews/carla-simulator/carla/358#-LBUleSA7Rgk5BxAAANo:-LBUleSCEXRk9o0ww3XL:brhv8al) (no related file):*
i run 
python manual_control.py -m . And I get

Traceback (most recent call last):
  File "manual_control.py", line 439, in <module>
    main()
  File "manual_control.py", line 428, in main
    game.execute()
  File "manual_control.py", line 158, in execute
    self._initialize_game()
  File "manual_control.py", line 173, in _initialize_game
    self._map = CarlaMap(self._city_name, 16.43, 50.0)
  File "/home/felipe/carla/PythonClient/carla/planner/map.py", line 44, in __init__
    self._graph = Graph(city_file, node_density)
  File "/home/felipe/carla/PythonClient/carla/planner/graph.py", line 44, in __init__
    with open(graph_file, 'r') as f:
IOError: [Errno 2] No such file or directory: u'/home/felipe/carla/PythonClient/carla/planner/.txt'

Seems the town name was not send to the map ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/358)*

**Comment by felipecode** [comment]
*[a discussion](https://reviewable.io/reviews/carla-simulator/carla/358#-LBUleSA7Rgk5BxAAANo:-LBzhl1RDpG0a-mk_P2b:b32w0x) (no related file):*
<details><summary><i>Previously, felipecode (Felipe Codevilla) wrote…</i></summary><blockquote>

i run 
python manual_control.py -m . And I get

Traceback (most recent call last):
  File "manual_control.py", line 439, in <module>
    main()
  File "manual_control.py", line 428, in main
    game.execute()
  File "manual_control.py", line 158, in execute
    self._initialize_game()
  File "manual_control.py", line 173, in _initialize_game
    self._map = CarlaMap(self._city_name, 16.43, 50.0)
  File "/home/felipe/carla/PythonClient/carla/planner/map.py", line 44, in __init__
    self._graph = Graph(city_file, node_density)
  File "/home/felipe/carla/PythonClient/carla/planner/graph.py", line 44, in __init__
    with open(graph_file, 'r') as f:
IOError: [Errno 2] No such file or directory: u'/home/felipe/carla/PythonClient/carla/planner/.txt'

Seems the town name was not send to the map ?

</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/358)*

**Comment by nsubiron** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/carla-simulator/carla/358#-LBUleSA7Rgk5BxAAANo:-LBzmCKl0brIM8KGMbtE:b-7cnf49) (no related file):*
<details><summary><i>Previously, felipecode (Felipe Codevilla) wrote…</i></summary><blockquote>

OK
</blockquote></details>

So the issue was that you were running a different version of the simulator right?

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/358)*

**Comment by felipecode** [comment]
*[a discussion](https://reviewable.io/reviews/carla-simulator/carla/358#-LBUleSA7Rgk5BxAAANo:-LBzmhSy0sLn4tPfHX9o:bn5hmnt) (no related file):*
<details><summary><i>Previously, nsubiron (Néstor Subirón) wrote…</i></summary><blockquote>

So the issue was that you were running a different version of the simulator right?
</blockquote></details>

Yes. Solved

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/358)*

**Pull request merged**
