### PR TITLE
Changes in CarlaSettingsDelegate so it wont apply max distance culling to foliage in Low mode

### LINKED ISSUE #396: Foliage culling uses the wrong distance in Low Mode
There is a problem with foliage culling using quality mode set to Low. When you are close to parts of the foliage seems like it uses a different origin of the foliage mesh. This is because the instanced foliage actor is using max culling instead of the foliage culling system.

foliage

### PR DESCRIPTION
**Pull request by juaxix**
Fix #396 
Now we don't get all the actors primitive components for landscapes actors or instancedfoliage actors to apply the max culling distance to them when the settings quality changes.

### Where has this been tested?

  * **Platform(s): Windows 10 x64
  * **Unreal Engine version(s):** 4.18.3

### Possible Drawbacks
Foliage models should now define a max distance for culling

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/397)

### CODE REVIEW

**Comment by nsubiron** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Settings/CarlaSettingsDelegate.cpp, line 40 at r1](https://reviewable.io/reviews/carla-simulator/carla/397#-LBzBSa6Brk_2QHmyGY3:-LBzBSa6Brk_2QHmyGY4:b939bo7) ([raw file](https://github.com/carla-simulator/carla/blob/3a8c7a80977fcf728a504c85d1777c871a0d3d66/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Settings/CarlaSettingsDelegate.cpp#L40)):*
> ```cpp
>   if (InActor != nullptr && IsValid(InActor) && !InActor->IsPendingKill() && 
>       InActor->IsA<AInstancedFoliageActor>() || //foliage culling is controlled per instance
>       InActor->IsA<ALandscape>() || //dont touch landscapes nor roads
> ```

Shouldn't this be `!InActor->IsA<AInstancedFoliageActor>() && !InActor->IsA<ALandscape>()`?

---

*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Settings/CarlaSettingsDelegate.cpp, line 265 at r1](https://reviewable.io/reviews/carla-simulator/carla/397#-LBzGq7b8ts9XdQRCIrq:-LBzGq7b8ts9XdQRCIrr:bdw63bf) ([raw file](https://github.com/carla-simulator/carla/blob/3a8c7a80977fcf728a504c85d1777c871a0d3d66/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Settings/CarlaSettingsDelegate.cpp#L265)):*
> ```cpp
>     {
>       AActor* actor = actors[i];
>       if(!IsValid(actor) || actor->IsPendingKillPending() || 
> ```

What's the difference between `IsPendingKill()` and `IsPendingKillPending()`? which one should be used?

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/397)*

**Comment by juaxix** [comment]
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Settings/CarlaSettingsDelegate.cpp, line 265 at r1](https://reviewable.io/reviews/carla-simulator/carla/397#-LBzGq7b8ts9XdQRCIrq:-LBzbZMq8F_WRTQ1nNP5:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/3a8c7a80977fcf728a504c85d1777c871a0d3d66/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Settings/CarlaSettingsDelegate.cpp#L265)):*
<details><summary><i>Previously, nsubiron (Néstor Subirón) wrote…</i></summary><blockquote>

What's the difference between `IsPendingKill()` and `IsPendingKillPending()`? which one should be used?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/397)*

**Comment by juaxix** [comment]
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Settings/CarlaSettingsDelegate.cpp, line 265 at r1](https://reviewable.io/reviews/carla-simulator/carla/397#-LBzGq7b8ts9XdQRCIrq:-LBzbyws87AKVjsAOfsV:bprt2sm) ([raw file](https://github.com/carla-simulator/carla/blob/3a8c7a80977fcf728a504c85d1777c871a0d3d66/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Settings/CarlaSettingsDelegate.cpp#L265)):*
<details><summary><i>Previously, juaxix (juaxix) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

IsPendingKill() is the one to use.

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/397)*

**Comment by juaxix** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/397)*

**Pull request merged**
