### PR TITLE
[NO_BUILD] First draft of Large Maps docs

### PR DESCRIPTION
**Pull request by corkyw10**
This PR builds upon the `corkyw10/maps-documentation` branch to include the changes made for Large Maps. It includes:

- Semantic update to core maps documentation
- Large maps overview
- How to Import/Package a large map
- Updating the name of `spawn_npc.py` to `generate_traffic.py`
- How to generate a large map in road runner

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4396)

### CODE REVIEW

**Review by Axel1092 — COMMENTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4396)* status: all files reviewed, 3 unresolved discussions (waiting on @bernatx and @corkyw10)

___
*[Docs/core_map.md, line 162 at r1](https://reviewable.io/reviews/carla-simulator/carla/4396#-MeecxpRBh7bAq_7nVxE:-MeecxpRBh7bAq_7nVxF:b-j1959d) ([raw file](https://github.com/carla-simulator/carla/blob/facff4d2fc141a927a642866be481e827c8cdb11/Docs/core_map.md#L162)):*
> ```Markdown
> ### Generating map navigation
> 
> The client needs to make a request to the server to get the `.xodr` map file and parse it to a [`carla.Map`](python_api.md#carla.Map) object. This only needs to be done once. Maps are heavy and unneccessary calls can be expensive. 
> ```

`world.get_map()` is no longer an expensive call so maybe this part can be removed.
___
*[Docs/large_map_overview.md, line 11 at r1](https://reviewable.io/reviews/carla-simulator/carla/4396#-Meee-WH0fijnTQiQipV:-Meee-WH0fijnTQiQipW:b-7rvhbl) ([raw file](https://github.com/carla-simulator/carla/blob/facff4d2fc141a927a642866be481e827c8cdb11/Docs/large_map_overview.md#L11)):*
> ```Markdown
> ## Large maps overview
> 
> The large map feature in CARLA allows users to perform simulations at a vast scale. In CARLA, large maps are divided into square tiles no larger than 2kmx2km. Tiles are streamed in and out of the server based on their proximity (streaming distance) to the ego vehicle. Other actors on the map are also managed according to their streaming distance from the ego vehicle.
> ```

maybe we should remind here how to set a vehicle as the ego, for now it needs to be set the attribute `rolename` to `hero`:
```
blueprint.set_attribute('role_name', 'hero' )
world.spawn_actor(blueprint, spawn_point)
```
___
*[Docs/large_map_overview.md, line 43 at r1](https://reviewable.io/reviews/carla-simulator/carla/4396#-Meeeqvk10wU76GRGhS1:-Meeeqvl0xj1PuOd25y1:bidqv2h) ([raw file](https://github.com/carla-simulator/carla/blob/facff4d2fc141a927a642866be481e827c8cdb11/Docs/large_map_overview.md#L43)):*
> ```Markdown
> The large map feature introduces the concept of dormant actors to CARLA. Dormant actors exist within the context of large maps only. Dormant actors are non-ego-vehicle actors in the simulation that are located outside of the __actor active distance__ of the ego vehicle, e.g., vehicles far from the ego vehicle. The actor active distance can be equal to or less than the streaming distance.
> 
> If an actor finds itself outside of the actor active distance of the ego vehicle, it will become dormant. The actor will still exist, but it will not be rendered. Physics will only be computed if [hybrid mode](adv_traffic_manager.md#hybrid-physics-mode) is set on that actor. A dormant actor's [location](python_api.md#carla.Actor.set_location) and [transformation](python_api.md#carla.Actor.set_transform) can still be set, even if their physics is not being calculated. Once the dormant actor comes within actor active distance of the ego vehicle again, it will wake up, and its rendering and physics will resume as normal.
> ```

We should say that physics are not computed at all for dormant actors but the traffic manager will be able to move vehicles in hybrid mode.

**Review by corkyw10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4396)* status: all files reviewed, 3 unresolved discussions (waiting on @Axel1092 and @bernatx)

___
*[Docs/core_map.md, line 162 at r1](https://reviewable.io/reviews/carla-simulator/carla/4396#-MeecxpRBh7bAq_7nVxE:-MeyHXKq5WpLaHQTP8YT:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/facff4d2fc141a927a642866be481e827c8cdb11/Docs/core_map.md#L162)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

`world.get_map()` is no longer an expensive call so maybe this part can be removed.
</blockquote></details>

Done.
___
*[Docs/large_map_overview.md, line 11 at r1](https://reviewable.io/reviews/carla-simulator/carla/4396#-Meee-WH0fijnTQiQipV:-MeyTIrU1SEtey-PEXmM:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/facff4d2fc141a927a642866be481e827c8cdb11/Docs/large_map_overview.md#L11)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

maybe we should remind here how to set a vehicle as the ego, for now it needs to be set the attribute `rolename` to `hero`:
```
blueprint.set_attribute('role_name', 'hero' )
world.spawn_actor(blueprint, spawn_point)
```
</blockquote></details>

Done.
___
*[Docs/large_map_overview.md, line 43 at r1](https://reviewable.io/reviews/carla-simulator/carla/4396#-Meeeqvk10wU76GRGhS1:-MeyTJ4DBJVq7S-w-cOw:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/facff4d2fc141a927a642866be481e827c8cdb11/Docs/large_map_overview.md#L43)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

We should say that physics are not computed at all for dormant actors but the traffic manager will be able to move vehicles in hybrid mode.
</blockquote></details>

Done.

**Review by bernatx — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4396)* status: 8 of 9 files reviewed, 7 unresolved discussions (waiting on @Axel1092, @corkyw10, and @XGodina)

___
*[Docs/large_map_import.md, line 21 at r2](https://reviewable.io/reviews/carla-simulator/carla/4396#-MfZlyQO7L_mRHJjNwQQ:-MfZlyQO7L_mRHJjNwQR:buvmwdg) ([raw file](https://github.com/carla-simulator/carla/blob/48598e228fff559c182e5ab8d3b1dd49e96d7ddf/Docs/large_map_import.md#L21)):*
> ```Markdown
> 
> !!! Note
>     It is not recommended to import large maps and normal maps at the same time.
> ```

I think we can not mix, so it is prohibited right now.
___
*[Docs/large_map_import.md, line 80 at r2](https://reviewable.io/reviews/carla-simulator/carla/4396#-MfZmrN3-_SJSTz1LqC5:-MfZmrN3-_SJSTz1LqC6:b-c1bgv2) ([raw file](https://github.com/carla-simulator/carla/blob/48598e228fff559c182e5ab8d3b1dd49e96d7ddf/Docs/large_map_import.md#L80)):*
> ```Markdown
> - __use_carla_materials:__ If __True__, the map will use CARLA materials. Otherwise, it will use RoadRunner materials.
> - __tiles:__ A list of the `.fbx` tile files that make up the entire map.
> ```

An important parameter is:
* __tile_size__: the size of each tile. By default, it is 2000 m (2 x 2 km)
___
*[Docs/large_map_import.md, line 92 at r2](https://reviewable.io/reviews/carla-simulator/carla/4396#-MfZnGRh32mfFg9fidch:-MfZnGRi8wOxSK2oHenQ:bacv22j) ([raw file](https://github.com/carla-simulator/carla/blob/48598e228fff559c182e5ab8d3b1dd49e96d7ddf/Docs/large_map_import.md#L92)):*
> ```Markdown
>         "xodr": "./Map01.xodr",
>         "use_carla_materials": true,
>         "tiles": [
> ```

"tile_size": 2000,
___
*[Docs/tuto_M_manual_map_package.md, line 5 at r2](https://reviewable.io/reviews/carla-simulator/carla/4396#-MfZq-3nEdRkmr1htWVw:-MfZq-3nEdRkmr1htWVx:b2fsedi) ([raw file](https://github.com/carla-simulator/carla/blob/48598e228fff559c182e5ab8d3b1dd49e96d7ddf/Docs/tuto_M_manual_map_package.md#L5)):*
> ```
> Normal Maps
> ```
This is just an opinion, but I don't like to call **normal maps** to the single maps we have, because in game art a normal map is a texture that modifies the light to add complexity to the models. I suggest to call our single maps in another way, maybe single maps, or on-tile- maps, or small maps, or standard map...

**Review by XGodina — APPROVED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4396)* status: all files reviewed, 7 unresolved discussions (waiting on @Axel1092 and @corkyw10)

**Review by corkyw10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4396)* status: 8 of 9 files reviewed, 6 unresolved discussions (waiting on @Axel1092, @bernatx, and @corkyw10)

___
*[Docs/large_map_import.md, line 21 at r2](https://reviewable.io/reviews/carla-simulator/carla/4396#-MfZlyQO7L_mRHJjNwQQ:-Mfchw5i-Cnqx1cumi7q:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/48598e228fff559c182e5ab8d3b1dd49e96d7ddf/Docs/large_map_import.md#L21)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

I think we can not mix, so it is prohibited right now.
</blockquote></details>

Done.

**Review by bernatx — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4396)* status: all files reviewed, 3 unresolved discussions (waiting on @Axel1092)

**Pull request merged**
