### PR TITLE
Upgrade PhysXVehicle for sweep wheel collisions

### PR DESCRIPTION
**Pull request by DSantosO**
#### Description

We have upgrade the PhysXVehicle plugin of Unreal to allow for sweep collision for wheels.
This results in much more realistic wheel-road interaction, this is important especially in curbs, but have a performance hit. 
This is disabled by default but it can be enable at any moment throught the physics control of the vehicle:

```
physics_control = vehicle.get_physics_control()
physics_control.use_sweep_wheel_collision = True
vehicle.apply_physics_control(physics_control)
```

Fixes # 

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04
  * **Python version(s):** Python 3.6
  * **Unreal Engine version(s):** Unreal 4.24

#### Possible Drawbacks

If enabled, it is expected to have a performance hit. If it not, everyhing should works as previously.
This requires the Unreal Engine to be patch (in the PhysXVehicle plugin) so it will require to build the Engine from source in Windows.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3620)

### CODE REVIEW

**Review by bernatx — APPROVED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3620)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @doterop)

**Review by doterop — APPROVED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3620)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by doterop — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3620)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by DSantosO** [comment]
This PR has been incorporated to PR #3662 so this one is not useful anymore.

**Pull request closed without merging**
