### PR TITLE
Client-side bounding boxes

### PR DESCRIPTION
**Pull request by Soolek**
#### Description

  * Example how to create bounding boxes around vehicles: PythonAPI/client_bounding_boxes.py

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04
  * **Python version(s):** 2.7

#### Possible Drawbacks

  * With high amount of agents the positioning of bounding boxes on screen seem to stutter slightly, possibly due to synchronisation issues

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/1383)

### CODE REVIEW

**Comment by wattsavolt** [comment]
___
*[PythonAPI/client_bounding_boxes.py, line 32 at r1](https://reviewable.io/reviews/carla-simulator/carla/1383#-Lap8Bkb9vJVAbVncpbF:-Lap8Bkb9vJVAbVncpbG:b6x2vde) ([raw file](https://github.com/carla-simulator/carla/blob/59d30b0f939c07ed94d79bca5489da87c1f10c1e/PythonAPI/client_bounding_boxes.py#L32)):*
> ```Python
> from pygame.locals import K_w
> 
> import carla
> ```

import carla only works for a release build. You need to add the following for carla to be imported for a development build:

import glob
import os
import sys

try:
    sys.path.append(glob.glob('**/carla-*%d.%d-%s.egg' % (
        sys.version_info.major,
        sys.version_info.minor,
        'win-amd64' if os.name == 'nt' else 'linux-x86_64'))[0])
except IndexError:
    pass

**Comment by Soolek** [comment]
> _[PythonAPI/client_bounding_boxes.py, line 32 at r1](https://reviewable.io/reviews/carla-simulator/carla/1383#-Lap8Bkb9vJVAbVncpbF:-Lap8Bkb9vJVAbVncpbG:b6x2vde) ([raw file](https://github.com/carla-simulator/carla/blob/59d30b0f939c07ed94d79bca5489da87c1f10c1e/PythonAPI/client_bounding_boxes.py#L32)):_
> 
> > ```python
> > from pygame.locals import K_w
> > 
> > import carla
> > ```
> 
> import carla only works for a release build. You need to add the following for carla to be imported for a development build:
> 
> import glob
> import os
> import sys
> 
> try:
> sys.path.append(glob.glob('**/carla-*%d.%d-%s.egg' % (
> sys.version_info.major,
> sys.version_info.minor,
> 'win-amd64' if os.name == 'nt' else 'linux-x86_64'))[0])
> except IndexError:
> pass

Done

**Comment by wattsavolt** [comment]
___
*[PythonAPI/client_bounding_boxes.py, line 32 at r1](https://reviewable.io/reviews/carla-simulator/carla/1383#-Lap8Bkb9vJVAbVncpbF:-LbT-zNr453-h1JBDS2T:bkn9eo6) ([raw file](https://github.com/carla-simulator/carla/blob/dd6cdee8ebeb06d1f2c0bd311fdd3fcca8629116/PythonAPI/client_bounding_boxes.py#L32)):*
<details><summary><i>Previously, wattsavolt (Aidan Clear) wrote…</i></summary><blockquote>

import carla only works for a release build. You need to add the following for carla to be imported for a development build:

import glob
import os
import sys

try:
    sys.path.append(glob.glob('**/carla-*%d.%d-%s.egg' % (
        sys.version_info.major,
        sys.version_info.minor,
        'win-amd64' if os.name == 'nt' else 'linux-x86_64'))[0])
except IndexError:
    pass
</blockquote></details>

A new folder called examples has been added in the PythonAPI folder and this is where the scripts will now reside. You will need to take changes from master and move your script to this folder.  You also need to fix the Pylint error from the CI build.

**Comment by ThierryDubois** [comment]
Any idea on how to minimize the stutter? I do not mind having the server running on low fps if it means that the coordinates are aligned with the objects.

**Comment by jeannotes** [comment]
@Soolek hi, how to get the camera intrinsic numbers, I am confusing of the fx and fy, can you explain.

**Comment by bender2po** [comment]
@Soolek Hello, thank you for your contribution.
I am trying to understand the the math behind the transformation. Could you explain the step 'cords_y_minus_z_x '. Why are interchanging the coordinates?
`  cords_x_y_z = ClientSideBoundingBoxes._vehicle_to_sensor(bb_cords, vehicle, camera)[:3, :]
  cords_y_minus_z_x = np.concatenate([cords_x_y_z[1, :], -cords_x_y_z[2, :], cords_x_y_z[0, :]])`

**Comment by Soolek** [comment]
Hi guys, unfortunately I was not the author of the transformation matrices and cannot say for my colleague why he did it in this particular way. 

AFAIK he was taught using a different orientation system at the university, therefore it was easier for him to use cords_y_minus_z_x to make matrix multiplication afterwards (as there was a lot of talk about it being "wrong" :) )

**Comment by kalelek** [comment]
image

**Comment by bender2po** [comment]
@Soolek No probelm
@kalelek Thank you! makes sense.

**Pull request merged**
