### PR TITLE
Recorder with skeleton bones

### LINKED ISSUE #4980: Walker bone transforms are not in sync with the rgb images
CARLA version: 0.9.13
Platform/OS: Windows
Problem you have experienced: I used the code from the examples/draw_skeleton.py to draw the bone positions of pedestrians. The bone positions seems to be out of sync with the rgb images  for pedestrians who are running. 

What you expected to happen: Bones in sync with the images.
Steps to reproduce: I am using sync mode with fixed delta secs  and the simulation is replaying a recording.

### PR DESCRIPTION
**Pull request by bernatx**
#### Description

The recorder now can store the bone position of the pedestrian skeleton. We need to enable the additional data flag for the recorder. Then the replayer will pose the pedestrians at the exact pose each frame.

Fixes #4980, #4975

#### Where has this been tested?

  * **Platform(s):** windows
  * **Python version(s):** 3.7
  * **Unreal Engine version(s):** 4.26

#### Possible Drawbacks

Recorder files a bit bigger due to the increment of data

- - -
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5987)

### CODE REVIEW

**Review by Axel1092 — COMMENTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5987)* status: all files reviewed, 1 unresolved discussion (waiting on @bernatx)

___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorderWalkerBones.h` line 19 at r1](https://reviewable.io/reviews/carla-simulator/carla/5987#-NHjQToE4m7RxFvjvSox:-NHjQToE4m7RxFvjvSoy:bjsc42b) ([raw file](https://github.com/carla-simulator/carla/blob/242636d941b7e8f3adb9d7d2d4bdb06eaaf0d43b/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorderWalkerBones.h#L19)):*
> ```objc
>   FVector Rotation;
> 
>   CarlaRecorderWalkerBone(FString &InName, FVector &InLocation, FVector &InRotation) : Name(InName), Location(InLocation), Rotation(InRotation) {}
> ```

Long line

**Review by bernatx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5987)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @Axel1092)

___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorderWalkerBones.h` line 19 at r1](https://reviewable.io/reviews/carla-simulator/carla/5987#-NHjQToE4m7RxFvjvSox:-NHxiIJT4g6-95tFc2DY:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/242636d941b7e8f3adb9d7d2d4bdb06eaaf0d43b/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorderWalkerBones.h#L19)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

Long line
</blockquote></details>

Done.

**Review by Axel1092 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5987)* status: all files reviewed, 1 unresolved discussion (waiting on @bernatx)

**Review by Axel1092 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5987)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bernatx)

**Pull request merged**
