### PR TITLE
Sensor data transformations fix

### PR DESCRIPTION
**Pull request by marcgpuig**
#### Description
- Temporally fixed sensor transformations and sensor data transformations mismatch in IMU and camera-based sensors.
  _This must be reverted once the new camera tick pipeline is implemented since it should fix this._
- Added additional smoke tests that validate this fix so it won't happen again.
- Added `PythonAPI/examples/lidar_to_camera.py`: a tutorial that shows how to create and use the camera intrinsic and extrinsic matrix to project 3D world positions to 2D image coordinates in CARLA. It requires the `Pillow` Python module in order to store the result as an image.

#### Where has this been tested?
  * **Platform(s):** Ubuntu 18.04
  * **Python version(s):** 3.6
  * **Unreal Engine version(s):** 4.24

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3454)

### CODE REVIEW

**Review by DSantosO — APPROVED** [review]
:lgtm:

> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3454#-:-MJzydlJ46JApiK46Dg1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @doterop)

**Review by doterop — APPROVED** [review]
:lgtm:

> Reviewed 8 of 14 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3454#-:-MKdq9Sk3HIPxi8c-vxk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by doterop — APPROVED** [review]
:lgtm:

> Reviewed 4 of 14 files at r1, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3454#-:-MKeSh7QEQzpYjoYyiC6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marcgpuig)

**Comment by aczy118** [comment]
Hi there,

When I try to run your script I am getting this error below:

ValueError: cannot reshape array of size 92262 into shape (30754,4)

It seems a simple error but I am a newbie. It would be appreciated if you could help me.

**Pull request merged**
