### PR TITLE
Added notes about command execution to build_windows.md documentation

### PR DESCRIPTION
**Pull request by nesjett**
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3049)

### CODE REVIEW

**Comment by nesjett** [comment]
> > _[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3049)_ status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nesjett and @sergi-e)
> 
> _[Docs/build_windows.md, line 32 at r1](https://reviewable.io/reviews/carla-simulator/carla/3049#-MD-wvPEAIIEHi33jxYz:-MD-wvPFBfliq44gZp6k:b-upspwo) ([raw file](https://github.com/carla-simulator/carla/blob/71c8265e6126a74b79a1e2046594c51e3fca964b/Docs/build_windows.md#L32)):_
> 
> > ```gfm
> > !!! Important
> >     To execute the "make" commands below, you MUST use the Visual Studio 2017 native console x64 WITH administrator rights, otherwise you may be getting permission errors.
> > ```
> 
> Could you please change "make" to `make` (so that it is showed as code) and the words with capital letters to bold (like **must** or **with**).
> Thanks for the contribution!

Changes are made.
- Greetings

**Review by sergi-e — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3049)* status: all files reviewed, 1 unresolved discussion (waiting on @sergi-e)

**Review by sergi-e — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3049)* status: all files reviewed, 1 unresolved discussion (waiting on @sergi-e)

**Review by sergi-e — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3049)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
