### PR TITLE
sergi-e/faq-pythonpath

### PR DESCRIPTION
**Pull request by sergi-e**
#### Description

- New error in F.A.Q.: Added a fix for rpc error in Linux build. 

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04.4
  * **Python version(s):** 3.6.9
  * **Unreal Engine version(s):** 4.24

Fixes #  #1707

#### Possible Drawbacks

- Are there more user cases and solutions to this?

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3275)

### CODE REVIEW

**Review by doterop — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3275#-:-MGmwSCkAZYlvJHbH6Yn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bernatx)

**Review by doterop — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3275)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by doterop — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3275)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sergi-e)

**Review by bernatx — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3275)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sergi-e)

**Pull request merged**
