### PR TITLE
[Agents] CARLA Agents python package

### PR DESCRIPTION
**Pull request by joel-mb**
#### Description

This PR adds the generation of the python package for the CARLA agents library. Similarly to the CARLA PythonAPI it builds both the `egg` and the `whl` file. The package can be built using the `make agents` command.

The package will be published in `pypi` and users will be able to install it using `pip`:

```sh
pip install carla-agents
```

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04 and Windows 10
  * **Python version(s):** 2.7, 3.6, 3.7, 3.8
  * **Unreal Engine version(s):** 4.26

#### Possible Drawbacks

The code has been moved from `PythonAPI/carla/agents` to `PythonAPI/agents/source`. Therefore, users may have to modify their `PYTHONPATH` to accommodate this location folder change. Also, it is needed to update other libraries documentation (e.g., `scenario-runner`, `ros-bridge`) to reflect this change.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4645)

### CODE REVIEW

**Review by glopezdiest — APPROVED** [review]
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4645)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bernatx)

**Comment by glopezdiest** [comment]
From the user side, everything seems good. You can work with the PYTHONPATH the same way it was previously done (but changing the path itself), or you can install the library and forget about it.

**Review by bernatx — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4645)* status: all files reviewed, 1 unresolved discussion (waiting on @joel-mb)

___
*[Jenkinsfile, line 71 at r2](https://reviewable.io/reviews/carla-simulator/carla/4645#-MklbYeuBOIG732mXZFr:-MklbYeuBOIG732mXZFs:b-2q13q5) ([raw file](https://github.com/carla-simulator/carla/blob/90a368b1e63ca480d43e583247d997f8bd7f438b/Jenkinsfile#L71)):*
> ```
>                                     stash includes: 'PythonAPI/agents/dist/*.egg', name: 'agents_eggs'
>                                     stash includes: 'PythonAPI/agents/dist/*.whl', name: 'agents_wheels'
> ```
can you remove those two lines? we don't need them in stash, as Jenkins will not use them later on. We only need to archive them for the final .tar.gz or .zip

**Review by joel-mb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4645)* status: 29 of 31 files reviewed, 1 unresolved discussion (waiting on @bernatx and @joel-mb)

___
*[Jenkinsfile, line 71 at r2](https://reviewable.io/reviews/carla-simulator/carla/4645#-MklbYeuBOIG732mXZFr:-MkpGrmH5m-J9qJ504z1:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/90a368b1e63ca480d43e583247d997f8bd7f438b/Jenkinsfile#L71)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
>                                     stash includes: 'PythonAPI/agents/dist/*.egg', name: 'agents_eggs'
>                                     stash includes: 'PythonAPI/agents/dist/*.whl', name: 'agents_wheels'
> ```
can you remove those two lines? we don't need them in stash, as Jenkins will not use them later on. We only need to archive them for the final .tar.gz or .zip
</blockquote></details>

Done.

**Pull request closed without merging**
