### PR TITLE
[WIP][PythonAPI] Add support for PyPI builds, pip install carla

### LINKED ISSUE #81: Making Carla Installable with pip install
Dear all,

are there any plans to make it possible to install Carla with a simple

```
pip install carlapy
```

using Python wheels?

and then use it by importing it and having a carla server automatically started in the background?

That would make it easier to get started for newcomers :)

Do you foresee any challenges with this (licensing of the binary artifacts for example)?

-- Philipp.

cc @robertnishihara @pschafhalter @gy20073

### PR DESCRIPTION
**Pull request by praveen-palanisamy**
#### Description

- Added support to build PythonAPI for Python versions: 2.7, 3.4, 3.5, 3.6, 3.7
- Added support to build manylinux1, pip install-able wheels
- Updated `carla` python module setup script
- Added a simple README for the `carla` module, long_description generated based on the source's API tutorial and docs. See https://pypi.org/project/carla/0.9.4/ for the generated output

Fixes #81 

#### Where has this been tested?

  * **Platform(s):** Ubuntu
  * **Python version(s):** 2.7, 3.4, 3.5, 3.6, 3.7
  * **PyPI**: 
    - https://test.pypi.org/project/carla/
    - https://pypi.org/project/carla/0.9.4/
    - **`pip install carla`** tested to work on Ubuntu/Linux for CARLA 0.9.3, 0.9.4, 0.9.5 & above listed Python version. See: https://github.com/carla-simulator/carla/issues/81#issuecomment-488215940

#### Possible Drawbacks
- Needs modifications to the container images & CI-CD pipeline for automatic builds & deployment

#### To-Dos:

- [ ] Update container image & pipeline for auto builds
- [ ] Setup tox, twine deploy keys
- [ ] Update docs to reflect `pip install carla`
- [ ] Update CHANGELOG when ready to merge
- [ ] (optional, separate PR) Fix CPP source files/deps packaging & add sdist when standalone source builds are working

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/1608)

### CODE REVIEW

**Comment by qhaas** [comment]
Thanks!  This appears to work on CentOS7 with Python 3.6 from EPEL and CARLA 0.9.5.I am seeing that the PNG files being generated by the upstream 'PythonAPI/examples/tutorial.py' script are actually TIFFs.  On your build server, was a condition met such that `LIBCARLA_IMAGE_WITH_PNG_SUPPORT` was set to false during the build process?

**Comment by praveen-palanisamy** [comment]
Hey @qhaas! Yes, the PNG support was turned off intentionally during the build as there are existing, unresolved issues with libpng16 (dependency introduced by Boost GIL that's in use). See #924, #1270,..

**Comment by ThrashAbaddon** [comment]
Why are windows users not supported, is it maybe a huge effort?

**Comment by qhaas** [comment]
Hope there is continued interest in providing this for CARLA 0.9.6, it was quite handy for those of us using versions of Python other than those shipped with CARLA and not wanting to compile from scratch.

**Comment by germanros1987** [comment]
I know this has been around for a while and sorry that it's taking too long. We are not planning to let this die. We are planning to add full support for pip packages in each release soon. I will follow up on this.

**Pull request closed without merging**
