### PR TITLE
sergi-e/fix-docs-issues

### PR DESCRIPTION
**Pull request by sergi-e**
#### Description

Some fixes and new additions to the docs. 
- Improved docs for sync/async methods in the PythonAPI. 
- Fixed TM links.
- Added a note on sensors reference about coordinate system. 
- Updated README. 
- New tutorial on how to add new semantic segmentation tags. 

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04.4
  * **Python version(s):** 3.6.9
  * **Unreal Engine version(s):** 4.24

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3386)

### CODE REVIEW

**Review by Madecu — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3386)* status: all files reviewed, 1 unresolved discussion (waiting on @doterop, @marcgpuig, and @sergi-e)

___
*[Docs/tuto_D_create_semantic_tags.md, line 56 at r1](https://reviewable.io/reviews/carla-simulator/carla/3386#-MIZnVVA-43WusQyAEoV:-MIZnVVA-43WusQyAEoW:b-o7rvmu) ([raw file](https://github.com/carla-simulator/carla/blob/fb1ca3ef04108605c7464cf38e80c7e54d6bc302/Docs/tuto_D_create_semantic_tags.md#L56)):*
> ```
> the elements 
> ```
I would specify 'mesh' or 'staticmesh' instead of "Element". Because element can refer to a blueprint that is made by several staticmeshes that are in other folders so that bp would have the colors of those folders instead of the category that it is in. The same with skeletal meshes or other elements.

**Review by doterop — CHANGES_REQUESTED** [review]
> Reviewed 4 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3386)* status: all files reviewed, 2 unresolved discussions (waiting on @Madecu, @marcgpuig, and @sergi-e)

___
*[Docs/tuto_D_create_semantic_tags.md, line 37 at r1](https://reviewable.io/reviews/carla-simulator/carla/3386#-MIZtUW2EwxA-qieeDSs:-MIZtUW2EwxA-qieeDSt:bpx1fbb) ([raw file](https://github.com/carla-simulator/carla/blob/fb1ca3ef04108605c7464cf38e80c7e54d6bc302/Docs/tuto_D_create_semantic_tags.md#L37)):*
> ```Markdown
> ### 3. Create two-way correspondence between UE and the code tag
> 
> __3.1. Open `Tagger.cpp`__ in `Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game`. Go to __`GetLabelByFolderName`__ Add the your tag by the end of the list.  
> ```

I think is good to clarify that the string that is compared is the name of the UE folder.
___
*[Docs/tuto_D_create_semantic_tags.md, line 56 at r1](https://reviewable.io/reviews/carla-simulator/carla/3386#-MIZnVVA-43WusQyAEoV:-MI_88uf8I1S_ReCkebx:buez2vj) ([raw file](https://github.com/carla-simulator/carla/blob/fb1ca3ef04108605c7464cf38e80c7e54d6bc302/Docs/tuto_D_create_semantic_tags.md#L56)):*
<details><summary><i>Previously, Madecu (Marcos) wrote…</i></summary><blockquote>

> ```
> the elements 
> ```
I would specify 'mesh' or 'staticmesh' instead of "Element". Because element can refer to a blueprint that is made by several staticmeshes that are in other folders so that bp would have the colors of those folders instead of the category that it is in. The same with skeletal meshes or other elements.
</blockquote></details>

Agree, I think meshes is the best definition

**Review by sergi-e — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3386)* status: all files reviewed, 2 unresolved discussions (waiting on @doterop, @Madecu, and @marcgpuig)

___
*[Docs/tuto_D_create_semantic_tags.md, line 37 at r1](https://reviewable.io/reviews/carla-simulator/carla/3386#-MIZtUW2EwxA-qieeDSs:-MIcNrMO7VXMsbQw-cCa:b-886gsx) ([raw file](https://github.com/carla-simulator/carla/blob/fb1ca3ef04108605c7464cf38e80c7e54d6bc302/Docs/tuto_D_create_semantic_tags.md#L37)):*
<details><summary><i>Previously, doterop wrote…</i></summary><blockquote>

I think is good to clarify that the string that is compared is the name of the UE folder.
</blockquote></details>

Fixed
___
*[Docs/tuto_D_create_semantic_tags.md, line 56 at r1](https://reviewable.io/reviews/carla-simulator/carla/3386#-MIZnVVA-43WusQyAEoV:-MIcPIv4EB19a8eRt-fK:bfuvcmr) ([raw file](https://github.com/carla-simulator/carla/blob/fb1ca3ef04108605c7464cf38e80c7e54d6bc302/Docs/tuto_D_create_semantic_tags.md#L56)):*
<details><summary><i>Previously, doterop wrote…</i></summary><blockquote>

Agree, I think meshes is the best definition
</blockquote></details>

That's the clarification I needed, thanks a lot!

**Review by Madecu — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3386)* status: all files reviewed, 1 unresolved discussion (waiting on @doterop and @marcgpuig)

**Review by DSantosO — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3386)* status: all files reviewed, 1 unresolved discussion (waiting on @doterop, @DSantosO, and @marcgpuig)

**Review by DSantosO — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3386#-:-MIc_79LB4QxN3aX5ulw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @doterop, @DSantosO, and @marcgpuig)

**Review by doterop — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3386#-:-MJ1MvLk79TlMTT_r8XH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marcgpuig)

**Pull request merged**
