### PR TITLE
Demonstration of left-handed hack for LibCarla

### PR DESCRIPTION
**Pull request by jeffreykxiao**
#### Description

Hacked in some left-handed traffic assumptions into LibCarla. This changes the assumptions from right-handed traffic (default) to left-handed. As this is not a good change, it is in a draft PR for reference purposes and should never be merged. 

This doesn't resolve any issues but users who want to ONLY work on left-handed traffic can use this fix. 

#### Procedure

First, use RoadRunner and make a map with left-handed traffic (left-hand lanes should have "forward" travel direction, "backward" for right handed lanes), export with the left-hand setting.

1. Get this change
2. `make clean`
3. `make LibCarla` (builds this change. copying into CarlaUE4 and PythonAPI dependencies folder)
4. `make pythonAPI` (builds PythonAPI with this change)
5. `make launch` (starts CarlaUE4 with this change)
6. Import the xodr/fbx you generated (Don't use `make import` because it's broken on master, I rely on [this change that fixes that](https://github.com/carla-simulator/carla/pull/2390))
7. run example

#### Proposal

I created this to show that it's fairly simple to handle left-handed traffic, it's just blocked by some assumptions carla makes. I have some ideas for real support:
- Determine first what kind of left-handed support we want to give. I think it's a requirement to support RHT and LHT in the same build, but is it necessary to support RHT and LHT in the same MAP?
- Ask RoadRunner to update their OpenDrive spec. They are using Opendrive 1.4, but if RoadRunner updated to OpenDrive 1.5 spec from 1.4 and use the updated Road Header Record (http://opendrive.org/docs/OpenDRIVEFormatSpecRev1.5M.pdf, section 5.3.1, rule), it could get rid of the current `<UserData><VectorRoad travelDir=forward/backward>` setup. Then Carla would also be able to support the OpenDrive 1.5 format (instead of needing to specifically support the custom tag in the OpenDrive file produced by RoadRunner). 
- Carla needs to parse either the RoadRunner tag or the OpenDrive 1.5 RHR to determine the handedness of roads. If we don't expect to find LHT and RHT together in a map, as soon as we see a lane of positive lane ID + backward/forward, we can assume the traffic direction for the whole file. If not, then it gets a bit more complicated but still doable.
- When parsing the lanes, since we already check the contents of <left> <center> and <right> headers in OpenDrive, why don't we give Carla Roads more descriptive arrays of left/center/right lanes? 
- If we don't want to do that, can we at least make a helper function for checking the ID? I didn't do it this time, but it is weird to keep doing comparisons against the lane ID. Would be much better to be on a higher level of abstraction and have a clear function that does it instead of a lane ID comparison and a comment every time saying what it's all about.

#### Where has this been tested?

  * **Platform(s):** ... Windows 10 x64, Ubuntu 18.04
  * **Python version(s):** ... 3.6.9
  * **Unreal Engine version(s):** ... 4.22.3

#### Possible Drawbacks

It literally breaks all right-handed traffic maps on import and driving on left-handed maps, so it has a huge drawback.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/2442)

### CODE REVIEW

**Comment by gjossep** [comment]
Not sure If im doing something wrong, but after getting the files. Doing a make clean, and then make LibCarla I get the following error:
`LibCarla/source/carla/road/Map.cpp:582:30: error: out-of-line definition of 'GenerateWaypointsOnRoadEntries' does not match any declaration in 'carla::road::Map'
  std::vector<Waypoint> Map::GenerateWaypointsOnRoadEntries() const {
`

**Comment by jeffreykxiao** [comment]
@gjossep Hopefully I'll have some time next week to check this out. Maybe Map.cpp changed on master or something since I am seeing that I can't update this branch from github due to a merge conflict.

I cloned this branch directly and it works fine for me. Maybe you can do that, build libcarla and pythonapi, and copy the files into your own carla. If you're cherry-picking my change onto master I'm sure there could be some issues, but the merge conflict shouldn't be too difficult to solve either.

**Comment by germanros1987** [comment]
@jeffreykxiao kudos to you for this hack. Would you be interested in coordinating with the team to propose a proper solution that can stand the pass of time?

**Comment by joealan11** [comment]
Hello, I am very interested in making this work. I have been trying to adapt this to the new version of CARLA 0.9.9 but it seems that they made a lot of changes in the way they generate the waypoints. Have you had a look at the new version? any advice? 

My other option is to make the route planner work again in the new version, but I do not know if this is viable.

**Comment by kino3** [comment]
Hi, I am also very interested in this work. Is there any update? @jeffreykxiao @gjossep @germanros1987 @joealan11 @marcgpuig 
I searched the issues, but cannot found any feature requests of left-hand driving. [Many countries (like UK, Japan)](https://en.wikipedia.org/wiki/Left-_and_right-hand_traffic) adopt left-hand traffic, so I hope Carla will officially support left-hand traffic.

**Comment by jxzzhang** [comment]
> #### Description
> Hacked in some left-handed traffic assumptions into LibCarla. This changes the assumptions from right-handed traffic (default) to left-handed. As this is not a good change, it is in a draft PR for reference purposes and should never be merged.
> 
> This doesn't resolve any issues but users who want to ONLY work on left-handed traffic can use this fix.
> 
> #### Procedure
> First, use RoadRunner and make a map with left-handed traffic (left-hand lanes should have "forward" travel direction, "backward" for right handed lanes), export with the left-hand setting.
> 
> 1. Get this change
> 2. `make clean`
> 3. `make LibCarla` (builds this change. copying into CarlaUE4 and PythonAPI dependencies folder)
> 4. `make pythonAPI` (builds PythonAPI with this change)
> 5. `make launch` (starts CarlaUE4 with this change)
> 6. Import the xodr/fbx you generated (Don't use `make import` because it's broken on master, I rely on [this change that fixes that](https://github.com/carla-simulator/carla/pull/2390))
> 7. run example
> 
> #### Proposal
> I created this to show that it's fairly simple to handle left-handed traffic, it's just blocked by some assumptions carla makes. I have some ideas for real support:
> 
> * Determine first what kind of left-handed support we want to give. I think it's a requirement to support RHT and LHT in the same build, but is it necessary to support RHT and LHT in the same MAP?
> * Ask RoadRunner to update their OpenDrive spec. They are using Opendrive 1.4, but if RoadRunner updated to OpenDrive 1.5 spec from 1.4 and use the updated Road Header Record (http://opendrive.org/docs/OpenDRIVEFormatSpecRev1.5M.pdf, section 5.3.1, rule), it could get rid of the current `<UserData><VectorRoad travelDir=forward/backward>` setup. Then Carla would also be able to support the OpenDrive 1.5 format (instead of needing to specifically support the custom tag in the OpenDrive file produced by RoadRunner).
> * Carla needs to parse either the RoadRunner tag or the OpenDrive 1.5 RHR to determine the handedness of roads. If we don't expect to find LHT and RHT together in a map, as soon as we see a lane of positive lane ID + backward/forward, we can assume the traffic direction for the whole file. If not, then it gets a bit more complicated but still doable.
> * When parsing the lanes, since we already check the contents of   and  headers in OpenDrive, why don't we give Carla Roads more descriptive arrays of left/center/right lanes?
> * If we don't want to do that, can we at least make a helper function for checking the ID? I didn't do it this time, but it is weird to keep doing comparisons against the lane ID. Would be much better to be on a higher level of abstraction and have a clear function that does it instead of a lane ID comparison and a comment every time saying what it's all about.
> 
> #### Where has this been tested?
> * **Platform(s):** ... Windows 10 x64, Ubuntu 18.04
> * **Python version(s):** ... 3.6.9
> * **Unreal Engine version(s):** ... 4.22.3
> 
> #### Possible Drawbacks
> It literally breaks all right-handed traffic maps on import and driving on left-handed maps, so it has a huge drawback.
> 
> This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/2442)

Hi I am also looking into a left handed modification. have you be able to make it work on later version of Carla? thanks

**Pull request closed without merging**
