### PR TITLE
Fixes in landmarks

### PR DESCRIPTION
**Pull request by Axel1092**
#### Description

This PR fixes `waypoint.get_landmarks()` functions as landmarks with s = 0 were ignored.
It also removes any landmark with lane validity [0,0] as additional landmarks are created that do not affect any lane (useless landmarks).

#### Where has this been tested?

  * **Platform(s):** Ubuntu18
  * **Python version(s):** 3
  * **Unreal Engine version(s):** 4.24

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3506)

### CODE REVIEW

**Review by joel-mb — DISMISSED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3506)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marcgpuig)

**Review by marcgpuig — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3506)* status: all files reviewed, 3 unresolved discussions (waiting on @Axel1092)

___
*[LibCarla/source/carla/road/Map.cpp, line 346 at r2](https://reviewable.io/reviews/carla-simulator/carla/3506#-MLMogjW9bGNrGfy3_4V:-MLMofPV401X_BUnG-mT:byuyuod) ([raw file](https://github.com/carla-simulator/carla/blob/738fae250552575c639f1721ab20a6cd48379c48/LibCarla/source/carla/road/Map.cpp#L346)):*
> ```
> SignalSearchData signal_data{signal, signal_waypoint, distance_to_signal};
> ```
this `signal_waypoint` is not really needed and changing this part a bit, it may save some copies
___
*[LibCarla/source/carla/road/MapBuilder.h, line 370 at r2](https://reviewable.io/reviews/carla-simulator/carla/3506#-MLMp4R65ysLTJYb5On6:-MLMp4R73eMQyNzFjepa:b-k56btm) ([raw file](https://github.com/carla-simulator/carla/blob/738fae250552575c639f1721ab20a6cd48379c48/LibCarla/source/carla/road/MapBuilder.h#L370)):*
> ```
>  /// Generates a default validity field for signal references with missing validity record in OpenDRIVE
> ```
This comment is a copy of the top one, can you explain what this function does and why?
___
*[LibCarla/source/carla/road/MapBuilder.cpp, line 993 at r2](https://reviewable.io/reviews/carla-simulator/carla/3506#-MLMpO359mHMuCrIadl1:-MLMpO359mHMuCrIadl2:b-p7m0ed) ([raw file](https://github.com/carla-simulator/carla/blob/738fae250552575c639f1721ab20a6cd48379c48/LibCarla/source/carla/road/MapBuilder.cpp#L993)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>             if (info_ptr.get() == element) {
>               return true;
>             }
>             return false;
> ```
</details>

`return (info_ptr.get() == element)`

**Review by Axel1092 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3506)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @joel-mb and @marcgpuig)

___
*[LibCarla/source/carla/road/Map.cpp, line 346 at r2](https://reviewable.io/reviews/carla-simulator/carla/3506#-MLMogjW9bGNrGfy3_4V:-MLN_E9CCtvVqvRwI_Te:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/738fae250552575c639f1721ab20a6cd48379c48/LibCarla/source/carla/road/Map.cpp#L346)):*
<details><summary><i>Previously, marcgpuig (Marc Garcia Puig) wrote…</i></summary><blockquote>

> ```
> SignalSearchData signal_data{signal, signal_waypoint, distance_to_signal};
> ```
this `signal_waypoint` is not really needed and changing this part a bit, it may save some copies
</blockquote></details>

Done.
___
*[LibCarla/source/carla/road/MapBuilder.h, line 370 at r2](https://reviewable.io/reviews/carla-simulator/carla/3506#-MLMp4R65ysLTJYb5On6:-MLN_EZW8LaRoUXrG4cS:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/738fae250552575c639f1721ab20a6cd48379c48/LibCarla/source/carla/road/MapBuilder.h#L370)):*
<details><summary><i>Previously, marcgpuig (Marc Garcia Puig) wrote…</i></summary><blockquote>

> ```
>  /// Generates a default validity field for signal references with missing validity record in OpenDRIVE
> ```
This comment is a copy of the top one, can you explain what this function does and why?
</blockquote></details>

Done.
___
*[LibCarla/source/carla/road/MapBuilder.cpp, line 993 at r2](https://reviewable.io/reviews/carla-simulator/carla/3506#-MLMpO359mHMuCrIadl1:-MLN_F9J1t4EgmVb12KG:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/738fae250552575c639f1721ab20a6cd48379c48/LibCarla/source/carla/road/MapBuilder.cpp#L993)):*
<details><summary><i>Previously, marcgpuig (Marc Garcia Puig) wrote…</i></summary><blockquote>

> ```
>             if (info_ptr.get() == element) {
>               return true;
>             }
>             return false;
> ```
`return (info_ptr.get() == element)`
</blockquote></details>

Done.

**Review by marcgpuig — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 3 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3506#-:-MLNaxCJ5dY4dl05pGsi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
