### PR TITLE
Ros bridge fixes

### PR DESCRIPTION
**Pull request by danil-tolkachev**
#### Description

This pull request fixing several bugs in the ros bridge:
- [x] fixing typo with lidar timestamp
- [x] fixing object bounding box size and transformation (using `bounding_box.transform`)
- [x] fixing calibration errors for nonzero roll and pitch angles

#### Where has this been tested?

  * **Platform(s):** Ubuntu 16.04
  * **Python version(s):** 2.7
  * **Unreal Engine version(s):** ...

#### Possible Drawbacks

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/527)

### CODE REVIEW

**Comment by danil-tolkachev** [comment]
Amend last commit because a typo. @laurent-george, could you review other changes, please?

**Comment by laurent-george** [comment]
Review status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @danil-tolkachev)

---

*[carla_ros_bridge/src/carla_ros_bridge/sensors.py, line 107 at r1](https://reviewable.io/reviews/carla-simulator/carla/527#-LFqJ0Ee9a8vsNqJ_Ebd:-LFqJ0Ee9a8vsNqJ_Ebe:b-k19fg7) ([raw file](https://github.com/carla-simulator/carla/blob/4120618132fdc73728b862726332c761b1bcc7f1/carla_ros_bridge/src/carla_ros_bridge/sensors.py#L107)):*
> ```Python
> 
>         t = TransformStamped()
>         t.header.stamp = cur_time
> ```

Yeah ! (well spotted)

---

*[carla_ros_bridge/src/carla_ros_bridge/sensors.py, line 118 at r1](https://reviewable.io/reviews/carla-simulator/carla/527#-LFqJMUB4ucFLW-hV6U9:-LFqJMUB4ucFLW-hV6UA:b-xif1lo) ([raw file](https://github.com/carla-simulator/carla/blob/4120618132fdc73728b862726332c761b1bcc7f1/carla_ros_bridge/src/carla_ros_bridge/sensors.py#L118)):*
> ```Python
>         quat = [r.x, r.y, r.z, r.w]
>         roll, pitch, yaw = tf.transformations.euler_from_quaternion(quat)
>         quat = tf.transformations.quaternion_from_euler(0, 0, yaw)
> ```

Great, works fine now.

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/527)*

**Comment by laurent-george** [comment]
Review status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @danil-tolkachev)

---

*[carla_ros_bridge/src/carla_ros_bridge/markers.py, line 139 at r1](https://reviewable.io/reviews/carla-simulator/carla/527#-LFqJZjiAztxuaDstVIL:-LFqJZjiAztxuaDstVIM:b-a3ud78) ([raw file](https://github.com/carla-simulator/carla/blob/4120618132fdc73728b862726332c761b1bcc7f1/carla_ros_bridge/src/carla_ros_bridge/markers.py#L139)):*
> ```Python
>     """
>     ros_transform = carla_transform_to_ros_transform(
>         carla_Transform(object.bounding_box.transform) *
> ```

Ok, nice, I missed that, now no more need of bumping the box, etc.

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/527)*

**Comment by laurent-george** [comment]
Nice, with your modification the lidar now works fine (and it works when there is a pitch/yaw difference between lidar and camera, so this contribuation is really great).

---

Review status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @danil-tolkachev)

---



*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/527#-:-LFqJgc9Czw0yKEFHfq_:b-vl0lpc)*

**Comment by laurent-george** [comment]
Review status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @danil-tolkachev)

---

*[carla_ros_bridge/src/carla_ros_bridge/markers.py, line 128 at r1](https://reviewable.io/reviews/carla-simulator/carla/527#-LFqK1GD9JL81KZQAvp4:-LFqK1GD9JL81KZQAvp5:blddlq) ([raw file](https://github.com/carla-simulator/carla/blob/c4dd6794fc8a2eb32025425cc322d28a578692d3/carla_ros_bridge/src/carla_ros_bridge/markers.py#L128)):*
> ```
>     if not is_player:  # related to bug request #322
>         marker.scale.x = marker.scale.x / 100.0
>         marker.scale.y = marker.scale.y / 100.0
> ```
Similar to pullrequest #518  (which was also fine)

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/527)*

**Comment by laurent-george** [comment]
@danil-tolkachev  thanks for your code, but as I am not part of carla dev team, it needed it to be reviewed by @nsubiron or @germanros1987.
In my point of view this pull request should be merged (I tested it on my computer, it works fine).

**Comment by danil-tolkachev** [comment]
@marcgpuig, should I rebase on master or squash commits?

**Comment by marcgpuig** [comment]
Just rebase thanks!

**Comment by danil-tolkachev** [comment]
OK, done!

**Comment by marcgpuig** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed, 4 unresolved discussions (waiting on @danil-tolkachev)

---



*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/527)*

**Comment by marcgpuig** [comment]
:lgtm:

---

Review status: all files reviewed, 4 unresolved discussions (waiting on @danil-tolkachev)

---



*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/527#-:-LFrbYEa7k6l33seJ0xW:bnfp4nl)*

**Comment by danil-tolkachev** [comment]
Review status: all files reviewed, 4 unresolved discussions (waiting on @laurent-george)

---

*[carla_ros_bridge/src/carla_ros_bridge/markers.py, line 128 at r1](https://reviewable.io/reviews/carla-simulator/carla/527#-LFqK1GD9JL81KZQAvp4:-LFrdjXI7V6dlbKq78PM:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/c4dd6794fc8a2eb32025425cc322d28a578692d3/carla_ros_bridge/src/carla_ros_bridge/markers.py#L128)):*
<details><summary><i>Previously, laurent-george (George Laurent) wrote…</i></summary><blockquote>

> ```
>     if not is_player:  # related to bug request #322
>         marker.scale.x = marker.scale.x / 100.0
>         marker.scale.y = marker.scale.y / 100.0
> ```
Similar to pullrequest #518  (which was also fine)
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/carla_ros_bridge/markers.py, line 139 at r1](https://reviewable.io/reviews/carla-simulator/carla/527#-LFqJZjiAztxuaDstVIL:-LFrdlqF4c112niPUAYh:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/4120618132fdc73728b862726332c761b1bcc7f1/carla_ros_bridge/src/carla_ros_bridge/markers.py#L139)):*
<details><summary><i>Previously, laurent-george (George Laurent) wrote…</i></summary><blockquote>

Ok, nice, I missed that, now no more need of bumping the box, etc.
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/carla_ros_bridge/sensors.py, line 107 at r1](https://reviewable.io/reviews/carla-simulator/carla/527#-LFqJ0Ee9a8vsNqJ_Ebd:-LFrdn-W6rZ5cwWUuGg5:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/4120618132fdc73728b862726332c761b1bcc7f1/carla_ros_bridge/src/carla_ros_bridge/sensors.py#L107)):*
<details><summary><i>Previously, laurent-george (George Laurent) wrote…</i></summary><blockquote>

Yeah ! (well spotted)
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/carla_ros_bridge/sensors.py, line 118 at r1](https://reviewable.io/reviews/carla-simulator/carla/527#-LFqJMUB4ucFLW-hV6U9:-LFrdo7oD1BOXczz5_-f:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/4120618132fdc73728b862726332c761b1bcc7f1/carla_ros_bridge/src/carla_ros_bridge/sensors.py#L118)):*
<details><summary><i>Previously, laurent-george (George Laurent) wrote…</i></summary><blockquote>

Great, works fine now.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/527)*

**Comment by danil-tolkachev** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed, 4 unresolved discussions (waiting on @laurent-george)

---



*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/527)*

**Comment by danil-tolkachev** [comment]
Oops. It seems I'm a little confused with Reviewable =)

**Comment by marcgpuig** [comment]
It's tricky when you use it for the first time ;)
Now I think it's @laurent-george's turn to acknowledge those changes that he proposed.

**Comment by laurent-george** [comment]
done

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/527#-:-LFrmhLmEQ4KGOO41rEp:bb7f2mf)*

**Pull request merged**
