### PR TITLE
Corkyw10/scenic tutorial

### PR DESCRIPTION
**Pull request by corkyw10**
# Scenic tutorial

I have created a tutorial to explain:

- The minimum requirements needed to run a Scenic script on CARLA.
- How to write a simple scenario definition using one of the examples (carlaChallenge2) in the Scenic repo as an outline
- How to run a Scenic script on CARLA.
- Parameters used to configure Scenic simulations on CARLA.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3986)

### CODE REVIEW

**Review by glopezdiest — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3986)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @corkyw10 and @joel-mb)

___
*[Docs/tuto_G_scenic.md, line 3 at r1](https://reviewable.io/reviews/carla-simulator/carla/3986#-MW43iWwD2sxJekt0cfE:-MW43iWwD2sxJekt0cfF:b5bns88) ([raw file](https://github.com/carla-simulator/carla/blob/80ac5ad632fefbc7216eac8d395ca3ca876391ad/Docs/tuto_G_scenic.md#L3)):*
> ```
> [simple]
> ```
I think they are called static scenarios
___
*[Docs/tuto_G_scenic.md, line 36 at r1](https://reviewable.io/reviews/carla-simulator/carla/3986#-MW492RfAWT-hwW9hPXr:-MW492Rg4pehYv9Xj7kF:b-dh0j8r) ([raw file](https://github.com/carla-simulator/carla/blob/80ac5ad632fefbc7216eac8d395ca3ca876391ad/Docs/tuto_G_scenic.md#L36)):*
> ```
> [`map`][scenic_map]
> ```
Not an issue but what does this do? Is it some kind of link?
___
*[Docs/tuto_G_scenic.md, line 37 at r1](https://reviewable.io/reviews/carla-simulator/carla/3986#-MW49Irz-tmj_4_-dw90:-MW49Irz-tmj_4_-dw91:b-32h4sf) ([raw file](https://github.com/carla-simulator/carla/blob/80ac5ad632fefbc7216eac8d395ca3ca876391ad/Docs/tuto_G_scenic.md#L37)):*
> ```
> If this is not defined then the `.xodr` file in `map` will also be used to generate the simulation map.
> ```
I don't know if it's worth mentioning but the first time I read it, it felt confusing. By having the `carla_map`, Scenic will load all the assets of the map (buildings, trees...), whereas without it, the OpenDRIVE standalone mode will be used.
___
*[Docs/tuto_G_scenic.md, line 67 at r1](https://reviewable.io/reviews/carla-simulator/carla/3986#-MW4D_kj8nhxlW5uPq5h:-MW4D_kk2OuYFYvL6q4w:b-ze4xua) ([raw file](https://github.com/carla-simulator/carla/blob/80ac5ad632fefbc7216eac8d395ca3ca876391ad/Docs/tuto_G_scenic.md#L67)):*
> ```
> as well as the CARLA specific [behaviours library]
> ```
this isn't understood from the links. Scenic has its own behaviors which can be used by any simulator (first link). Additionally, each simulator can additionally have their own behaviors, using their own API (second link).

**Review by corkyw10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3986)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @glopezdiest and @joel-mb)

___
*[Docs/tuto_G_scenic.md, line 3 at r1](https://reviewable.io/reviews/carla-simulator/carla/3986#-MW43iWwD2sxJekt0cfE:-MW8xSz62dkOmcNBwf7n:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/80ac5ad632fefbc7216eac8d395ca3ca876391ad/Docs/tuto_G_scenic.md#L3)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> [simple]
> ```
I think they are called static scenarios
</blockquote></details>

Done.
___
*[Docs/tuto_G_scenic.md, line 36 at r1](https://reviewable.io/reviews/carla-simulator/carla/3986#-MW492RfAWT-hwW9hPXr:-MW8x5_y9Q4m96QeCkZ4:b-j8qkwt) ([raw file](https://github.com/carla-simulator/carla/blob/80ac5ad632fefbc7216eac8d395ca3ca876391ad/Docs/tuto_G_scenic.md#L36)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> [`map`][scenic_map]
> ```
Not an issue but what does this do? Is it some kind of link?
</blockquote></details>

Yeah it's a different way of defining a link because I used this link twice. The URL is defined on line 47
___
*[Docs/tuto_G_scenic.md, line 37 at r1](https://reviewable.io/reviews/carla-simulator/carla/3986#-MW49Irz-tmj_4_-dw90:-MW8yJlD4863CKFWUYR-:b-9kojf7) ([raw file](https://github.com/carla-simulator/carla/blob/80ac5ad632fefbc7216eac8d395ca3ca876391ad/Docs/tuto_G_scenic.md#L37)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> If this is not defined then the `.xodr` file in `map` will also be used to generate the simulation map.
> ```
I don't know if it's worth mentioning but the first time I read it, it felt confusing. By having the `carla_map`, Scenic will load all the assets of the map (buildings, trees...), whereas without it, the OpenDRIVE standalone mode will be used.
</blockquote></details>

Done. I updated the sentence to reflect your comment.
___
*[Docs/tuto_G_scenic.md, line 67 at r1](https://reviewable.io/reviews/carla-simulator/carla/3986#-MW4D_kj8nhxlW5uPq5h:-MW99gW9Bu9Y8oHt521W:b-mz6lko) ([raw file](https://github.com/carla-simulator/carla/blob/80ac5ad632fefbc7216eac8d395ca3ca876391ad/Docs/tuto_G_scenic.md#L67)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> as well as the CARLA specific [behaviours library]
> ```
this isn't understood from the links. Scenic has its own behaviors which can be used by any simulator (first link). Additionally, each simulator can additionally have their own behaviors, using their own API (second link).
</blockquote></details>

Done. I have moved this information to a separate section at the beginning of the guide because it feels a bit clunky to have it here in the middle. Let me know what you think

**Review by glopezdiest — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3986)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @corkyw10 and @joel-mb)

___
*[Docs/tuto_G_scenic.md, line 49 at r2](https://reviewable.io/reviews/carla-simulator/carla/3986#-MW9GwXcE0p6XXU-Q7F6:-MW9GwXcE0p6XXU-Q7F7:bl5i4ee) ([raw file](https://github.com/carla-simulator/carla/blob/b396847acaa694101b6fc4af2803b74acce1ce2f/Docs/tuto_G_scenic.md#L49)):*
> ```
> if this is not defined
> ```
and if not, then...

**Review by corkyw10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3986)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @glopezdiest and @joel-mb)

___
*[Docs/tuto_G_scenic.md, line 49 at r2](https://reviewable.io/reviews/carla-simulator/carla/3986#-MW9GwXcE0p6XXU-Q7F6:-MW9Il5mEUi2qRP0qrq4:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/b396847acaa694101b6fc4af2803b74acce1ce2f/Docs/tuto_G_scenic.md#L49)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> if this is not defined
> ```
and if not, then...
</blockquote></details>

Done.

**Review by glopezdiest — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3986)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @joel-mb)

**Review by joel-mb — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3986)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @corkyw10)

___
*[Docs/tuto_G_scenic.md, line 31 at r3](https://reviewable.io/reviews/carla-simulator/carla/3986#-MW9kOg_BTGweXwCriKp:-MW9kOg_BTGweXwCriKq:b-1qksgs) ([raw file](https://github.com/carla-simulator/carla/blob/e6289e25d594998a6535be2f089f8357d4fe948f/Docs/tuto_G_scenic.md#L31)):*
> ```Markdown
> ---
> 
> ## Scenic Libraries
> ```

This sections sounds weird to me. Instead of "libraries" I would talk about "interfaces" or "domains".

The idea is that Scenic has one general driving domain that can be used by all the simulators and then has a specific domain for each simulator.

General driving domain (can be used with all the simulators): https://scenic-lang.readthedocs.io/en/latest/modules/scenic.domains.driving.html
Specific CARLA simulator (only can be used with CARLA simulator): https://scenic-lang.readthedocs.io/en/latest/modules/scenic.simulators.carla.html

Inside each domain the most important points for the user are behaviours and actions. The driving domain defines behaviours and actions that can be used across simulators and then the CARLA simulator domain defines other behaviours and actions that only can be used within CARLA. Here some links:

* Actions driving domain: https://scenic-lang.readthedocs.io/en/latest/modules/scenic.domains.driving.actions.html
* Actions CARLA domain: https://scenic-lang.readthedocs.io/en/latest/modules/scenic.simulators.carla.actions.html#module-scenic.simulators.carla.actions

* Behaviours driving domain: https://scenic-lang.readthedocs.io/en/latest/modules/scenic.domains.driving.behaviors.html
* Behaviours CARLA simulator: https://scenic-lang.readthedocs.io/en/latest/modules/scenic.simulators.carla.behaviors.html

Apart from that, everything looks good to me!

**Review by joel-mb — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3986)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corkyw10)

**Pull request merged**
