### PR TITLE
[NO_BUILD] Missing Python API docs

### PR DESCRIPTION
**Pull request by corkyw10**
Methods added and who should check them please:

Bernat:
- `client.set_replayer_ignore_hero`
- `client.set_files_base_folder`
- `client.get_required_files`
- `client.request_file`
- `map.get_crosswalks`

Santos:
- `actor.set_enable_gravity`
- `actor.show_debug_telemetry`
- `command.SetEnableGravity`
- `command.ShowDebugTelemetry`
- `vector3d.__abs__`
- `location.__abs__`
- `VehiclePhysicsControl.methods`

Roel:
- `WeatherParams.scattering_intensity`
- `WeatherParams.scattering_intensity`
- `WeatherParams.rayleigh_scattering_scale`

Jacopo:
- `TrafficManager.set_boundaries_respawn_dormant_vehicles`
- `TrafficManager.set_respawn_dormant_vehicles`

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4453)

### CODE REVIEW

**Review by jackbart94 — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4453)* status: 1 of 8 files reviewed, all discussions resolved (waiting on @algababr, @bernatx, and @DSantosO)

**Review by DSantosO — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4453)* status: 5 of 8 files reviewed, all discussions resolved (waiting on @algababr and @bernatx)

**Review by algababr — COMMENTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4453)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @bernatx)

**Review by bernatx — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4453#-:-Mfh7La85GKRRkVSccxC:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @corkyw10)

___
*[Docs/python_api.md, line 520 at r4](https://reviewable.io/reviews/carla-simulator/carla/4453#-Mfh7goR31UxXWL2GsOz:-Mfh7goSDLMXO_jdewF2:b49astr) ([raw file](https://github.com/carla-simulator/carla/blob/13ff3eb3c7eb3817d198bb54c29f2ca04d89352b/Docs/python_api.md#L520)):*
> ```
> Folder where files required by the client will be downloaded t
> ```

**Pull request merged**
