### PR TITLE
sergi-e/tm-determinism-and-updates-docs

### PR DESCRIPTION
**Pull request by sergi-e**
#### Description

- New additions for carla.TrafficManager in the PythonAPI reference. 

- Updated "Other considerations" section in adv_tm.md:
   - Removed "FPS limitations". 
   - Updated "Synchronous mode". 

- TBD: Determinism for TM docs. 

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04.4
  * **Python version(s):** 3.6.9
  * **Unreal Engine version(s):** 4.24

#### Possible Drawbacks

- Check PythonAPI docs for discrepancies on TM 2.0 architecture.
- Should a note be added in adv_synchrony_timestep.md regarding TM.set_synchronous_mode()?

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3453)

### CODE REVIEW

**Review by jackbart94 — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3453)* status: all files reviewed, 5 unresolved discussions (waiting on @sergi-e)

___
*[Docs/adv_traffic_manager.md, line 310 at r2](https://reviewable.io/reviews/carla-simulator/carla/3453#-MJk_fV45LRIquqH_DDP:-MJk_fV525CM63IWsKbc:bk9zqgo) ([raw file](https://github.com/carla-simulator/carla/blob/8168f9f3f3ddaf92f161c3c3243b9b631d2876d2/Docs/adv_traffic_manager.md#L310)):*
> ```
> for
> ```
under
___
*[Docs/adv_traffic_manager.md, line 310 at r2](https://reviewable.io/reviews/carla-simulator/carla/3453#-MJk_kZcC1x-QL8-VZur:-MJk_kZcC1x-QL8-VZus:b-lpk8jp) ([raw file](https://github.com/carla-simulator/carla/blob/8168f9f3f3ddaf92f161c3c3243b9b631d2876d2/Docs/adv_traffic_manager.md#L310)):*
> ```
> Do not mistake determinism with the recorder. The recorder stores all the information of a simulation so it can be played back. Determinism does not involve any log nor recording, and produces different outputs for different conditions.
> ```

This whole paragraph can be rephrased, especially the last sentence. For example:

Do not mistake determinism with the recorder. While the recorder allows you to store the log of a simulation to play it back, determinism ensures that Traffic Manager will always have the same output over different executions of a script, if the same conditions are maintained. 
___
*[Docs/adv_traffic_manager.md, line 312 at r2](https://reviewable.io/reviews/carla-simulator/carla/3453#-MJkaqQE2FA8vxCI2fxF:-MJkaqQE2FA8vxCI2fxG:b-3z4ank) ([raw file](https://github.com/carla-simulator/carla/blob/8168f9f3f3ddaf92f161c3c3243b9b631d2876d2/Docs/adv_traffic_manager.md#L312)):*
> ```
> In asynchronous mode, there is much less control over the simulation, and a deterministic behaviour cannot be guaranteed.
> ```

Not only it can't be guaranteed, it literally doesn't happen ahah
___
*[Docs/adv_traffic_manager.md, line 327 at r2](https://reviewable.io/reviews/carla-simulator/carla/3453#-MJkb0Xo9qMivjZX4PwW:-MJkb0Xo9qMivjZX4PwX:b-utqllf) ([raw file](https://github.com/carla-simulator/carla/blob/8168f9f3f3ddaf92f161c3c3243b9b631d2876d2/Docs/adv_traffic_manager.md#L327)):*
> ```
> --sed 9
> ```
--seed 9

(or -s 9)
___
*[Docs/python_api.md, line 2095 at r2](https://reviewable.io/reviews/carla-simulator/carla/3453#-MJkuZhN7IHXOfjXRjfu:-MJkuZhN7IHXOfjXRjfv:boqlw62) ([raw file](https://github.com/carla-simulator/carla/blob/8168f9f3f3ddaf92f161c3c3243b9b631d2876d2/Docs/python_api.md#L2095)):*
> ```
> a deterministic system.·
> ```
deterministic.

**Review by sergi-e — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3453)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @jackbart94)

___
*[Docs/adv_traffic_manager.md, line 310 at r2](https://reviewable.io/reviews/carla-simulator/carla/3453#-MJk_fV45LRIquqH_DDP:-MJlzdl298llfUwNKjC7:b-886gsx) ([raw file](https://github.com/carla-simulator/carla/blob/8168f9f3f3ddaf92f161c3c3243b9b631d2876d2/Docs/adv_traffic_manager.md#L310)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

> ```
> for
> ```
under
</blockquote></details>

Fixed
___
*[Docs/adv_traffic_manager.md, line 310 at r2](https://reviewable.io/reviews/carla-simulator/carla/3453#-MJk_kZcC1x-QL8-VZur:-MJm-g6G6ZqczWaTwAg8:b-az01xo) ([raw file](https://github.com/carla-simulator/carla/blob/8168f9f3f3ddaf92f161c3c3243b9b631d2876d2/Docs/adv_traffic_manager.md#L310)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

> ```
> Do not mistake determinism with the recorder. The recorder stores all the information of a simulation so it can be played back. Determinism does not involve any log nor recording, and produces different outputs for different conditions.
> ```

This whole paragraph can be rephrased, especially the last sentence. For example:

Do not mistake determinism with the recorder. While the recorder allows you to store the log of a simulation to play it back, determinism ensures that Traffic Manager will always have the same output over different executions of a script, if the same conditions are maintained. 
</blockquote></details>

Replaced! 
___
*[Docs/adv_traffic_manager.md, line 312 at r2](https://reviewable.io/reviews/carla-simulator/carla/3453#-MJkaqQE2FA8vxCI2fxF:-MJlzyEn6KBlF6Rlm5xY:b-ffj78i) ([raw file](https://github.com/carla-simulator/carla/blob/8168f9f3f3ddaf92f161c3c3243b9b631d2876d2/Docs/adv_traffic_manager.md#L312)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

> ```
> In asynchronous mode, there is much less control over the simulation, and a deterministic behaviour cannot be guaranteed.
> ```

Not only it can't be guaranteed, it literally doesn't happen ahah
</blockquote></details>

Modified to "...determinism cannot be achieved"?
___
*[Docs/adv_traffic_manager.md, line 327 at r2](https://reviewable.io/reviews/carla-simulator/carla/3453#-MJkb0Xo9qMivjZX4PwW:-MJm-764EoJkHYsccx0F:b-886gsx) ([raw file](https://github.com/carla-simulator/carla/blob/8168f9f3f3ddaf92f161c3c3243b9b631d2876d2/Docs/adv_traffic_manager.md#L327)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

> ```
> --sed 9
> ```
--seed 9

(or -s 9)
</blockquote></details>

Fixed
___
*[Docs/python_api.md, line 2095 at r2](https://reviewable.io/reviews/carla-simulator/carla/3453#-MJkuZhN7IHXOfjXRjfu:-MJm-FhbDGtdC7dDeqEZ:bt2vr1b) ([raw file](https://github.com/carla-simulator/carla/blob/8168f9f3f3ddaf92f161c3c3243b9b631d2876d2/Docs/python_api.md#L2095)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

> ```
> a deterministic system.·
> ```
deterministic.
</blockquote></details>

Fixed.

**Review by jackbart94 — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3453)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[Docs/adv_traffic_manager.md, line 312 at r2](https://reviewable.io/reviews/carla-simulator/carla/3453#-MJkaqQE2FA8vxCI2fxF:-MK4lVf33IfPAiv_8l_I:brxp9sd) ([raw file](https://github.com/carla-simulator/carla/blob/8168f9f3f3ddaf92f161c3c3243b9b631d2876d2/Docs/adv_traffic_manager.md#L312)):*
<details><summary><i>Previously, sergi-e (sergi.e) wrote…</i></summary><blockquote>

Modified to "...determinism cannot be achieved"?
</blockquote></details>

Sounds good!

**Review by jackbart94 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3453)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jackbart94 — APPROVED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3453)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
