### PR TITLE
 Changes default behavior for OSM parameter in TM

### PR DESCRIPTION
**Pull request by jackbart94**
#### Description

The OSM parameter is now True by default, meaning that each vehicle that has no next() will be deleted. In case an user turns this parameter off and executes TM on an OSM map, a warning to turn on the parameter is sent, without however launching an exception.

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18
  * **Python version(s):** Python 3.6
  * **Unreal Engine version(s):** 4.24

#### Possible Drawbacks

 None

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3355)

### CODE REVIEW

**Review by Axel1092 — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3355)* status: all files reviewed, 1 unresolved discussion (waiting on @jackbart94 and @pravinblaze)

___
*[LibCarla/source/carla/trafficmanager/LocalizationStage.cpp, line 173 at r2](https://reviewable.io/reviews/carla-simulator/carla/3355#-MHvp2gB9K8EDpixs7Hf:-MHvp2gB9K8EDpixs7Hg:b5ijch1) ([raw file](https://github.com/carla-simulator/carla/blob/53835c1b84a0e5ba35aedbe40d338cc0ff78c159/LibCarla/source/carla/trafficmanager/LocalizationStage.cpp#L173)):*
> ```cpp
>     } else if (next_waypoints.size() == 0) {
>       if (!parameters.GetOSMMode()) {
>         std::cout << "This is an OSM, please change the set_open_street_map parameter to true" << std::endl;
> ```

I would change this message to something like "This map has open ended roads..."

**Review by Axel1092 — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3355)* status: all files reviewed, 1 unresolved discussion (waiting on @jackbart94 and @pravinblaze)

**Review by jackbart94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3355)* status: all files reviewed, 1 unresolved discussion (waiting on @Axel1092 and @pravinblaze)

___
*[LibCarla/source/carla/trafficmanager/LocalizationStage.cpp, line 173 at r2](https://reviewable.io/reviews/carla-simulator/carla/3355#-MHvp2gB9K8EDpixs7Hf:-MHvqqzl7oKZto6bhYQI:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/53835c1b84a0e5ba35aedbe40d338cc0ff78c159/LibCarla/source/carla/trafficmanager/LocalizationStage.cpp#L173)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

I would change this message to something like "This map has open ended roads..."
</blockquote></details>

Done.

**Review by bernatx — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3355)* status: all files reviewed, 1 unresolved discussion (waiting on @Axel1092)

**Review by bernatx — APPROVED** [review]
> Dismissed @Axel1092 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3355)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
