### PR TITLE
Adding load control on sublevels

### PR DESCRIPTION
**Pull request by doterop**
#### Description

There have been added two new functions to control the layers being loaded on the map: `load_map_layer` and `unload_map_layer`.
This only works in new maps that were created with sub-levelling in UE. Does not perform any actions in old maps.

There have been updated too the `load_world` to support this feature, so the client is able to configure the sublayers when the map is loaded.

To select the sublayers a new enum has been added `carla.MapLayer`. This enum works as a bitfield making it possible to select more than one layer at once.

The `manual_control.py` script has been updated with this feature, working as a testing scenario and example for users.

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04
  * **Python version(s):** 3
  * **Unreal Engine version(s):** 4.24

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3515)

### CODE REVIEW

**Review by marcgpuig — CHANGES_REQUESTED** [review]
> Reviewed 8 of 16 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3515)* status: 10 of 16 files reviewed, 9 unresolved discussions (waiting on @Axel1092, @doterop, @marcgpuig, and @XGodina)

___
*[LibCarla/source/carla/client/detail/Client.h, line 94 at r3](https://reviewable.io/reviews/carla-simulator/carla/3515#-MKpBRqcDFRddJLqDdTc:-MKpBRqcDFRddJLqDdTd:b-f0b8zg) ([raw file](https://github.com/carla-simulator/carla/blob/dfcfe9f37a5995eab1f2dfd2693e8566518a99e7/LibCarla/source/carla/client/detail/Client.h#L94)):*
> ```objc
>     std::string GetServerVersion();
> 
>     void LoadEpisode(std::string map_name, rpc::MapLayer map_layers);
> ```

What about a default value for the `map_layer` here too? Do you think it's needed.
___
*[LibCarla/source/carla/rpc/MapLayer.h, line 18 at r3](https://reviewable.io/reviews/carla-simulator/carla/3515#-MKpBJg86Dqjm-MHrTNv:-MKpBJg86Dqjm-MHrTNw:bq5kcta) ([raw file](https://github.com/carla-simulator/carla/blob/dfcfe9f37a5995eab1f2dfd2693e8566518a99e7/LibCarla/source/carla/rpc/MapLayer.h#L18)):*
> ```
> enum class MapLayer : uint16_t
> ```
enum class MapLayer : MapLayerType
___
*[PythonAPI/carla/source/libcarla/Client.cpp, line 184 at r3](https://reviewable.io/reviews/carla-simulator/carla/3515#-MKpBhs1AWhRrdNVcTtp:-MKpBhs1AWhRrdNVcTtq:bnexauq) ([raw file](https://github.com/carla-simulator/carla/blob/dfcfe9f37a5995eab1f2dfd2693e8566518a99e7/PythonAPI/carla/source/libcarla/Client.cpp#L184)):*
> ```
> arg("MapLayers")=rpc::MapLayer::All))
> ```
`arg("map_layers")=rpc::MapLayer::All))`
___
*[PythonAPI/carla/source/libcarla/World.cpp, line 241 at r3](https://reviewable.io/reviews/carla-simulator/carla/3515#-MKpBrDM3NBTmgZaU7gj:-MKpBrDM3NBTmgZaU7gk:bs850iw) ([raw file](https://github.com/carla-simulator/carla/blob/dfcfe9f37a5995eab1f2dfd2693e8566518a99e7/PythonAPI/carla/source/libcarla/World.cpp#L241)):*
> ```
> arg("MapLayers"))
> ```
`arg("map_layers"))`
___
*[PythonAPI/carla/source/libcarla/World.cpp, line 242 at r3](https://reviewable.io/reviews/carla-simulator/carla/3515#-MKpBu7D0SCtW5CcVjbN:-MKpBu7D0SCtW5CcVjbO:bs850iw) ([raw file](https://github.com/carla-simulator/carla/blob/dfcfe9f37a5995eab1f2dfd2693e8566518a99e7/PythonAPI/carla/source/libcarla/World.cpp#L242)):*
> ```
> arg("MapLayers"))
> ```
`arg("map_layers"))`
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameInstance.h, line 119 at r3](https://reviewable.io/reviews/carla-simulator/carla/3515#-MKpCJ3X3aBim_2yEb7L:-MKpCJ3X3aBim_2yEb7M:b-4cr62x) ([raw file](https://github.com/carla-simulator/carla/blob/dfcfe9f37a5995eab1f2dfd2693e8566518a99e7/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameInstance.h#L119)):*
> ```
> int32 CurrentMapLayer = static_cast<int32>(carla::rpc::MapLayer::All);
> ```
I think that MapLayerType is `uint16_t`, why is this `int32`? Maybe using something like:

`carla::rpc::MapLayer::MapLayerType CurrentMapLayer = static_cast<carla::rpc::MapLayer::MapLayerType>(carla::rpc::MapLayer::All);`

Do you have any better solution? Same for the others `int32`.
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.h, line 93 at r3](https://reviewable.io/reviews/carla-simulator/carla/3515#-MKpDWeFA3U88md1bs2d:-MKpDWeFA3U88md1bs2e:b-5gaokn) ([raw file](https://github.com/carla-simulator/carla/blob/dfcfe9f37a5995eab1f2dfd2693e8566518a99e7/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.h#L93)):*
> ```objc
>   void RegisterEnvironmentObject();
> 
>   void ConvertMapLayerMaskToMapNames(int32 MapLayer, TArray<FName>& OutLevelNames);
> ```

same int32
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp, line 31 at r3](https://reviewable.io/reviews/carla-simulator/carla/3515#-MKpEYoI1dOTo6UnUQ0F:-MKpEYoI1dOTo6UnUQ0G:bpyako5) ([raw file](https://github.com/carla-simulator/carla/blob/dfcfe9f37a5995eab1f2dfd2693e8566518a99e7/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp#L31)):*
> ```cpp
> namespace cre = carla::road::element;
> 
> static FString MapLayerToString(crp::MapLayer MapLayerValue)
> ```

what about moving this to MapLayer.h?
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp, line 283 at r3](https://reviewable.io/reviews/carla-simulator/carla/3515#-MKpEllO7Yrmi6S_nb-W:-MKpEllO7Yrmi6S_nb-X:b-nmgum2) ([raw file](https://github.com/carla-simulator/carla/blob/dfcfe9f37a5995eab1f2dfd2693e8566518a99e7/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp#L283)):*
> ```cpp
>       RESPOND_ERROR("unable to find CARLA game mode");
>     }
>     GameMode->UnLoadMapLayer(static_cast<int32>(MapLayers));
> ```

that `int32` here too

**Review by doterop — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3515#-:-MKpS1V94FYAutCJGAHI:b-qs70w8)* status: 10 of 16 files reviewed, 9 unresolved discussions (waiting on @Axel1092, @marcgpuig, and @XGodina)

___
*[LibCarla/source/carla/client/detail/Client.h, line 94 at r3](https://reviewable.io/reviews/carla-simulator/carla/3515#-MKpBRqcDFRddJLqDdTc:-MKpIGn81GSFxXF6BG6x:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/dfcfe9f37a5995eab1f2dfd2693e8566518a99e7/LibCarla/source/carla/client/detail/Client.h#L94)):*
<details><summary><i>Previously, marcgpuig (Marc Garcia Puig) wrote…</i></summary><blockquote>

What about a default value for the `map_layer` here too? Do you think it's needed.
</blockquote></details>

Done.
___
*[LibCarla/source/carla/rpc/MapLayer.h, line 18 at r3](https://reviewable.io/reviews/carla-simulator/carla/3515#-MKpBJg86Dqjm-MHrTNv:-MKpII8_3sbeHFeqh7Ys:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/dfcfe9f37a5995eab1f2dfd2693e8566518a99e7/LibCarla/source/carla/rpc/MapLayer.h#L18)):*
<details><summary><i>Previously, marcgpuig (Marc Garcia Puig) wrote…</i></summary><blockquote>

> ```
> enum class MapLayer : uint16_t
> ```
enum class MapLayer : MapLayerType
</blockquote></details>

Done.
___
*[PythonAPI/carla/source/libcarla/Client.cpp, line 184 at r3](https://reviewable.io/reviews/carla-simulator/carla/3515#-MKpBhs1AWhRrdNVcTtp:-MKpIUe12ot5OJlHPzKb:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/dfcfe9f37a5995eab1f2dfd2693e8566518a99e7/PythonAPI/carla/source/libcarla/Client.cpp#L184)):*
<details><summary><i>Previously, marcgpuig (Marc Garcia Puig) wrote…</i></summary><blockquote>

> ```
> arg("MapLayers")=rpc::MapLayer::All))
> ```
`arg("map_layers")=rpc::MapLayer::All))`
</blockquote></details>

Done.
___
*[PythonAPI/carla/source/libcarla/World.cpp, line 241 at r3](https://reviewable.io/reviews/carla-simulator/carla/3515#-MKpBrDM3NBTmgZaU7gj:-MKpIcczBMs604CAJHyZ:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/dfcfe9f37a5995eab1f2dfd2693e8566518a99e7/PythonAPI/carla/source/libcarla/World.cpp#L241)):*
<details><summary><i>Previously, marcgpuig (Marc Garcia Puig) wrote…</i></summary><blockquote>

> ```
> arg("MapLayers"))
> ```
`arg("map_layers"))`
</blockquote></details>

Done.
___
*[PythonAPI/carla/source/libcarla/World.cpp, line 242 at r3](https://reviewable.io/reviews/carla-simulator/carla/3515#-MKpBu7D0SCtW5CcVjbN:-MKpIcMPAKvBD8wasCkJ:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/dfcfe9f37a5995eab1f2dfd2693e8566518a99e7/PythonAPI/carla/source/libcarla/World.cpp#L242)):*
<details><summary><i>Previously, marcgpuig (Marc Garcia Puig) wrote…</i></summary><blockquote>

> ```
> arg("MapLayers"))
> ```
`arg("map_layers"))`
</blockquote></details>

Done.
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameInstance.h, line 119 at r3](https://reviewable.io/reviews/carla-simulator/carla/3515#-MKpCJ3X3aBim_2yEb7L:-MKpKB3oC_7zv4Lyf-8U:b-5oh32l) ([raw file](https://github.com/carla-simulator/carla/blob/dfcfe9f37a5995eab1f2dfd2693e8566518a99e7/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameInstance.h#L119)):*
<details><summary><i>Previously, marcgpuig (Marc Garcia Puig) wrote…</i></summary><blockquote>

> ```
> int32 CurrentMapLayer = static_cast<int32>(carla::rpc::MapLayer::All);
> ```
I think that MapLayerType is `uint16_t`, why is this `int32`? Maybe using something like:

`carla::rpc::MapLayer::MapLayerType CurrentMapLayer = static_cast<carla::rpc::MapLayer::MapLayerType>(carla::rpc::MapLayer::All);`

Do you have any better solution? Same for the others `int32`.
</blockquote></details>

Unreal UPROPERTYs and UFUNTIONs only supports int32 and int8
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.h, line 93 at r3](https://reviewable.io/reviews/carla-simulator/carla/3515#-MKpDWeFA3U88md1bs2d:-MKpKK_R8Pt0aFnsKvrG:bpxzujo) ([raw file](https://github.com/carla-simulator/carla/blob/dfcfe9f37a5995eab1f2dfd2693e8566518a99e7/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.h#L93)):*
<details><summary><i>Previously, marcgpuig (Marc Garcia Puig) wrote…</i></summary><blockquote>

same int32
</blockquote></details>

This could be a MapLayer but since is called from UFUNCTIONs that receive an int32, I kept the int32 to avoid a cast
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp, line 31 at r3](https://reviewable.io/reviews/carla-simulator/carla/3515#-MKpEYoI1dOTo6UnUQ0F:-MKpPQ1V9h-yviIBYwX3:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/dfcfe9f37a5995eab1f2dfd2693e8566518a99e7/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp#L31)):*
<details><summary><i>Previously, marcgpuig (Marc Garcia Puig) wrote…</i></summary><blockquote>

what about moving this to MapLayer.h?
</blockquote></details>

Done.
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp, line 283 at r3](https://reviewable.io/reviews/carla-simulator/carla/3515#-MKpEllO7Yrmi6S_nb-W:-MKpRzsA3Wql8s3-BoKV:bjgqqd9) ([raw file](https://github.com/carla-simulator/carla/blob/dfcfe9f37a5995eab1f2dfd2693e8566518a99e7/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp#L283)):*
> Unreal UPROPERTYs and UFUNTIONs only supports int32 and int8
Same, Unreal UPROPERTYs and UFUNTIONs only supports int32 and int8

**Review by marcgpuig — APPROVED** [review]
:lgtm:

> Reviewed 2 of 16 files at r1, 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3515#-:-ML7NFui-kteMdhRZY5R:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Axel1092 and @XGodina)

___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameInstance.h, line 119 at r3](https://reviewable.io/reviews/carla-simulator/carla/3515#-MKpCJ3X3aBim_2yEb7L:-ML7MH3j0QrY_GmZ80A7:byr86b6) ([raw file](https://github.com/carla-simulator/carla/blob/dfcfe9f37a5995eab1f2dfd2693e8566518a99e7/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameInstance.h#L119)):*
<details><summary><i>Previously, doterop wrote…</i></summary><blockquote>

Unreal UPROPERTYs and UFUNTIONs only supports int32 and int8
</blockquote></details>

Nice to know

**Comment by XGodina** [comment]
:lgtm:

**Pull request merged**
