### PR TITLE
Global Routing and Basic Agent Lane Change Extension

### PR DESCRIPTION
**Pull request by pravinblaze**
#### Description

* Global router now has lane change connections for routing with lane changes
* Basic agent performs lane changes

#### Where has this been tested?

  * **Platform(s):** ... Ubuntu 18.04
  * **Python version(s):** ... 2.7

#### Possible Drawbacks

* Issue with lane change API in Town03 causing segmentation fault
* Topology issue with Town06

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/1332)

### CODE REVIEW

**Comment by pravinblaze** [comment]
Yes, setting up the router involves calling get_right_lane() / get_left_lane() on waypoints of all road segments where the API says it is possible to change lane to build the graph representation but doing so on some waypoints is causing a segmentation fault in Town03.

**Comment by felipecode** [comment]
___
*[PythonAPI/agents/navigation/global_route_planner.py, line 230 at r2](https://reviewable.io/reviews/carla-simulator/carla/1332#-L_y_zfz14Vgvi_TDZK1:-L_y_zfz14Vgvi_TDZK2:b-4ivfe8) ([raw file](https://github.com/carla-simulator/carla/blob/966a6bbb3e364732653c7949fad207ae189f7b9f/PythonAPI/agents/navigation/global_route_planner.py#L230)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>     def _localize(self, location):
>         """
>         This function finds the road segment closest to given location
> 
>         location        :   carla.Location to be localized in the graph
>         return          :   pair node ids representing an edge in the graph
>         """
>         waypoint = self._dao.get_waypoint(location)
>         return self._road_id_to_edge[waypoint.road_id][waypoint.lane_id]
> ```
</details>

Arent you computing the route twice ?

**Comment by felipecode** [comment]
I am having some problems when trying to trace routes the following
code gives me some unexpected results:

```
import carla

from agents.navigation.global_route_planner import GlobalRoutePlanner
from agents.navigation.global_route_planner_dao import GlobalRoutePlannerDAO

client = carla.Client('localhost', int(2000))
client.set_timeout(25.0)
world = client.load_world('Town01')

dao = GlobalRoutePlannerDAO(world.get_map(), 2.0)
grp = GlobalRoutePlanner(dao)
grp.setup()

start_point = carla.Location(x=338.7027893066406,
                             y=226.75003051757812,
                             z=0)

print("    BEGIN ", start_point)
end_point = carla.Location(x=321.98931884765625,
                           y=194.67242431640625,
                           z=0)

interpolated_trace = grp.trace_route(start_point, end_point)

for wp in interpolated_trace:
    print(wp[0].transform.location, wp[0].transform.rotation)

print("    END ", end_point)
```

Ouput:

```
 BEGIN  Location(x=338.703, y=226.75, z=0)
Location(x=338.703, y=227.451, z=0) Rotation(pitch=360, yaw=269.979, roll=0)
Location(x=338.702, y=225.451, z=0) Rotation(pitch=360, yaw=269.979, roll=0)
Location(x=338.702, y=223.451, z=0) Rotation(pitch=360, yaw=269.979, roll=0)
Location(x=338.701, y=221.451, z=0) Rotation(pitch=360, yaw=269.979, roll=0)
Location(x=338.7, y=219.451, z=0) Rotation(pitch=360, yaw=269.979, roll=0)
Location(x=338.699, y=217.451, z=0) Rotation(pitch=360, yaw=269.979, roll=0)
Location(x=338.699, y=215.451, z=0) Rotation(pitch=360, yaw=269.979, roll=0)
Location(x=338.698, y=213.451, z=0) Rotation(pitch=360, yaw=269.979, roll=0)
Location(x=338.697, y=211.451, z=0) Rotation(pitch=360, yaw=269.979, roll=0)
Location(x=338.696, y=207.652, z=0) Rotation(pitch=360, yaw=269.979, roll=0)
Location(x=338.696, y=207.652, z=0) Rotation(pitch=0, yaw=-90.0209, roll=0)
Location(x=338.695, y=205.652, z=0) Rotation(pitch=0, yaw=-90.0209, roll=0)
Location(x=338.55, y=203.325, z=0) Rotation(pitch=0, yaw=-99.614, roll=0)
Location(x=337.846, y=200.951, z=0) Rotation(pitch=0, yaw=-113.43, roll=0)
Location(x=336.595, y=198.814, z=0) Rotation(pitch=0, yaw=-127.247, roll=0)
Location(x=334.877, y=197.041, z=0) Rotation(pitch=0, yaw=-140.86, roll=0)
Location(x=332.804, y=195.72, z=0) Rotation(pitch=0, yaw=-154.132, roll=0)
Location(x=330.483, y=194.91, z=0) Rotation(pitch=0, yaw=-167.404, roll=0)
Location(x=328.057, y=194.655, z=0) Rotation(pitch=0, yaw=179.832, roll=0)
Location(x=325.663, y=194.662, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=325.663, y=194.662, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=323.663, y=194.668, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=321.663, y=194.673, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=319.663, y=194.679, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=317.663, y=194.685, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=315.663, y=194.691, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=313.663, y=194.697, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=311.663, y=194.703, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=309.663, y=194.708, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=307.663, y=194.714, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=305.663, y=194.72, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=303.663, y=194.726, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=301.663, y=194.732, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=299.663, y=194.738, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=297.663, y=194.744, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=295.663, y=194.749, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=293.663, y=194.755, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=291.663, y=194.761, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=289.663, y=194.767, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=287.663, y=194.773, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=285.663, y=194.779, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=283.663, y=194.785, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=281.663, y=194.79, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=279.663, y=194.796, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=277.663, y=194.802, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=275.663, y=194.808, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=273.663, y=194.814, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=271.663, y=194.82, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=269.663, y=194.826, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=267.663, y=194.831, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=265.663, y=194.837, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=263.663, y=194.843, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=261.663, y=194.849, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=259.663, y=194.855, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=257.663, y=194.861, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=255.663, y=194.867, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=253.663, y=194.872, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=251.663, y=194.878, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=249.663, y=194.884, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=247.663, y=194.89, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=245.663, y=194.896, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=243.663, y=194.902, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=241.663, y=194.908, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=239.663, y=194.913, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=237.663, y=194.919, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=235.663, y=194.925, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=233.663, y=194.931, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=231.663, y=194.937, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=229.663, y=194.943, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=227.663, y=194.948, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=225.663, y=194.954, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=223.663, y=194.96, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=221.663, y=194.966, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=219.663, y=194.972, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=217.663, y=194.978, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=215.663, y=194.984, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=213.663, y=194.989, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=211.663, y=194.995, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=209.663, y=195.001, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=207.663, y=195.007, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=205.663, y=195.013, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=203.663, y=195.019, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=201.663, y=195.025, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=199.663, y=195.03, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=197.663, y=195.036, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=195.663, y=195.042, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=193.663, y=195.048, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=191.663, y=195.054, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=189.663, y=195.06, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=187.664, y=195.066, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=185.664, y=195.071, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=183.664, y=195.077, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=181.664, y=195.083, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=179.664, y=195.089, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=177.664, y=195.095, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=175.664, y=195.101, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=173.664, y=195.107, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=171.664, y=195.112, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=169.664, y=195.118, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=167.664, y=195.124, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=165.664, y=195.13, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=163.664, y=195.136, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=161.664, y=195.142, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=159.664, y=195.148, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=157.664, y=195.153, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=155.664, y=195.159, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=153.664, y=195.165, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=151.664, y=195.171, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=149.664, y=195.177, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=147.664, y=195.183, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=145.664, y=195.188, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=143.664, y=195.194, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=141.664, y=195.2, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=139.664, y=195.206, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=137.664, y=195.212, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=135.664, y=195.218, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=133.664, y=195.224, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=131.664, y=195.229, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=129.664, y=195.235, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=127.664, y=195.241, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=125.664, y=195.247, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=123.664, y=195.253, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=121.664, y=195.259, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=119.664, y=195.265, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=117.664, y=195.27, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=115.664, y=195.276, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=113.664, y=195.282, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=111.664, y=195.288, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=109.664, y=195.294, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=107.664, y=195.3, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=105.664, y=195.306, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=103.664, y=195.311, z=0) Rotation(pitch=360, yaw=179.832, roll=0)
Location(x=101.419, y=195.318, z=0) Rotation(pitch=0, yaw=179.832, roll=0)
    END  Location(x=321.989, y=194.672, z=0)
```

It clearly traces the route after the end point. Am I doing something wrong ??

**Comment by pravinblaze** [comment]
Hey @felipecode , please check now. There was an issue with comparing distance with the destination waypoint. It's fixed.

**Comment by felipecode** [comment]
:lgtm:

**Comment by nsubiron** [comment]
Merged by #1464.

**Pull request merged**
