### PR TITLE
sergi-e/tm-fix-osm

### PR DESCRIPTION
**Pull request by sergi-e**
#### Description

- New method in PythonAPI regarding TM (client.md). The method fixes a bug that causes TM to crash on OSM generated maps. 

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04.4
  * **Python version(s):** 3.6.9
  * **Unreal Engine version(s):** 4.24

#### Possible drawbacks

- This update may change when the bug is solved.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3325)

### CODE REVIEW

**Review by jackbart94 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3325)* status: all files reviewed, 6 unresolved discussions (waiting on @sergi-e)

___
*[Docs/python_api.md, line 2024 at r2](https://reviewable.io/reviews/carla-simulator/carla/3325#-MHk-VFe2n4mIl4EUlzZ:-MHk-VFe2n4mIl4EUlz_:b-xwokvu) ([raw file](https://github.com/carla-simulator/carla/blob/ee6c2f25fd9a84795e89edb54783545629e2e270/Docs/python_api.md#L2024)):*
> ```
> fixes a bug
> ```
Doesn't really fix any bug, it was just not expected to have roads without an exit. Let's write ``allows the user to run a map created with the OSM feature``
___
*[Docs/python_api.md, line 2024 at r2](https://reviewable.io/reviews/carla-simulator/carla/3325#-MHk-i8X7Haf7QeJhgQM:-MHk-i8X7Haf7QeJhgQN:b7ao0qc) ([raw file](https://github.com/carla-simulator/carla/blob/ee6c2f25fd9a84795e89edb54783545629e2e270/Docs/python_api.md#L2024)):*
> ```
> These maps usually have roads with abrupt ends (borders when the map is outlined).
> ```
These maps allow having dead-end streets.
___
*[Docs/python_api.md, line 2024 at r2](https://reviewable.io/reviews/carla-simulator/carla/3325#-MHk09byBfXYxYBI3kVg:-MHk09byBfXYxYBI3kVh:bv7sxsk) ([raw file](https://github.com/carla-simulator/carla/blob/ee6c2f25fd9a84795e89edb54783545629e2e270/Docs/python_api.md#L2024)):*
> ```
> Vehicles cannot find the next waypoint, causing the TM to crash. When OSM mode is enabled, vehicles will be destroyed when no next waypoint is found.··
> ```
Normally, if vehicles cannot find the next waypoint, TM crashes. Now it throws an exception, warning the user to activate ``set_osm_mode`` and then stops.
___
*[Docs/python_api.md, line 2026 at r2](https://reviewable.io/reviews/carla-simulator/carla/3325#-MHk04fMATIAqlX6YGaR:-MHk04fN5ACAJ3FXlO5R:br4moxi) ([raw file](https://github.com/carla-simulator/carla/blob/ee6c2f25fd9a84795e89edb54783545629e2e270/Docs/python_api.md#L2026)):*
> ```
> the OSM is enabled.··
> ```
The OSM mode is enabled
___
*[Docs/tuto_G_openstreetmap.md, line 104 at r2](https://reviewable.io/reviews/carla-simulator/carla/3325#-MHk0Qzo4kICt06QM7ik:-MHk0Qzo4kICt06QM7il:byukguo) ([raw file](https://github.com/carla-simulator/carla/blob/ee6c2f25fd9a84795e89edb54783545629e2e270/Docs/tuto_G_openstreetmap.md#L104)):*
> ```
> Temporarily, to workaround this bug,
> ```
Again, not fixing a bug, nor creating a workaround, it's literally supposed to work this way :)
___
*[PythonAPI/docs/client.yml, line 446 at r2](https://reviewable.io/reviews/carla-simulator/carla/3325#-MHk1TUk9aGUqQsniB5l:-MHk1TUk9aGUqQsniB5m:b-6fmq08) ([raw file](https://github.com/carla-simulator/carla/blob/ee6c2f25fd9a84795e89edb54783545629e2e270/PythonAPI/docs/client.yml#L446)):*
> ```
>   Enables or disables the OSM mode. This mode fixes a bug when running a map created with the [OSM feature](tuto_G_openstreetmap.md). These maps usually have roads with abrupt ends (borders when the map is outlined). Vehicles cannot find the next waypoint, causing the TM to crash. When OSM mode is enabled, vehicles will be destroyed when no next waypoint is found.··
> ```
Same as above

**Review by sergi-e — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3325)* status: all files reviewed, 6 unresolved discussions (waiting on @jackbart94)

___
*[Docs/python_api.md, line 2024 at r2](https://reviewable.io/reviews/carla-simulator/carla/3325#-MHk-i8X7Haf7QeJhgQM:-MHmYV9l6gr5T4Cl3N7w:b-bsjbuv) ([raw file](https://github.com/carla-simulator/carla/blob/ee6c2f25fd9a84795e89edb54783545629e2e270/Docs/python_api.md#L2024)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

> ```
> These maps usually have roads with abrupt ends (borders when the map is outlined).
> ```
These maps allow having dead-end streets.
</blockquote></details>

Done (wanted to avoid specifically "dead-end streets" in case there were "legal" ones in CARLA, but it is not likely the case). 
___
*[Docs/python_api.md, line 2024 at r2](https://reviewable.io/reviews/carla-simulator/carla/3325#-MHk09byBfXYxYBI3kVg:-MHmYVms8SUkxVgN_t53:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/ee6c2f25fd9a84795e89edb54783545629e2e270/Docs/python_api.md#L2024)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

> ```
> Vehicles cannot find the next waypoint, causing the TM to crash. When OSM mode is enabled, vehicles will be destroyed when no next waypoint is found.··
> ```
Normally, if vehicles cannot find the next waypoint, TM crashes. Now it throws an exception, warning the user to activate ``set_osm_mode`` and then stops.
</blockquote></details>

Done.
___
*[Docs/python_api.md, line 2024 at r2](https://reviewable.io/reviews/carla-simulator/carla/3325#-MHk-VFe2n4mIl4EUlzZ:-MHmZH1rBQndQ72myO7z:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/ee6c2f25fd9a84795e89edb54783545629e2e270/Docs/python_api.md#L2024)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

> ```
> fixes a bug
> ```
Doesn't really fix any bug, it was just not expected to have roads without an exit. Let's write ``allows the user to run a map created with the OSM feature``
</blockquote></details>

Done.
___
*[Docs/python_api.md, line 2026 at r2](https://reviewable.io/reviews/carla-simulator/carla/3325#-MHk04fMATIAqlX6YGaR:-MHmYDz4DOlaIiKeGQdi:bs7wubq) ([raw file](https://github.com/carla-simulator/carla/blob/ee6c2f25fd9a84795e89edb54783545629e2e270/Docs/python_api.md#L2026)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

> ```
> the OSM is enabled.··
> ```
The OSM mode is enabled
</blockquote></details>

Done! 
___
*[Docs/tuto_G_openstreetmap.md, line 104 at r2](https://reviewable.io/reviews/carla-simulator/carla/3325#-MHk0Qzo4kICt06QM7ik:-MHmcjd26gB0TW0qvfWp:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/ee6c2f25fd9a84795e89edb54783545629e2e270/Docs/tuto_G_openstreetmap.md#L104)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

> ```
> Temporarily, to workaround this bug,
> ```
Again, not fixing a bug, nor creating a workaround, it's literally supposed to work this way :)
</blockquote></details>

Done.
___
*[PythonAPI/docs/client.yml, line 446 at r2](https://reviewable.io/reviews/carla-simulator/carla/3325#-MHk1TUk9aGUqQsniB5l:-MHmck6oEFdC9HPxJpAr:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/ee6c2f25fd9a84795e89edb54783545629e2e270/PythonAPI/docs/client.yml#L446)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

> ```
>   Enables or disables the OSM mode. This mode fixes a bug when running a map created with the [OSM feature](tuto_G_openstreetmap.md). These maps usually have roads with abrupt ends (borders when the map is outlined). Vehicles cannot find the next waypoint, causing the TM to crash. When OSM mode is enabled, vehicles will be destroyed when no next waypoint is found.··
> ```
Same as above
</blockquote></details>

Done.

**Review by jackbart94 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3325)* status: all files reviewed, 7 unresolved discussions (waiting on @sergi-e)

___
*[Docs/python_api.md, line 2024 at r3](https://reviewable.io/reviews/carla-simulator/carla/3325#-MHvp9GU5XXy9SD6j_lf:-MHvp9GU5XXy9SD6j_lg:b-emx2da) ([raw file](https://github.com/carla-simulator/carla/blob/543ebd919bddd45d89caeedca49a972e3ebc359d/Docs/python_api.md#L2024)):*
> ```
> Now it throws an exception, warning the user to activate <code>set_osm_mode</code> and then stops.··
> ```
Doesn't throw an exception anymore, just warns the user before removing the vehicle.
___
*[Docs/python_api.md, line 2027 at r3](https://reviewable.io/reviews/carla-simulator/carla/3325#-MHvp5XrBrHbYf665J4w:-MHvp5XrBrHbYf665J4x:b-ic7gif) ([raw file](https://github.com/carla-simulator/carla/blob/543ebd919bddd45d89caeedca49a972e3ebc359d/Docs/python_api.md#L2027)):*
> ```
>     - **Note:** <font color="#8E8E8E">_The argument `--osm` in `PythonAPI/examples/spawn_npc.py` makes use of this method to enable OSM mode.
> _</font>
> ```
Not anymore, it's True by default. 
___
*[Docs/tuto_G_openstreetmap.md, line 104 at r3](https://reviewable.io/reviews/carla-simulator/carla/3325#-MHvpFm67KC37YyxFSws:-MHvpFm67KC37YyxFSwt:bz1s4qz) ([raw file](https://github.com/carla-simulator/carla/blob/543ebd919bddd45d89caeedca49a972e3ebc359d/Docs/tuto_G_openstreetmap.md#L104)):*
> ```
>  or directly the `--osm` argument in `PythonAPI/examples/spawn_npc.py` 
> ```
Removed.
___
*[Docs/tuto_G_openstreetmap.md, line 104 at r3](https://reviewable.io/reviews/carla-simulator/carla/3325#-MHvpHKo8-ddBfJAb0ow:-MHvpHKo8-ddBfJAb0ox:b-n7sxfu) ([raw file](https://github.com/carla-simulator/carla/blob/543ebd919bddd45d89caeedca49a972e3ebc359d/Docs/tuto_G_openstreetmap.md#L104)):*
> ```
> Use [set_osm_mode()](python_api.md#carlatrafficmanager) or directly the `--osm` argument in `PythonAPI/examples/spawn_npc.py` to enable de OSM mode.
> ```
Set to True by default
___
*[PythonAPI/docs/client.yml, line 442 at r3](https://reviewable.io/reviews/carla-simulator/carla/3325#-MHvpRL25_tlnfraaeks:-MHvpRL25_tlnfraaekt:bkooxtk) ([raw file](https://github.com/carla-simulator/carla/blob/543ebd919bddd45d89caeedca49a972e3ebc359d/PythonAPI/docs/client.yml#L442)):*
> ```
>       default: true
> ```
This was wrong before, now it's correct ahah
___
*[PythonAPI/docs/client.yml, line 446 at r3](https://reviewable.io/reviews/carla-simulator/carla/3325#-MHvpK6t103GwoEImQyl:-MHvpK6t103GwoEImQym:b-7i4jdk) ([raw file](https://github.com/carla-simulator/carla/blob/543ebd919bddd45d89caeedca49a972e3ebc359d/PythonAPI/docs/client.yml#L446)):*
> ```
>       note: >
>         The argument `--osm` in `PythonAPI/examples/spawn_npc.py` makes use of this method to enable OSM mode.
> ```

That's gone
___
*[PythonAPI/docs/client.yml, line 448 at r3](https://reviewable.io/reviews/carla-simulator/carla/3325#-MHvpM8d4zOvHdxz6vJT:-MHvpM8d4zOvHdxz6vJU:bwc8pxr) ([raw file](https://github.com/carla-simulator/carla/blob/543ebd919bddd45d89caeedca49a972e3ebc359d/PythonAPI/docs/client.yml#L448)):*
> ```
>      Enables or disables the OSM mode. This mode allows the user to run TM in a map created with the [OSM feature](tuto_G_openstreetmap.md). These maps allow having dead-end streets. Normally, if vehicles cannot find the next waypoint, TM crashes. Now it throws an exception, warning the user to activate <code>set_osm_mode</code> and then stops.··
> ```

Same changes as above

**Review by sergi-e — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3325)* status: all files reviewed, 7 unresolved discussions (waiting on @jackbart94)

___
*[Docs/python_api.md, line 2024 at r3](https://reviewable.io/reviews/carla-simulator/carla/3325#-MHvp9GU5XXy9SD6j_lf:-MHzoeXt7EO697oKqcv-:b-17q4fl) ([raw file](https://github.com/carla-simulator/carla/blob/543ebd919bddd45d89caeedca49a972e3ebc359d/Docs/python_api.md#L2024)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

> ```
> Now it throws an exception, warning the user to activate <code>set_osm_mode</code> and then stops.··
> ```
Doesn't throw an exception anymore, just warns the user before removing the vehicle.
</blockquote></details>

Rewritten.
___
*[Docs/python_api.md, line 2027 at r3](https://reviewable.io/reviews/carla-simulator/carla/3325#-MHvp5XrBrHbYf665J4w:-MHzofWQ6O7O5fu8Je05:bss4a2b) ([raw file](https://github.com/carla-simulator/carla/blob/543ebd919bddd45d89caeedca49a972e3ebc359d/Docs/python_api.md#L2027)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

> ```
>     - **Note:** <font color="#8E8E8E">_The argument `--osm` in `PythonAPI/examples/spawn_npc.py` makes use of this method to enable OSM mode.
> _</font>
> ```
Not anymore, it's True by default. 
</blockquote></details>

Removed.
___
*[Docs/tuto_G_openstreetmap.md, line 104 at r3](https://reviewable.io/reviews/carla-simulator/carla/3325#-MHvpHKo8-ddBfJAb0ow:-MHzoqcNEM09Ie0O3kLD:bxdm8kx) ([raw file](https://github.com/carla-simulator/carla/blob/543ebd919bddd45d89caeedca49a972e3ebc359d/Docs/tuto_G_openstreetmap.md#L104)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

> ```
> Use [set_osm_mode()](python_api.md#carlatrafficmanager) or directly the `--osm` argument in `PythonAPI/examples/spawn_npc.py` to enable de OSM mode.
> ```
Set to True by default
</blockquote></details>

Rewritten. 
___
*[Docs/tuto_G_openstreetmap.md, line 104 at r3](https://reviewable.io/reviews/carla-simulator/carla/3325#-MHvpFm67KC37YyxFSws:-MHzpo4t-GU69O4V_KQr:bss4a2b) ([raw file](https://github.com/carla-simulator/carla/blob/543ebd919bddd45d89caeedca49a972e3ebc359d/Docs/tuto_G_openstreetmap.md#L104)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

> ```
>  or directly the `--osm` argument in `PythonAPI/examples/spawn_npc.py` 
> ```
Removed.
</blockquote></details>

Removed.
___
*[PythonAPI/docs/client.yml, line 442 at r3](https://reviewable.io/reviews/carla-simulator/carla/3325#-MHvpRL25_tlnfraaeks:-MHznJtB6VT_xZJiP05D:b7klxpq) ([raw file](https://github.com/carla-simulator/carla/blob/543ebd919bddd45d89caeedca49a972e3ebc359d/PythonAPI/docs/client.yml#L442)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

> ```
>       default: true
> ```
This was wrong before, now it's correct ahah
</blockquote></details>

All the risks were calculated
___
*[PythonAPI/docs/client.yml, line 446 at r3](https://reviewable.io/reviews/carla-simulator/carla/3325#-MHvpK6t103GwoEImQyl:-MHznBzt5odTfHMOqdtR:bss4a1y) ([raw file](https://github.com/carla-simulator/carla/blob/543ebd919bddd45d89caeedca49a972e3ebc359d/PythonAPI/docs/client.yml#L446)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

> ```
>       note: >
>         The argument `--osm` in `PythonAPI/examples/spawn_npc.py` makes use of this method to enable OSM mode.
> ```

That's gone
</blockquote></details>

Removed!
___
*[PythonAPI/docs/client.yml, line 448 at r3](https://reviewable.io/reviews/carla-simulator/carla/3325#-MHvpM8d4zOvHdxz6vJT:-MHzpdPOCcrEUfIWOoLt:b-lx4fua) ([raw file](https://github.com/carla-simulator/carla/blob/543ebd919bddd45d89caeedca49a972e3ebc359d/PythonAPI/docs/client.yml#L448)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

> ```
>      Enables or disables the OSM mode. This mode allows the user to run TM in a map created with the [OSM feature](tuto_G_openstreetmap.md). These maps allow having dead-end streets. Normally, if vehicles cannot find the next waypoint, TM crashes. Now it throws an exception, warning the user to activate <code>set_osm_mode</code> and then stops.··
> ```

Same changes as above
</blockquote></details>

Fixed!

**Review by jackbart94 — APPROVED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3325)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jackbart94 — APPROVED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3325)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
