### PR TITLE
Fixed markings color bug

### PR DESCRIPTION
**Pull request by algababr**
#### Where has this been tested?

  * **Platform(s):** Windows
  * **Python version(s):** 3.7.9
  * **Unreal Engine version(s):** 4.26

#### Possible Drawbacks

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4297)

### CODE REVIEW

**Review by bernatx — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4297)* status: all files reviewed, 1 unresolved discussion (waiting on @algababr)

___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/PrepareAssetsForCookingCommandlet.cpp, line 215 at r1](https://reviewable.io/reviews/carla-simulator/carla/4297#-MbuDIv00sZr_hkLoSTU:-MbuDIv00sZr_hkLoSTV:b-qqicgm) ([raw file](https://github.com/carla-simulator/carla/blob/10458238a22bf8606fbd6f65a1a88ce57f447164/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/PrepareAssetsForCookingCommandlet.cpp#L215)):*
> ```cpp
>             else
>             {
>               MeshActor->GetStaticMeshComponent()->SetMaterial(0, MarkingNodeExterior);
> ```

Here we need to check the name of the material, because RoadRunner does not export always in the same order, some times the yellow material can be the first one and other times will be the second one. So, I suggest to make a loop and check for each material name, if it has the **yellow** word, then assign the yellow material, otherwise the **white** one.

**Review by bernatx — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4297)* status: all files reviewed, 2 unresolved discussions (waiting on @algababr)

___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/PrepareAssetsForCookingCommandlet.cpp, line 54 at r1](https://reviewable.io/reviews/carla-simulator/carla/4297#-MbuDrnqCa4jo5S2LFkx:-MbuDrnqCa4jo5S2LFky:b-g0yds2) ([raw file](https://github.com/carla-simulator/carla/blob/10458238a22bf8606fbd6f65a1a88ce57f447164/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/PrepareAssetsForCookingCommandlet.cpp#L54)):*
> ```
> MarkingNodeCenterMaterial
> ```
It is better to rename this variable names with something like **MarkingNodeYellow**, and the other with **MarkingNodeWhite**

**Comment by algababr** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/PrepareAssetsForCookingCommandlet.cpp, line 54 at r1](https://reviewable.io/reviews/carla-simulator/carla/4297#-MbuDrnqCa4jo5S2LFkx:-Mbv3qrI-AewA46IY7uf:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/10458238a22bf8606fbd6f65a1a88ce57f447164/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/PrepareAssetsForCookingCommandlet.cpp#L54)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
> MarkingNodeCenterMaterial
> ```
It is better to rename this variable names with something like **MarkingNodeYellow**, and the other with **MarkingNodeWhite**
</blockquote></details>

Done.

**Comment by algababr** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/PrepareAssetsForCookingCommandlet.cpp, line 215 at r1](https://reviewable.io/reviews/carla-simulator/carla/4297#-MbuDIv00sZr_hkLoSTU:-Mbv3tUm9DOwNNefFoOk:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/10458238a22bf8606fbd6f65a1a88ce57f447164/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/PrepareAssetsForCookingCommandlet.cpp#L215)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

Here we need to check the name of the material, because RoadRunner does not export always in the same order, some times the yellow material can be the first one and other times will be the second one. So, I suggest to make a loop and check for each material name, if it has the **yellow** word, then assign the yellow material, otherwise the **white** one. 
</blockquote></details>

Done.

**Review by algababr — COMMENTED** [review]
> Reviewed 30 of 35 files at r2, 3 of 4 files at r4, 1 of 1 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4297)* status: all files reviewed, 2 unresolved discussions (waiting on @bernatx)

**Pull request closed without merging**
