### PR TITLE
sergi-e/api-units

### PR DESCRIPTION
**Pull request by sergi-e**
#### Description

- Modified the PythonAPI reference generator (doc_gen.py) to add units in variables, parameters and returns. 
- Added units when corresponding all along the API. 
- Modified the description of carla.Rotation for better clarity on coordinates system and declaration order. 
- Added a note in First steps > Actors and blueprints (core_actors.md) to remark the coordinates system and the declaration order in rotations. 
- Minor modifications in API texts. 

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04.4
  * **Python version(s):** 3.6.9
  * **Unreal Engine version(s):** 4.24

#### Possible Drawbacks

- Is the new addition useful/easy to understand? 
- Have all units been properly specified?

#### Note for reviewers

Due to the large amount of files to check, I suggest the following file distribution: 

@marcgpuig : 
doc_gen.py
python_api.md
core_actors.md

@doterop : 
actor.yml
blueprint.yml
client.yml
world.yml

@bernatx : 
commands.yml
control.yml
geom.yml

@Axel1092 : 
light_manager.yml
map.yml
osm2odr.yml

@DSantosO : 
sensor.yml
sensor_data.yml
snapshot.yml
weather.yml

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3292)

### CODE REVIEW

**Review by DSantosO — COMMENTED** [review]
> Reviewed 3 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3292)* status: 3 of 15 files reviewed, 4 unresolved discussions (waiting on @Axel1092, @bernatx, @doterop, @DSantosO, @marcgpuig, and @sergi-e)

___
*[PythonAPI/docs/actor.yml, line 50 at r1](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHG8XJS-8JOfwOU5EXu:-MHG8XJT2lJ2sgIhedE8:b-23cyp5) ([raw file](https://github.com/carla-simulator/carla/blob/1b2a3c4f1dbd85de302adf0cb63e9e0b0f2e86bb/PythonAPI/docs/actor.yml#L50)):*
> ```
>  param_units: N * m * s
> ```

This is the correct unit for angular impulse but, according to the documentation, in UE4 the angular impulse is measured directly in angles. Specifically, we are using the degrees function, so the units should be degrees.
___
*[PythonAPI/docs/sensor_data.yml, line 269 at r1](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHG77jZ5nvcxwLq8AK3:-MHG77jZ5nvcxwLq8AK4:bjr3zju) ([raw file](https://github.com/carla-simulator/carla/blob/1b2a3c4f1dbd85de302adf0cb63e9e0b0f2e86bb/PythonAPI/docs/sensor_data.yml#L269)):*
> ```
>   [CARLA index](https://carla.readthedocs.io/en/latest/ref_sensors/#semantic-segmentation-camera) of the hit actor.
> ```

The object idx is the index of the actor, nothing to do with the semantic segmentation index. Maybe you could link the actor section or another in which the actor index is explained.
___
*[PythonAPI/docs/sensor_data.yml, line 297 at r1](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHG9yzv63N4DYpQUmEC:-MHG9yzv63N4DYpQUmED:b-m6m8d2) ([raw file](https://github.com/carla-simulator/carla/blob/1b2a3c4f1dbd85de302adf0cb63e9e0b0f2e86bb/PythonAPI/docs/sensor_data.yml#L297)):*
> ```
> N*m
> ```

Should be N*s?
___
*[PythonAPI/docs/sensor_data.yml, line 382 at r1](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHGACCH6XTnGG4MgxuJ:-MHGACCH6XTnGG4MgxuK:bvl967u) ([raw file](https://github.com/carla-simulator/carla/blob/1b2a3c4f1dbd85de302adf0cb63e9e0b0f2e86bb/PythonAPI/docs/sensor_data.yml#L382)):*
> ```
>       var_units: m*s<sup>2</sup>
> ```

should be m/s2

**Review by marcgpuig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3292)* status: 3 of 15 files reviewed, 10 unresolved discussions (waiting on @Axel1092, @bernatx, @doterop, @DSantosO, @marcgpuig, and @sergi-e)

___
*[Docs/core_actors.md, line 77 at r1](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHGo1fz7wTRoTjrOscj:-MHGo1fz7wTRoTjrOsck:b-24i2ib) ([raw file](https://github.com/carla-simulator/carla/blob/1b2a3c4f1dbd85de302adf0cb63e9e0b0f2e86bb/Docs/core_actors.md#L77)):*
> ```Markdown
> 
> ```py
> transform = Transform(Location(x=230, y=195, z=40), Rotation(0,180,0))
> ```

Why this change? I think it was clear already, you can declare a Rotation with `Rotation(yaw=180))` or `Rotation(roll=20, yaw=180, pitch=10))` regardless of the order in the constructor parameters since they are optional.
___
*[Docs/core_actors.md, line 82 at r1](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHGoCfC4cxxZmJr_-7I:-MHGoCfC4cxxZmJr_-7J:b-7ig9np) ([raw file](https://github.com/carla-simulator/carla/blob/1b2a3c4f1dbd85de302adf0cb63e9e0b0f2e86bb/Docs/core_actors.md#L82)):*
> ```
> CARLA uses the [Unreal Engine coordinates system](https://carla.readthedocs.io/en/latest/python_api/#carlarotation), and rotations are declared in a specific order, `(pitch,yaw,roll)`, which is different in the Unreal Engine Editor.
> ```
to:
```
CARLA uses the [Unreal Engine coordinates system](https://carla.readthedocs.io/en/latest/python_api/#carlarotation). Remember that `carla.Rotation` constructor is defined as `(pitch, yaw, roll)`, that differs from Unreal Engine Editor `(roll, pitch, yaw)`.
```
___
*[PythonAPI/docs/actor.yml, line 50 at r1](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHG8XJS-8JOfwOU5EXu:-MHGjkbI3d9nP2RYVF5l:bxvm674) ([raw file](https://github.com/carla-simulator/carla/blob/1b2a3c4f1dbd85de302adf0cb63e9e0b0f2e86bb/PythonAPI/docs/actor.yml#L50)):*
<details><summary><i>Previously, DSantosO wrote…</i></summary><blockquote>

> ```
>  param_units: N * m * s
> ```

This is the correct unit for angular impulse but, according to the documentation, in UE4 the angular impulse is measured directly in angles. Specifically, we are using the degrees function, so the units should be degrees.
</blockquote></details>

@dsantoso In the client-side, almost everything should use radians instead of degrees
___
*[PythonAPI/docs/doc_gen.py, line 337 at r1](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHGl9-Y5JK6rlTzyO2v:-MHGl9-Y5JK6rlTzyO2w:bvzbjaw) ([raw file](https://github.com/carla-simulator/carla/blob/1b2a3c4f1dbd85de302adf0cb63e9e0b0f2e86bb/PythonAPI/docs/doc_gen.py#L337)):*
> ```
> param_units = '<small> – '+create_hyperlinks(param['param_units']+'</small>')
> ```
Shouldn't this be:
```
param_units = '<small> – ' + param['param_units'] + '</small>'
```
you don't need hyperlinks that link to another `carla.something` here right?
___
*[PythonAPI/docs/doc_gen.py, line 380 at r1](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHGm9jfDC54eGlPjCGQ:-MHGm9jfDC54eGlPjCGR:b-10zief) ([raw file](https://github.com/carla-simulator/carla/blob/1b2a3c4f1dbd85de302adf0cb63e9e0b0f2e86bb/PythonAPI/docs/doc_gen.py#L380)):*
> ```Python
>         return_units = ''
>         if valid_dic_val(method, 'return_units'):
>             return_units = '<small> – '+create_hyperlinks(method['return_units']+'</small>')
> ```

same here, I recommend creating a function for this:
```py
def html_small(buf):
    return join(['<small>', buf, '</small>'])
```
___
*[PythonAPI/docs/doc_gen.py, line 434 at r1](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHGmDCV8VDtriDrBm-w:-MHGmDCV8VDtriDrBm-x:b-2guby3) ([raw file](https://github.com/carla-simulator/carla/blob/1b2a3c4f1dbd85de302adf0cb63e9e0b0f2e86bb/PythonAPI/docs/doc_gen.py#L434)):*
> ```Python
>         return_units = ''
>         if valid_dic_val(method, 'return_units'):
>             return_units = '<small> – '+create_hyperlinks(method['return_units']+'</small>')
> ```

same here
___
*[PythonAPI/docs/doc_gen.py, line 510 at r1](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHGmGhg4KK7_Orw9FCS:-MHGmGhg4KK7_Orw9FCT:bb7od0r) ([raw file](https://github.com/carla-simulator/carla/blob/1b2a3c4f1dbd85de302adf0cb63e9e0b0f2e86bb/PythonAPI/docs/doc_gen.py#L510)):*
> ```Python
>     if valid_dic_val(inst_var, 'type'):
>         if valid_dic_val(inst_var, 'var_units'):
>             var_units = '<small> – '+create_hyperlinks(inst_var['var_units']+'</small>')
> ```

same

**Comment by DSantosO** [comment]
___
*[PythonAPI/docs/actor.yml, line 50 at r1](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHG8XJS-8JOfwOU5EXu:-MHGuzLFCu4n-BMT7GyW:bueu5y5) ([raw file](https://github.com/carla-simulator/carla/blob/1b2a3c4f1dbd85de302adf0cb63e9e0b0f2e86bb/PythonAPI/docs/actor.yml#L50)):*
<details><summary><i>Previously, marcgpuig (Marc Garcia Puig) wrote…</i></summary><blockquote>

@dsantoso In the client-side, almost everything should use radians instead of degrees
</blockquote></details>

@marcgpuig I agree that we should use radians but right now in the CarlaServer this function is using AddAngularImpulseInDegrees

**Review by sergi-e — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3292)* status: 3 of 15 files reviewed, 10 unresolved discussions (waiting on @Axel1092, @bernatx, @doterop, @DSantosO, and @marcgpuig)

___
*[Docs/core_actors.md, line 77 at r1](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHGo1fz7wTRoTjrOscj:-MHGz-bR7ZSm1buCQY3O:bporkvw) ([raw file](https://github.com/carla-simulator/carla/blob/1b2a3c4f1dbd85de302adf0cb63e9e0b0f2e86bb/Docs/core_actors.md#L77)):*
<details><summary><i>Previously, marcgpuig (Marc Garcia Puig) wrote…</i></summary><blockquote>

Why this change? I think it was clear already, you can declare a Rotation with `Rotation(yaw=180))` or `Rotation(roll=20, yaw=180, pitch=10))` regardless of the order in the constructor parameters since they are optional.
</blockquote></details>

Changed to previous state
___
*[Docs/core_actors.md, line 82 at r1](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHGoCfC4cxxZmJr_-7I:-MHGudOs-E9BaNcYPXkC:b-896fja) ([raw file](https://github.com/carla-simulator/carla/blob/1b2a3c4f1dbd85de302adf0cb63e9e0b0f2e86bb/Docs/core_actors.md#L82)):*
<details><summary><i>Previously, marcgpuig (Marc Garcia Puig) wrote…</i></summary><blockquote>

> ```
> CARLA uses the [Unreal Engine coordinates system](https://carla.readthedocs.io/en/latest/python_api/#carlarotation), and rotations are declared in a specific order, `(pitch,yaw,roll)`, which is different in the Unreal Engine Editor.
> ```
to:
```
CARLA uses the [Unreal Engine coordinates system](https://carla.readthedocs.io/en/latest/python_api/#carlarotation). Remember that `carla.Rotation` constructor is defined as `(pitch, yaw, roll)`, that differs from Unreal Engine Editor `(roll, pitch, yaw)`.
```
</blockquote></details>

Done!
___
*[PythonAPI/docs/actor.yml, line 50 at r1](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHG8XJS-8JOfwOU5EXu:-MHGb1eJCcUWNqQv4R4X:bt85mjk) ([raw file](https://github.com/carla-simulator/carla/blob/1b2a3c4f1dbd85de302adf0cb63e9e0b0f2e86bb/PythonAPI/docs/actor.yml#L50)):*
<details><summary><i>Previously, DSantosO wrote…</i></summary><blockquote>

@marcgpuig I agree that we should use radians but right now in the CarlaServer this function is using AddAngularImpulseInDegrees 
</blockquote></details>

I fixed this for both, the actor add_angular_impulse() and the command.ApplyAngularImpulse(), as degrees for now.
___
*[PythonAPI/docs/doc_gen.py, line 337 at r1](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHGl9-Y5JK6rlTzyO2v:-MHGuxWH--6JhfSGASVl:byybsf5) ([raw file](https://github.com/carla-simulator/carla/blob/1b2a3c4f1dbd85de302adf0cb63e9e0b0f2e86bb/PythonAPI/docs/doc_gen.py#L337)):*
<details><summary><i>Previously, marcgpuig (Marc Garcia Puig) wrote…</i></summary><blockquote>

> ```
> param_units = '<small> – '+create_hyperlinks(param['param_units']+'</small>')
> ```
Shouldn't this be:
```
param_units = '<small> – ' + param['param_units'] + '</small>'
```
you don't need hyperlinks that link to another `carla.something` here right?
</blockquote></details>

Not at all. Removed (I used that while testing different formatting and forgot to drop it afterwards)
___
*[PythonAPI/docs/doc_gen.py, line 380 at r1](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHGm9jfDC54eGlPjCGQ:-MHGwmT45EbGNlb7Ojwb:bs7xpm3) ([raw file](https://github.com/carla-simulator/carla/blob/1b2a3c4f1dbd85de302adf0cb63e9e0b0f2e86bb/PythonAPI/docs/doc_gen.py#L380)):*
<details><summary><i>Previously, marcgpuig (Marc Garcia Puig) wrote…</i></summary><blockquote>

same here, I recommend creating a function for this:
```py
def html_small(buf):
    return join(['<small>', buf, '</small>'])
```
</blockquote></details>

Doone!
___
*[PythonAPI/docs/doc_gen.py, line 434 at r1](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHGmDCV8VDtriDrBm-w:-MHGwnZr0ybToMTwZJRJ:bmgp9mi) ([raw file](https://github.com/carla-simulator/carla/blob/1b2a3c4f1dbd85de302adf0cb63e9e0b0f2e86bb/PythonAPI/docs/doc_gen.py#L434)):*
<details><summary><i>Previously, marcgpuig (Marc Garcia Puig) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Dooone!
___
*[PythonAPI/docs/doc_gen.py, line 510 at r1](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHGmGhg4KK7_Orw9FCS:-MHGwpdrDPM7lHECMEII:b-dxce2d) ([raw file](https://github.com/carla-simulator/carla/blob/1b2a3c4f1dbd85de302adf0cb63e9e0b0f2e86bb/PythonAPI/docs/doc_gen.py#L510)):*
<details><summary><i>Previously, marcgpuig (Marc Garcia Puig) wrote…</i></summary><blockquote>

same
</blockquote></details>

Doooone!
___
*[PythonAPI/docs/sensor_data.yml, line 269 at r1](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHG77jZ5nvcxwLq8AK3:-MHGuDegDJRuGyhs8VHl:blzqj96) ([raw file](https://github.com/carla-simulator/carla/blob/1b2a3c4f1dbd85de302adf0cb63e9e0b0f2e86bb/PythonAPI/docs/sensor_data.yml#L269)):*
<details><summary><i>Previously, DSantosO wrote…</i></summary><blockquote>

> ```
>   [CARLA index](https://carla.readthedocs.io/en/latest/ref_sensors/#semantic-segmentation-camera) of the hit actor.
> ```

The object idx is the index of the actor, nothing to do with the semantic segmentation index. Maybe you could link the actor section or another in which the actor index is explained.
</blockquote></details>

Fixed to "ID" for consistency
___
*[PythonAPI/docs/sensor_data.yml, line 297 at r1](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHG9yzv63N4DYpQUmEC:-MHGa4Za1wyJYycRa9m0:b-3f84t8) ([raw file](https://github.com/carla-simulator/carla/blob/1b2a3c4f1dbd85de302adf0cb63e9e0b0f2e86bb/PythonAPI/docs/sensor_data.yml#L297)):*
<details><summary><i>Previously, DSantosO wrote…</i></summary><blockquote>

> ```
> N*m
> ```

Should be N*s?
</blockquote></details>

Yep, my bad
___
*[PythonAPI/docs/sensor_data.yml, line 382 at r1](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHGACCH6XTnGG4MgxuJ:-MHGaID86ohATx3GTVtt:b-97ve) ([raw file](https://github.com/carla-simulator/carla/blob/1b2a3c4f1dbd85de302adf0cb63e9e0b0f2e86bb/PythonAPI/docs/sensor_data.yml#L382)):*
<details><summary><i>Previously, DSantosO wrote…</i></summary><blockquote>

> ```
>       var_units: m*s<sup>2</sup>
> ```

should be m/s2
</blockquote></details>

Thank God reviewers exist

**Review by DSantosO — COMMENTED** [review]
> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3292)* status: 3 of 16 files reviewed, 10 unresolved discussions (waiting on @Axel1092, @bernatx, @doterop, @DSantosO, and @marcgpuig)

**Review by Axel1092 — COMMENTED** [review]
> Reviewed 3 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3292)* status: 6 of 16 files reviewed, 10 unresolved discussions (waiting on @Axel1092, @bernatx, @doterop, @DSantosO, and @marcgpuig)

**Review by doterop — COMMENTED** [review]
> Reviewed 2 of 15 files at r1, 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3292)* status: 9 of 16 files reviewed, 7 unresolved discussions (waiting on @Axel1092, @bernatx, @doterop, @DSantosO, @marcgpuig, and @sergi-e)

___
*[PythonAPI/docs/actor.yml, line 42 at r2](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHLz76Q0TKe73-9V7qT:-MHLz76RAADThw2K8DqY:bxeu0xr) ([raw file](https://github.com/carla-simulator/carla/blob/33224b6712f72a705d23365073cbb8aea9a0a600/PythonAPI/docs/actor.yml#L42)):*
> ```YAML
>       - param_name: impulse
>         type: carla.Vector3D
>         param_units: N*s
> ```

Only N

**Review by bernatx — COMMENTED** [review]
> Reviewed 2 of 15 files at r1, 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3292)* status: 12 of 16 files reviewed, 10 unresolved discussions (waiting on @Axel1092, @bernatx, @doterop, @DSantosO, @marcgpuig, and @sergi-e)

___
*[PythonAPI/docs/commands.yml, line 245 at r2](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHLxjES3rwQxYW6LBlw:-MHLxjES3rwQxYW6LBlx:b-d76qoc) ([raw file](https://github.com/carla-simulator/carla/blob/33224b6712f72a705d23365073cbb8aea9a0a600/PythonAPI/docs/commands.yml#L245)):*
> ```YAML
>     - var_name: angular_velocity
>       type: carla.Vector3D
>       var_units: rad/s
> ```

it should be **deg/s**
We use degrees in the API
___
*[PythonAPI/docs/commands.yml, line 258 at r2](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHLxr4PBuXfg5cWRl9T:-MHLxr4PBuXfg5cWRl9U:beunqxd) ([raw file](https://github.com/carla-simulator/carla/blob/33224b6712f72a705d23365073cbb8aea9a0a600/PythonAPI/docs/commands.yml#L258)):*
> ```YAML
>       - param_name: angular_velocity
>         type: carla.Vector3D
>         param_units: rad/s
> ```

same here, **deg/s**
___
*[PythonAPI/docs/geom.yml, line 217 at r2](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHMMjHb7LVL_GE94LOE:-MHMMjHb7LVL_GE94LOF:bks0evq) ([raw file](https://github.com/carla-simulator/carla/blob/33224b6712f72a705d23365073cbb8aea9a0a600/PythonAPI/docs/geom.yml#L217)):*
> ```
> However, the declaration order of the axis' rotation is different in CARLA than in Unreal Engine
> ```
I would remark that we mean UE4 Editor using the GUI directly, and not through the CARLA API.

**Review by sergi-e — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3292)* status: 12 of 16 files reviewed, 10 unresolved discussions (waiting on @Axel1092, @bernatx, @doterop, @DSantosO, and @marcgpuig)

___
*[PythonAPI/docs/actor.yml, line 42 at r2](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHLz76Q0TKe73-9V7qT:-MHNSIad0MDfvIxFaSaY:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/33224b6712f72a705d23365073cbb8aea9a0a600/PythonAPI/docs/actor.yml#L42)):*
<details><summary><i>Previously, doterop wrote…</i></summary><blockquote>

Only N
</blockquote></details>

Done.
___
*[PythonAPI/docs/commands.yml, line 245 at r2](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHLxjES3rwQxYW6LBlw:-MHNTjWT903FDpkd-uAl:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/33224b6712f72a705d23365073cbb8aea9a0a600/PythonAPI/docs/commands.yml#L245)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

it should be **deg/s**
We use degrees in the API
</blockquote></details>

Done.
___
*[PythonAPI/docs/commands.yml, line 258 at r2](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHLxr4PBuXfg5cWRl9T:-MHNTjhh9X2n-aiteACE:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/33224b6712f72a705d23365073cbb8aea9a0a600/PythonAPI/docs/commands.yml#L258)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

same here, **deg/s**
</blockquote></details>

Done.
___
*[PythonAPI/docs/geom.yml, line 217 at r2](https://reviewable.io/reviews/carla-simulator/carla/3292#-MHMMjHb7LVL_GE94LOE:-MHNaMAsCgoUCB7g4P1y:b5y9mte) ([raw file](https://github.com/carla-simulator/carla/blob/33224b6712f72a705d23365073cbb8aea9a0a600/PythonAPI/docs/geom.yml#L217)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
> However, the declaration order of the axis' rotation is different in CARLA than in Unreal Engine
> ```
I would remark that we mean UE4 Editor using the GUI directly, and not through the CARLA API.
</blockquote></details>

Simplified for clarity. UE Editor not mentioned above, but in a warning in the constructor method.

**Review by DSantosO — COMMENTED** [review]
> Reviewed 3 of 7 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3292)* status: all files reviewed, 9 unresolved discussions (waiting on @bernatx and @marcgpuig)

**Review by DSantosO — APPROVED** [review]
> Reviewed 6 of 15 files at r1, 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3292)* status: all files reviewed, 9 unresolved discussions (waiting on @bernatx and @marcgpuig)

**Review by DSantosO — APPROVED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3292)* status: all files reviewed, 9 unresolved discussions (waiting on @bernatx and @marcgpuig)

**Review by marcgpuig — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3292)* status: all files reviewed, 3 unresolved discussions (waiting on @bernatx)

**Review by bernatx — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3292)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by DSantosO — APPROVED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3292)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
