### PR TITLE
New Features: Constant Velocity Mode, Add Force and Add Torque

### PR DESCRIPTION
**Pull request by DSantosO**
#### Description

We have added the following new features:
  - We have added a mode to set the vehicle to a constant velocity, this is working with manual input and traffic manager. Please use it carefully because it overrides any other velocity change.
  - We have exposed the add_force and add_torque functions. They are thought to apply forces during a finite amount of time, do not use for instantaneous forces.

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04
  * **Python version(s):** 3.6.9
  * **Unreal Engine version(s):** 4.24

#### Possible Drawbacks

This PR exposes new functionalities so it should not change any current feature.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3345)

### CODE REVIEW

**Review by bernatx — APPROVED** [review]
> Reviewed 13 of 14 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3345)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marcgpuig)

**Review by marcgpuig — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3345)* status: all files reviewed, 4 unresolved discussions (waiting on @DSantosO)

___
*[PythonAPI/examples/vehicle_physics.py, line 21 at r2](https://reviewable.io/reviews/carla-simulator/carla/3345#-MHuqDqE7eWaIwyEfRBX:-MHuqDqE7eWaIwyEfRBY:b-cm98ug) ([raw file](https://github.com/carla-simulator/carla/blob/d29a565f0e012d99d7b5bced3c0c39c479f066be/PythonAPI/examples/vehicle_physics.py#L21)):*
> ```
> import random
> ```
Check out the imports since many of them are not used.
___
*[PythonAPI/examples/vehicle_physics.py, line 73 at r2](https://reviewable.io/reviews/carla-simulator/carla/3345#-MHupTUKBuOimP-gucXe:-MHupTUKBuOimP-gucXf:b-hbml73) ([raw file](https://github.com/carla-simulator/carla/blob/d29a565f0e012d99d7b5bced3c0c39c479f066be/PythonAPI/examples/vehicle_physics.py#L73)):*
> ```Python
> 
>         physics_vehicle = vehicle.get_physics_control()
>         car_mass = physics_vehicle.mass
> ```

In this script, I think it will be useful to add comments of the unit system
___
*[PythonAPI/examples/vehicle_physics.py, line 82 at r2](https://reviewable.io/reviews/carla-simulator/carla/3345#-MHupHSv6509EzWu9Hpo:-MHupHSv6509EzWu9Hpp:b-ya008u) ([raw file](https://github.com/carla-simulator/carla/blob/d29a565f0e012d99d7b5bced3c0c39c479f066be/PythonAPI/examples/vehicle_physics.py#L82)):*
> ```Python
> 
> 
>         # We want to
> ```

Is this comment unfinished?
___
*[PythonAPI/examples/vehicle_physics.py, line 111 at r2](https://reviewable.io/reviews/carla-simulator/carla/3345#-MHupqWzEnk7lrvbxo7L:-MHupqX-07NYqaApjbq0:b-bhzc0k) ([raw file](https://github.com/carla-simulator/carla/blob/d29a565f0e012d99d7b5bced3c0c39c479f066be/PythonAPI/examples/vehicle_physics.py#L111)):*
> ```
> wait(world)
> ```

Maybe to:
```py
wait(world, 500)
```

**Review by DSantosO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3345)* status: 11 of 15 files reviewed, 4 unresolved discussions (waiting on @bernatx, @DSantosO, and @marcgpuig)

___
*[PythonAPI/examples/vehicle_physics.py, line 73 at r2](https://reviewable.io/reviews/carla-simulator/carla/3345#-MHupTUKBuOimP-gucXe:-MHvAkn54WF5gySJ208E:bbr6us3) ([raw file](https://github.com/carla-simulator/carla/blob/d29a565f0e012d99d7b5bced3c0c39c479f066be/PythonAPI/examples/vehicle_physics.py#L73)):*
<details><summary><i>Previously, marcgpuig (Marc Garcia Puig) wrote…</i></summary><blockquote>

In this script, I think it will be useful to add comments of the unit system
</blockquote></details>

I have added the units of the impulse and force.
___
*[PythonAPI/examples/vehicle_physics.py, line 82 at r2](https://reviewable.io/reviews/carla-simulator/carla/3345#-MHupHSv6509EzWu9Hpo:-MHvAoaTB4C0m-MqScId:b-jg84d9) ([raw file](https://github.com/carla-simulator/carla/blob/d29a565f0e012d99d7b5bced3c0c39c479f066be/PythonAPI/examples/vehicle_physics.py#L82)):*
<details><summary><i>Previously, marcgpuig (Marc Garcia Puig) wrote…</i></summary><blockquote>

Is this comment unfinished?
</blockquote></details>

Yes, done. And also removed the mass of the vehicle.
___
*[PythonAPI/examples/vehicle_physics.py, line 111 at r2](https://reviewable.io/reviews/carla-simulator/carla/3345#-MHupqWzEnk7lrvbxo7L:-MHvAuDrBLO1VMjwb-ai:bb6un1j) ([raw file](https://github.com/carla-simulator/carla/blob/d29a565f0e012d99d7b5bced3c0c39c479f066be/PythonAPI/examples/vehicle_physics.py#L111)):*
<details><summary><i>Previously, marcgpuig (Marc Garcia Puig) wrote…</i></summary><blockquote>

> ```
> wait(world)
> ```

Maybe to:
```py
wait(world, 500)
```
</blockquote></details>

Done

**Review by bernatx — COMMENTED** [review]
> Reviewed 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3345)* status: 14 of 15 files reviewed, 4 unresolved discussions (waiting on @bernatx and @marcgpuig)

**Review by marcgpuig — COMMENTED** [review]
> Reviewed 1 of 4 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3345)* status: 14 of 16 files reviewed, all discussions resolved (waiting on @bernatx and @marcgpuig)

**Review by marcgpuig — APPROVED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3345)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
