### PR TITLE
Features/basic agent

### PR DESCRIPTION
**Pull request by germanros1987**
#### Description

New BasicAgent class that performs navigation to a target point given in carla coordinates. It is able to deal with traffic and traffic lights.

Fixes #  

#### Where has this been tested?

  * **Platform(s): Ubuntu 16.04
  * **Python version(s): 3.5
  * **Unreal Engine version(s):** ...

#### Possible Drawbacks

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/1066)

### CODE REVIEW

**Comment by fabianoboril** [comment]
@germanros1987 : For our code we use 120c line length, and that is far better, so I am absolutely on your side 👍

**Comment by nsubiron** [comment]
We do use 120 lines for Python, autopep8 should automatically pick the .pep8 config in the repo.

**Comment by fabianoboril** [comment]
@nsubiron : Maybe then the documentation should be updated: https://carla.readthedocs.io/en/latest/coding_standard/

**Comment by nsubiron** [comment]
Done!

**Pull request merged**
