### PR TITLE
Build DDS extension using Unreal sysroot under Linux

### PR DESCRIPTION
**Pull request by berndgassmann**
Use correct Unreal sysroot for dds and ros2 server build Use correct constants that are available in the Unreal delivered sysroot Remove stdc++ library from CarlaUE4 plugin
Allow unresolved symbols (which is carla::throw_exception) in CarlaUE4 and StreetMap plugin to be able to load it in conjunction with Carla plugin itself
Add some helper scripts to run under Linux

#### Description

On Unbuntu 22.04 the ROS2 extension is not compiling/linking since the build process for fastDDS extension used the system provided libraries. Since glibc of the system provides different symbols those remained unresolved. With these changes (and the adaptions of the StreetMap repo) it compiles, links and runs.
For sure one might be able to make some things nicer .... for example the duplicate of the asio exceptions, but that might require some changes at another place from where the clmdep_asio namespace comes from.
Feel free to comment and/or proivde extension/adaptions to this ;-)

Fixes #  

#### Where has this been tested?
Ubunut 22.04, Ros2 humble, python 3.10
  * **Platform(s):** ...
  * **Python version(s):** ...
  * **Unreal Engine version(s):** ...

#### Possible Drawbacks

- - -
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/6960)

### CODE REVIEW

**Review by Blyron — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/6960)* status: all files reviewed, 2 unresolved discussions (waiting on @berndgassmann)

___
*[`Util/BuildTools/BuildUE4Plugins.sh` line 18 at r1](https://reviewable.io/reviews/carla-simulator/carla/6960#-NkUGAfF8VnpEnWVLeuV:-NkUGAfGEERi0e7eiIUe:bvdxtvd) ([raw file](https://github.com/carla-simulator/carla/blob/c3da3364b0d8c87ff8344a3d3920b0f7aaa9a622/Util/BuildTools/BuildUE4Plugins.sh#L18)):*
> ```Shell
> GIT_PULL=true
> CURRENT_STREETMAP_COMMIT=5bae647f8b433ed703ce0adba2ca0d1b08471d9c
> STREETMAP_BRANCH=master
> ```

You should change Branch if you want to use your own branch we will try to adapt your changes as soon as we can
___
*[`Util/BuildTools/Setup.sh` line 1048 at r1](https://reviewable.io/reviews/carla-simulator/carla/6960#-NkUGVacE1kL1RUkwzTu:-NkUGVacE1kL1RUkwzTv:b-quoeoy) ([raw file](https://github.com/carla-simulator/carla/blob/c3da3364b0d8c87ff8344a3d3920b0f7aaa9a622/Util/BuildTools/Setup.sh#L1048)):*
> ```Shell
> 
> popd >/dev/null
> ```

Remove Empty line

**Review by berndgassmann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/6960)* status: all files reviewed, 2 unresolved discussions (waiting on @Blyron)

___
*[`Util/BuildTools/BuildUE4Plugins.sh` line 18 at r1](https://reviewable.io/reviews/carla-simulator/carla/6960#-NkUGAfF8VnpEnWVLeuV:-NkUWL966ZMf1XYhul1B:bi1se9s) ([raw file](https://github.com/carla-simulator/carla/blob/c3da3364b0d8c87ff8344a3d3920b0f7aaa9a622/Util/BuildTools/BuildUE4Plugins.sh#L18)):*
<details><summary><i>Previously, Blyron (Blyron) wrote…</i></summary><blockquote>

You should change Branch if you want to use your own branch we will try to adapt your changes as soon as we can
</blockquote></details>

I'll try to get rid of the ignore unresolved symbols, because that shadows also other potential missing symbols. If putting the Exceptions.cpp into a shared library all others are linked against it might work. I'll provide an update on this.
___
*[`Util/BuildTools/Setup.sh` line 1048 at r1](https://reviewable.io/reviews/carla-simulator/carla/6960#-NkUGVacE1kL1RUkwzTu:-NkUWs_c1f8SAoCkbyJF:b-pemrwd) ([raw file](https://github.com/carla-simulator/carla/blob/c3da3364b0d8c87ff8344a3d3920b0f7aaa9a622/Util/BuildTools/Setup.sh#L1048)):*
<details><summary><i>Previously, Blyron (Blyron) wrote…</i></summary><blockquote>

Remove Empty line
</blockquote></details>

sure, will do.

**Comment by Blyron** [comment]
Now with the new changes windows build has broken 
6960\Unreal\CarlaUE4\Plugins\CarlaTools\Intermediate\Build\Win64\UE4Editor\Development\CarlaTools\UE4Editor-CarlaTools.suppressed.exp
  carla_server.lib(MeshFactory.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXAEBVexception@std@@@Z)
  carla_server.lib(GeoReferenceParser.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXAEBVexception@std@@@Z)
  carla_server.lib(MapBuilder.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXAEBVexception@std@@@Z)
  carla_server.lib(Geometry.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXAEBVexception@std@@@Z)
  Module.CarlaTools.cpp.obj : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXAEBVexception@std@@@Z)
  Module.CarlaTools.gen.2_of_2.cpp.obj : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXAEBVexception@std@@@Z)
  carla_server.lib(Map.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXAEBVexception@std@@@Z)
  carla_server.lib(OpenDriveParser.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXAEBVexception@std@@@Z)
  Module.CarlaTools.cpp.obj : error LNK2019: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &,struct boost::source_location const &)" (?throw_exception@boost@@YAXAEBVexception@std@@AEBUsource_location@1@@Z) referenced in function "void __cdecl boost::asio::detail::do_throw_error(class boost::system::error_code const &,char const *,struct boost::source_location const &)" (?do_throw_error@detail@asio@boost@@YAXAEBVerror_code@system@3@PEBDAEBUsource_location@3@@Z)
  Module.CarlaTools.gen.1_of_2.cpp.obj : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &,struct boost::source_location const &)" (?throw_exception@boost@@YAXAEBVexception@std@@AEBUsource_location@1@@Z)
  Module.CarlaTools.gen.2_of_2.cpp.obj : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &,struct boost::source_location const &)" (?throw_exception@boost@@YAXAEBVexception@std@@AEBUsource_location@1@@Z)
  C:\jenkins\workspace\carla_PR-6960\Unreal\CarlaUE4\Plugins\CarlaTools\Binaries\Win64\UE4Editor-CarlaTools.dll : fatal error LNK1120: 2 unresolved externals
  [71/72] UE4Editor-Carla.dll
     Creating library C:\jenkins\workspace\carla_PR-6960\Unreal\CarlaUE4\Plugins\Carla\Intermediate\Build\Win64\UE4Editor\Development\Carla\UE4Editor-Carla.suppressed.lib and object C:\jenkins\workspace\carla_PR-6960\Unreal\CarlaUE4\Plugins\Carla\Intermediate\Build\Win64\UE4Editor\Development\Carla\UE4Editor-Carla.suppressed.exp
  carla_server.lib(Geometry.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXAEBVexception@std@@@Z)
  carla_server.lib(MeshFactory.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXAEBVexception@std@@@Z)
  carla_server.lib(GeoReferenceParser.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXAEBVexception@std@@@Z)
  carla_server.lib(MapBuilder.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXAEBVexception@std@@@Z)
  carla_server.lib(ServerSession.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXAEBVexception@std@@@Z)
  carla_server.lib(Server.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXAEBVexception@std@@@Z)
  carla_server.lib(listener.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXAEBVexception@std@@@Z)
  carla_server.lib(primary.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXAEBVexception@std@@@Z)
  carla_server.lib(router.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXAEBVexception@std@@@Z)
  carla_server.lib(Map.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXAEBVexception@std@@@Z)
  carla_server.lib(secondary.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXAEBVexception@std@@@Z)
  carla_server.lib(OpenDriveParser.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXAEBVexception@std@@@Z)
  Module.Carla.1_of_4.cpp.obj : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXAEBVexception@std@@@Z)
  Module.Carla.2_of_4.cpp.obj : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXAEBVexception@std@@@Z)
  Module.Carla.3_of_4.cpp.obj : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXAEBVexception@std@@@Z)
  carla_server.lib(Token.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXAEBVexception@std@@@Z)
  carla_server.lib(primary.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &,struct boost::source_location const &)" (?throw_exception@boost@@YAXAEBVexception@std@@AEBUsource_location@1@@Z)
  carla_server.lib(ServerSession.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &,struct boost::source_location const &)" (?throw_exception@boost@@YAXAEBVexception@std@@AEBUsource_location@1@@Z)
  carla_server.lib(StreamStateBase.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &,struct boost::source_location const &)" (?throw_exception@boost@@YAXAEBVexception@std@@AEBUsource_location@1@@Z)
  carla_server.lib(Server.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &,struct boost::source_location const &)" (?throw_exception@boost@@YAXAEBVexception@std@@AEBUsource_location@1@@Z)
  carla_server.lib(listener.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &,struct boost::source_location const &)" (?throw_exception@boost@@YAXAEBVexception@std@@AEBUsource_location@1@@Z)
  carla_server.lib(primaryCommands.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &,struct boost::source_location const &)" (?throw_exception@boost@@YAXAEBVexception@std@@AEBUsource_location@1@@Z)
  carla_server.lib(router.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &,struct boost::source_location const &)" (?throw_exception@boost@@YAXAEBVexception@std@@AEBUsource_location@1@@Z)
  carla_server.lib(Dispatcher.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &,struct boost::source_location const &)" (?throw_exception@boost@@YAXAEBVexception@std@@AEBUsource_location@1@@Z)
  carla_server.lib(secondary.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &,struct boost::source_location const &)" (?throw_exception@boost@@YAXAEBVexception@std@@AEBUsource_location@1@@Z)
  Module.Carla.gen.5_of_8.cpp.obj : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &,struct boost::source_location const &)" (?throw_exception@boost@@YAXAEBVexception@std@@AEBUsource_location@1@@Z)
  Module.Carla.gen.6_of_8.cpp.obj : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &,struct boost::source_location const &)" (?throw_exception@boost@@YAXAEBVexception@std@@AEBUsource_location@1@@Z)
  Module.Carla.gen.7_of_8.cpp.obj : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &,struct boost::source_location const &)" (?throw_exception@boost@@YAXAEBVexception@std@@AEBUsource_location@1@@Z)
  carla_server.lib(Token.obj) : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &,struct boost::source_location const &)" (?throw_exception@boost@@YAXAEBVexception@std@@AEBUsource_location@1@@Z)
  Module.Carla.gen.1_of_8.cpp.obj : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &,struct boost::source_location const &)" (?throw_exception@boost@@YAXAEBVexception@std@@AEBUsource_location@1@@Z)
  Module.Carla.gen.2_of_8.cpp.obj : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &,struct boost::source_location const &)" (?throw_exception@boost@@YAXAEBVexception@std@@AEBUsource_location@1@@Z)
  Module.Carla.gen.3_of_8.cpp.obj : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &,struct boost::source_location const &)" (?throw_exception@boost@@YAXAEBVexception@std@@AEBUsource_location@1@@Z)
  Module.Carla.gen.4_of_8.cpp.obj : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &,struct boost::source_location const &)" (?throw_exception@boost@@YAXAEBVexception@std@@AEBUsource_location@1@@Z)
  Module.Carla.1_of_4.cpp.obj : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &,struct boost::source_location const &)" (?throw_exception@boost@@YAXAEBVexception@std@@AEBUsource_location@1@@Z)
  Module.Carla.2_of_4.cpp.obj : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &,struct boost::source_location const &)" (?throw_exception@boost@@YAXAEBVexception@std@@AEBUsource_location@1@@Z)
  Module.Carla.3_of_4.cpp.obj : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &,struct boost::source_location const &)" (?throw_exception@boost@@YAXAEBVexception@std@@AEBUsource_location@1@@Z)
  Module.Carla.4_of_4.cpp.obj : error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &,struct boost::source_location const &)" (?throw_exception@boost@@YAXAEBVexception@std@@AEBUsource_location@1@@Z)
  C:\jenkins\workspace\carla_PR-6960\Unreal\CarlaUE4\Plugins\Carla\Binaries\Win64\UE4Editor-Carla.dll : fatal error LNK1120: 2 unresolved externals
make: *** [CarlaUE4Editor] Error 6

**Comment by Blyron** [comment]
Are that many files need to fix DDS build? if not please redo PR Description to know what this exactly does

**Comment by berndgassmann** [comment]
Hi, Yes I'll do so. Maybe I can also split the commit in the build system related stuff (which was actually the starting point of this work) and the ROS2 feature work ... There is actually more to come. 
I mean the ROS2 feature at the state in dev branch is actually not fully operational yet -- at least not for what we require to run our simulation runs. I'm currently working on correct, not duplicated and more efficient data type transformation (getting rid of sin/cos calls, because Unreal AND ROS are using quaternions, so no need for an intermediate step towards RPY and back to quat which introduce 12 calls to sin/cos for EVERY transformation that is send). That (nearly) compiles, but cannot be merged before verified that it actually work/rotates in correct direction, etc.. But also some crucial interfaces are missing like VehicleStatus/VehicleInfo/Objects/TrafficLights and maybe some of the control interfaces. Let's see, what is required to have all interfaces up and running that I need for our project work. I believe the native ROS2 interface will speed up and ease the usage in conjunction with ROS2 and scenario runner dramatically -- we will still need lot's of the client extensions of the original carla ros bridge, I'm sure. Ah, and then I'll have to integrate the synchronization of the ego-vehicles control ... and improve the handling over the possibilities I had formerly with the python ROS bridge; I plan to extend at least the control interface by a timestamp (which was heavily missing to get a notion of the data based on the control decision) and extend that by a windowing mechanism to allow for continuous runs also in sync mode if the applications allows windowing. Maybe I need then some help by someone who knows/supports on the multi-server syncronization; let's see when I'm on that. Sorry for the tremendous refactoring, but especially the build system has grown up over time and it was extremely hard to find what's going wrong -- and like that error prone for extensions especially if people are not into the deep of the rather complex setup in conjunction with Unreal ;-).

**Comment by Blyron** [comment]
Would be nice to have this PR splitted in the two parts. We are aware of our build system issues we are also working on refactoring this. About ROS2 that's true it is incompleted that's why it is not in release patch notes.  

Thank you very much for your efforts. I will be on top of this PR and the new one.

**Pull request closed without merging**
