### PR TITLE
Extended the make import process for applying road painter materials

### PR DESCRIPTION
**Pull request by algababr**
#### Description

Iterated over the import process in order to apply the road painter materials (art tool) into imported maps. In this process, new textures are generated where the roads are rendered to so the road painter can use this in order to paint the roads and apply decals. The decals can now be loaded through a JSON script which is generated with default values if the JSON is not present inside the Import folder. A video will be done, explaining the new improvements to the import process.

Fixes #  

#### Where has this been tested?

  * **Platform(s):** Windows
  * **Python version(s):** 3.7.9
  * **Unreal Engine version(s):** 4.24

#### Possible Drawbacks

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4083)

### CODE REVIEW

**Review by bernatx — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4083)* status: 2 of 14 files reviewed, 1 unresolved discussion (waiting on @algababr)

___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.h, line 16 at r4](https://reviewable.io/reviews/carla-simulator/carla/4083#-MZMSS6I2z2T5SiNjopL:-MZMSS6I2z2T5SiNjopM:b-r4xeqf) ([raw file](https://github.com/carla-simulator/carla/blob/fbf2a0a09bd4e8c0e9492a06bb2129039f9221e8/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.h#L16)):*
> ```objc
> UCLASS()
> class CARLA_API ULoadAssetMaterialsCommandlet
> 	: public UCommandlet
> ```

Please replace all TAB as spaces and fix all indentations

**Review by bernatx — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 7 of 11 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4083#-:-MZRNgVK1XnTllFE6foW:bnfp4nl)* status: 10 of 14 files reviewed, 8 unresolved discussions (waiting on @algababr)

___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp, line 32 at r4](https://reviewable.io/reviews/carla-simulator/carla/4083#-MZRNwU-AMqR78SsxuVG:-MZRNwU0B4B4dUyqF6HD:b-8i6wz1) ([raw file](https://github.com/carla-simulator/carla/blob/fbf2a0a09bd4e8c0e9492a06bb2129039f9221e8/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp#L32)):*
> ```cpp
> 
>   RoadPainterSubclass = (UClass*)RoadPainterBlueprint.Object->GeneratedClass;
>   
> ```

Two spaces here to remove
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp, line 40 at r4](https://reviewable.io/reviews/carla-simulator/carla/4083#-MZRPIFZ0Ah9O8rhCsDH:-MZRPIFZ0Ah9O8rhCsDI:blyxy2b) ([raw file](https://github.com/carla-simulator/carla/blob/fbf2a0a09bd4e8c0e9492a06bb2129039f9221e8/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp#L40)):*
> ```
> //This
> ```
Please insert an space between // and the comment, for clarity
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp, line 224 at r4](https://reviewable.io/reviews/carla-simulator/carla/4083#-MZRPkGV25lU45Rk806t:-MZRPkGV25lU45Rk806u:b-hql3gd) ([raw file](https://github.com/carla-simulator/carla/blob/fbf2a0a09bd4e8c0e9492a06bb2129039f9221e8/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp#L224)):*
> ```cpp
> }
> 
> #endif
> ```

End with an extra return
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/NamingScript.h, line 1 at r4](https://reviewable.io/reviews/carla-simulator/carla/4083#-MZRQ05f004QOoGfUASg:-MZRQ05f004QOoGfUASh:bf4de7i) ([raw file](https://github.com/carla-simulator/carla/blob/fbf2a0a09bd4e8c0e9492a06bb2129039f9221e8/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/NamingScript.h#L1)):*
> ```objc
> // Copyright (c) 2017 Computer Vision Center (CVC) at the Universitat Autonoma
> ```

For new files please use current year
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/NamingScript.h, line 22 at r4](https://reviewable.io/reviews/carla-simulator/carla/4083#-MZRQA1H8LHv8xnc4SRg:-MZRQA1IDNyucuBDaP95:bmvancy) ([raw file](https://github.com/carla-simulator/carla/blob/fbf2a0a09bd4e8c0e9492a06bb2129039f9221e8/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/NamingScript.h#L22)):*
> ```objc
> enum class AssetTypes : uint8{
> 	
> 	//Textures
> ```

remove tabs and insert space in comments
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/RoadPainterWrapper.cpp, line 123 at r4](https://reviewable.io/reviews/carla-simulator/carla/4083#-MZRQiTg7ZS1dxqpLEN7:-MZRQiTg7ZS1dxqpLEN8:b-i6dgwc) ([raw file](https://github.com/carla-simulator/carla/blob/fbf2a0a09bd4e8c0e9492a06bb2129039f9221e8/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/RoadPainterWrapper.cpp#L123)):*
> ```cpp
>       bool IsRoadPainterReady = JsonParsed->GetBoolField(TEXT("prepared_roadpainter"));
>       if(IsRoadPainterReady == false){
>         
> ```

remove extra spaces
___
*[Util/BuildTools/Import.py, line 300 at r4](https://reviewable.io/reviews/carla-simulator/carla/4083#-MZRR4AQ2YyR6giqjINT:-MZRR4AQ2YyR6giqjINU:bes8koz) ([raw file](https://github.com/carla-simulator/carla/blob/fbf2a0a09bd4e8c0e9492a06bb2129039f9221e8/Util/BuildTools/Import.py#L300)):*
> ```Python
>     with open(os.path.join(package_config_path, package_name + ".Package.json"), "w+") as fh:
>         json.dump(output_json, fh, indent=4)
>         
> ```

more extra spaces

**Review by bernatx — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 2 of 11 files at r5, 7 of 10 files at r7.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4083)* status: 11 of 14 files reviewed, 8 unresolved discussions (waiting on @algababr and @bernatx)

___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.h, line 57 at r7](https://reviewable.io/reviews/carla-simulator/carla/4083#-MZqhsc19JWXUGZkLoLy:-MZqhsc19JWXUGZkLoLz:b71a3em) ([raw file](https://github.com/carla-simulator/carla/blob/3434c6c5d350adaa565e12091c5ed95a4bb09a52/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.h#L57)):*
> ```objc
>   UPROPERTY()
>   UWorld *NewWorldToLoad;
>   
> ```

We have some blankc lines with extra spaces here, check this file further please
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/PrepareAssetsForCookingCommandlet.cpp, line 186 at r7](https://reviewable.io/reviews/carla-simulator/carla/4083#-MZqi3rcDfGX5NW-JN58:-MZqi3rcDfGX5NW-JN59:b9juoil) ([raw file](https://github.com/carla-simulator/carla/blob/3434c6c5d350adaa565e12091c5ed95a4bb09a52/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/PrepareAssetsForCookingCommandlet.cpp#L186)):*
> ```cpp
>         else if (AssetName.Contains(SSTags::R_ROAD1) || AssetName.Contains(SSTags::R_ROAD2))
>         {
> 		  MeshActor->GetStaticMeshComponent()->SetMaterial(0, RoadNodeMaterial);
> ```

Here TABs again, please remove

**Comment by algababr** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.h, line 16 at r4](https://reviewable.io/reviews/carla-simulator/carla/4083#-MZMSS6I2z2T5SiNjopL:-M_5yr_J9hWR4QEZK4_o:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/fbf2a0a09bd4e8c0e9492a06bb2129039f9221e8/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.h#L16)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

Please replace all TAB as spaces and fix all indentations
</blockquote></details>

Done.

**Comment by algababr** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp, line 224 at r4](https://reviewable.io/reviews/carla-simulator/carla/4083#-MZRPkGV25lU45Rk806t:-M_5yvvM0DxWlIeMrliz:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/fbf2a0a09bd4e8c0e9492a06bb2129039f9221e8/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp#L224)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

End with an extra return
</blockquote></details>

Done.

**Comment by algababr** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp, line 40 at r4](https://reviewable.io/reviews/carla-simulator/carla/4083#-MZRPIFZ0Ah9O8rhCsDH:-M_5yvgu4fyaVff8ZQ8f:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/fbf2a0a09bd4e8c0e9492a06bb2129039f9221e8/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp#L40)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
> //This
> ```
Please insert an space between // and the comment, for clarity
</blockquote></details>

Done.

**Comment by algababr** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp, line 32 at r4](https://reviewable.io/reviews/carla-simulator/carla/4083#-MZRNwU-AMqR78SsxuVG:-M_5yvU1EQf3nuLz9AJR:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/fbf2a0a09bd4e8c0e9492a06bb2129039f9221e8/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp#L32)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

Two spaces here to remove
</blockquote></details>

Done.

**Comment by algababr** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/PrepareAssetsForCookingCommandlet.cpp, line 186 at r7](https://reviewable.io/reviews/carla-simulator/carla/4083#-MZqi3rcDfGX5NW-JN58:-M_5yxMe8tJl7tMDp8z7:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/3434c6c5d350adaa565e12091c5ed95a4bb09a52/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/PrepareAssetsForCookingCommandlet.cpp#L186)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

Here TABs again, please remove
</blockquote></details>

Done.

**Comment by algababr** [comment]
___
*[Util/BuildTools/Import.py, line 300 at r4](https://reviewable.io/reviews/carla-simulator/carla/4083#-MZRR4AQ2YyR6giqjINT:-M_5z-VHD2Sx7wplaMG5:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/fbf2a0a09bd4e8c0e9492a06bb2129039f9221e8/Util/BuildTools/Import.py#L300)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

more extra spaces
</blockquote></details>

Done.

**Comment by algababr** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/RoadPainterWrapper.cpp, line 123 at r4](https://reviewable.io/reviews/carla-simulator/carla/4083#-MZRQiTg7ZS1dxqpLEN7:-M_5yzzO7brrt0rd3d41:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/fbf2a0a09bd4e8c0e9492a06bb2129039f9221e8/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/RoadPainterWrapper.cpp#L123)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

remove extra spaces
</blockquote></details>

Done.

**Review by bernatx — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4083)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @algababr)

**Review by bernatx — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4083)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @algababr)

**Pull request merged**
