### PR TITLE
sergi-e/docs-vel-force-torque

### PR DESCRIPTION
**Pull request by sergi-e**
#### Description

- Updates on:
   - set_velocity() -> set_target_velocity()
   - set_angular_velocity() -> set_target_angular_velocity()
   - ApplyVelocity() -> ApplyTargetVelocity()
   - ApplyAngularVelocity() -> ApplyTargetAngularVelocity()

- Added/Modified in carla.Actor: 
   - add_angular_impulse()
   - add_impulse()
   - add_force()
   - add_torque()
   - enable_constant_velocity()
   - disable_constant_velocity()

- Added commands: 
   - ApplyForce()
   - ApplyTargetAngularVelocity()
   - ApplyTargetVelocity()
   - ApplyTorque

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04.4
  * **Python version(s):** 3.6.9
  * **Unreal Engine version(s):** 4.24

#### Possible drawbacks

- Missing units until PR on API units is merged. 
- Modifications are yet to come for this methods.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3349)

### CODE REVIEW

**Review by DSantosO — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3349)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @DSantosO and @sergi-e)

___
*[PythonAPI/docs/actor.yml, line 45 at r2](https://reviewable.io/reviews/carla-simulator/carla/3349#-MHz4dJK-got0lVJqUG3:-MHz4dJK-got0lVJqUG4:b-3924o0) ([raw file](https://github.com/carla-simulator/carla/blob/91edc49f653d7d1ea189d8847a4358a3ecfee00c/PythonAPI/docs/actor.yml#L45)):*
> ```
> Applies an impulse at the center of mass of the actor. Impulses only last an instant. Use __<font color="#7fb800">add_force()</font>__ to apply forces over a period of time.
> ```
I would change it to something like this:
Applies an angular impulse at the center of mass of the actor. This method should be used for instantaneous torques, usually applied once. Use __<font color="#7fb800">add_torque()</font>__ to apply rotation forces over a period of time.
___
*[PythonAPI/docs/actor.yml, line 63 at r2](https://reviewable.io/reviews/carla-simulator/carla/3349#-MHz9A8c3AzffheG4wGK:-MHz9A8c3AzffheG4wGL:bll8zed) ([raw file](https://github.com/carla-simulator/carla/blob/91edc49f653d7d1ea189d8847a4358a3ecfee00c/PythonAPI/docs/actor.yml#L63)):*
> ```
>  Applies an impulse at the center of mass of the actor. Impulses only last an instant. Use __<font color="#7fb800">add_force()</font>__ to apply forces over a period of time.··
> ```

I would change it to something like this:
Applies an impulse at the center of mass of the actor. This method should be used for instantaneous forces, usually applied once. Use __<font color="#7fb800">add_torque()</font>__ to apply forces over a period of time.
___
*[PythonAPI/docs/actor.yml, line 96 at r2](https://reviewable.io/reviews/carla-simulator/carla/3349#-MHzATgn7vcCkOdyH_YW:-MHzATgn7vcCkOdyH_YX:btbia7a) ([raw file](https://github.com/carla-simulator/carla/blob/91edc49f653d7d1ea189d8847a4358a3ecfee00c/PythonAPI/docs/actor.yml#L96)):*
> ```
> It will not be able to override the constant velocity being set.··
> ```
Actually, it overrides the velocity of the TM so it alter its behaviour, for this it needs to be use carefully with it.
___
*[PythonAPI/docs/actor.yml, line 164 at r2](https://reviewable.io/reviews/carla-simulator/carla/3349#-MHzAmyf-PKPwyW0dbME:-MHzAmygETDFu7-sHL1G:b53d25p) ([raw file](https://github.com/carla-simulator/carla/blob/91edc49f653d7d1ea189d8847a4358a3ecfee00c/PythonAPI/docs/actor.yml#L164)):*
> ```
> The modification will be effective two frames after the setting, and the update between velocities will be sudden.
> ```
Let only:
 The modification will be effective two frames after the setting. 

It is a setter, it is implied that once is effecive it is 'sudden'. (The same in the angular one)

**Review by sergi-e — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3349)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @DSantosO and @sergi-e)

___
*[PythonAPI/docs/actor.yml, line 45 at r2](https://reviewable.io/reviews/carla-simulator/carla/3349#-MHz4dJK-got0lVJqUG3:-MHz_avB0GmDnunE5l3Y:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/91edc49f653d7d1ea189d8847a4358a3ecfee00c/PythonAPI/docs/actor.yml#L45)):*
<details><summary><i>Previously, DSantosO wrote…</i></summary><blockquote>

> ```
> Applies an impulse at the center of mass of the actor. Impulses only last an instant. Use __<font color="#7fb800">add_force()</font>__ to apply forces over a period of time.
> ```
I would change it to something like this:
Applies an angular impulse at the center of mass of the actor. This method should be used for instantaneous torques, usually applied once. Use __<font color="#7fb800">add_torque()</font>__ to apply rotation forces over a period of time.
</blockquote></details>

Done.
___
*[PythonAPI/docs/actor.yml, line 63 at r2](https://reviewable.io/reviews/carla-simulator/carla/3349#-MHz9A8c3AzffheG4wGK:-MHz_bI40sCnovsglwNr:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/91edc49f653d7d1ea189d8847a4358a3ecfee00c/PythonAPI/docs/actor.yml#L63)):*
<details><summary><i>Previously, DSantosO wrote…</i></summary><blockquote>

> ```
>  Applies an impulse at the center of mass of the actor. Impulses only last an instant. Use __<font color="#7fb800">add_force()</font>__ to apply forces over a period of time.··
> ```

I would change it to something like this:
Applies an impulse at the center of mass of the actor. This method should be used for instantaneous forces, usually applied once. Use __<font color="#7fb800">add_torque()</font>__ to apply forces over a period of time.
</blockquote></details>

Done.
___
*[PythonAPI/docs/actor.yml, line 96 at r2](https://reviewable.io/reviews/carla-simulator/carla/3349#-MHzATgn7vcCkOdyH_YW:-MHz_6DT74ftArKbhwUg:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/91edc49f653d7d1ea189d8847a4358a3ecfee00c/PythonAPI/docs/actor.yml#L96)):*
<details><summary><i>Previously, DSantosO wrote…</i></summary><blockquote>

> ```
> It will not be able to override the constant velocity being set.··
> ```
Actually, it overrides the velocity of the TM so it alter its behaviour, for this it needs to be use carefully with it.
</blockquote></details>

Done.
___
*[PythonAPI/docs/actor.yml, line 164 at r2](https://reviewable.io/reviews/carla-simulator/carla/3349#-MHzAmyf-PKPwyW0dbME:-MHzZFGIDytozRGgQow1:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/91edc49f653d7d1ea189d8847a4358a3ecfee00c/PythonAPI/docs/actor.yml#L164)):*
<details><summary><i>Previously, DSantosO wrote…</i></summary><blockquote>

> ```
> The modification will be effective two frames after the setting, and the update between velocities will be sudden.
> ```
Let only:
 The modification will be effective two frames after the setting. 

It is a setter, it is implied that once is effecive it is 'sudden'. (The same in the angular one)
</blockquote></details>

Done.

**Review by DSantosO — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3349)* status: all files reviewed, 3 unresolved discussions (waiting on @DSantosO)

**Review by DSantosO — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3349)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by DSantosO — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3349#-:-MHzdMNe3NUwUv_5Knlc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
