### PR TITLE
Add 0.9.6 windows realease

### PR DESCRIPTION
**Pull request by Amin-Tgz**
Recently I build Carla for windows with 0.9.6 version source code and Unreal 4.22.
my experience exists [here](https://github.com/carla-simulator/carla/issues/2098)
if I upload binary files (about 4 gigs) on Google drive, would you put it in release part of the repository for other people use?

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/2108)

### CODE REVIEW

**Comment by for-testgit** [comment]
Is it possible to add it in release part?

**Comment by Amin-Tgz** [comment]
@nsubiron
if I upload CARLA binary built [0.9.6] for windows, would you place the google drive link of that in release part of the repository?

**Comment by DamnRicky** [comment]
Could you tell me when will the version of **_Carla 0.9.6_** for windows be available?

**Comment by Amin-Tgz** [comment]
I will be uploading files up to the weekend
All the files will be uploaded here:
[Awesome-CARLA](https://github.com/Amin-Tgz/awesome-CARLA)

**Comment by marcgpuig** [comment]
Hi @Amin-Tgz
First of all thanks for your PR.
This is really useful information! We'll be glad to merge these content if it is merged in the docs, not just a link to an issue.
Sadly, and as you could understand, we cannot provide these kinds of user-created-download links in our documentation :(

**Pull request closed without merging**
