### PR TITLE
CarSim tutorial refactoring and name change to bring in line with oth…

### PR DESCRIPTION
**Pull request by corkyw10**
I have refactored the CarSim tutorial:
- to bring the requisites together into a "Before you begin" section and have each requirement explained within that section
- added two highlight boxes, one for the beta feature and one to highlight the Vehicle Size discrepancy between CARLA and CarSim
- Split the plugin installation into Windows and Ubuntu 
- Changed the file name so it is in line with the other general tutorials

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3793)

### CODE REVIEW

**Review by bernatx — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3793)* status: all files reviewed, 2 unresolved discussions (waiting on @corkyw10)

___
*[Docs/tuto_G_carsim_integration.md, line 35 at r1](https://reviewable.io/reviews/carla-simulator/carla/3793#-MQmQKhC3p2F-Q2hlLGr:-MQmQKhC3p2F-Q2hlLGs:b-iygu3e) ([raw file](https://github.com/carla-simulator/carla/blob/c5dc4f89d87a1ae517139ff83957a9bdccaadac4/Docs/tuto_G_carsim_integration.md#L35)):*
> ```
> in the source version
> ```
maybe **source version* is misunderstood because we are using source version (GIT)? maybe better something like **root folder of CARLA**, or **source root**, or similars.
___
*[Docs/tuto_G_carsim_integration.md, line 91 at r1](https://reviewable.io/reviews/carla-simulator/carla/3793#-MQmRC224ANgLyDm-Wf_:-MQmRC224ANgLyDm-Wfa:bo64t3s) ([raw file](https://github.com/carla-simulator/carla/blob/c5dc4f89d87a1ae517139ff83957a9bdccaadac4/Docs/tuto_G_carsim_integration.md#L91)):*
> ```
> Generate the `.sim` file in Windows
> ```
Maybe this is not mandatory if the user creates the .sim file from scratch on Ubuntu (this is just a text file), and just modify the folders. That is why I added the content of the .sim file here, so they can do that with easy. I think it is faster than going to Windows and use a different license to just generate the .sim file.

**Comment by corkyw10** [comment]
I have made the requested changes. 

- Clarified where to run make launch
- Simplified Ubuntu sim file instructions and instructed users that they can use the file template

**Review by corkyw10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3793)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @bernatx)

___
*[Docs/tuto_G_carsim_integration.md, line 35 at r1](https://reviewable.io/reviews/carla-simulator/carla/3793#-MQmQKhC3p2F-Q2hlLGr:-MQrK8ZX92shr7urIQd0:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/c5dc4f89d87a1ae517139ff83957a9bdccaadac4/Docs/tuto_G_carsim_integration.md#L35)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
> in the source version
> ```
maybe **source version* is misunderstood because we are using source version (GIT)? maybe better something like **root folder of CARLA**, or **source root**, or similars.
</blockquote></details>

Done.
___
*[Docs/tuto_G_carsim_integration.md, line 91 at r1](https://reviewable.io/reviews/carla-simulator/carla/3793#-MQmRC224ANgLyDm-Wf_:-MQrK9cu3Ndz0tocmmdf:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/c5dc4f89d87a1ae517139ff83957a9bdccaadac4/Docs/tuto_G_carsim_integration.md#L91)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
> Generate the `.sim` file in Windows
> ```
Maybe this is not mandatory if the user creates the .sim file from scratch on Ubuntu (this is just a text file), and just modify the folders. That is why I added the content of the .sim file here, so they can do that with easy. I think it is faster than going to Windows and use a different license to just generate the .sim file.
</blockquote></details>

Done.

**Review by bernatx — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3793)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
