### PR TITLE
Sid1057/hotfix pythonapi examples

### PR DESCRIPTION
**Pull request by Sid1057**
#### Description

minor bug fixes in PythonAPI examples

Fixes #  
-  bug in PythonAPI/examples/lidar_to_camera.py
```
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '_out/00003003.png'
```
-  bug in PythonAPI/examples/visualize_multiple_sensors.py
```
    bp = world.get_blueprint_library().filter('charger2020')[0]
IndexError: index out of range

```

#### Where has this been tested?

  * **Platform(s):** linux
  * **Python version(s):** 3.7
  * **Unreal Engine version(s):** 4.26

#### Possible Drawbacks

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4485)

### CODE REVIEW

**Review by DSantosO — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4485)* status: all files reviewed, 1 unresolved discussion (waiting on @Sid1057)

___
*[PythonAPI/examples/lidar_to_camera.py, line 78 at r1](https://reviewable.io/reviews/carla-simulator/carla/4485#-MgQkLgU9846zyjpqo7m:-MgQkLgU9846zyjpqo7n:b-ucb40j) ([raw file](https://github.com/carla-simulator/carla/blob/c6aab48f44c85d9910e57197ce40bf92fe23f13f/PythonAPI/examples/lidar_to_camera.py#L78)):*
> ```Python
> 
>     try:
>         os.system('mkdir -p _out' if os.name != 'nt' else 'if not exist _out mkdir _out')
> ```

For compatibility reasons, it is better if you use `os.mkdir` instead of a `os.system` call.

**Comment by DSantosO** [comment]
Hello @Sid1057,
Thank you for your pull request. 
I have reviewed it asking for a change in the `lidar_ to_ camera` script.

**Comment by Sid1057** [comment]
Hello @DSantosO , thanks for the review.

> For compatibility reasons, it is better if you use `os.mkdir` instead of a `os.system` call.

Sure, my bad.

**Review by DSantosO — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4485)* status: all files reviewed, 1 unresolved discussion (waiting on @Sid1057)

**Review by DSantosO — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4485#-:-MgQqaFi7NKwqd2o2fOp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Sid1057)

**Comment by DSantosO** [comment]
Merged!
Thanks for the contribution.

**Pull request merged**
