### PR TITLE
Corkyw10/maps documentation

### PR DESCRIPTION
**Pull request by corkyw10**
## Maps major reformat

I have made a reformat of all the maps documentation. There is now a tutorial section devoted entirely to maps and it follows the below structure.

  - Overview of custom maps in CARLA
  - Create a map in RoadRunner
  - Import map in CARLA package
  - Import map in CARLA source build
  - Alternative ways to import maps
  - Manually prepare map package
  - Customizing maps: Layered maps
  - Customizing maps: Traffic lights and signs
  - Customizing maps: Road painter
  - Customizing maps: Procedural Buildings
  - Customizing maps: Weather and landscape
  - Generate pedestrian navigation

I will need to add the Open Street Map options in the future.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4233)

### CODE REVIEW

**Review by XGodina — CHANGES_REQUESTED** [review]
> Reviewed 34 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4233)* status: all files reviewed, 2 unresolved discussions (waiting on @bernatx and @corkyw10)

___
*[Docs/tuto_A_material_customization.md, line 145 at r1](https://reviewable.io/reviews/carla-simulator/carla/4233#-Mc5GeJ21kFerkuPoiX2:-Mc5GeJ21kFerkuPoiX3:b-iokcvr) ([raw file](https://github.com/carla-simulator/carla/blob/34084f272fed062eb28834fc1322ecc00ffebdf4/Docs/tuto_A_material_customization.md#L145)):*
> ```Markdown
> 	*   `MetallicCorrection` — Changes the intensity of the metallic map.  
> 	*   `NormalFlatness` — Changes the intensity of the normal map.  
> ```

Maybe in that section, we should put some pictures about Building shader. The section above has images of cars and the material. I think it better illustrates how the shader works. Marcos, he could provide you some pictures.
___
*[Docs/tuto_M_generate_pedestrian_navigation.md, line 40 at r1](https://reviewable.io/reviews/carla-simulator/carla/4233#-Mc6CZriEh5a-uqxpWZ2:-Mc6CVye-zQcv-Tlynfw:b-iqzx5t) ([raw file](https://github.com/carla-simulator/carla/blob/f68e0acb286ea73625c25e7f831a63db6b46d9ab/Docs/tuto_M_generate_pedestrian_navigation.md#L40)):*
> ```Markdown
> 
> These spawning points will be used in scripts such as [`spawn_npc.py`](https://github.com/carla-simulator/carla/blob/master/PythonAPI/examples/spawn_npc.py):
> ```

Currently, we don't use to add Spawn point for pedestrians. I'm not totally sure, Bernat knows better than me. Clarify this part with him, just in case.

**Review by corkyw10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4233)* status: 32 of 37 files reviewed, 2 unresolved discussions (waiting on @bernatx, @corkyw10, and @XGodina)

___
*[Docs/tuto_M_generate_pedestrian_navigation.md, line 40 at r1](https://reviewable.io/reviews/carla-simulator/carla/4233#-Mc6CZriEh5a-uqxpWZ2:-Mfi05JR-dA0lZkrEmPg:bseruls) ([raw file](https://github.com/carla-simulator/carla/blob/f68e0acb286ea73625c25e7f831a63db6b46d9ab/Docs/tuto_M_generate_pedestrian_navigation.md#L40)):*
<details><summary><i>Previously, XGodina (Xavi ) wrote…</i></summary><blockquote>

Currently, we don't use to add Spawn point for pedestrians. I'm not totally sure, Bernat knows better than me. Clarify this part with him, just in case.
</blockquote></details>

@bernatx  should I remove the part about the spawn points?

**Review by bernatx — DISMISSED** [review]
> Reviewed 4 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4233)* status: all files reviewed, 2 unresolved discussions (waiting on @corkyw10 and @XGodina)

___
*[Docs/tuto_M_generate_pedestrian_navigation.md, line 40 at r1](https://reviewable.io/reviews/carla-simulator/carla/4233#-Mc6CZriEh5a-uqxpWZ2:-MfiH80L2CYX9a380h7S:b-wc7zm9) ([raw file](https://github.com/carla-simulator/carla/blob/f68e0acb286ea73625c25e7f831a63db6b46d9ab/Docs/tuto_M_generate_pedestrian_navigation.md#L40)):*
<details><summary><i>Previously, corkyw10 (Corinne) wrote…</i></summary><blockquote>

@bernatx  should I remove the part about the spawn points?
</blockquote></details>

Yes, those spawn points are not used for the pedestrians. They are spawn by code only in sidewalks. So, if there are sidewalks there, then the user does not need to do anything extra. Random points from those sidewalks will be choosed to spawn each pedestrian. We can remove the 'Create new spawning points' section.

**Review by bernatx — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4233)* status: 39 of 42 files reviewed, 4 unresolved discussions (waiting on @corkyw10 and @XGodina)

___
*[Docs/large_map_import.md, line 18 at r4](https://reviewable.io/reviews/carla-simulator/carla/4233#-Mfj0zzL-yTBrBbiEuzi:-Mfj0zzL-yTBrBbiEuzj:bn7dn6y) ([raw file](https://github.com/carla-simulator/carla/blob/4a18f245dd8f199c0cd0248a1a67eea522f130c7/Docs/large_map_import.md#L18)):*
> ```
> - Subfolders for each `.fbx` file containing textures for the assets if required.
> ```
These subfolders are created by the .fbx parser that extracts all those textures in those subfolders automatically, because the textures can be embedded inside the .fbx
So, the user does not need to create those subfolders, they are extracted automatically if required.
I would probably remove those subfolders from the structure below also.
___
*[Docs/large_map_import.md, line 60 at r4](https://reviewable.io/reviews/carla-simulator/carla/4233#-Mfj1btwEb0bR7uALkY8:-Mfj1btwEb0bR7uALkY9:b-525dmv) ([raw file](https://github.com/carla-simulator/carla/blob/4a18f245dd8f199c0cd0248a1a67eea522f130c7/Docs/large_map_import.md#L60)):*
<details><summary><i alt="summary">Quoted 16 lines of code…</i></summary>

> ```
>   ├── Map01_Tile_0_0.fbm
>   |   ├── Grass1_Diff.jpg
>   |   ├── Grass1_Norm.jpg
>   |   └── Grass1_Spec.jpg
>   ├── Map01_Tile_0_1.fbm
>   |   ├── Grass1_Diff.jpg
>   |   ├── Grass1_Norm.jpg
>   |   └── Grass1_Spec.jpg
>   ├── Map01_Tile_1_0.fbm
>   |   ├── Grass1_Diff.jpg
>   |   ├── Grass1_Norm.jpg
>   |   └── Grass1_Spec.jpg
>   └── Map01_Tile_1_1.fbm
>       ├── Grass1_Diff.jpg
>       ├── Grass1_Norm.jpg
>       └── Grass1_Spec.jpg
> ```
</details>

all these is extracted from the .fbx files, so the user does not need to put it there. I would remove them for clarifying.

**Review by corkyw10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4233)* status: 39 of 42 files reviewed, 4 unresolved discussions (waiting on @bernatx, @corkyw10, and @XGodina)

___
*[Docs/large_map_import.md, line 18 at r4](https://reviewable.io/reviews/carla-simulator/carla/4233#-Mfj0zzL-yTBrBbiEuzi:-Mfl2QRE4iEsd03aVJ67:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/4a18f245dd8f199c0cd0248a1a67eea522f130c7/Docs/large_map_import.md#L18)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
> - Subfolders for each `.fbx` file containing textures for the assets if required.
> ```
These subfolders are created by the .fbx parser that extracts all those textures in those subfolders automatically, because the textures can be embedded inside the .fbx
So, the user does not need to create those subfolders, they are extracted automatically if required.
I would probably remove those subfolders from the structure below also.
</blockquote></details>

Done.
___
*[Docs/large_map_import.md, line 60 at r4](https://reviewable.io/reviews/carla-simulator/carla/4233#-Mfj1btwEb0bR7uALkY8:-Mfl2Qhv-LInO-oKIoE-:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/4a18f245dd8f199c0cd0248a1a67eea522f130c7/Docs/large_map_import.md#L60)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
>   ├── Map01_Tile_0_0.fbm
>   |   ├── Grass1_Diff.jpg
>   |   ├── Grass1_Norm.jpg
>   |   └── Grass1_Spec.jpg
>   ├── Map01_Tile_0_1.fbm
>   |   ├── Grass1_Diff.jpg
>   |   ├── Grass1_Norm.jpg
>   |   └── Grass1_Spec.jpg
>   ├── Map01_Tile_1_0.fbm
>   |   ├── Grass1_Diff.jpg
>   |   ├── Grass1_Norm.jpg
>   |   └── Grass1_Spec.jpg
>   └── Map01_Tile_1_1.fbm
>       ├── Grass1_Diff.jpg
>       ├── Grass1_Norm.jpg
>       └── Grass1_Spec.jpg
> ```
all these is extracted from the .fbx files, so the user does not need to put it there. I would remove them for clarifying.
</blockquote></details>

Done.
___
*[Docs/tuto_A_material_customization.md, line 145 at r1](https://reviewable.io/reviews/carla-simulator/carla/4233#-Mc5GeJ21kFerkuPoiX2:-Mfl20rh0iFg6dBjARYL:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/34084f272fed062eb28834fc1322ecc00ffebdf4/Docs/tuto_A_material_customization.md#L145)):*
<details><summary><i>Previously, XGodina (Xavi ) wrote…</i></summary><blockquote>

Maybe in that section, we should put some pictures about Building shader. The section above has images of cars and the material. I think it better illustrates how the shader works. Marcos, he could provide you some pictures.
</blockquote></details>

Done.
___
*[Docs/tuto_M_generate_pedestrian_navigation.md, line 40 at r1](https://reviewable.io/reviews/carla-simulator/carla/4233#-Mc6CZriEh5a-uqxpWZ2:-Mfl1hBNCrdst-q3lJOM:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/f68e0acb286ea73625c25e7f831a63db6b46d9ab/Docs/tuto_M_generate_pedestrian_navigation.md#L40)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

Yes, those spawn points are not used for the pedestrians. They are spawn by code only in sidewalks. So, if there are sidewalks there, then the user does not need to do anything extra. Random points from those sidewalks will be choosed to spawn each pedestrian. We can remove the 'Create new spawning points' section.
</blockquote></details>

Done.

**Review by bernatx — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r4, 2 of 2 files at r7, 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4233)* status: all files reviewed, 3 unresolved discussions (waiting on @corkyw10 and @XGodina)

___
*[Docs/tuto_M_manual_map_package.md, line 5 at r8](https://reviewable.io/reviews/carla-simulator/carla/4233#-Mfn5dEX0l7vTEPrnUH7:-Mfn5dEX0l7vTEPrnUH8:bdmix15) ([raw file](https://github.com/carla-simulator/carla/blob/2234782e73e34f332cd73727bb35acb5885165a9/Docs/tuto_M_manual_map_package.md#L5)):*
> ```Markdown
> A map package follows a certain folder structure and must contain a `.json` file describing that structure. Our automatic map import processes create this `.json` file automatically, but you also have the option to prepare it yourself. Including your own `.json` file will overwrite any arguments passed to the `make import` command.
> 
> - [__Normal Maps__](#normal-maps)
> ```

Can we use here also the term **standard** maps instead of normal?

**Review by corkyw10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4233)* status: 41 of 42 files reviewed, 3 unresolved discussions (waiting on @bernatx and @XGodina)

___
*[Docs/tuto_M_manual_map_package.md, line 5 at r8](https://reviewable.io/reviews/carla-simulator/carla/4233#-Mfn5dEX0l7vTEPrnUH7:-MfnBFYNEVK7QfUQjxMb:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/10ecd566ceb5dfbe2d1050a791f7648561ae0f92/Docs/tuto_M_manual_map_package.md#L5)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

Can we use here also the term **standard** maps instead of normal?
</blockquote></details>

Done.

**Review by bernatx — APPROVED** [review]
> Reviewed 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4233)* status: all files reviewed, 2 unresolved discussions (waiting on @XGodina)

**Pull request merged**
