### PR TITLE
Fixed client crash when rotating vehicle wheels

### PR DESCRIPTION
**Pull request by algababr**
#### Description

Changes for rotating vehicle wheels through the Python API without any crashes. Needs update from engine for this to work.

#### Where has this been tested?

  * **Platform(s):** Windows
  * **Python version(s):** 3.7.9
  * **Unreal Engine version(s):** 4.26

#### Possible Drawbacks

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4370)

### CODE REVIEW

**Comment by DSantosO** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp, line 499 at r1](https://reviewable.io/reviews/carla-simulator/carla/4370#-Me49aLW8k-6YPvkf2wm:-Me49aLW8k-6YPvkf2wn:b-svrxit) ([raw file](https://github.com/carla-simulator/carla/blob/b855d61bdcba712aaec18f5d48cac98ae988f53b/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp#L499)):*
> ```cpp
>     VehicleAnim->SetWheelRotYaw((uint8)WheelLocation, AngleInDeg);
>   }
>   else {
> ```

In the plugin, follow Unreal coding stype. Opening curly brackets in the next line. 
Also, be careful with new lines like the one before the Log

**Review by DSantosO — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4370)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @algababr)

___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp, line 546 at r1](https://reviewable.io/reviews/carla-simulator/carla/4370#-Me4A3QcD2b7qKUgiosv:-Me4A3QcD2b7qKUgiosw:bpjkbbi) ([raw file](https://github.com/carla-simulator/carla/blob/b855d61bdcba712aaec18f5d48cac98ae988f53b/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp#L546)):*
> ```cpp
>   GetWorld()->GetPhysicsScene()->GetPxScene()->lockWrite();
>   if (enabled) {
> ```

Again, coding style and new lines.

**Comment by algababr** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp, line 546 at r1](https://reviewable.io/reviews/carla-simulator/carla/4370#-Me4A3QcD2b7qKUgiosv:-MeiWwWn-FsAdULngjYp:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/4a9dfa1a1a8a68939d9edc72a3a70f3d8828ac0d/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp#L546)):*
<details><summary><i>Previously, DSantosO wrote…</i></summary><blockquote>

Again, coding style and new lines.
</blockquote></details>

Done.

**Comment by algababr** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp, line 499 at r1](https://reviewable.io/reviews/carla-simulator/carla/4370#-Me49aLW8k-6YPvkf2wm:-MeiWvWm-gmHie0Za0F6:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/4a9dfa1a1a8a68939d9edc72a3a70f3d8828ac0d/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp#L499)):*
<details><summary><i>Previously, DSantosO wrote…</i></summary><blockquote>

In the plugin, follow Unreal coding stype. Opening curly brackets in the next line. 
Also, be careful with new lines like the one before the Log
</blockquote></details>

Done.

**Review by algababr — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4370)* status: all files reviewed, 2 unresolved discussions (waiting on @DSantosO)

**Review by bernatx — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4370)* status: all files reviewed, 2 unresolved discussions (waiting on @DSantosO)

**Review by DSantosO — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4370)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @algababr)

**Pull request merged**
