### PR TITLE
Add reset all traffic lights function

### PR DESCRIPTION
**Pull request by Axel1092**
#### Description

This PR adds a function to the class world in the API that resets all traffic lights to the initial state in the simulation. It is useful to synchronize all lights to a determined initial state.

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04
  * **Python version(s):** 3
  * **Unreal Engine version(s):** 4.24

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3334)

### CODE REVIEW

**Review by sergi-e — APPROVED** [review]
> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3334)* status: 2 of 9 files reviewed, all discussions resolved (waiting on @glopezdiest, @marcgpuig, and @sergi-e)

**Review by bernatx — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3334)* status: all files reviewed, 1 unresolved discussion (waiting on @Axel1092, @glopezdiest, and @marcgpuig)

___
*[LibCarla/source/carla/client/detail/Client.cpp, line 330 at r2](https://reviewable.io/reviews/carla-simulator/carla/3334#-MHopqndETI7lM9Nn4gM:-MHopqneCwXZMGXJGoZK:b-enhpkc) ([raw file](https://github.com/carla-simulator/carla/blob/c385cc02ff832ea50afd44d18e597190e4dee1e6/LibCarla/source/carla/client/detail/Client.cpp#L330)):*
> ```
> AsyncCall
> ```
Probably would be better to use **CallAndWait** for this function? It is meant to be used for determinism purposes, so better if the function waits for the job?

**Review by Axel1092 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3334)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @bernatx, @glopezdiest, and @marcgpuig)

___
*[LibCarla/source/carla/client/detail/Client.cpp, line 330 at r2](https://reviewable.io/reviews/carla-simulator/carla/3334#-MHopqndETI7lM9Nn4gM:-MHoswea9OoOAgQw7xIL:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/c385cc02ff832ea50afd44d18e597190e4dee1e6/LibCarla/source/carla/client/detail/Client.cpp#L330)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
> AsyncCall
> ```
Probably would be better to use **CallAndWait** for this function? It is meant to be used for determinism purposes, so better if the function waits for the job?
</blockquote></details>

Done.

**Review by bernatx — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3334)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @glopezdiest and @marcgpuig)

**Review by bernatx — APPROVED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3334)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @glopezdiest and @marcgpuig)

**Pull request merged**
