### PR TITLE
Initial CHRONO implementation

### PR DESCRIPTION
**Pull request by Axel1092**
#### Description

This PR brings an initial implementation of the CHRONO physics engine for vehicles (http://projectchrono.org/) to CARLA.
For vehicles, it adds a new function `enable_chrono_physics(max_substeps, max_substep_delta_time)`, which hands the physics simulation of the vehicle to CHRONO.

The implementation is done in `ChronoMovementComponent.h` and `ChronoMovementComponent.cpp`.

The build system has been changed to add the CHRONO library to be compiled and included in CARLA. CHRONO is added as an optional module, in order to include it in your project you need to add the argument "--chrono" to the `make XXX` commands.

In addition, CHRONO requires RTTI enabled which requires a small modification to the Unreal Engine: in the file `Engine\Source\Programs\UnrealBuildTool\Configuration\TargetRules.cs` the line `public bool bForceEnableRTTI = false;` needs to chenge to `public bool bForceEnableRTTI = true;`.

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18, Windows
  * **Python version(s):** 3
  * **Unreal Engine version(s):** 4.24

#### Possible Drawbacks
For Linux, without the chrono module CARLA is compatible with RTTI on and off but this is not the case for Windows. If RTTI is on then the CHRONO flag should be used as well. This will change once we enable RTTI always.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3858)

### CODE REVIEW

**Review by bernatx — CHANGES_REQUESTED** [review]
> Reviewed 20 of 23 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3858)* status: 21 of 22 files reviewed, 1 unresolved discussion (waiting on @Axel1092 and @DSantosO)

___
*[Util/InstallersWin/install_chrono.bat, line 119 at r2](https://reviewable.io/reviews/carla-simulator/carla/3858#-MT12pdGAqI1-gpxBCzx:-MT12pdHEcv2ivYXuHki:b6g5du4) ([raw file](https://github.com/carla-simulator/carla/blob/5a712687595efc62249e557083ca0c473ed1652b/Util/InstallersWin/install_chrono.bat#L119)):*
> ```
> xerces
> ```
Change all **xerces** references to **chrono**

**Review by bernatx — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3858)* status: all files reviewed, 1 unresolved discussion (waiting on @Axel1092 and @DSantosO)

**Review by Axel1092 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3858)* status: 18 of 22 files reviewed, 1 unresolved discussion (waiting on @bernatx and @DSantosO)

___
*[Util/InstallersWin/install_chrono.bat, line 119 at r2](https://reviewable.io/reviews/carla-simulator/carla/3858#-MT12pdGAqI1-gpxBCzx:-MTfK9KX24Ix-ROsJbqD:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/5a712687595efc62249e557083ca0c473ed1652b/Util/InstallersWin/install_chrono.bat#L119)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
> xerces
> ```
Change all **xerces** references to **chrono**
</blockquote></details>

Done.

**Review by bernatx — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3858)* status: 20 of 22 files reviewed, 2 unresolved discussions (waiting on @Axel1092, @bernatx, and @DSantosO)

___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/MovementComponents/ChronoMovementComponent.h, line 57 at r4](https://reviewable.io/reviews/carla-simulator/carla/3858#-MTfURuVDMpZQHtN3mxW:-MTfURuWDOyGgLY_-JCn:b-jiicry) ([raw file](https://github.com/carla-simulator/carla/blob/737e1126b21dc46f46f74ec7f780a8d2e3107e70/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/MovementComponents/ChronoMovementComponent.h#L57)):*
> ```objc
>   float MaxSubstepDeltaTime = 0.01;
>   FVehicleControl VehicleControl;
>   // FString VehicleFilePath = "/home/axel/Documents/Chrono/build/data/hmmwv/vehicle/HMMWV_Vehicle.json";
> ```

May you remove commented lines? :)
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/MovementComponents/ChronoMovementComponent.cpp, line 170 at r4](https://reviewable.io/reviews/carla-simulator/carla/3858#-MTfUmiR5QLKFnJWsS4j:-MTfUmiR5QLKFnJWsS4k:b-jiicry) ([raw file](https://github.com/carla-simulator/carla/blob/737e1126b21dc46f46f74ec7f780a8d2e3107e70/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/MovementComponents/ChronoMovementComponent.cpp#L170)):*
> ```cpp
>   my_hmmwv.SetAerodynamicDrag(0.5, 5.0, 1.2);
>   my_hmmwv.Initialize();
>   // vehicle = WheeledVehicle(vehicle::GetDataFile(carla::rpc::FromFString(VehicleFilePath)));
> ```

May you remove commented lines? :)

**Review by Axel1092 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3858)* status: 20 of 22 files reviewed, 2 unresolved discussions (waiting on @bernatx and @DSantosO)

___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/MovementComponents/ChronoMovementComponent.h, line 57 at r4](https://reviewable.io/reviews/carla-simulator/carla/3858#-MTfURuVDMpZQHtN3mxW:-MTf_jXQ8yuGleTS8bhp:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/737e1126b21dc46f46f74ec7f780a8d2e3107e70/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/MovementComponents/ChronoMovementComponent.h#L57)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

May you remove commented lines? :)
</blockquote></details>

Done.
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/MovementComponents/ChronoMovementComponent.cpp, line 170 at r4](https://reviewable.io/reviews/carla-simulator/carla/3858#-MTfUmiR5QLKFnJWsS4j:-MTf_m2B0eRWVTKnXj_F:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/737e1126b21dc46f46f74ec7f780a8d2e3107e70/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/MovementComponents/ChronoMovementComponent.cpp#L170)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

May you remove commented lines? :)
</blockquote></details>

Done.

**Review by bernatx — APPROVED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3858)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DSantosO)

**Pull request merged**
