### PR TITLE
Fix Build Issue on Ubuntu 20.04

### PR DESCRIPTION
**Pull request by SwiftGust**
#### Description

Fixes #  

- https://github.com/carla-simulator/carla/issues/6901

- https://github.com/carla-simulator/carla/issues/6776

1. Added missing c++ standard header, updated library version & compile command
3. Updated std C++ to 17
4. Updated Boost to 1.83.0 and build command accordingly - use local clang packaged under Unreal Engine
5. Updated Proj to 9.3.0 according to the https://github.com/carla-simulator/carla/issues/6776
6. Made sure to build dependencies to be built with Position Independent Code

#### Where has this been tested?

  * **Platform(s):** Ubuntu 20.04
  * **Python version(s):** Python 3.8
  * **Unreal Engine version(s):** UE 4.26

#### Possible Drawbacks
Introduction of C++ 17, boost 1.83.0, proj 9.3.0 may introduce compatibility issue

- - -
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/6974)

### CODE REVIEW

**Comment by ll7** [comment]
I do have the the mentioned errors, however checking out this PR still results in the same 'thread' error in my case.

```bash
carla$ make PythonAPI
Util/BuildTools/Linux.mk:163: warning: overriding recipe for target 'downloadplugins'
Util/BuildTools/Linux.mk:142: warning: ignoring old recipe for target 'downloadplugins'
Setup.sh: Retrieving boost.
Setup.sh: Extracting boost for Python 3.
Building B2 engine..

A C++11 capable compiler is required for building the B2 engine.
Toolset 'clang' does not appear to support C++11.

> clang++ -x c++ -std=c++11  check_cxx11.cpp
check_cxx11.cpp:14:10: fatal error: 'thread' file not found
#include <thread>
         ^~~~~~~~
1 error generated.


** Note, the C++11 capable compiler is _only_ required for building the B2
** engine. The B2 build system allows for using any C++ level and any other
** supported language and resource in your projects.


You can specify the toolset as the argument, i.e.:
    ./build.sh [options] gcc

Toolsets supported by this script are:
    acc, clang, como, gcc, intel-darwin, intel-linux, kcc, kylix, mipspro,
    pathscale, pgi, qcc, sun, sunpro, tru64cxx, vacpp

For any toolset you can override the path to the compiler with the '--cxx'
option. You can also use additional flags for the compiler with the
'--cxxflags' option.

A special toolset; cxx, is available which is used as a fallback when a more
specific toolset is not found and the cxx command is detected. The 'cxx'
toolset will use the '--cxx' and '--cxxflags' options, if present.

Options:
    --help                  Show this help message.
    --verbose               Show messages about what this script is doing.
    --debug                 Build b2 with debug information, and no
                            optimizations.
    --guess-toolset         Print the toolset we can detect for building.
    --cxx=CXX               The compiler exec to use instead of the detected
                            compiler exec.
    --cxxflags=CXXFLAGS     The compiler flags to use in addition to the
                            flags for the detected compiler.



Failed to build B2 build engine
make: *** [Util/BuildTools/Linux.mk:142: setup] Error 1
```

**Comment by juliancao** [comment]
The fix didn't work for me, either.

**Comment by SwiftGust** [comment]
@ll7 @juliancao sorry for inconvenience, this error could be related to trying to build boost with clang included in Carla's fork of  UnrealEngine, would you test build with system installed g++ by removing `include="${LLVM_INCLUDE},${LLVM_LIBPATH}` in https://github.com/carla-simulator/carla/pull/6974/files#diff-b617d525d7cf7a5c9bb4a0a916007bd224ad09709521611a0b23df1701084624R122-R123

**Comment by juliancao** [comment]
I tried removing `include="${LLVM_INCLUDE},${LLVM_LIBPATH} `, the error still exists

**Comment by ll7** [comment]
> @ll7 @juliancao sorry for inconvenience, this error could be related to trying to build boost with clang included in Carla's fork of UnrealEngine, would you test build with system installed g++ by removing `include="${LLVM_INCLUDE},${LLVM_LIBPATH}` in https://github.com/carla-simulator/carla/pull/6974/files#diff-b617d525d7cf7a5c9bb4a0a916007bd224ad09709521611a0b23df1701084624R122-R123

Sorry, I upgraded to ubuntu 22.04 and no longer have any issues. Therefore, I am unable to test your suggestion.

**Comment by Blyron** [comment]
All PRs must be against dev. We have fixed issues with Ubuntu 22.04 So please check latest docs and see if this is still necesary
https://carla.readthedocs.io/en/latest/build_linux/

**Pull request closed without merging**
