### PR TITLE
Controllable walkers by python

### PR DESCRIPTION
**Pull request by dnovillo-CVC**
#### Description

Added a walker bone controller to be able to send bone and position to walkers and modify them.

Fixes #  

#### Where has this been tested?

  * **Platform(s):** Linux
  * **Python version(s):** 2,3
  * **Unreal Engine version(s):** 4.22

#### Possible Drawbacks

It should be independent enough, but beware of the controller in Unreal's side, just in case.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/1719)

### CODE REVIEW

**Comment by M-Elfeki** [comment]
**Python API for invoking the bone_transforms is not working:**

When running this code:
`world = client.get_world()
    blueprint = random.choice(world.get_blueprint_library().filter('walker.*'))

    spawn_point = random.choice(world.get_map().get_spawn_points())
    walker_control = carla.WalkerControl()
    walker_control.speed = 1
    walker_control.direction = spawn_point.rotation.get_forward_vector()
    walker = world.try_spawn_actor(blueprint, spawn_point)
    walker_bones = carla.WalkerBoneControl()
    if walker is not None:
        actor_list.append(walker)
        walker.set_manual_bones_mode()
        walker.apply_control(walker_bones)
        print walker_bones.bone_transforms`

It shows the following error:
`Traceback (most recent call last):
  File "extract_bones.py", line 46, in <module>
    print walker_bones.bone_transforms
TypeError: No to_python (by-value) converter found for C++ type: std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, carla::geom::Transform>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, carla::geom::Transform> > >`

Does anyone know the reason?
Thanks.

**Comment by wattsavolt** [comment]
___
*[LibCarla/source/carla/client/Walker.h, line 42 at r1](https://reviewable.io/reviews/carla-simulator/carla/1719#-LgXwkeM3lHBVG82KbMS:-LhGbQbe92OMQnk0VyT9:bas4jaw) ([raw file](https://github.com/carla-simulator/carla/blob/bef3c8b8abb203ebc30231414e18dcdc8e94fbef/LibCarla/source/carla/client/Walker.h#L42)):*
<details><summary><i>Previously, nsubiron (Néstor Subirón) wrote…</i></summary><blockquote>

This `_bone_control` is not necessary and not used.
</blockquote></details>

It is used in the cpp. We could use a boost variant?

**Comment by wattsavolt** [comment]
___
*[LibCarla/source/carla/rpc/WalkerBoneControl.h, line 73 at r1](https://reviewable.io/reviews/carla-simulator/carla/1719#-LgXtZZj5_fbIy8W9Zn6:-LhGcbNsB6NkNNVxbJcG:bvgojm) ([raw file](https://github.com/carla-simulator/carla/blob/bef3c8b8abb203ebc30231414e18dcdc8e94fbef/LibCarla/source/carla/rpc/WalkerBoneControl.h#L73)):*
<details><summary><i>Previously, nsubiron (Néstor Subirón) wrote…</i></summary><blockquote>

Same here, rotations can be automatically converted.
</blockquote></details>


This is being done when the FVector values are being created in carla.Location. The conversion from meters to centimetres is working.

**Comment by wattsavolt** [comment]
___
*[LibCarla/source/carla/sensor/data/ActorDynamicState.h, line 116 at r1](https://reviewable.io/reviews/carla-simulator/carla/1719#-LgXtmu20oRqqljvZ-8o:-LhGdB_eBQoa1E5hBCgo:b4kwxvs) ([raw file](https://github.com/carla-simulator/carla/blob/bef3c8b8abb203ebc30231414e18dcdc8e94fbef/LibCarla/source/carla/sensor/data/ActorDynamicState.h#L116)):*
<details><summary><i>Previously, nsubiron (Néstor Subirón) wrote…</i></summary><blockquote>

Vectors cannot be packed, I would remove this class if not used.
</blockquote></details>

It needs to be used if the user wants to get back the data from the server. They probably wouldn't need to seeing as they'd have the current skeletal joint orientations and locations on the client side. Maybe they'd want to get the data from the default pose though. This does not cause a compile error but I haven't checked if it returns the data correctly. I'll check that.

**Comment by wattsavolt** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Walker/WalkerBoneControl.h, line 17 at r1](https://reviewable.io/reviews/carla-simulator/carla/1719#-LgXv3sCCJLbrSLHytdk:-LhGfJUA7ntA_1jr6w1_:bzbo2zm) ([raw file](https://github.com/carla-simulator/carla/blob/bef3c8b8abb203ebc30231414e18dcdc8e94fbef/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Walker/WalkerBoneControl.h#L17)):*
<details><summary><i>Previously, nsubiron (Néstor Subirón) wrote…</i></summary><blockquote>

Is `bModifyBones` necessary?
</blockquote></details>

Sorted

**Comment by wattsavolt** [comment]
> **Python API for invoking the bone_transforms is not working:**
> 
> When running this code:
> `world = client.get_world()
> blueprint = random.choice(world.get_blueprint_library().filter('walker.*'))
> 
> ```
> spawn_point = random.choice(world.get_map().get_spawn_points())
> walker_control = carla.WalkerControl()
> walker_control.speed = 1
> walker_control.direction = spawn_point.rotation.get_forward_vector()
> walker = world.try_spawn_actor(blueprint, spawn_point)
> walker_bones = carla.WalkerBoneControl()
> if walker is not None:
>     actor_list.append(walker)
>     walker.set_manual_bones_mode()
>     walker.apply_control(walker_bones)
>     print walker_bones.bone_transforms`
> ```
> 
> It shows the following error:
> `Traceback (most recent call last): File "extract_bones.py", line 46, in <module> print walker_bones.bone_transforms TypeError: No to_python (by-value) converter found for C++ type: std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, carla::geom::Transform>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, carla::geom::Transform> > >`
> 
> When I did more debugging, it shows that the code fails at this loop in 'Control.cpp' and does not print any bone_transform
> `for (auto bone_transform : control.bone_transforms) { out << "(first=" << bone_transform.first << ", second" << bone_transform.second << ')'; }`
> 
> Does anyone know the reason?
> Thanks.

The bones in your WalkerControl instance will be empty because you have not assigned them yet. You have to add bones to the control before trying to apply it. When printing, you may need to do print('{}'.format(surround walker_bones.bone_transforms)). We have not yet added the ability get the existing skeletal bones information from the server. You can just modify the skeletal from the client currently.

**Comment by wattsavolt** [comment]
___
*[PythonAPI/carla/source/libcarla/Control.cpp, line 47 at r3](https://reviewable.io/reviews/carla-simulator/carla/1719#-Lhdz0yl2Td7uEshTD_I:-LhfMDPI18Y-ByMOUsN2:bb7f2mf) ([raw file](https://github.com/carla-simulator/carla/blob/1e6f37186ce76852db1df82fccded8e148d61927/PythonAPI/carla/source/libcarla/Control.cpp#L47)):*
<details><summary><i>Previously, nsubiron (Néstor Subirón) wrote…</i></summary><blockquote>

Maybe instead of "first" and "second" we can give some descriptive names.
</blockquote></details>

done

**Comment by wattsavolt** [comment]
___
*[PythonAPI/carla/source/libcarla/Control.cpp, line 39 at r3](https://reviewable.io/reviews/carla-simulator/carla/1719#-LhdysuZ5kb1Lq0LUk6X:-LhfMFIN2KSFQAt3l--o:bb7f2mf) ([raw file](https://github.com/carla-simulator/carla/blob/1e6f37186ce76852db1df82fccded8e148d61927/PythonAPI/carla/source/libcarla/Control.cpp#L39)):*
<details><summary><i>Previously, nsubiron (Néstor Subirón) wrote…</i></summary><blockquote>

Something went wrong here merging, these lines shouldn't be here.
</blockquote></details>

done

**Comment by wattsavolt** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Walker/WalkerController.cpp, line 95 at r3](https://reviewable.io/reviews/carla-simulator/carla/1719#-Lhe-WXyE3DAYXmuyfV8:-LhfMMml9cRLcG-H4zyQ:b4rrjn3) ([raw file](https://github.com/carla-simulator/carla/blob/1e6f37186ce76852db1df82fccded8e148d61927/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Walker/WalkerController.cpp#L95)):*
<details><summary><i>Previously, nsubiron (Néstor Subirón) wrote…</i></summary><blockquote>

Just FYI, there is a `boost::apply_visitor` so there is no need of doing a switch for variants; it does the same thing
</blockquote></details>

Done. Made the visitor class a nested private class of the controller because it allows access to private and protected functions of the controller without having to make it a friend. I can move outside and make it a friend if you want.

**Comment by wattsavolt** [comment]
___
*[LibCarla/source/carla/sensor/data/ActorDynamicState.h, line 15 at r3](https://reviewable.io/reviews/carla-simulator/carla/1719#-LhdyRh5Ev-S_Hh_DW8Y:-LhfMmdG1iUsfGJnD3iN:bb6un1j) ([raw file](https://github.com/carla-simulator/carla/blob/1e6f37186ce76852db1df82fccded8e148d61927/LibCarla/source/carla/sensor/data/ActorDynamicState.h#L15)):*
<details><summary><i>Previously, nsubiron (Néstor Subirón) wrote…</i></summary><blockquote>

Unused include
</blockquote></details>

Done

**Comment by wattsavolt** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Walker/WalkerController.cpp, line 95 at r3](https://reviewable.io/reviews/carla-simulator/carla/1719#-Lhe-WXyE3DAYXmuyfV8:-Lhjknhu1OZRC1HygVew:bj98w0s) ([raw file](https://github.com/carla-simulator/carla/blob/1e6f37186ce76852db1df82fccded8e148d61927/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Walker/WalkerController.cpp#L95)):*
<details><summary><i>Previously, nsubiron (Néstor Subirón) wrote…</i></summary><blockquote>

Yeah, this works :+1:

Just another tip, you can also create a visitor out of lambdas like this :wink:
```cpp
auto visitor = carla::Functional::MakeOverload(
    [](const FWalkerControl &control) { ... },
    [](const FWalkerBoneControl &control) { ... });
```
</blockquote></details>

Nice this would have been handier

**Comment by wattsavolt** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Walker/WalkerController.cpp, line 95 at r3](https://reviewable.io/reviews/carla-simulator/carla/1719#-Lhe-WXyE3DAYXmuyfV8:-LhkVV_B2Ee8NtXJAphJ:b757v2w) ([raw file](https://github.com/carla-simulator/carla/blob/1e6f37186ce76852db1df82fccded8e148d61927/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Walker/WalkerController.cpp#L95)):*
<details><summary><i>Previously, wattsavolt (Aidan Clear) wrote…</i></summary><blockquote>

Nice this would have been handier
</blockquote></details>

Will you be approving this?

**Comment by wattsavolt** [comment]
___
*[LibCarla/source/carla/client/detail/Client.h, line 165 at r1](https://reviewable.io/reviews/carla-simulator/carla/1719#-LgXxTvgBE5Fli88trt2:-LhoRBCP100IM-0O7DuC:bb6un1j) ([raw file](https://github.com/carla-simulator/carla/blob/bef3c8b8abb203ebc30231414e18dcdc8e94fbef/LibCarla/source/carla/client/detail/Client.h#L165)):*
<details><summary><i>Previously, nsubiron (Néstor Subirón) wrote…</i></summary><blockquote>

Why this function? It does the same as `ApplyBoneControlToWalker`.
</blockquote></details>

Done

**Comment by wattsavolt** [comment]
___
*[LibCarla/source/carla/rpc/WalkerBoneControl.h, line 42 at r3](https://reviewable.io/reviews/carla-simulator/carla/1719#-LhK8CAABVN8X7EW--RK:-LhoSVGX05HfqTxiq13e:bb6un1j) ([raw file](https://github.com/carla-simulator/carla/blob/1e6f37186ce76852db1df82fccded8e148d61927/LibCarla/source/carla/rpc/WalkerBoneControl.h#L42)):*
<details><summary><i>Previously, nsubiron (Néstor Subirón) wrote…</i></summary><blockquote>

Use to `ToFString()` in "String.h", that uses UE4 macros for encoding strings.
</blockquote></details>

Done

**Comment by wattsavolt** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp, line 155 at r1](https://reviewable.io/reviews/carla-simulator/carla/1719#-LgXuBH8AwcW5kIDmcKm:-LhoSYUn0th_oy9KgvkP:bb6un1j) ([raw file](https://github.com/carla-simulator/carla/blob/bef3c8b8abb203ebc30231414e18dcdc8e94fbef/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp#L155)):*
<details><summary><i>Previously, nsubiron (Néstor Subirón) wrote…</i></summary><blockquote>

:grimacing: don't use uncrustify in this file, it has a bug with lambdas that breaks indentation
</blockquote></details>

Done

**Comment by wattsavolt** [comment]
*[a discussion](https://reviewable.io/reviews/carla-simulator/carla/1719#-LgXw9p550pjKxtOB7aX:-LhoW7QeBUVj_qSRZN6w:bs7wumx) (no related file):*
<details><summary><i>Previously, nsubiron (Néstor Subirón) wrote…</i></summary><blockquote>

Can we make the "set manual bones mode" automatic in the server-side based on the type of control received? This way we simplify the API
</blockquote></details>

Done. 

---

**Comment by wattsavolt** [comment]
___
*[LibCarla/source/carla/rpc/BoneTransformData.h, line 1 at r6](https://reviewable.io/reviews/carla-simulator/carla/1719#-Lhu-n0C8spOG7Ha0xlb:-LiE78az1pOeG6trnRLk:bb6un1j) ([raw file](https://github.com/carla-simulator/carla/blob/2539e51f38ebe9943e605a79956d6187a740fdc7/LibCarla/source/carla/rpc/BoneTransformData.h#L1)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

2019?
</blockquote></details>

Done

**Comment by wattsavolt** [comment]
*[a discussion](https://reviewable.io/reviews/carla-simulator/carla/1719#-Lhq-qAg4Amh6McZ49ta:-LiE7IdF1A__mwIP398z:bb6un1j) (no related file):*
<details><summary><i>Previously, nsubiron (Néstor Subirón) wrote…</i></summary><blockquote>

We're just missing documentation, 

@wattsavolt can you update python_api.md?
@xgodina can you coordinate creating a document showing the bones that are available?
</blockquote></details>

Done

---

**Comment by wattsavolt** [comment]
___
*[PythonAPI/carla/source/libcarla/Control.cpp, line 97 at r6](https://reviewable.io/reviews/carla-simulator/carla/1719#-Lhu71tl3CBAsb35Cayz:-LiE7R5W6-8AALa_vEsz:bb6un1j) ([raw file](https://github.com/carla-simulator/carla/blob/2539e51f38ebe9943e605a79956d6187a740fdc7/PythonAPI/carla/source/libcarla/Control.cpp#L97)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

Would be nicer if we use aliases for repetitive and long namespaces, like:

namespace bp = boost::python;
namespace cr = carla::rpc;

it would make code a bit clear and less verbose.
Some aliases are already used inside the export_control() function, but not outside the function.
</blockquote></details>

Done

**Comment by wattsavolt** [comment]
___
*[PythonAPI/carla/source/libcarla/Control.cpp, line 100 at r6](https://reviewable.io/reviews/carla-simulator/carla/1719#-Lhu1IIN-YUDUuSPG0Q7:-LiE7S_9BlfqZPgTndUf:bb6un1j) ([raw file](https://github.com/carla-simulator/carla/blob/2539e51f38ebe9943e605a79956d6187a740fdc7/PythonAPI/carla/source/libcarla/Control.cpp#L100)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

just a typo, 'lenght' should be 'length'?
</blockquote></details>

Done

**Comment by wattsavolt** [comment]
___
*[PythonAPI/carla/source/libcarla/Control.cpp, line 97 at r6](https://reviewable.io/reviews/carla-simulator/carla/1719#-Lhu71tl3CBAsb35Cayz:-LiJuM-G0DjArI94jUdt:bcetdcc) ([raw file](https://github.com/carla-simulator/carla/blob/2539e51f38ebe9943e605a79956d6187a740fdc7/PythonAPI/carla/source/libcarla/Control.cpp#L97)):*
<details><summary><i>Previously, nsubiron (Néstor Subirón) wrote…</i></summary><blockquote>

Actually you should not put these aliases in the global namespace, these cpp files in PythonAPI are built all together as unity build, there could be conflicts with other aliases in other files.
</blockquote></details>

Changed back. Done

**Comment by wattsavolt** [comment]
___
*[Docs/walker_bone_control.md, line 49 at r10](https://reviewable.io/reviews/carla-simulator/carla/1719#-LiJjuAAE3ophozxRVm8:-LiJuR-T50x3Z8xMVpRL:bb6un1j) ([raw file](https://github.com/carla-simulator/carla/blob/7c59b4eb8489f95b21e1f96c7666ef64af5e6626/Docs/walker_bone_control.md#L49)):*
<details><summary><i>Previously, nsubiron (Néstor Subirón) wrote…</i></summary><blockquote>

We can probably skip the "hero" attribute no? it's not necessary for controlling the walker
</blockquote></details>

Done

**Comment by wattsavolt** [comment]
___
*[Docs/walker_bone_control.md, line 11 at r10](https://reviewable.io/reviews/carla-simulator/carla/1719#-LiJiUS42drpGgKKrdPZ:-LiJuPfD90d2Ah8eu357:bb6un1j) ([raw file](https://github.com/carla-simulator/carla/blob/7c59b4eb8489f95b21e1f96c7666ef64af5e6626/Docs/walker_bone_control.md#L11)):*
<details><summary><i>Previously, nsubiron (Néstor Subirón) wrote…</i></summary><blockquote>

"Python API tutorial"
</blockquote></details>

Done

**Comment by wattsavolt** [comment]
___
*[Docs/walker_bone_control.md, line 11 at r10](https://reviewable.io/reviews/carla-simulator/carla/1719#-LiJiUS42drpGgKKrdPZ:-LiNLDNl9SY213i7BH_S:b-altc99) ([raw file](https://github.com/carla-simulator/carla/blob/7c59b4eb8489f95b21e1f96c7666ef64af5e6626/Docs/walker_bone_control.md#L11)):*
<details><summary><i>Previously, nsubiron (Néstor Subirón) wrote…</i></summary><blockquote>

Haha that too, but I meant the link, it says Python API reference but points to Python API tutorial
</blockquote></details>

lol sorry will update it

**Comment by wattsavolt** [comment]
___
*[Docs/walker_bone_control.md, line 11 at r10](https://reviewable.io/reviews/carla-simulator/carla/1719#-LiJiUS42drpGgKKrdPZ:-LiNU3UK5Lvp9ONWCD4U:bb6un1j) ([raw file](https://github.com/carla-simulator/carla/blob/7c59b4eb8489f95b21e1f96c7666ef64af5e6626/Docs/walker_bone_control.md#L11)):*
<details><summary><i>Previously, wattsavolt (Aidan Clear) wrote…</i></summary><blockquote>

lol sorry will update it
</blockquote></details>

Done

**Pull request merged**
