### PR TITLE
Spawn actors in batch

### PR DESCRIPTION
**Pull request by nsubiron**
#### Description

Added methods to spawn actor in batch mode, reducing the number of accidents related to vehicles spawning on top of each other.

  * Added new `carla.command.SpawnActor` to spawn actors in batch
  * Added method `client.apply_batch_sync` that waits for server response
  * Updated `spawn_npc.py` to spawn vehicles in batch

The `SpawnActor` command also accepts queuing commands to be applied to the newly spawned actor.
```py
batch.append(
    SpawnActor(blueprint, transform).then(
        SetAutopilot(FutureActor, True)).then(
            ApplyVelocity(FutureActor, Vector3D(z=5))))
```

 `spawn_npc.py` has been updated to spawn all the vehicles in batch, but now it does not support spawning more vehicles than spawn points. This is probably a good thing due to the amount of accidents that it was producing.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/1489)

### CODE REVIEW

**Comment by wattsavolt** [comment]
___
*[PythonAPI/examples/spawn_npc.py, line 95 at r1](https://reviewable.io/reviews/carla-simulator/carla/1489#-Lbciu8W0Ee8JLzJFPVJ:-LbcikN-9ygeFuTFSFS0:b-8jszbc) ([raw file](https://github.com/carla-simulator/carla/blob/e6debe3c0faadbfaeb127bff91a328d7a93edb36/PythonAPI/examples/spawn_npc.py#L95)):*
> ```Python
>         batch = []
>         for n, transform in enumerate(spawn_points):
>             if n >= args.number_of_vehicles:
> ```

This conditional check seems unnecessary because args.number_of_vehicles is assigned to the number of spawn points above if the original value was greater.

**Comment by tinmodeHuang** [comment]
@nsubiron  I haven't found the call `carla.command.FutureActor` in the documentation, introducing it to me, please

**Comment by nsubiron** [comment]
@tinmodeHuang It's just a place-holder value to make the code more readable, it'll be replaced by the actor id of the newly created actor.

**Comment by tinmodeHuang** [comment]
thanks! and otherwise could you explain it to me that the statement `light_state = vls.Position | vls.LowBeam | vls.LowBeam`?

**Comment by doterop** [comment]
That is just setting the light configuration of the vehicles to turn them on

**Comment by tinmodeHuang** [comment]
the call `print('light_state:',light_state)` outputs as follows:
```
(python37) E:\CARLA_0.9.9.4\WindowsNoEditor\PythonAPI\examples>python spawn_npc.py --car-lights-on
light_state: 3
light_state: 3
light_state: 3
light_state: 3
light_state: 3
light_state: 3
light_state: 3
light_state: 3
light_state: 3
light_state: 3
```
so what the 3 means

**Comment by doterop** [comment]
One thing that I notice is that one `vls.LowBeam` is duplicated and didn't need it, so the final set should be:
`light_state = vls.Position | vls.LowBeam`

`VehicleLightState` is an enum used as a flag to configure the lights of the vehicles. In this case, the position and low beam lights are set to be turned on. The 3 value that you see is just the final result of the mask.

**Comment by tinmodeHuang** [comment]
I can't agree more with you, and then `light_state = vls.Position | vls.LowBeam | vls.HighBeam` means that there are seven kinds of states for lights of a vehicle.
`light_state: 7`

**Comment by doterop** [comment]
In that case, you are setting those 3 types of lights, but the 7 is the result of the mask not the number of lights.

**Comment by tinmodeHuang** [comment]
all states lists as follows:
```turn on: None, Position, LowBeam, HighBeam, Position + LowBeam, Position + HighBeam and what is the other?```

**Comment by doterop** [comment]
LightState is an enum whose values are used as flags, so its values are:

```
NONE          = 0         = 0   
Position      = 0x1       = 1   
LowBeam       = 0x1 <<  1 = 2   
HighBeam      = 0x1 <<  2 = 4   
Brake         = 0x1 <<  3 = 8   
RightBlinker  = 0x1 <<  4 = 16  
LeftBlinker   = 0x1 <<  5 = 32  
Reverse       = 0x1 <<  6 = 64  
Fog           = 0x1 <<  7 = 128 
Interior      = 0x1 <<  8 = 256 
Special1      = 0x1 <<  9 = 512 
Special2      = 0x1 << 10 = 1024
```

If you want to turn on only position lights: `light_state = vls.Position` and light_state is 1 

If you want to turn on only low beam lights: `light_state = vls.LowBeam`  and light_state is 2

If you want to turn on position and low beam lights: `light_state = vls.Position | vls.LowBeam` and light state is 3 because the mask of those light types is: light_state = 1 | 2 = 3. Is an add bitwise operation.

**Comment by tinmodeHuang** [comment]
get it, thank you very much, but I'm sorry for having the last problem, a block of statements in spawn_npc.py as follows:
```python
                batch.append(SpawnActor(blueprint, transform)
                    .then(SetAutopilot(FutureActor, True, traffic_manager.get_port()))
                    .then(SetVehicleLightState(FutureActor, light_state)))

        for response in client.apply_batch_sync(batch, synchronous_master):
            if response.error:
                logging.error(response.error)
            else:
                vehicles_list.append(response.actor_id)
                print('\n',response.actor_id)
```
it outputs as follows:
```bash
(python37) E:\CARLA_0.9.10.1\WindowsNoEditor\PythonAPI\examples>python spawn_actor.py --car-lights-on
{'number_of_vehicles': 10, 'number_of_walkers': 50, 'safe': False, 'filterv': 'vehicle.*', 'filterw': 'walker.pedestrian.*', 'tm_port': 8000, 'sync': False, 'hybrid': False, 'seed': None, 'car_lights_on': True}

 96

 97

 98

 99

 100

 101

 102

 103

 104

 105
```
I wanna know about how to get the actor `vehicle.tesla.model3` I want.
maybe I should clear my head to use other way being convenient to spawning all actor.

**Comment by doterop** [comment]
I suggest you to use `spawn_actor` instead to control one specific actor.

**Comment by tinmodeHuang** [comment]
> I suggest you to use `spawn_actor` instead to control one specific actor.
fair enough

**Pull request merged**
