### PR TITLE
Corkyw10/rllib documentation

### PR DESCRIPTION
**Pull request by corkyw10**
# RLlib Integration Documentation

I have created a section in general tutorials for the RLlib integration. Docs are largely taken from the RLlib README but have been reformatted to fit better as documentation in the larger Carla docs rather than in the repo README.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3919)

### CODE REVIEW

**Comment by glopezdiest** [comment]
Hey, so far, everything seems fine. We actually updated the README with the final piece of information (https://github.com/carla-simulator/rllib-integration/commit/c295aa0c20d4b68081b84106519b9ba10039d990), so if you can please, update this docs as well.

**Comment by corkyw10** [comment]
@glopezdiest I have added the latest information

**Review by joel-mb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3919)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @corkyw10, @glopezdiest, and @jackbart94)

___
*[Docs/tuto_G_rllib_integration.md, line 150 at r3](https://reviewable.io/reviews/carla-simulator/carla/3919#-MUOuZPOERDgL_NFtPTE:-MUOuZPOERDgL_NFtPTF:bqmily7) ([raw file](https://github.com/carla-simulator/carla/blob/e2d8bb8ca9c3aa0e724e9532dce92a934cc6ecb0/Docs/tuto_G_rllib_integration.md#L150)):*
> ```
> Configure AWS
> ```
I think we should add a `Configure your cluster` section explaining the autoscaler configuration (also to the README in github).
I propose the following structure:
1. Running on AWS
1.1. Configure AWS
1.2 Create the training AMI
1.3. Configure the cluster
1.4. Run the training.

In this new section I would add the note:
```
There will be an output with information about the ceated image. To use the Ray autoscaler, update the `<ImageId>` and `<SecurityGroupIds>` settings in your [autoscaler configuration file][autoscalerSettings] with the information from the output.
```
that is now on the `Create training AMI` and point to the official documentation of ray autoscaler: https://docs.ray.io/en/latest/cluster/config.html

The specific cluster configuration we are using for the dqn_example is here: https://github.com/carla-simulator/rllib-integration/blob/main/dqn_example/dqn_autoscaler.yaml

@glopezdiest @jackbart94 @corkyw10 what do you think?

**Review by jackbart94 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3919)* status: all files reviewed, 1 unresolved discussion (waiting on @corkyw10 and @glopezdiest)

**Review by joel-mb — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3919)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @glopezdiest)

**Review by glopezdiest — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3919)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
