### PR TITLE
Aaron/opendrivetomapineditor

### PR DESCRIPTION
**Pull request by Blyron**
#### Description

Added first version of road generation supporting Download of osm, translation to xodr, and mesh generation.
Mesh generation includes tesselation, deformation and simplification

Fixes #  

#### Where has this been tested?

  * **Platform(s):** Ubuntu 20 and Windows 10
  * **Python version(s):**  3.8
  * **Unreal Engine version(s):** 4.26

#### Possible Drawbacks

Maybe a full clean of project will be need

- - -
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/6056)

### CODE REVIEW

**Review by bernatx — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 9 of 20 files at r4, 14 of 16 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/6056#-:-NOEDJ3992b3aj6tGdZn:bnfp4nl)* status: all files reviewed, 38 unresolved discussions (waiting on @Axel1092 and @Blyron)

___
*[`LibCarla/source/carla/geom/Mesh.h` line 136 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEDvuA7aV0NCv7bWzf:-NOEDvuA7aV0NCv7bWzg:b-13vedn) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/LibCarla/source/carla/geom/Mesh.h#L136)):*
> ```objc
>     const std::vector<index_type>& GetIndexes() const;
> 
>     std::vector<index_type> &GetIndices();
> ```

We should use the same function name for both, as the only difference is that one returns as const and the other no.



_Code quote:_
```objc
    const std::vector<index_type>& GetIndexes() const;

    std::vector<index_type> &GetIndices();
```
___
*[`LibCarla/source/carla/geom/Mesh.cpp` line 310 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEDnsa6Rw58zwJSF5Q:-NOEDnsa6Rw58zwJSF5R:b62nn0k) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/LibCarla/source/carla/geom/Mesh.cpp#L310)):*
> ```cpp
> 
>     const int vertex_to_start_concating = v_num - num_vertices_to_link;
>    
> ```

Remove spaces
___
*[`LibCarla/source/carla/road/Map.cpp` line 1138 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEFdZK4Rzj27dIhhAZ:-NOEFdZLAURIMfKcedkd:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/LibCarla/source/carla/road/Map.cpp#L1138)):*
> ```cpp
>     std::map<road::Lane::LaneType , std::vector<std::unique_ptr<geom::Mesh>>> out_mesh_list;
>     std::unordered_map<JuncId, geom::Mesh> junction_map;
>     
> ```

remove spaces
___
*[`LibCarla/source/carla/road/Map.cpp` line 1217 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEFm7h5GfI0mVVnpf6:-NOEFm7h5GfI0mVVnpf7:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/LibCarla/source/carla/road/Map.cpp#L1217)):*
> ```cpp
>         Simplify::vertices.clear();
>         Simplify::triangles.clear();
>         
> ```

remove spaces
___
*[`LibCarla/source/carla/road/MeshFactory.cpp` line 73 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEG57FARQDChvDxRVg:-NOEG57FARQDChvDxRVh:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/LibCarla/source/carla/road/MeshFactory.cpp#L73)):*
> ```cpp
> 
>     std::vector<geom::Vector3D> vertices;
>     
> ```

remove spaces
___
*[`LibCarla/source/carla/road/MeshFactory.cpp` line 81 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEG3hV6d50MyB7Jt3r:-NOEG3hV6d50MyB7Jt3s:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/LibCarla/source/carla/road/MeshFactory.cpp#L81)):*
> ```cpp
>       vertices.push_back(edges.second);
>     } else 
>    
> ```

remove spaces
___
*[`LibCarla/source/carla/road/MeshFactory.cpp` line 145 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEG8j00WbEClNSEbwu:-NOEG8j00WbEClNSEbwv:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/LibCarla/source/carla/road/MeshFactory.cpp#L145)):*
> ```cpp
>       s_current += road_param.resolution;
>     } while (s_current < s_end);
>     
> ```

remove spaces
___
*[`LibCarla/source/carla/road/MeshFactory.cpp` line 149 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEGAZm5zhmxfzzGVyW:-NOEGAZm5zhmxfzzGVyX:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/LibCarla/source/carla/road/MeshFactory.cpp#L149)):*
> ```cpp
>     // This ensures the mesh is constant and have no gaps between roads,
>     // adding geometry at the very end of the lane
>     
> ```

remove spaces
___
*[`LibCarla/source/carla/road/MeshFactory.cpp` line 161 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEGCDaAZ88vPav0RXL:-NOEGCDaAZ88vPav0RXM:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/LibCarla/source/carla/road/MeshFactory.cpp#L161)):*
> ```cpp
>       }
>     }
>      
> ```

remove spaces
___
*[`LibCarla/source/carla/road/MeshFactory.cpp` line 183 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEGE_G4D98BHUGQjIn:-NOEGE_G4D98BHUGQjIo:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/LibCarla/source/carla/road/MeshFactory.cpp#L183)):*
> ```cpp
>       }
>     }
>     
> ```

remove spaces
___
*[`LibCarla/source/carla/road/MeshFactory.cpp` line 383 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEGIU18pBOrqUbcn_G:-NOEGIU18pBOrqUbcn_H:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/LibCarla/source/carla/road/MeshFactory.cpp#L383)):*
> ```cpp
>         std::make_move_iterator(section_uptr_list.end()));
>     }
>     
> ```

remove spaces
___
*[`LibCarla/source/carla/road/MeshFactory.cpp` line 390 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEGKFeCOnOgs_Fpghr:-NOEGKFeCOnOgs_Fpghs:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/LibCarla/source/carla/road/MeshFactory.cpp#L390)):*
> ```cpp
>     const road::LaneSection &lane_section) const {
>       const int vertices_in_width = road_param.vertex_width_resolution >= 2 ? road_param.vertex_width_resolution : 2;
>       
> ```

remove spaces
___
*[`LibCarla/source/carla/road/MeshFactory.cpp` line 410 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEGML4582jTLEqJ10C:-NOEGML5C-TDDd409slI:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/LibCarla/source/carla/road/MeshFactory.cpp#L410)):*
> ```cpp
>               (mesh_uptr_list[lane_pair.second.GetType()][0])->ConcatMesh(lane_section_mesh, vertices_in_width);
>             }
>             
> ```

remove spaces
___
*[`LibCarla/source/third-party/simplify/Simplify.h` line 17 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEGbLJANq0nNnENw4c:-NOEGbLJANq0nNnENw4d:bhsyhzp) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/LibCarla/source/third-party/simplify/Simplify.h#L17)):*
> ```objc
> #include <fstream>
> #include <algorithm>
> //#include <stddef.h>
> ```

maybe we can remove the commented includes noet needed, and also convert de TAB to spaces.
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Carla.Build.cs` line 308 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEGvSfB1l_q1u_KdOV:-NOEGvSfB1l_q1u_KdOW:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Carla.Build.cs#L308)):*
> ```Smalltalk
>         PublicAdditionalLibraries.Add("stdc++");
>         PublicAdditionalLibraries.Add("/usr/lib/x86_64-linux-gnu/libpython3.9.so");
>       }      
> ```

remove spaces
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Carla.Build.cs` line 320 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEGtv84sct9W2UTNOj:-NOEGtv84sct9W2UTNOk:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Carla.Build.cs#L320)):*
> ```Smalltalk
>     }
>     bEnableExceptions = true;
>     
> ```

remove spaces
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Online/CustomFileDownloader.h` line 18 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEH16I3qfLoFlaZQ7B:-NOEH16I3qfLoFlaZQ7C:b-5em5ia) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Online/CustomFileDownloader.h#L18)):*
> ```objc
> {
>   GENERATED_BODY()
> public:	
> ```

remove TAB
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Online/CustomFileDownloader.cpp` line 23 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEHC-u0apSVKZC2K10:-NOEHC-u0apSVKZC2K11:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Online/CustomFileDownloader.cpp#L23)):*
> ```cpp
>     if(FFileHelper::LoadFileToString(FileContent, *FilePath, FFileHelper::EHashOptions::None))
>     {
>       UE_LOG(LogCarla, Warning, TEXT("FileManipulation: Text From File: %s"), *FilePath);  
> ```

remove spaces
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Online/CustomFileDownloader.cpp` line 31 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEHDol1GMCNthdJky1:-NOEHDol1GMCNthdJky2:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Online/CustomFileDownloader.cpp#L31)):*
> ```cpp
>   }else{
>     UE_LOG(LogCarla, Warning, TEXT("File: %s does not exist"), *FilePath);
>     return;  
> ```

remove spaces
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Online/CustomFileDownloader.cpp` line 76 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEHKCV1OQcazyFiNUS:-NOEHKCV1OQcazyFiNUT:b-5em5ia) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Online/CustomFileDownloader.cpp#L76)):*
> ```cpp
>   Request->SetURL(Url);
>   Request->SetVerb(Verb);
>   Request->ProcessRequest();	
> ```

remove TAB
___
*[`Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp` line 1 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEH_bcC3SmwqkGNXcG:-NOEH_bcC3SmwqkGNXcH:bq9se0d) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp#L1)):*
> ```cpp
> // Copyright (c) 2017 Computer Vision Center (CVC) at the Universitat Autonoma de Barcelona (UAB). This work is licensed under the terms of the MIT license. For a copy, see <https://opensource.org/licenses/MIT>.
> ```

we can use current year for new files, 2023



_Code quote:_
```cpp
2017
```
___
*[`Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp` line 45 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEHgWWA15pR7kVYV4v:-NOEHgWWA15pR7kVYV4w:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp#L45)):*
> ```cpp
>   case carla::road::Lane::LaneType::Shoulder:
>     return FString("Shoulder");
>     break;  
> ```

remove spaces
___
*[`Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp` line 48 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEHj057n9yswLNyWfB:-NOEHj06CQeeY0uKbxx4:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp#L48)):*
> ```cpp
>   case carla::road::Lane::LaneType::Biking:
>     return FString("Biking");
>     break;  
> ```

remove spaces
___
*[`Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp` line 51 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEHkMPBqqf2oyntOXp:-NOEHkMPBqqf2oyntOXq:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp#L51)):*
> ```cpp
>   case carla::road::Lane::LaneType::Sidewalk:
>     return FString("Sidewalk");
>     break;  
> ```

remove spaces
___
*[`Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp` line 247 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEHwYb54d4Jey2zfnu:-NOEHwYb54d4Jey2zfnv:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp#L247)):*
> ```cpp
> 
>       RoadType.Add(LaneTypeToFString(PairMap.first));
>       RoadMesh.Add(TempPMC);          
> ```

remove spaces
___
*[`Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp` line 250 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEHuvv52fMxsS1_FdB:-NOEHuvv52fMxsS1_FdC:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp#L250)):*
> ```cpp
>     }
>   }
>     
> ```

remove spaces
___
*[`Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp` line 276 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEI04W-5-CGqNgfOjN:-NOEI04W-5-CGqNgfOjO:b-mf4u3d) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp#L276)):*
> ```cpp
>     // if (!Success)
>     // {
>     //   UE_LOG(LogCarla, Error, TEXT("The road collision mesh could not be generated!"));
> ```

remove commented code, and some spaces below



_Code quote:_
```cpp
  /*
    if(!Parameters.enable_mesh_visibility)
    {
      for(AActor * actor : ActorMeshList)
      {
        actor->SetActorHiddenInGame(true);
      }
    }
  */
    // // Build collision data
    // FTriMeshCollisionData CollisitonData;
    // CollisitonData.bDeformableMesh = false;
    // CollisitonData.bDisableActiveEdgePrecompute = false;
    // CollisitonData.bFastCook = false;
    // CollisitonData.bFlipNormals = false;
    // CollisitonData.Indices = TriIndices;
    // CollisitonData.Vertices = Vertices;

    // RoadMesh->ContainsPhysicsTriMeshData(true);
    // bool Success = RoadMesh->GetPhysicsTriMeshData(&CollisitonData, true);
    // if (!Success)
    // {
    //   UE_LOG(LogCarla, Error, TEXT("The road collision mesh could not be generated!"));
    // }
```
___
*[`Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp` line 292 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEIE_I1lqtLWjlLmv7:-NOEIE_I1lqtLWjlLmv8:b-njlish) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp#L292)):*
> ```cpp
>     Spawner->SetActorRotation(Trans.GetRotation());
>     Spawner->SetActorLocation(Trans.GetTranslation() + FVector(0.f, 0.f, SpawnersHeight));
>     //VehicleSpawners.Add(Spawner);
> ```

this commented line should be reviewed or removed.
___
*[`Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp` line 383 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEIWogC0aqAAxcJRR1:-NOEIWogC0aqAAxcJRR2:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp#L383)):*
> ```cpp
> 
>   IPlatformFile& PlatformFile = FPlatformFileManager::Get().GetPlatformFile();
>   
> ```

remove spaces
___
*[`Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp` line 439 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEIZATDbWrfmWEuVAG:-NOEIZATDbWrfmWEuVAH:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp#L439)):*
> ```cpp
>       CurrentStaticMesh->CreateMeshDescription(0, MoveTemp(MeshDescription));
>       CurrentStaticMesh->CommitMeshDescription(0);
>       
> ```

remove spaces
___
*[`Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp` line 489 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEIahW7V0AX6lUtpJT:-NOEIahW7V0AX6lUtpJU:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp#L489)):*
> ```cpp
>       FAssetRegistryModule::AssetCreated(CurrentStaticMesh);
>       UPackage::SavePackage(Package, CurrentStaticMesh, EObjectFlags::RF_Public | EObjectFlags::RF_Standalone, *MeshName, GError, nullptr, true, true, SAVE_NoError);
>     
> ```

remove spaces
___
*[`Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Public/OpenDriveToMap.h` line 26 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEIftFB4oNBy7ATUFZ:-NOEIftFB4oNBy7ATUF_:b-21cnjk) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Public/OpenDriveToMap.h#L26)):*
> ```objc
> {
>   GENERATED_BODY()
>   
> ```

remove spaces, and below
___
*[`Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Public/OpenDriveToMap.h` line 72 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEIip-ApLJGw8R3fIX:-NOEIip-ApLJGw8R3fIY:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Public/OpenDriveToMap.h#L72)):*
> ```objc
>   UStaticMesh* CreateStaticMeshAsset(UProceduralMeshComponent* ProcMeshComp, int32 MeshIndex, FString FolderName);
>   TArray<UStaticMesh*> CreateStaticMeshAssets();
>   
> ```

remove spaces
___
*[`Util/BuildTools/BuildOSM2ODR.bat` line 112 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEIowr6Nwk4g87x8fD:-NOEIowr6Nwk4g87x8fE:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Util/BuildTools/BuildOSM2ODR.bat#L112)):*
> ```Batchfile
>     cmake --build . --config Release --target install | findstr /V "Up-to-date:"
>     if %errorlevel% neq 0 goto error_install
>     
> ```

remove spaces
___
*[`Util/BuildTools/BuildOSM2ODR.sh` line 104 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEIrSH2oZMzgyl5Ogr:-NOEIrSIBEtHNc5Xuf1_:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Util/BuildTools/BuildOSM2ODR.sh#L104)):*
> ```Shell
>       -DXercesC_INCLUDE_DIR=${CARLA_BUILD_FOLDER}/xerces-c-3.2.3-install/include \
>       -DXercesC_LIBRARY=${CARLA_BUILD_FOLDER}/xerces-c-3.2.3-install/lib/libxerces-c.a
>   
> ```

remove spaces
___
*[`Util/BuildTools/BuildOSM2ODR.sh` line 114 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEIt8t90ALKyPzQNmu:-NOEIt8t90ALKyPzQNmv:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Util/BuildTools/BuildOSM2ODR.sh#L114)):*
> ```Shell
>   LLVM_INCLUDE=${CARLA_BUILD_FOLDER}/${LLVM_BASENAME}-install/include/c++/v1
>   LLVM_LIBPATH=${CARLA_BUILD_FOLDER}/${LLVM_BASENAME}-install/lib
>   
> ```

remove spaces
___
*[`Util/BuildTools/Linux.mk` line 82 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEJ6hhBCYFwphLZJ47:-NOEJ6hhBCYFwphLZJ48:b-59j7si) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Util/BuildTools/Linux.mk#L82)):*
> ```Makefile
> 	@for D in ${CARLA_EXAMPLES_FOLDER}/*; do [ -d "$${D}" ] && make -C $${D} run.only; done
> 
> CarlaUE4Editor: LibCarla.server.release osm2odr
> ```

osm2odr is not built in the setup step? Do we need to force here each time we compile the LibCarla or launch?
___
*[`Util/BuildTools/Windows.mk` line 19 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEJSZ_-TmRIsrlYi2V:-NOEJSZ_-TmRIsrlYi2W:bw8vd2i) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Util/BuildTools/Windows.mk#L19)):*
> ```Makefile
> 	@"${CARLA_BUILD_TOOLS_FOLDER}/Import.py" $(ARGS)
> 
> CarlaUE4Editor: LibCarla osm2odr
> ```

same question as in Linux.mk

**Review by bernatx — CHANGES_REQUESTED** [review]
> Reviewed 9 of 11 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/6056)* status: all files reviewed, 12 unresolved discussions (waiting on @Axel1092 and @Blyron)

___
*[`Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp` line 247 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEHwYb54d4Jey2zfnu:-NOJB2L22eqUqyTucaYI:bz2tcqv) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp#L247)):*
<details><summary><i>Previously, Blyron (Blyron) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

still there
___
*[`Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp` line 489 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEIahW7V0AX6lUtpJT:-NOJBAWjA9oD2ci3Sxqm:bz2tcqv) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp#L489)):*
<details><summary><i>Previously, Blyron (Blyron) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

still there

**Review by Blyron — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/6056)* status: 24 of 25 files reviewed, 12 unresolved discussions (waiting on @Axel1092 and @bernatx)

___
*[`Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp` line 247 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEHwYb54d4Jey2zfnu:-NOJEoTgCdqI86tXNU0h:b-exaupj) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp#L247)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

still there
</blockquote></details>

Done. In this morning commit, sorry for the incoveniencies, visual code was not showing me that
___
*[`Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp` line 489 at r8](https://reviewable.io/reviews/carla-simulator/carla/6056#-NOEIahW7V0AX6lUtpJT:-NOJEabHEJBQ7-tasg4K:b-giqtb3) ([raw file](https://github.com/carla-simulator/carla/blob/b2cee0af3e37d595d73af044d921b761eac5b2b1/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp#L489)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

still there
</blockquote></details>

Done. In this morning commit, sorry for the incoveniencies, visual code was not showing me that

**Review by bernatx — APPROVED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/6056)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Axel1092)

**Pull request merged**
