### PR TITLE
Roel/final changes import

### PR DESCRIPTION
**Pull request by algababr**
#### Description

Changed the process in which the decals are applied during the cooking time in "make import" for large maps
Modified the materials applied to imported roads.

Fixes #  

#### Where has this been tested?

  * **Platform(s):** Windows
  * **Python version(s):** 3.7.9
  * **Unreal Engine version(s):** 4.26

#### Possible Drawbacks

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4231)

### CODE REVIEW

**Review by bernatx — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4231)* status: all files reviewed, 4 unresolved discussions (waiting on @algababr)

___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp, line 132 at r2](https://reviewable.io/reviews/carla-simulator/carla/4231#-Ma5VvoM1GLT7V2PiYSD:-Ma5VvoM1GLT7V2PiYSE:brz2fwh) ([raw file](https://github.com/carla-simulator/carla/blob/3ff3359f60f4067753e14e145d4e9d42d68704e1/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp#L132)):*
> ```cpp
>       TileData.XODRName = LoadedMapName.LeftChop((LoadedMapName.GetCharArray().Num() - 1) - LoadedMapName.Find("_", ESearchCase::IgnoreCase, ESearchDir::Type::FromStart));
>       // As the OpenDrive file has the same name as level, build the path to the
>       // xodr file using the lavel name and the game content directory.
> ```

label instead of lavel :)
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp, line 135 at r2](https://reviewable.io/reviews/carla-simulator/carla/4231#-Ma5W0LHANTqTQWZUiEA:-Ma5W0LHANTqTQWZUiEB:b4gdzp8) ([raw file](https://github.com/carla-simulator/carla/blob/3ff3359f60f4067753e14e145d4e9d42d68704e1/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp#L135)):*
> ```
> XODRMap->GenerateWaypointsOnRoadEntries();
> ```
do we need to call this?
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp, line 162 at r2](https://reviewable.io/reviews/carla-simulator/carla/4231#-Ma5WZ3YArChwLVBdi89:-Ma5WZ3YArChwLVBdi8A:b3b7fdo) ([raw file](https://github.com/carla-simulator/carla/blob/3ff3359f60f4067753e14e145d4e9d42d68704e1/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp#L162)):*
> ```
> LoadedMapName.GetCharArray().Num() - 2
> ```
This will not work for tiles with more than 1 digit.
For example for Tile_100_150 you will  get only the '0'
We need a more robust way to get the indexes from the name.
For example, we can search in reverse like: (Axel snippet)
```    
    FString TileName = AssetData.AssetName.ToString();
    FString TileName_X = "";
    FString TileName_Y = "";
    size_t i = TileName.Len()-1;
    for (; i > 0; i--) {
      TCHAR character = TileName[i];
      if (character == '_') {
        break;
      }
      TileName_Y = FString::Chr(character) + TileName_Y;
    }
    i--;
    for (; i > 0; i--) {
      TCHAR character = TileName[i];
      if (character == '_') {
        break;
      }
      TileName_X = FString::Chr(character) + TileName_X;
    }
    FIntVector TileVectorID = FIntVector(FCString::Atoi(*TileName_X), FCString::Atoi(*TileName_Y), 0);
```

But I think a simpler solution can be found

What something like:
```
FString aString = TEXT("_Tile_100_150");
TArray stringArray = {};
aString.ParseIntoArray(stringArray, TEXT("_"), false);
int x = FCString::Atoi(*stringArray[stringArray.Num()-2]);
int y = FCString::Atoi(*stringArray[stringArray.Num()-1]);
```
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp, line 361 at r2](https://reviewable.io/reviews/carla-simulator/carla/4231#-Ma5_Smm46mEH3zNgzw8:-Ma5_Smm46mEH3zNgzw9:bynisif) ([raw file](https://github.com/carla-simulator/carla/blob/3ff3359f60f4067753e14e145d4e9d42d68704e1/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp#L361)):*
> ```
> Tile
> ```
Probably better to search for '_Tile_' to be sure tile is not part of the name like 'TileableMap'

**Comment by algababr** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp, line 132 at r2](https://reviewable.io/reviews/carla-simulator/carla/4231#-Ma5VvoM1GLT7V2PiYSD:-Ma87KSF8q0xKLKPHz8f:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/3ff3359f60f4067753e14e145d4e9d42d68704e1/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp#L132)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

label instead of lavel :)
</blockquote></details>

Done.

**Comment by algababr** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp, line 135 at r2](https://reviewable.io/reviews/carla-simulator/carla/4231#-Ma5W0LHANTqTQWZUiEA:-Ma87MP5Dba1O3mnyVYW:b-ku1p2r) ([raw file](https://github.com/carla-simulator/carla/blob/3ff3359f60f4067753e14e145d4e9d42d68704e1/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp#L135)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
> XODRMap->GenerateWaypointsOnRoadEntries();
> ```
do we need to call this?
</blockquote></details>

Removed it. Was to in order to make sure I was getting the waypoints I needed, but once the .XODR is loaded there's no need for this

**Comment by algababr** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp, line 162 at r2](https://reviewable.io/reviews/carla-simulator/carla/4231#-Ma5WZ3YArChwLVBdi89:-Ma87_8Q6xtaC0qcjsKc:bhiuz4x) ([raw file](https://github.com/carla-simulator/carla/blob/3ff3359f60f4067753e14e145d4e9d42d68704e1/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp#L162)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
> LoadedMapName.GetCharArray().Num() - 2
> ```
This will not work for tiles with more than 1 digit.
For example for Tile_100_150 you will  get only the '0'
We need a more robust way to get the indexes from the name.
For example, we can search in reverse like: (Axel snippet)
```    
    FString TileName = AssetData.AssetName.ToString();
    FString TileName_X = "";
    FString TileName_Y = "";
    size_t i = TileName.Len()-1;
    for (; i > 0; i--) {
      TCHAR character = TileName[i];
      if (character == '_') {
        break;
      }
      TileName_Y = FString::Chr(character) + TileName_Y;
    }
    i--;
    for (; i > 0; i--) {
      TCHAR character = TileName[i];
      if (character == '_') {
        break;
      }
      TileName_X = FString::Chr(character) + TileName_X;
    }
    FIntVector TileVectorID = FIntVector(FCString::Atoi(*TileName_X), FCString::Atoi(*TileName_Y), 0);
```

But I think a simpler solution can be found

What something like:
```
FString aString = TEXT("_Tile_100_150");
TArray stringArray = {};
aString.ParseIntoArray(stringArray, TEXT("_"), false);
int x = FCString::Atoi(*stringArray[stringArray.Num()-2]);
int y = FCString::Atoi(*stringArray[stringArray.Num()-1]);
```
</blockquote></details>

Done. That didn't cross my mind, since I was used to work with the testmap that has only 1 digit.

**Comment by algababr** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp, line 361 at r2](https://reviewable.io/reviews/carla-simulator/carla/4231#-Ma5_Smm46mEH3zNgzw8:-Ma87iCE58YOrn9SRaM5:bk3n5fm) ([raw file](https://github.com/carla-simulator/carla/blob/3ff3359f60f4067753e14e145d4e9d42d68704e1/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp#L361)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
> Tile
> ```
Probably better to search for '_Tile_' to be sure tile is not part of the name like 'TileableMap'
</blockquote></details>

Changed it to look for _Tile_. More specific

**Comment by algababr** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp, line 361 at r2](https://reviewable.io/reviews/carla-simulator/carla/4231#-Ma5_Smm46mEH3zNgzw8:-Ma87r080QGlADbRlRQJ:bkg4igh) ([raw file](https://github.com/carla-simulator/carla/blob/3ff3359f60f4067753e14e145d4e9d42d68704e1/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp#L361)):*
<details><summary><i>Previously, algababr (Roel Algaba Brizuela) wrote…</i></summary><blockquote>

Changed it to look for _Tile_. More specific
</blockquote></details>

Whoops, seems reviewable removes the _ . I meant  _ Tile _

**Review by bernatx — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4231)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @algababr)

**Pull request merged**
