### PR TITLE
Adding episodes to rosbridge:

### PR DESCRIPTION
**Pull request by aranga81**
- episodes & framesperepisode added for rosbag recording
- writing control inputs to bag

#### Description

@laurent-george - Hi - I added episodes to the existing ros bridge. Please review the changes ! 

Fixes #  

#### Where has this been tested?

  * **Platform(s):** Ubuntu 16.04
  * **Python version(s):** 2.7
  * **Unreal Engine version(s):** 4.8

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/536)

### CODE REVIEW

**Comment by laurent-george** [comment]
Review status: 0 of 5 files reviewed, 10 unresolved discussions (waiting on @aranga81)

---

*[.gitignore, line 32 at r1](https://reviewable.io/reviews/carla-simulator/carla/536#-LG-mLfPBsxP8_epxqbZ:-LG-mLfPBsxP8_epxqb_:bim8cnk) ([raw file](https://github.com/carla-simulator/carla/blob/e15586d4e71682a083e33c283eee532888cae0ce/.gitignore#L32)):*
> ```
> _site
> core
> /.project
> ```

Minor, please remove this line from .gitignore (don't know where it cames from, but people don't have .project in default repo I guess that's only relevant for specific ide.

---

*[carla_ros_bridge/config/settings.yaml, line 10 at r1](https://reviewable.io/reviews/carla-simulator/carla/536#-LG-mfmN-9JOlk2UUVjX:-LG-mfmN-9JOlk2UUVjY:bdcomgu) ([raw file](https://github.com/carla-simulator/carla/blob/e15586d4e71682a083e33c283eee532888cae0ce/carla_ros_bridge/config/settings.yaml#L10)):*
> ```YAML
>   NumberOfPedestrians: 10
>   WeatherId: 1
>   Framesperepisode: -1
> ```

Maybee add a comment after Framesperepisode, something like: 
Framesperepisode: 300  # use -1 to run it indefinitely ? What do you think ?

---

*[carla_ros_bridge/src/carla_ros_bridge/bridge.py, line 12 at r1](https://reviewable.io/reviews/carla-simulator/carla/536#-LG-n1mJ53-nvEvOrfVG:-LG-n1mLEC4OtunrHDWd:bzfhvhi) ([raw file](https://github.com/carla-simulator/carla/blob/e15586d4e71682a083e33c283eee532888cae0ce/carla_ros_bridge/src/carla_ros_bridge/bridge.py#L12)):*
> ```Python
> import rospy
> from std_msgs.msg import Float32, Bool
> from itertools import count
> ```

Please sort import : (I am not sure what is the carla guideline but I like to use: 

    standard library imports
    third-party imports
    application-specific imports

example: 

import random
from itertools import count

import rospy
from std_msgs.msg import Float32, Bool

from carla.settings import CarlaSettings
from carla_ros_bridge.control import InputController


What do you think ?
@nsubiron  what do you recommend ?

---

*[carla_ros_bridge/src/carla_ros_bridge/bridge.py, line 64 at r1](https://reviewable.io/reviews/carla-simulator/carla/536#-LG-pXtD9SLZkXsIR0C-:-LG-pXtD9SLZkXsIR0C0:bso96ne) ([raw file](https://github.com/carla-simulator/carla/blob/e15586d4e71682a083e33c283eee532888cae0ce/carla_ros_bridge/src/carla_ros_bridge/bridge.py#L64)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> # control inputs - float std msgs
>         self.steer = Float32(0.0)
>         self.brake = Float32(0.0)
>         self.throttle = Float32(0.0)
>         # control inputs - Bool msgs
>         self.reverse = Bool(False)
>         self.hand_brake = Bool(False)
> ```
</details>


Not needed, already done using InputController class

---

*[carla_ros_bridge/src/carla_ros_bridge/bridge.py, line 153 at r1](https://reviewable.io/reviews/carla-simulator/carla/536#-LG-qzsD4wel9EMZIkGZ:-LG-qzsD4wel9EMZIkG_:b30scoz) ([raw file](https://github.com/carla-simulator/carla/blob/e15586d4e71682a083e33c283eee532888cae0ce/carla_ros_bridge/src/carla_ros_bridge/bridge.py#L153)):*
> ```Python
> 
>         for frame in count():
>             if frame == self.frames_per_episode:
> ```

please keep a is_shutdown() (so we can intercept a ctrl-c), something like: 

if frame == self.sframes_per_episode  or rospy.is_shutdown():
   break

---

*[carla_ros_bridge/src/carla_ros_bridge/bridge.py, line 180 at r1](https://reviewable.io/reviews/carla-simulator/carla/536#-LG-rGYaA3BE5NkVXXyK:-LG-rGYaA3BE5NkVXXyL:bn35ka) ([raw file](https://github.com/carla-simulator/carla/blob/e15586d4e71682a083e33c283eee532888cae0ce/carla_ros_bridge/src/carla_ros_bridge/bridge.py#L180)):*
> ```Python
>                 self.client.send_control(**control)
> 
>             self.steer.data = control.steer
> ```

Why do you require to do that ?

---

*[carla_ros_bridge/src/carla_ros_bridge/bridge.py, line 185 at r1](https://reviewable.io/reviews/carla-simulator/carla/536#-LG-rIoy6oXnQAhYOc7E:-LG-rIoy6oXnQAhYOc7F:b-540uo2) ([raw file](https://github.com/carla-simulator/carla/blob/e15586d4e71682a083e33c283eee532888cae0ce/carla_ros_bridge/src/carla_ros_bridge/bridge.py#L185)):*
> ```Python
> 
>             # publish all messages
>             self.send_msgs()
> ```

why moving send_msg ?

---

*[carla_ros_bridge/src/carla_ros_bridge/bridge_with_rosbag.py, line 11 at r1](https://reviewable.io/reviews/carla-simulator/carla/536#-LG-rO63-wcBD6JduBzW:-LG-rO63-wcBD6JduBzX:b-c9jazu) ([raw file](https://github.com/carla-simulator/carla/blob/e15586d4e71682a083e33c283eee532888cae0ce/carla_ros_bridge/src/carla_ros_bridge/bridge_with_rosbag.py#L11)):*
> ```Python
> import rospy
> import os
> from datetime import datetime
> ```

please import datetime just after time 

---

*[carla_ros_bridge/src/carla_ros_bridge/bridge_with_rosbag.py, line 32 at r1](https://reviewable.io/reviews/carla-simulator/carla/536#-LG-rjz1-h0B2MpNJ3Rs:-LG-rjz1-h0B2MpNJ3Rt:bcds98x) ([raw file](https://github.com/carla-simulator/carla/blob/e15586d4e71682a083e33c283eee532888cae0ce/carla_ros_bridge/src/carla_ros_bridge/bridge_with_rosbag.py#L32)):*
> ```
> 
>         self.bag.write('steer', self.steer, self.cur_time)
>         self.bag.write('brake', self.brake, self.cur_time)
> ```
maybee remove that from this pullrequest (that is for episode feature), and maybee propose an other pull request for ego-motion information (in that case I think it's maybee preferable to use a dedicated ros message that contains brake/gas/steer and not 3 differents message, what do you think about that ?

---

*[carla_ros_bridge/src/carla_ros_bridge/client.py, line 28 at r1](https://reviewable.io/reviews/carla-simulator/carla/536#-LG-sKGX9E3xCJq8FFAV:-LG-sKGX9E3xCJq8FFAW:bye95m) ([raw file](https://github.com/carla-simulator/carla/blob/e15586d4e71682a083e33c283eee532888cae0ce/carla_ros_bridge/src/carla_ros_bridge/client.py#L28)):*
> ```Python
> 
>         for episode in range(0, num_episodes):
>             rospy.loginfo("Starting Episode --> {}".format(episode))
> ```

add a like like if rospy.is_shutdown() -> break, to be able to cleanly stop after a ctrl-C

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/536)*

**Comment by nsubiron** [comment]
Review status: 0 of 5 files reviewed, 10 unresolved discussions (waiting on @aranga81)

---

*[carla_ros_bridge/src/carla_ros_bridge/bridge.py, line 12 at r1](https://reviewable.io/reviews/carla-simulator/carla/536#-LG-n1mJ53-nvEvOrfVG:-LG04nCO95Ux9TNRbbMV:b-jwmzl4) ([raw file](https://github.com/carla-simulator/carla/blob/e15586d4e71682a083e33c283eee532888cae0ce/carla_ros_bridge/src/carla_ros_bridge/bridge.py#L12)):*
<details><summary><i>Previously, laurent-george (George Laurent) wrote…</i></summary><blockquote>

Please sort import : (I am not sure what is the carla guideline but I like to use: 

    standard library imports
    third-party imports
    application-specific imports

example: 

import random
from itertools import count

import rospy
from std_msgs.msg import Float32, Bool

from carla.settings import CarlaSettings
from carla_ros_bridge.control import InputController


What do you think ?
@nsubiron  what do you recommend ?




</blockquote></details>

Yes, we follow "PEP8" style guide https://www.python.org/dev/peps/pep-0008/?#imports

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/536)*

**Comment by aranga81** [comment]
@laurent-george @nsubiron 
Follow-up changes made in the new commit. Please check !
- removed control inputs - steer|brake|throttle from this PR.
- import adjustments according to "PEP8"
- if frame == self.sframes_per_episode or rospy.is_shutdown(): --> added to bridge.py

**Comment by marcgpuig** [comment]
Hey @aranga81!
First of all thank you for this PR!
As we use Reviewable, you need to use it to mark as _done_ **all** the corrections the reviewer made to your code.
After that, the reviewer can _agree_ with **all** your changes and proceed with the PR.
So... click every red button on Reviewable, this will send you to the next _thing_ you must check/accept :)

**Comment by aranga81** [comment]
Hello - Thank you! marking out the changes in reviewable !

---

Review status: 0 of 4 files reviewed, 8 unresolved discussions (waiting on @laurent-george and @aranga81)

---

*[carla_ros_bridge/config/settings.yaml, line 10 at r1](https://reviewable.io/reviews/carla-simulator/carla/536#-LG-mfmN-9JOlk2UUVjX:-LG5scg49bwnurbr_ZGD:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/e15586d4e71682a083e33c283eee532888cae0ce/carla_ros_bridge/config/settings.yaml#L10)):*
<details><summary><i>Previously, laurent-george (George Laurent) wrote…</i></summary><blockquote>

Maybee add a comment after Framesperepisode, something like: 
Framesperepisode: 300  # use -1 to run it indefinitely ? What do you think ?
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/carla_ros_bridge/bridge.py, line 12 at r1](https://reviewable.io/reviews/carla-simulator/carla/536#-LG-n1mJ53-nvEvOrfVG:-LG5sgpS3-mSB8LS3X2B:b-fojosz) ([raw file](https://github.com/carla-simulator/carla/blob/e15586d4e71682a083e33c283eee532888cae0ce/carla_ros_bridge/src/carla_ros_bridge/bridge.py#L12)):*
<details><summary><i>Previously, nsubiron (Néstor Subirón) wrote…</i></summary><blockquote>

Yes, we follow "PEP8" style guide https://www.python.org/dev/peps/pep-0008/?#imports
</blockquote></details>

Please check the changes - also not writing the control inputs to bag so no more std_msgs import.

---

*[carla_ros_bridge/src/carla_ros_bridge/bridge.py, line 64 at r1](https://reviewable.io/reviews/carla-simulator/carla/536#-LG-pXtD9SLZkXsIR0C-:-LG5swRXCGWPyF290nS-:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/e15586d4e71682a083e33c283eee532888cae0ce/carla_ros_bridge/src/carla_ros_bridge/bridge.py#L64)):*
<details><summary><i>Previously, laurent-george (George Laurent) wrote…</i></summary><blockquote>

> ```
> # control inputs - float std msgs
>         self.steer = Float32(0.0)
>         self.brake = Float32(0.0)
>         self.throttle = Float32(0.0)
>         # control inputs - Bool msgs
>         self.reverse = Bool(False)
>         self.hand_brake = Bool(False)
> ```

Not needed, already done using InputController class
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/carla_ros_bridge/bridge.py, line 153 at r1](https://reviewable.io/reviews/carla-simulator/carla/536#-LG-qzsD4wel9EMZIkGZ:-LG5sxlD31pxEMomcAeo:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/e15586d4e71682a083e33c283eee532888cae0ce/carla_ros_bridge/src/carla_ros_bridge/bridge.py#L153)):*
<details><summary><i>Previously, laurent-george (George Laurent) wrote…</i></summary><blockquote>

please keep a is_shutdown() (so we can intercept a ctrl-c), something like: 

if frame == self.sframes_per_episode  or rospy.is_shutdown():
   break


</blockquote></details>

Done.

---

*[carla_ros_bridge/src/carla_ros_bridge/bridge_with_rosbag.py, line 11 at r1](https://reviewable.io/reviews/carla-simulator/carla/536#-LG-rO63-wcBD6JduBzW:-LG5t2I26RveM24G7-MC:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/e15586d4e71682a083e33c283eee532888cae0ce/carla_ros_bridge/src/carla_ros_bridge/bridge_with_rosbag.py#L11)):*
<details><summary><i>Previously, laurent-george (George Laurent) wrote…</i></summary><blockquote>

please import datetime just after time 
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/carla_ros_bridge/bridge_with_rosbag.py, line 32 at r1](https://reviewable.io/reviews/carla-simulator/carla/536#-LG-rjz1-h0B2MpNJ3Rs:-LG5t9ZD-Iqmgpt_WVMz:bjzwtq1) ([raw file](https://github.com/carla-simulator/carla/blob/e15586d4e71682a083e33c283eee532888cae0ce/carla_ros_bridge/src/carla_ros_bridge/bridge_with_rosbag.py#L32)):*
<details><summary><i>Previously, laurent-george (George Laurent) wrote…</i></summary><blockquote>

> ```
> 
>         self.bag.write('steer', self.steer, self.cur_time)
>         self.bag.write('brake', self.brake, self.cur_time)
> ```
maybee remove that from this pullrequest (that is for episode feature), and maybee propose an other pull request for ego-motion information (in that case I think it's maybee preferable to use a dedicated ros message that contains brake/gas/steer and not 3 differents message, what do you think about that ?

</blockquote></details>

Removed this part for the PR !

---

*[carla_ros_bridge/src/carla_ros_bridge/client.py, line 28 at r1](https://reviewable.io/reviews/carla-simulator/carla/536#-LG-sKGX9E3xCJq8FFAV:-LG5tHAvBllHsNLMTUlm:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/e15586d4e71682a083e33c283eee532888cae0ce/carla_ros_bridge/src/carla_ros_bridge/client.py#L28)):*
<details><summary><i>Previously, laurent-george (George Laurent) wrote…</i></summary><blockquote>

add a like like if rospy.is_shutdown() -> break, to be able to cleanly stop after a ctrl-C
</blockquote></details>

Done.

---

*[.gitignore, line 32 at r1](https://reviewable.io/reviews/carla-simulator/carla/536#-LG5tK3JCNP5RErQPRwG:-LG5tK3JCNP5RErQPRwH:b6z0tf4) ([raw file](https://github.com/carla-simulator/carla/blob/e15586d4e71682a083e33c283eee532888cae0ce/.gitignore#L32)):*
> ```
> _site
> core
> /.project
> ```

removed this from .gitignore !

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/536#-:-LG5tVSQDrbEAdBdOfMg:b-f3pue5)*

**Comment by laurent-george** [comment]
Review status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @laurent-george and @aranga81)

---

*[carla_ros_bridge/src/carla_ros_bridge/bridge_with_rosbag.py, line 21 at r2](https://reviewable.io/reviews/carla-simulator/carla/536#-LG5wqKTCbXgRySjzP9e:-LG5wqKTCbXgRySjzP9f:b9yk6sx) ([raw file](https://github.com/carla-simulator/carla/blob/a864cc27c3889f1c2f0c42cb16abe59e0b32e9d1/carla_ros_bridge/src/carla_ros_bridge/bridge_with_rosbag.py#L21)):*
> ```Python
> 
>         fname = '{:%m%d_%H%M}'.format(datetime.now())
>         rosbag_fname = os.path.join(rospy.get_param('rosbag_fname'), 
> ```

after trying it on my computer, I end up with errors, 

rosbag_fname is for example /tmp/out.bag 

I think the output files should then be:

/tmp/out_episode_0.bag
/tmp/out_episode_1.bag 

or  (if we want the date):
/tmp/out_episode_0_{date}.bag
/tmp/out_episode_1_{date}.bag 

or (if we want only date):
/tmp/out_episode_{date}.bag
/tmp/out_episode_{date}.bag 

What do you think ? (it's just a suggestion)

I think the code to do it could be :

prefix, extension = os.path.splitext(rospy.get_param('rosbag_fname'))
rosbag_fname = os.path.join([prefix, "_{date}".format(cur_date)])


but maybee it's overcomplicated, and just modifying the documentation/renaming parameter from rosbag_fname to rosbag_directory_path  could do it.

What do you think ? 

---

*[carla_ros_bridge/src/carla_ros_bridge/client.py, line 28 at r1](https://reviewable.io/reviews/carla-simulator/carla/536#-LG-sKGX9E3xCJq8FFAV:-LG5zcx50gbkw5CiflgC:b-j75ypa) ([raw file](https://github.com/carla-simulator/carla/blob/e15586d4e71682a083e33c283eee532888cae0ce/carla_ros_bridge/src/carla_ros_bridge/client.py#L28)):*
<details><summary><i>Previously, aranga81 (Adithya Ranga) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

the rospy.is_shutdown seems to still be missing..

maybe something like: 

if rospy.is_shutdown():
    break  (just after the for)

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/536)*

**Comment by aranga81** [comment]
Review status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @laurent-george)

---

*[carla_ros_bridge/src/carla_ros_bridge/bridge_with_rosbag.py, line 21 at r2](https://reviewable.io/reviews/carla-simulator/carla/536#-LG5wqKTCbXgRySjzP9e:-LG6WE513pY1YqwwUkCS:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/a864cc27c3889f1c2f0c42cb16abe59e0b32e9d1/carla_ros_bridge/src/carla_ros_bridge/bridge_with_rosbag.py#L21)):*
<details><summary><i>Previously, laurent-george (George Laurent) wrote…</i></summary><blockquote>

after trying it on my computer, I end up with errors, 

rosbag_fname is for example /tmp/out.bag 

I think the output files should then be:

/tmp/out_episode_0.bag
/tmp/out_episode_1.bag 

or  (if we want the date):
/tmp/out_episode_0_{date}.bag
/tmp/out_episode_1_{date}.bag 

or (if we want only date):
/tmp/out_episode_{date}.bag
/tmp/out_episode_{date}.bag 

What do you think ? (it's just a suggestion)

I think the code to do it could be :

prefix, extension = os.path.splitext(rospy.get_param('rosbag_fname'))
rosbag_fname = os.path.join([prefix, "_{date}".format(cur_date)])


but maybee it's overcomplicated, and just modifying the documentation/renaming parameter from rosbag_fname to rosbag_directory_path  could do it.

What do you think ? 
</blockquote></details>

Done.

---

*[carla_ros_bridge/src/carla_ros_bridge/client.py, line 28 at r1](https://reviewable.io/reviews/carla-simulator/carla/536#-LG-sKGX9E3xCJq8FFAV:-LG6WHM93u88Omk1VcWN:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/e15586d4e71682a083e33c283eee532888cae0ce/carla_ros_bridge/src/carla_ros_bridge/client.py#L28)):*
<details><summary><i>Previously, laurent-george (George Laurent) wrote…</i></summary><blockquote>

the rospy.is_shutdown seems to still be missing..

maybe something like: 

if rospy.is_shutdown():
    break  (just after the for)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/536)*

**Comment by laurent-george** [comment]
Reviewed 3 of 4 files at r2, 3 of 3 files at r3.
Review status: all files reviewed, 2 unresolved discussions (waiting on @laurent-george)

---



*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/536)*

**Comment by laurent-george** [comment]
Ok, Done, LGTM.

---

Review status: all files reviewed, 2 unresolved discussions (waiting on @laurent-george)

---



*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/536#-:-LG77SAg1wVjWDlWu6fy:bq1sxgb)*

**Comment by laurent-george** [comment]
:lgtm:

---

Review status: all files reviewed, 2 unresolved discussions (waiting on @laurent-george)

---



*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/536#-:-LG77_pPBc-AE98DXFIv:bnfp4nl)*

**Comment by laurent-george** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @aranga81)

---

*[.gitignore, line 32 at r1](https://reviewable.io/reviews/carla-simulator/carla/536#-LG5tK3JCNP5RErQPRwG:-LG77eTs2sSnJj3pLwu6:b32wtd) ([raw file](https://github.com/carla-simulator/carla/blob/e15586d4e71682a083e33c283eee532888cae0ce/.gitignore#L32)):*
<details><summary><i>Previously, aranga81 (Adithya Ranga) wrote…</i></summary><blockquote>

removed this from .gitignore !
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/536)*

**Comment by laurent-george** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @aranga81)

---

*[.gitignore, line 32 at r1](https://reviewable.io/reviews/carla-simulator/carla/536#-LG5tK3JCNP5RErQPRwG:-LG9_y_O89EdRPgPIdM-:b2ni9ah) ([raw file](https://github.com/carla-simulator/carla/blob/e15586d4e71682a083e33c283eee532888cae0ce/.gitignore#L32)):*
<details><summary><i>Previously, laurent-george (George Laurent) wrote…</i></summary><blockquote>

ok
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/536)*

**Comment by laurent-george** [comment]
Reviewed 1 of 5 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @aranga81)

---



*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/536)*

**Comment by nsubiron** [comment]
Cool :)

**Pull request merged**
