### PR TITLE
Adding Ignore Hero to Replayer (Issue 1769)

### PR DESCRIPTION
**Pull request by bernatx**
#### Description

A new parameter has been added at the time of replaying a session, where you can choose if the recorded hero vehicles will be replayed or not. If they are not, then they can drive freely while the recorder system is replaying all other vehicles. That allows to the hero vehicles to test different strategies while the simulation is the same every time.

The parameter is the `-i` or `--ignore_hero`
For example: `./start_replaying.py -f recorded.log -i`

Fixes # 1605
Fixes # 1769

#### Where has this been tested?

  * **Platform(s):** Ubuntu 16.04
  * **Python version(s):** 2.7 and 3.7
  * **Unreal Engine version(s):** 4.22

#### Possible Drawbacks

Take care with the collisions, because the replayed vehicles will not react to collisions from the hero, and they will maintain always the recorded position.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/1807)

### CODE REVIEW

**Comment by wattsavolt** [comment]
___
*[CHANGELOG.md, line 2 at r1](https://reviewable.io/reviews/carla-simulator/carla/1807#-LiIou17E7nflEGKV1hs:-LiIou17E7nflEGKV1ht:b-p2h53k) ([raw file](https://github.com/carla-simulator/carla/blob/e0513be4bcbf1c449a594644279b70f3a1ff34e5/CHANGELOG.md#L2)):*
> ```Markdown
> ## Latest
>   * Added an option (-i) when replaying a session to ignore the hero vehicles (whose are not replayed).
> ```

typo: whose/who

**Comment by wattsavolt** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayer.h, line 84 at r1](https://reviewable.io/reviews/carla-simulator/carla/1807#-LiIpm-WEbVdvJQWOzaQ:-LiIpm-WEbVdvJQWOzaR:b1o982r) ([raw file](https://github.com/carla-simulator/carla/blob/e0513be4bcbf1c449a594644279b70f3a1ff34e5/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayer.h#L84)):*
> ```objc
>   void SetIgnoreHero(bool MyIgnoreHero)
>   {
>     IgnoreHero = MyIgnoreHero;
> ```

Maybe parameter should be called InIgnoreHero for consistency.

**Comment by wattsavolt** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayer.h, line 119 at r1](https://reviewable.io/reviews/carla-simulator/carla/1807#-LiIqDzXEx38-Z8OkeeD:-LiIqDzXEx38-Z8OkeeE:b-33dt2r) ([raw file](https://github.com/carla-simulator/carla/blob/e0513be4bcbf1c449a594644279b70f3a1ff34e5/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayer.h#L119)):*
> ```objc
>   // ignore hero vehicles
>   bool IgnoreHero { false };
>   std::unordered_map<uint32_t, bool> IsHero;
> ```

IsHero name make sit seem as though it's a bool value. Maybe IsHeroMap?

**Comment by wattsavolt** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayer.cpp, line 574 at r1](https://reviewable.io/reviews/carla-simulator/carla/1807#-LiIqx_yAJvo0ek7PRec:-LiIqx_yAJvo0ek7PRed:bmsb91p) ([raw file](https://github.com/carla-simulator/carla/blob/e0513be4bcbf1c449a594644279b70f3a1ff34e5/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayer.cpp#L574)):*
> ```cpp
> 
>   // go through each actor and update
>   for (i = 0; i < CurrPos.size(); ++i)
> ```

for (auto& Pos : CurrPos) might be cleaner here because the code never looks up any index other than i.

**Comment by wattsavolt** [comment]
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayer.cpp, line 594 at r1](https://reviewable.io/reviews/carla-simulator/carla/1807#-LiIsA_jBTzg-1oPWpGJ:-LiIsA_jBTzg-1oPWpGK:b-awa7gi) ([raw file](https://github.com/carla-simulator/carla/blob/e0513be4bcbf1c449a594644279b70f3a1ff34e5/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayer.cpp#L594)):*
> ```cpp
>       {
>         // assign last position (we don't have previous one)
>         InterpolatePosition(CurrPos[i], CurrPos[i], 0.0, DeltaTime);
> ```

Or I might be mistaken.  Should one of these args be Currpos[i - 1]?

**Comment by JunweiLiang** [comment]
Is it possible to ignore a list of actors instead of just one while replaying?

**Comment by bernatx** [comment]
> Is it possible to ignore a list of actors instead of just one while replaying?

It would be possible, but to pass a list of id means that you need to know first the id's (through the info from 'show_recorded_file.py' for example) and then specify all of them as an argument. It is more cumbersome I think. Can you share a use case for that?

**Comment by germanros1987** [comment]
@bernatx are we merging or closing this PR?

**Comment by bernatx** [comment]
We are trying to merge, this pull request comes from far away

**Pull request merged**
