### PR TITLE
fix stuck in DrawBuffer at LocalizationStage

### PR DESCRIPTION
**Pull request by hellojql**
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3474)

### CODE REVIEW

**Review by pravinblaze — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3474)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by pravinblaze** [comment]
Fixes issue #3465

**Review by jackbart94 — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3474)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by bernatx** [comment]
It is not compiling for Windows: 
`LocalizationStage.cpp(408): error C2672: 'std::max': no matching overloaded function found`

**Review by pravinblaze — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3474)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
