### PR TITLE
Speed up setup script

### PR DESCRIPTION
**Pull request by nsubiron**
A couple of measures to speed up the _Setup.sh_ script.

  * Added an option to run the `make` commands with multiple async jobs.
  * Boost only compiles the used libraries, `system`.

It runs now in about 5min30s in our build machine (before it was 12min) :+1:

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/408)

### CODE REVIEW

**Comment by nsubiron** [comment]
@marcgpuig is assigned because he is working on the windows version of this script

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/408#-:-LD6Bn9V7RyZQrqcjWsc:b42wdyj)*

**Comment by marcgpuig** [comment]
*[Setup.sh, line 153 at r1](https://reviewable.io/reviews/carla-simulator/carla/408#-LDD0YBzDTYaLmjK-Znv:-LDD0YBzDTYaLmjK-Znw:b-n92zvx) ([raw file](https://github.com/carla-simulator/carla/blob/df619333382be5a4fc65624a874bb855c1975d94/Setup.sh#L153)):*
> ```Shell
> pushd protobuf-source >/dev/null
> 
> git submodule update --init --recursive
> ```

You can add the "--depth=1" attribute here. More [info](https://stackoverflow.com/questions/2144406/how-to-make-shallow-git-submodules).
Or you can merge it with the clone (using "--recurse-submodules") and it will spare the "--depth" attribute too.

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/408)*

**Comment by marcgpuig** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/408)*

**Comment by nsubiron** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[Setup.sh, line 153 at r1](https://reviewable.io/reviews/carla-simulator/carla/408#-LDD0YBzDTYaLmjK-Znv:-LDDDNAkAi1m9PpNknd9:b-yf1vox) ([raw file](https://github.com/carla-simulator/carla/blob/df619333382be5a4fc65624a874bb855c1975d94/Setup.sh#L153)):*
<details><summary><i>Previously, marcgpuig (Marc Garcia Puig) wrote…</i></summary><blockquote>

You can add the "--depth=1" attribute here. More [info](https://stackoverflow.com/questions/2144406/how-to-make-shallow-git-submodules).
Or you can merge it with the clone (using "--recurse-submodules") and it will spare the "--depth" attribute too.
</blockquote></details>

Done, I amended the commit. Also the -j doesn't seem to be available in Ubuntu 16.04

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/408)*

**Comment by marcgpuig** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/408#-:-LDDE94vCt7dQGYLL8aw:bnfp4nl)*

**Pull request merged**
