### PR TITLE
Added optical flow documentation

### PR DESCRIPTION
**Pull request by corkyw10**
# Optical Flow camera documentation

Added the new optical flow camera information to the list of cameras in the core camera and sensor doc and the sensors reference.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4272)

### CODE REVIEW

**Review by Axel1092 — DISMISSED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4272)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corkyw10)

**Review by corkyw10 — COMMENTED** [review]
> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4272)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @corkyw10)

**Review by Axel1092 — APPROVED** [review]
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4272)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corkyw10)

**Review by corkyw10 — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4272)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corkyw10)

**Pull request merged**
