### PR TITLE
Add IO methods for sensor data

### LINKED ISSUE #751: Migrate image handling methods to new API
Child of #630.

Migrate our small image handling library (Python) to the new API (C++) so they can be used with our new API both in C++ and Python.

- [ ] Methods for saving images to disk.
- [ ] Methods for converting images (depth, sem seg) to different formats.
- [ ] Keep compatibility with numpy.

### LINKED ISSUE #821: Add save_to_disk methods to the sensor measurements
Child of #630.

Add `save_to_disk(path)` functions to at least images and lidar measurements. Same as we had in 0.8.x API, but now needs to be implemented in C++.

Blocked by #815.

### LINKED ISSUE #851: Problem with semantic segmentation in carla 0.9.0
Hi,

I'm trying to get the semantic segmentations from the carla simulator by using the Python API. 
I'm using the following python code to create two camera's: one that captures the current RGB view and the other one should get the semantic segmentation of that view.

```python
...

def save_to_disk(image, name):
    """Save this image to disk (requires PIL installed)."""

    filename = '{}/{:0>6d}_{:s}.png'.format(name, image.frame_number, image.type)

    image = PImage.frombytes(
        mode="RGBA",
        size=(image.width, image.height),
        data=image.raw_data,
        decoder_name='raw')

    color = image.split()
    image = PImage.merge("RGB", color[2::-1])

    folder = os.path.dirname(filename)
    if not os.path.isdir(folder):
        os.makedirs(folder)
    image.save(filename)

def save_semantic_img(image, name):
    res = labels_to_cityscapes_palette(image)

    filename = '{}/{:0>6d}_{:s}.png'.format(name, image.frame_number, image.type)

    image = PImage.fromarray(res)

    folder = os.path.dirname(filename)
    if not os.path.isdir(folder):
        os.makedirs(folder)
    image.save(filename)

bp = world.get_blueprint_library()
blueprint = bp.find('sensor.camera')
blueprint.set_attribute('post_processing', 'SceneFinal')
LOC = Location(x=155.5, y=55.8, z=39)
transform = Transform(LOC, Rotation(yaw=90))
cam1 = world.spawn_actor(blueprint, transform)
cam1.listen(lambda image: save_to_disk(image, "scene"))

blueprint2 = bp.find('sensor.camera')
blueprint.set_attribute('post_processing', 'SemanticSegmentation')
transform = Transform(LOC, Rotation(yaw=90))
cam2 = world.spawn_actor(blueprint, transform)
cam2.listen(lambda image: save_semantic_img(image, "semantic"))

time.sleep(4)
```

These are the images I get:
006973_scenefinal

008821_semanticsegmentation

As you can see the semantic image looks really weird but I have no idea how this came to be. Did anyone have the same problem?

### PR DESCRIPTION
**Pull request by nsubiron**
#### Description

Requires #815.

Adds the following methods to the API:

  * Image: `save_to_disk(filename, color_converter=None)`, saves the image to disk applying the given color converter. Available formats, PNG, TIFF and JPEG (JPEG has losses though).
  * Image: `convert(color_converter)` Apply the given color converter in place.
  * LidarMeasurement: `save_to_disk(filename)` Saves the point cloud in PLY format.

The following color converters are available:

- `None`
- `Depth`
- `LogarithmicDepth`
- `CityScapesPalette`

Related issues:

- Fix #821.
- Fix #751.
- Fix #851.

#### Where has this been tested?

  * **Platform(s):** Ubuntu 16.04
  * **Python version(s):** 2.7
  * **Unreal Engine version(s):** 4.19

Needs to be tested on Windows though.

#### Drawbacks

Adds the following dependencies `libpng16-dev`, `libtiff5-dev`, and `libjpeg-dev`. The build system can be tweaked to support only one of them. Travis build is changed because travis does not support `libpng16`.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/855)

### CODE REVIEW

**Comment by ThierryDeruyttere** [comment]
Although I know that you don't support mac officially, I just wish to mention that when pulling `issue#815` and `issue#821` into carla 0.9.0 I get multiple errors.
First one is 
```
/Users/thierryderuyttere/Documents/carla/LibCarla/cmake/../source/carla/Buffer.h:292:7: error: call to member function 'reset' is ambiguous
      reset(boost::asio::buffer_size(source) + offset);
      ^~~~~
/Users/thierryderuyttere/Documents/carla/LibCarla/cmake/../source/carla/Buffer.h:285:7: note: in instantiation of function template specialization 'carla::Buffer::copy_from<boost::asio::const_buffer>'
      requested here
      copy_from(offset, rhs.buffer());
      ^
/Users/thierryderuyttere/Documents/carla/LibCarla/cmake/../source/carla/Buffer.h:233:10: note: candidate function
    void reset(size_type size) {
         ^
/Users/thierryderuyttere/Documents/carla/LibCarla/cmake/../source/carla/Buffer.h:243:10: note: candidate function
    void reset(uint64_t size) {
         ^
/Users/thierryderuyttere/Documents/carla/LibCarla/cmake/../source/carla/Buffer.h:292:7: error: call to member function 'reset' is ambiguous
      reset(boost::asio::buffer_size(source) + offset);
      ^~~~~
/Users/thierryderuyttere/Documents/carla/LibCarla/cmake/../source/carla/Buffer.h:321:7: note: in instantiation of function template specialization 'carla::Buffer::copy_from<boost::asio::const_buffers_1>'
      requested here
      copy_from(offset, boost::asio::buffer(data, size));
      ^
/Users/thierryderuyttere/Documents/carla/LibCarla/cmake/../source/carla/Buffer.h:233:10: note: candidate function
    void reset(size_type size) {
         ^
/Users/thierryderuyttere/Documents/carla/LibCarla/cmake/../source/carla/Buffer.h:243:10: note: candidate function
    void reset(uint64_t size) {
         ^
```
It seems that uint64_t and size_type are the same on mac?
When commenting the `void reset(uint64_t size)` function I get a new error concerning boost:

```
/Users/thierryderuyttere/Documents/carla/LibCarla/cmake/../source/carla/Buffer.h:303:25: error: no matching function for call to 'buffer'
      copy_from(offset, boost::asio::buffer(source));
                        ^~~~~~~~~~~~~~~~~~~
/Users/thierryderuyttere/Documents/carla/LibCarla/cmake/../source/carla/Buffer.h:273:7: note: in instantiation of function template specialization 'carla::Buffer::copy_from<unsigned long>' requested here
      copy_from(0u, source);
      ^
/Users/thierryderuyttere/Documents/carla/LibCarla/cmake/../source/carla/Buffer.h:82:7: note: in instantiation of function template specialization 'carla::Buffer::copy_from<unsigned long>' requested here
      copy_from(source);
      ^
```

**Comment by nsubiron** [comment]
Hi @ThierryDeruyttere, thanks for the report!

Argh, size type is defined as 32 bit, basically I have a function that overloads for `unit32_t` and `uint64_t`, I didn't think that could fail, but... https://stackoverflow.com/questions/11603818/why-is-there-ambiguity-between-uint32-t-and-uint64-t-when-using-size-t-on-mac-os

I think the second error might be related to this one. Can you check if it compiles commenting out the uint64_t version of `reset`?
```cpp
    void reset(uint64_t size) {
      DEBUG_ASSERT(size <= max_size());
      reset(static_cast<size_type>(size));
    }
```
after all it's just a debug check.

**Comment by ThierryDeruyttere** [comment]
That seems to fix the issue. Big thanks!

**Comment by ThierryDeruyttere** [comment]
Okay I had some other problems (with linking lpng) but after I solved that, I got these 3 new errors:

The first error is:
```
[5/15] Compile Module.Carla.gen.2_of_2.cpp
In file included from /Users/thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Intermediate/Build/Mac/UE4Editor/Development/Carla/Module.Carla.gen.2_of_2.cpp:22:
In file included from /Users/thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Intermediate/Build/Mac/UE4Editor/Inc/Carla/TheNewCarlaGameModeBase.gen.cpp:9:
../../../../../thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/TheNewCarlaGameModeBase.h:44:3: error: unknown type name 'UCarlaGameInstance'; did you mean 'UGameInstance'?
  UCarlaGameInstance *GameInstance = nullptr;
  ^~~~~~~~~~~~~~~~~~
  UGameInstance
/Users/Shared/EpicGames/UE_4.19/Engine/Source/Runtime/Engine/Classes/Engine/LocalPlayer.h:25:7: note: 'UGameInstance' declared here
class UGameInstance;
      ^
```
With including `CarlaGameInstance.h` in `TheNewCarlaGameModeBase.h`solves this issue.

The second error:
```
In file included from /Users/thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Intermediate/Build/Mac/UE4Editor/Development/Carla/Module.Carla.gen.2_of_2.cpp:23:
In file included from /Users/thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Intermediate/Build/Mac/UE4Editor/Inc/Carla/TrafficLightBase.gen.cpp:9:
In file included from ../../../../../thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficLightBase.h:9:
../../../../../thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficSignBase.h:55:3: error: unknown type name 'UTrafficSignAgentComponent'
  UTrafficSignAgentComponent *TrafficSignAgentComponent;
  ^
```
The third error:
```
../../../../../thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficSignBase.h:31:3: error: cannot initialize return object of type 'UObject *' with an rvalue of type 'ATrafficSignBase *'
  GENERATED_BODY()
  ^~~~~~~~~~~~~~~~
Runtime/CoreUObject/Public/UObject/ObjectMacros.h:589:29: note: expanded from macro 'GENERATED_BODY'
#define GENERATED_BODY(...) BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_GENERATED_BODY);
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Runtime/CoreUObject/Public/UObject/ObjectMacros.h:584:37: note: expanded from macro 'BODY_MACRO_COMBINE'
#define BODY_MACRO_COMBINE(A,B,C,D) BODY_MACRO_COMBINE_INNER(A,B,C,D)
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Runtime/CoreUObject/Public/UObject/ObjectMacros.h:583:43: note: expanded from macro 'BODY_MACRO_COMBINE_INNER'
#define BODY_MACRO_COMBINE_INNER(A,B,C,D) A##B##C##D
                                          ^~~~~~~~~~
note: (skipping 1 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
../../../../../thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Intermediate/Build/Mac/UE4Editor/Inc/Carla/TrafficSignBase.generated.h:124:2: note: expanded from macro 'CarlaUE4_Plugins_Carla_Source_Carla_Traffic_TrafficSignBase_h_31_GENERATED_BODY'
        CarlaUE4_Plugins_Carla_Source_Carla_Traffic_TrafficSignBase_h_31_ENHANCED_CONSTRUCTORS \
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Intermediate/Build/Mac/UE4Editor/Inc/Carla/TrafficSignBase.generated.h:96:60: note: expanded from macro 'CarlaUE4_Plugins_Carla_Source_Carla_Traffic_TrafficSignBase_h_31_ENHANCED_CONSTRUCTORS'
        DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, ATrafficSignBase); \
                                                                  ^
Runtime/CoreUObject/Public/UObject/ObjectMacros.h:1409:11: note: expanded from macro '\
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER'
                        return new (EC_InternalUseOnlyConstructor, (UObject*)GetTransientPackage(), NAME_None, RF_NeedLoad | RF_ClassDefaultObject | RF_TagGarbageTemp) TClass(Helper); \
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Intermediate/Build/Mac/UE4Editor/Development/Carla/Module.Carla.gen.2_of_2.cpp:23:
In file included from /Users/thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Intermediate/Build/Mac/UE4Editor/Inc/Carla/TrafficLightBase.gen.cpp:9:
../../../../../thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficLightBase.h:21:3: error: cannot initialize return object of type 'UObject *' with an rvalue of type 'ATrafficLightBase *'
  GENERATED_BODY()
  ^~~~~~~~~~~~~~~~
Runtime/CoreUObject/Public/UObject/ObjectMacros.h:589:29: note: expanded from macro 'GENERATED_BODY'
#define GENERATED_BODY(...) BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_GENERATED_BODY);
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Runtime/CoreUObject/Public/UObject/ObjectMacros.h:584:37: note: expanded from macro 'BODY_MACRO_COMBINE'
#define BODY_MACRO_COMBINE(A,B,C,D) BODY_MACRO_COMBINE_INNER(A,B,C,D)
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Runtime/CoreUObject/Public/UObject/ObjectMacros.h:583:43: note: expanded from macro 'BODY_MACRO_COMBINE_INNER'
#define BODY_MACRO_COMBINE_INNER(A,B,C,D) A##B##C##D
                                          ^~~~~~~~~~
note: (skipping 1 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
../../../../../thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Intermediate/Build/Mac/UE4Editor/Inc/Carla/TrafficLightBase.generated.h:172:2: note: expanded from macro 'CarlaUE4_Plugins_Carla_Source_Carla_Traffic_TrafficLightBase_h_21_GENERATED_BODY'
        CarlaUE4_Plugins_Carla_Source_Carla_Traffic_TrafficLightBase_h_21_ENHANCED_CONSTRUCTORS \
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Intermediate/Build/Mac/UE4Editor/Inc/Carla/TrafficLightBase.generated.h:139:61: note: expanded from macro 'CarlaUE4_Plugins_Carla_Source_Carla_Traffic_TrafficLightBase_h_21_ENHANCED_CONSTRUCTORS'
        DECLARE_VTABLE_PTR_HELPER_CTOR(NO_API, ATrafficLightBase); \
                                                                   ^
Runtime/CoreUObject/Public/UObject/ObjectMacros.h:1409:11: note: expanded from macro '\
DEFINE_VTABLE_PTR_HELPER_CTOR_CALLER'
                        return new (EC_InternalUseOnlyConstructor, (UObject*)GetTransientPackage(), NAME_None, RF_NeedLoad | RF_ClassDefaultObject | RF_TagGarbageTemp) TClass(Helper); \
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Intermediate/Build/Mac/UE4Editor/Development/Carla/Module.Carla.gen.2_of_2.cpp:23:
/Users/thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Intermediate/Build/Mac/UE4Editor/Inc/Carla/TrafficLightBase.gen.cpp:35:16: error: cannot initialize object parameter of type 'const UObject' with an expression of type 'ATrafficLightBase'
                ProcessEvent(FindFunctionChecked(NAME_ATrafficLightBase_OnTrafficLightStateChanged),&Parms);
                             ^~~~~~~~~~~~~~~~~~~
/Users/thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Intermediate/Build/Mac/UE4Editor/Inc/Carla/TrafficLightBase.gen.cpp:196:206: error: non-constant-expression cannot be narrowed from type 'unsigned long' to 'int32' (aka 'int') in initializer list [-Wc++11-narrowing]
                        static const UE4CodeGen_Private::FArrayPropertyParams NewProp_Vehicles = { UE4CodeGen_Private::EPropertyClass::Array, "Vehicles", RF_Public|RF_Transient|RF_MarkAsNative, 0x0040000000020001, 1, nullptr, STRUCT_OFFSET(ATrafficLightBase, Vehicles), METADATA_PARAMS(NewProp_Vehicles_MetaData, ARRAY_COUNT(NewProp_Vehicles_MetaData)) };
                                                                                                                                                                                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/Shared/EpicGames/UE_4.19/Engine/Source/Runtime/Core/Public/Templates/UnrealTemplate.h:161:40: note: expanded from macro 'STRUCT_OFFSET'
#define STRUCT_OFFSET( struc, member )  offsetof(struc, member)
                                        ^~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include/stddef.h:120:24: note: expanded from macro 'offsetof'
#define offsetof(t, d) __builtin_offsetof(t, d)
                       ^~~~~~~~~~~~~~~~~~~~~~~~
/Users/thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Intermediate/Build/Mac/UE4Editor/Inc/Carla/TrafficLightBase.gen.cpp:196:206: note: insert an explicit cast to silence this issue
                        static const UE4CodeGen_Private::FArrayPropertyParams NewProp_Vehicles = { UE4CodeGen_Private::EPropertyClass::Array, "Vehicles", RF_Public|RF_Transient|RF_MarkAsNative, 0x0040000000020001, 1, nullptr, STRUCT_OFFSET(ATrafficLightBase, Vehicles), METADATA_PARAMS(NewProp_Vehicles_MetaData, ARRAY_COUNT(NewProp_Vehicles_MetaData)) };
                                                                                                                                                                                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                                                                                                                                                  static_cast<int32>(                       )
/Users/Shared/EpicGames/UE_4.19/Engine/Source/Runtime/Core/Public/Templates/UnrealTemplate.h:161:40: note: expanded from macro 'STRUCT_OFFSET'
#define STRUCT_OFFSET( struc, member )  offsetof(struc, member)
                                        ^~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include/stddef.h:120:24: note: expanded from macro 'offsetof'
#define offsetof(t, d) __builtin_offsetof(t, d)
                       ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Intermediate/Build/Mac/UE4Editor/Development/Carla/Module.Carla.gen.2_of_2.cpp:23:
/Users/thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Intermediate/Build/Mac/UE4Editor/Inc/Carla/TrafficLightBase.gen.cpp:204:198: error: non-constant-expression cannot be narrowed from type 'unsigned long' to 'int32' (aka 'int') in initializer list [-Wc++11-narrowing]
                        static const UE4CodeGen_Private::FEnumPropertyParams NewProp_State = { UE4CodeGen_Private::EPropertyClass::Enum, "State", RF_Public|RF_Transient|RF_MarkAsNative, 0x0040000000000001, 1, nullptr, STRUCT_OFFSET(ATrafficLightBase, State), Z_Construct_UEnum_Carla_ETrafficLightState, METADATA_PARAMS(NewProp_State_MetaData, ARRAY_COUNT(NewProp_State_MetaData)) };
                                                                                                                                                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/Shared/EpicGames/UE_4.19/Engine/Source/Runtime/Core/Public/Templates/UnrealTemplate.h:161:40: note: expanded from macro 'STRUCT_OFFSET'
#define STRUCT_OFFSET( struc, member )  offsetof(struc, member)
                                        ^~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include/stddef.h:120:24: note: expanded from macro 'offsetof'
#define offsetof(t, d) __builtin_offsetof(t, d)
                       ^~~~~~~~~~~~~~~~~~~~~~~~
/Users/thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Intermediate/Build/Mac/UE4Editor/Inc/Carla/TrafficLightBase.gen.cpp:204:198: note: insert an explicit cast to silence this issue
                        static const UE4CodeGen_Private::FEnumPropertyParams NewProp_State = { UE4CodeGen_Private::EPropertyClass::Enum, "State", RF_Public|RF_Transient|RF_MarkAsNative, 0x0040000000000001, 1, nullptr, STRUCT_OFFSET(ATrafficLightBase, State), Z_Construct_UEnum_Carla_ETrafficLightState, METADATA_PARAMS(NewProp_State_MetaData, ARRAY_COUNT(NewProp_State_MetaData)) };
                                                                                                                                                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                                                                                                                                          static_cast<int32>(                    )
/Users/Shared/EpicGames/UE_4.19/Engine/Source/Runtime/Core/Public/Templates/UnrealTemplate.h:161:40: note: expanded from macro 'STRUCT_OFFSET'
#define STRUCT_OFFSET( struc, member )  offsetof(struc, member)
                                        ^~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include/stddef.h:120:24: note: expanded from macro 'offsetof'
#define offsetof(t, d) __builtin_offsetof(t, d)
                       ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Intermediate/Build/Mac/UE4Editor/Development/Carla/Module.Carla.gen.2_of_2.cpp:26:
/Users/thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Intermediate/Build/Mac/UE4Editor/Inc/Carla/TrafficSignBase.gen.cpp:185:242: error: non-constant-expression cannot be narrowed from type 'unsigned long' to 'int32' (aka 'int') in initializer list [-Wc++11-narrowing]
                        static const UE4CodeGen_Private::FObjectPropertyParams NewProp_TrafficSignAgentComponent = { UE4CodeGen_Private::EPropertyClass::Object, "TrafficSignAgentComponent", RF_Public|RF_Transient|RF_MarkAsNative, 0x00400000000a0009, 1, nullptr, STRUCT_OFFSET(ATrafficSignBase, TrafficSignAgentComponent), Z_Construct_UClass_UTrafficSignAgentComponent_NoRegister, METADATA_PARAMS(NewProp_TrafficSignAgentComponent_MetaData, ARRAY_COUNT(NewProp_TrafficSignAgentComponent_MetaData)) };
                                                                                                                                                                                                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/Shared/EpicGames/UE_4.19/Engine/Source/Runtime/Core/Public/Templates/UnrealTemplate.h:161:40: note: expanded from macro 'STRUCT_OFFSET'
#define STRUCT_OFFSET( struc, member )  offsetof(struc, member)
                                        ^~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include/stddef.h:120:24: note: expanded from macro 'offsetof'
#define offsetof(t, d) __builtin_offsetof(t, d)
                       ^~~~~~~~~~~~~~~~~~~~~~~~
/Users/thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Intermediate/Build/Mac/UE4Editor/Inc/Carla/TrafficSignBase.gen.cpp:185:242: note: insert an explicit cast to silence this issue
                        static const UE4CodeGen_Private::FObjectPropertyParams NewProp_TrafficSignAgentComponent = { UE4CodeGen_Private::EPropertyClass::Object, "TrafficSignAgentComponent", RF_Public|RF_Transient|RF_MarkAsNative, 0x00400000000a0009, 1, nullptr, STRUCT_OFFSET(ATrafficSignBase, TrafficSignAgentComponent), Z_Construct_UClass_UTrafficSignAgentComponent_NoRegister, METADATA_PARAMS(NewProp_TrafficSignAgentComponent_MetaData, ARRAY_COUNT(NewProp_TrafficSignAgentComponent_MetaData)) };
                                                                                                                                                                                                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                                                                                                                                                                                      static_cast<int32>(                                       )
/Users/Shared/EpicGames/UE_4.19/Engine/Source/Runtime/Core/Public/Templates/UnrealTemplate.h:161:40: note: expanded from macro 'STRUCT_OFFSET'
#define STRUCT_OFFSET( struc, member )  offsetof(struc, member)
                                        ^~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include/stddef.h:120:24: note: expanded from macro 'offsetof'
#define offsetof(t, d) __builtin_offsetof(t, d)
                       ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Intermediate/Build/Mac/UE4Editor/Development/Carla/Module.Carla.gen.2_of_2.cpp:26:
/Users/thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Intermediate/Build/Mac/UE4Editor/Inc/Carla/TrafficSignBase.gen.cpp:192:220: error: non-constant-expression cannot be narrowed from type 'unsigned long' to 'int32' (aka 'int') in initializer list [-Wc++11-narrowing]
                        static const UE4CodeGen_Private::FEnumPropertyParams NewProp_TrafficSignState = { UE4CodeGen_Private::EPropertyClass::Enum, "TrafficSignState", RF_Public|RF_Transient|RF_MarkAsNative, 0x0040000000000001, 1, nullptr, STRUCT_OFFSET(ATrafficSignBase, TrafficSignState), Z_Construct_UEnum_Carla_ETrafficSignState, METADATA_PARAMS(NewProp_TrafficSignState_MetaData, ARRAY_COUNT(NewProp_TrafficSignState_MetaData)) };
                                                                                                                                                                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/Shared/EpicGames/UE_4.19/Engine/Source/Runtime/Core/Public/Templates/UnrealTemplate.h:161:40: note: expanded from macro 'STRUCT_OFFSET'
#define STRUCT_OFFSET( struc, member )  offsetof(struc, member)
                                        ^~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include/stddef.h:120:24: note: expanded from macro 'offsetof'
#define offsetof(t, d) __builtin_offsetof(t, d)
                       ^~~~~~~~~~~~~~~~~~~~~~~~
/Users/thierryderuyttere/Documents/carla/Unreal/CarlaUE4/Plugins/Carla/Intermediate/Build/Mac/UE4Editor/Inc/Carla/TrafficSignBase.gen.cpp:192:220: note: insert an explicit cast to silence this issue
                        static const UE4CodeGen_Private::FEnumPropertyParams NewProp_TrafficSignState = { UE4CodeGen_Private::EPropertyClass::Enum, "TrafficSignState", RF_Public|RF_Transient|RF_MarkAsNative, 0x0040000000000001, 1, nullptr, STRUCT_OFFSET(ATrafficSignBase, TrafficSignState), Z_Construct_UEnum_Carla_ETrafficSignState, METADATA_PARAMS(NewProp_TrafficSignState_MetaData, ARRAY_COUNT(NewProp_TrafficSignState_MetaData)) };
                                                                                                                                                                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                                                                                                                                                                static_cast<int32>(                              )
/Users/Shared/EpicGames/UE_4.19/Engine/Source/Runtime/Core/Public/Templates/UnrealTemplate.h:161:40: note: expanded from macro 'STRUCT_OFFSET'
#define STRUCT_OFFSET( struc, member )  offsetof(struc, member)
                                        ^~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include/stddef.h:120:24: note: expanded from macro 'offsetof'
#define offsetof(t, d) __builtin_offsetof(t, d)
                       ^~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by ThierryDeruyttere** [comment]
Concerning PythonAPI: 

I had just one error:

```In file included from source/libcarla/libcarla.cpp:10:
source/libcarla/Blueprint.cpp:57:5: error: static_assert failed "Please update this function."
    static_assert(static_cast<uint8_t>(Type::SIZE) == 5u, "Please update this function.");
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Which I solved by just commenting that function. After commenting this the PythonAPI build fine on my mac.

**Comment by nsubiron** [comment]
Yes, I had these missing includes issue recently too. I think is fixed on a different branch, I'll do the merge. UE4 adapts the unit build it does depending on the targets that has to compile. Our Jenkins pipeline sometimes does not catch missing includes because does a clean build (a unit build of all the files), then at some point in your computer some code that hasn't being touched in ages fails with a missing include, annoying.

I'm concerned about the last error though

```
source/libcarla/Blueprint.cpp:57:5: error: static_assert failed "Please update this function."
    static_assert(static_cast<uint8_t>(Type::SIZE) == 5u, "Please update this function.");
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
You can ignored for now, it should work anyway. But I would like to understand why fails and fix it, I will open an issue with that.

Thanks again for reporting, very useful as we don't have macs here to test!

**Pull request merged**
