### PR TITLE
Corkyw10/import maps tutorial

### PR DESCRIPTION
**Pull request by corkyw10**
# Update "Add a new map" tutorial

- Due to the length of the tutorial and the very distinct routes a user has to go down, to prevent confusion for users I have split the tutorial into 5 parts that are on different pages:
    1. Overview - this has links to each other part of the guide
    2. Generate the map in RoadRunner
    3. Import for source
    4. Import for package
    5. Deprecated methods
- Due to limitations of mkdocs, I can't have the different parts listed in the nav bar which is why I did the overview to act as a gateway into the tutorial.
- I have added the new naming convention that will be used in the newer version of RoadRunner
- I added updated pre-requisites for the package import guide
- All links within the rest of the documentation have been updated to lead to the overview page
- In the deprecated section, the dropdowns had broken the markdown so everything has been moved out of the dropdowns and they have been removed
- There has been considerable rewording and reformatting of each individual guide

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3875)

### CODE REVIEW

**Review by bernatx — CHANGES_REQUESTED** [review]
> Reviewed 10 of 13 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3875)* status: 12 of 13 files reviewed, 10 unresolved discussions (waiting on @corkyw10 and @XGodina)

___
*[Docs/tuto_A_add_map/add_map_deprecated.md, line 296 at r2](https://reviewable.io/reviews/carla-simulator/carla/3875#-MTbW3MP47vtkDRNYpI2:-MTbW3MP47vtkDRNYpI3:boki1cq) ([raw file](https://github.com/carla-simulator/carla/blob/767cf9e39c31c2803151dc721211984bc5742315/Docs/tuto_A_add_map/add_map_deprecated.md#L296)):*
> ```Markdown
> ue_meshes 
> 
> __3.__ Crosswalks have to be manually created. For each of them, create a plane mesh that extends a bit over both sidewalks connected. __Place it overlapping the ground, and disable its physics and rendering__. 
> ```

The crosswalks defined through RoadRunner are saved into the .xodr file, and those are parsed automatically when we recreate the .bin file. The only crosswalks that the user need to create with invisible planes are the ones that are not defined in the .xodr file, by any reason. We used those invisible planes for old towns because we could not recreate the .xodr. So in this case we added the crosswalks as invisible planes, but in the map there was no texture that indicate the existence of crosswalks. So, crosswalks can be given by two ways, from the .xodr or by invisible planes with the name (Road_Crosswalk or Roads_Crosswalk).
___
*[Docs/tuto_A_add_map/add_map_deprecated.md, line 300 at r2](https://reviewable.io/reviews/carla-simulator/carla/3875#-MTbVlPeBpe5P2eeA-cC:-MTbVlPeBpe5P2eeA-cD:b-m9plqs) ([raw file](https://github.com/carla-simulator/carla/blob/767cf9e39c31c2803151dc721211984bc5742315/Docs/tuto_A_add_map/add_map_deprecated.md#L300)):*
> ```
> `Road_Crosswalk_mapname`
> ```
The name just need to start with Road_Crosswalk (or Roads_Crosswalk). The rest is whatever, it seems that it needs to be the map name, but that is not true.
___
*[Docs/tuto_A_add_map/add_map_deprecated.md, line 302 at r2](https://reviewable.io/reviews/carla-simulator/carla/3875#-MTbX3LI1EoaQwVtv-n8:-MTbX3LJCxFDvh7_IWTo:bt117ym) ([raw file](https://github.com/carla-simulator/carla/blob/767cf9e39c31c2803151dc721211984bc5742315/Docs/tuto_A_add_map/add_map_deprecated.md#L302)):*
> ```Markdown
> __4.__ Name these planes following the common format `Road_Crosswalk_mapname`. 
> 
> __5.__ Press `G` to deselect everything, and export the map. `File > Export CARLA...`.  
> ```

Maybe we can say, be sure to deselect any object or only that will be exported. Because I think 'G' key only hides some lines.
Also, the exported is called "CARLA exporter"
___
*[Docs/tuto_A_add_map/add_map_deprecated.md, line 303 at r2](https://reviewable.io/reviews/carla-simulator/carla/3875#-MTbXQta5mR4a83qZLa_:-MTbXQta5mR4a83qZLaa:b-vnoj77) ([raw file](https://github.com/carla-simulator/carla/blob/767cf9e39c31c2803151dc721211984bc5742315/Docs/tuto_A_add_map/add_map_deprecated.md#L303)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> __6.__ Run RecastDemo `./RecastDemo`.
>   * Select `Solo Mesh` from the `Sample` parameter's box.
>   * Select the `mapname.obj` file from the `Input Mesh` parameter's box.
> recast_example
> __7.__ Click on the `Build` button.
> __8.__ Once the build has finished, click on the `Save` button.
> __9.__ Change the **filename** of the binary file generated at `RecastDemo/Bin` to `mapname.bin`.
> ```
</details>

All these steps are done by the RecastBuilder.exe
We don't have an RecastDemo anymore.
So, after exporting the .obj by the CARLA exporter, they need to copy this file and the .xodr into the 'carla\Util\DockerUtils\dist\' where the RecastBuilder exist. Then execute the build.bat or build.sh that will make all the steps until generate the .bin
___
*[Docs/tuto_A_add_map/add_map_package.md, line 62 at r2](https://reviewable.io/reviews/carla-simulator/carla/3875#-MTbYcEgEnR86ID5alJW:-MTbYcEgEnR86ID5alJX:b-jo6n94) ([raw file](https://github.com/carla-simulator/carla/blob/767cf9e39c31c2803151dc721211984bc5742315/Docs/tuto_A_add_map/add_map_package.md#L62)):*
> ```Markdown
> __6.__ The package will be generated in the `output_folder` as `<map_package>.tar.gz`. This is the standalone package that is now ready to be imported into CARLA:
> 
> > *   __On Windows__ extract the package to the `WindowsNoEditor` folder. 
> ```

You can not use a package exported from Docker as it is cookd to be use for a Linux version of CARLA. So, Docker is only for Linux platform.
___
*[Docs/tuto_A_add_map/add_map_package.md, line 70 at r2](https://reviewable.io/reviews/carla-simulator/carla/3875#-MTbYvAc2sjM7kZ-JN-y:-MTbYvAc2sjM7kZ-JN-z:b-qx77k3) ([raw file](https://github.com/carla-simulator/carla/blob/767cf9e39c31c2803151dc721211984bc5742315/Docs/tuto_A_add_map/add_map_package.md#L70)):*
> ```Markdown
> ```
> 
> __7.__ Two packages cannot have the same name in CARLA so you may need to change the name of the package folder. Go to `CarlaUE4/Content` and change the package name appropriately.
> ```

The name of the package can be the same, and then the maps are added to that package in CARLA. The problem is when that package has a map with the same name of one that we are importing, then a conflict arise and will fail.
___
*[Docs/tuto_A_add_map/add_map_source.md, line 33 at r2](https://reviewable.io/reviews/carla-simulator/carla/3875#-MTbZYtsAxvH2ogWYU2j:-MTbZYtsAxvH2ogWYU2k:bntjsp5) ([raw file](https://github.com/carla-simulator/carla/blob/767cf9e39c31c2803151dc721211984bc5742315/Docs/tuto_A_add_map/add_map_source.md#L33)):*
> ```
> --no-carla-materials
> ```
I have to check if this parameter is being used, because we have that parameter for each map in the .json file.
___
*[Docs/tuto_A_add_map/add_map_source.md, line 49 at r2](https://reviewable.io/reviews/carla-simulator/carla/3875#-MTbZx3oCo5UTnm5sa6Y:-MTbZx3oCo5UTnm5sa6Z:b-eyqizn) ([raw file](https://github.com/carla-simulator/carla/blob/767cf9e39c31c2803151dc721211984bc5742315/Docs/tuto_A_add_map/add_map_source.md#L49)):*
> ```
> __Add crosswalk meshes to crosswalks defined in the `.xodr` file.__ Crosswalks defined inside the `.xodr` file remain in the logic of the map, but are not visible. For each of them, create a plane mesh that extends a bit over both sidewalks connected. __Place it overlapping the ground, and disable its physics and rendering__.·
> ```
I think RoadRunner now export the crosswalks with texture, so you don't need to do anything extra.
___
*[Docs/tuto_A_add_map/add_map_source.md, line 50 at r2](https://reviewable.io/reviews/carla-simulator/carla/3875#-MTb_8wKCKjCF6D3MVTN:-MTb_8wKCKjCF6D3MVTO:bg199sm) ([raw file](https://github.com/carla-simulator/carla/blob/767cf9e39c31c2803151dc721211984bc5742315/Docs/tuto_A_add_map/add_map_source.md#L50)):*
> ```Markdown
>     - Place the spawn point about 0.5-1m above the ground to prevent collisions with the road.
> *   __Add crosswalk meshes to crosswalks defined in the `.xodr` file.__ Crosswalks defined inside the `.xodr` file remain in the logic of the map, but are not visible. For each of them, create a plane mesh that extends a bit over both sidewalks connected. __Place it overlapping the ground, and disable its physics and rendering__. 
> * __Generate new crosswalks__ by changing the name of the mesh to `Road_Crosswalk` or `Roads_Crosswalk`. Avoid doing this if the crosswalk is already defined the `.xodr` file. This will lead to duplication. 
> ```

Maybe here we could say the same about create invisible planes where we want pedestrians to cross the road.
___
*[Docs/tuto_A_add_map/add_map_source.md, line 62 at r2](https://reviewable.io/reviews/carla-simulator/carla/3875#-MTb_LSS2J_JXdvb7yLm:-MTb_LSS2J_JXdvb7yLn:b-7scnm3) ([raw file](https://github.com/carla-simulator/carla/blob/767cf9e39c31c2803151dc721211984bc5742315/Docs/tuto_A_add_map/add_map_source.md#L62)):*
> ```
> Road_Crosswalk_<mapName>
> ```
Same as previously, I think the part _<mapName> is confusing as it could be any name after the Road_Crosswalk, usually there is an increasing number only.

**Review by corkyw10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3875)* status: 11 of 13 files reviewed, 10 unresolved discussions (waiting on @bernatx, @corkyw10, and @XGodina)

___
*[Docs/tuto_A_add_map/add_map_package.md, line 62 at r2](https://reviewable.io/reviews/carla-simulator/carla/3875#-MTbYcEgEnR86ID5alJW:-MTeG54T3CJIQnp_m52r:bekavf0) ([raw file](https://github.com/carla-simulator/carla/blob/767cf9e39c31c2803151dc721211984bc5742315/Docs/tuto_A_add_map/add_map_package.md#L62)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

You can not use a package exported from Docker as it is cookd to be use for a Linux version of CARLA. So, Docker is only for Linux platform.
</blockquote></details>

Done. I also added in the section description that it's only available for Linux.

**Review by XGodina — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3875)* status: 12 of 13 files reviewed, 11 unresolved discussions (waiting on @bernatx and @corkyw10)

___
*[Docs/tuto_A_add_map/generate_map_roadrunner.md, line 54 at r3](https://reviewable.io/reviews/carla-simulator/carla/3875#-MTekqSACaRntNnohswE:-MTekqSACaRntNnohswF:b4qava0) ([raw file](https://github.com/carla-simulator/carla/blob/59275c5705fc5f0f623f78fe4bef6cfe7d40bd85/Docs/tuto_A_add_map/generate_map_roadrunner.md#L54)):*
> ```Markdown
>     _OpenDrive Preview Tool_ makes it easier to test the integrity of the map. If there are any errors with junctions, click on `Maneuver Tool`, and `Rebuild Maneuver Roads`.
> ```

I think it will be a good idea to add more information when you export .fbx

1- Split by Segmentation: Divide the mesh by semantic segmentation. 
2- Power of two texture Dimensions: works better and helps performance
3- Embed Textures: The textures are in the mesh
4- Export to Tiles: You can choose the size of the Tile or unchecked only one piece.
5- Export Individual Tiles: For each piece one .fbx

I will provide a picture.

**Review by corkyw10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3875)* status: 12 of 13 files reviewed, 11 unresolved discussions (waiting on @bernatx, @corkyw10, and @XGodina)

___
*[Docs/tuto_A_add_map/add_map_package.md, line 70 at r2](https://reviewable.io/reviews/carla-simulator/carla/3875#-MTbYvAc2sjM7kZ-JN-y:-MTfB9eb5-jrIflXvCR3:bb3u6kg) ([raw file](https://github.com/carla-simulator/carla/blob/767cf9e39c31c2803151dc721211984bc5742315/Docs/tuto_A_add_map/add_map_package.md#L70)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

The name of the package can be the same, and then the maps are added to that package in CARLA. The problem is when that package has a map with the same name of one that we are importing, then a conflict arise and will fail.
</blockquote></details>

I have taken this bit away and added in the "Before you begin" for both source and package that you can import several maps into a package and they need to have unique names.
___
*[Docs/tuto_A_add_map/add_map_source.md, line 49 at r2](https://reviewable.io/reviews/carla-simulator/carla/3875#-MTbZx3oCo5UTnm5sa6Y:-MTfBRP-CWXVmff-fKKe:b-yqx1zs) ([raw file](https://github.com/carla-simulator/carla/blob/767cf9e39c31c2803151dc721211984bc5742315/Docs/tuto_A_add_map/add_map_source.md#L49)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
> __Add crosswalk meshes to crosswalks defined in the `.xodr` file.__ Crosswalks defined inside the `.xodr` file remain in the logic of the map, but are not visible. For each of them, create a plane mesh that extends a bit over both sidewalks connected. __Place it overlapping the ground, and disable its physics and rendering__.·
> ```
I think RoadRunner now export the crosswalks with texture, so you don't need to do anything extra.
</blockquote></details>

Done. I have removed this.
___
*[Docs/tuto_A_add_map/add_map_source.md, line 50 at r2](https://reviewable.io/reviews/carla-simulator/carla/3875#-MTb_8wKCKjCF6D3MVTN:-MTfBYlt8i--vCBJQYEW:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/767cf9e39c31c2803151dc721211984bc5742315/Docs/tuto_A_add_map/add_map_source.md#L50)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

Maybe here we could say the same about create invisible planes where we want pedestrians to cross the road.
</blockquote></details>

Done.
___
*[Docs/tuto_A_add_map/add_map_source.md, line 62 at r2](https://reviewable.io/reviews/carla-simulator/carla/3875#-MTb_LSS2J_JXdvb7yLm:-MTfBb5W-CWH9gWdkDi9:b8x5d86) ([raw file](https://github.com/carla-simulator/carla/blob/767cf9e39c31c2803151dc721211984bc5742315/Docs/tuto_A_add_map/add_map_source.md#L62)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
> Road_Crosswalk_<mapName>
> ```
Same as previously, I think the part _<mapName> is confusing as it could be any name after the Road_Crosswalk, usually there is an increasing number only.
</blockquote></details>

I have changed this a bit now and changed to "Double check your mesh names. Mesh names should start with any of the appropriate formats listed below in order to be recognized as areas where pedestrians can walk. By default, pedestrians will be able to walk over sidewalks, crosswalks, and grass (with minor influence over the rest)"

**Review by corkyw10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3875)* status: 8 of 12 files reviewed, 11 unresolved discussions (waiting on @bernatx, @corkyw10, and @XGodina)

___
*[Docs/tuto_A_add_map/add_map_deprecated.md, line 296 at r2](https://reviewable.io/reviews/carla-simulator/carla/3875#-MTbW3MP47vtkDRNYpI2:-MTfDDtr3Xaczet7JadE:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/767cf9e39c31c2803151dc721211984bc5742315/Docs/tuto_A_add_map/add_map_deprecated.md#L296)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

The crosswalks defined through RoadRunner are saved into the .xodr file, and those are parsed automatically when we recreate the .bin file. The only crosswalks that the user need to create with invisible planes are the ones that are not defined in the .xodr file, by any reason. We used those invisible planes for old towns because we could not recreate the .xodr. So in this case we added the crosswalks as invisible planes, but in the map there was no texture that indicate the existence of crosswalks. So, crosswalks can be given by two ways, from the .xodr or by invisible planes with the name (Road_Crosswalk or Roads_Crosswalk).
</blockquote></details>

Done.
___
*[Docs/tuto_A_add_map/add_map_deprecated.md, line 300 at r2](https://reviewable.io/reviews/carla-simulator/carla/3875#-MTbVlPeBpe5P2eeA-cC:-MTfDDYe-QZm-6Hhos7R:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/767cf9e39c31c2803151dc721211984bc5742315/Docs/tuto_A_add_map/add_map_deprecated.md#L300)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
> `Road_Crosswalk_mapname`
> ```
The name just need to start with Road_Crosswalk (or Roads_Crosswalk). The rest is whatever, it seems that it needs to be the map name, but that is not true.
</blockquote></details>

Done.
___
*[Docs/tuto_A_add_map/add_map_deprecated.md, line 302 at r2](https://reviewable.io/reviews/carla-simulator/carla/3875#-MTbX3LI1EoaQwVtv-n8:-MTfDEQf13hqxvt-ZFSV:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/767cf9e39c31c2803151dc721211984bc5742315/Docs/tuto_A_add_map/add_map_deprecated.md#L302)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

Maybe we can say, be sure to deselect any object or only that will be exported. Because I think 'G' key only hides some lines.
Also, the exported is called "CARLA exporter"
</blockquote></details>

Done.
___
*[Docs/tuto_A_add_map/add_map_deprecated.md, line 303 at r2](https://reviewable.io/reviews/carla-simulator/carla/3875#-MTbXQta5mR4a83qZLa_:-MTfDElM3nXWOiFN3GyN:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/767cf9e39c31c2803151dc721211984bc5742315/Docs/tuto_A_add_map/add_map_deprecated.md#L303)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
> __6.__ Run RecastDemo `./RecastDemo`.
>   * Select `Solo Mesh` from the `Sample` parameter's box.
>   * Select the `mapname.obj` file from the `Input Mesh` parameter's box.
> recast_example
> __7.__ Click on the `Build` button.
> __8.__ Once the build has finished, click on the `Save` button.
> __9.__ Change the **filename** of the binary file generated at `RecastDemo/Bin` to `mapname.bin`.
> ```
All these steps are done by the RecastBuilder.exe
We don't have an RecastDemo anymore.
So, after exporting the .obj by the CARLA exporter, they need to copy this file and the .xodr into the 'carla\Util\DockerUtils\dist\' where the RecastBuilder exist. Then execute the build.bat or build.sh that will make all the steps until generate the .bin
</blockquote></details>

Done.
___
*[Docs/tuto_A_add_map/add_map_package.md, line 70 at r2](https://reviewable.io/reviews/carla-simulator/carla/3875#-MTbYvAc2sjM7kZ-JN-y:-MTfDFsO-BUp6262hGwG:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/767cf9e39c31c2803151dc721211984bc5742315/Docs/tuto_A_add_map/add_map_package.md#L70)):*
<details><summary><i>Previously, corkyw10 (Corinne) wrote…</i></summary><blockquote>

I have taken this bit away and added in the "Before you begin" for both source and package that you can import several maps into a package and they need to have unique names.
</blockquote></details>

Done.
___
*[Docs/tuto_A_add_map/add_map_source.md, line 62 at r2](https://reviewable.io/reviews/carla-simulator/carla/3875#-MTb_LSS2J_JXdvb7yLm:-MTfDI1b926omL5l5DRy:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/767cf9e39c31c2803151dc721211984bc5742315/Docs/tuto_A_add_map/add_map_source.md#L62)):*
<details><summary><i>Previously, corkyw10 (Corinne) wrote…</i></summary><blockquote>

I have changed this a bit now and changed to "Double check your mesh names. Mesh names should start with any of the appropriate formats listed below in order to be recognized as areas where pedestrians can walk. By default, pedestrians will be able to walk over sidewalks, crosswalks, and grass (with minor influence over the rest)"
</blockquote></details>

Done.

**Review by corkyw10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3875)* status: 8 of 13 files reviewed, 11 unresolved discussions (waiting on @bernatx, @corkyw10, and @XGodina)

___
*[Docs/tuto_A_add_map/generate_map_roadrunner.md, line 54 at r3](https://reviewable.io/reviews/carla-simulator/carla/3875#-MTekqSACaRntNnohswE:-MTfId2P-7sKIXB06jSe:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/59275c5705fc5f0f623f78fe4bef6cfe7d40bd85/Docs/tuto_A_add_map/generate_map_roadrunner.md#L54)):*
<details><summary><i>Previously, XGodina (Xavi ) wrote…</i></summary><blockquote>

I think it will be a good idea to add more information when you export .fbx

1- Split by Segmentation: Divide the mesh by semantic segmentation. 
2- Power of two texture Dimensions: works better and helps performance
3- Embed Textures: The textures are in the mesh
4- Export to Tiles: You can choose the size of the Tile or unchecked only one piece.
5- Export Individual Tiles: For each piece one .fbx

I will provide a picture.

</blockquote></details>

Done.

**Review by bernatx — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3875)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @corkyw10 and @XGodina)

___
*[Docs/tuto_A_add_map/add_map_source.md, line 33 at r2](https://reviewable.io/reviews/carla-simulator/carla/3875#-MTbZYtsAxvH2ogWYU2j:-MTfPmdg3OhKdUVYVCUf:b-dpozcl) ([raw file](https://github.com/carla-simulator/carla/blob/767cf9e39c31c2803151dc721211984bc5742315/Docs/tuto_A_add_map/add_map_source.md#L33)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
> --no-carla-materials
> ```
I have to check if this parameter is being used, because we have that parameter for each map in the .json file.
</blockquote></details>

I checked it, and that parameters is only used if the .json needs to be automatically created, otherwise it is ignored and the values of the .json file are used.

**Review by XGodina — DISMISSED** [review]
> Reviewed 9 of 13 files at r1, 2 of 2 files at r2, 1 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3875)* status: all files reviewed, 1 unresolved discussion (waiting on @corkyw10)

**Review by corkyw10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3875)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @bernatx)

___
*[Docs/tuto_A_add_map/add_map_source.md, line 33 at r2](https://reviewable.io/reviews/carla-simulator/carla/3875#-MTbZYtsAxvH2ogWYU2j:-MTjRm9Y6PHtWYQjLduL:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/767cf9e39c31c2803151dc721211984bc5742315/Docs/tuto_A_add_map/add_map_source.md#L33)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

I checked it, and that parameters is only used if the .json needs to be automatically created, otherwise it is ignored and the values of the .json file are used.
</blockquote></details>

Done.

**Review by bernatx — APPROVED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3875)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by XGodina** [comment]
___
*[Docs/tuto_A_add_map/add_map_alternative.md, line 190 at r8](https://reviewable.io/reviews/carla-simulator/carla/3875#-MW-o-6YDuGYDgvaRX0H:-MW-o-6Z4gy3R8tLrnd8:b-cc51uq) ([raw file](https://github.com/carla-simulator/carla/blob/f83e6b4c03a122bb303ea2852e0173b47b38061b/Docs/tuto_A_add_map/add_map_alternative.md#L190)):*
> ```Markdown
> __1.__ Generate new crosswalks if needed. Avoid doing this if the crosswalk is already defined in the `.xodr` file as this will lead to duplication:
> 
> - Create a plane mesh that extends a bit over two sidewalks that you want to connect.
> ```

I would also mention that it has to hide the meshes in the render and remove the collisions.

**Review by corkyw10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3875)* status: 12 of 18 files reviewed, 1 unresolved discussion (waiting on @bernatx, @corkyw10, and @XGodina)

___
*[Docs/tuto_A_add_map/add_map_alternative.md, line 190 at r8](https://reviewable.io/reviews/carla-simulator/carla/3875#-MW-o-6YDuGYDgvaRX0H:-MW-sStw7w_rMrZOOWF7:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/f83e6b4c03a122bb303ea2852e0173b47b38061b/Docs/tuto_A_add_map/add_map_alternative.md#L190)):*
<details><summary><i>Previously, XGodina (Xavi ) wrote…</i></summary><blockquote>

I would also mention that it has to hide the meshes in the render and remove the collisions.
</blockquote></details>

Done.

**Review by XGodina — APPROVED** [review]
> Reviewed 2 of 6 files at r4, 1 of 2 files at r5, 4 of 5 files at r7, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3875)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corkyw10)

**Pull request merged**
