### PR TITLE
Fixed recorder/replayer

### PR DESCRIPTION
**Pull request by LuisPoveda**
- Fixed vehicle wheels rotation and steering angle.
- Fixed bikers animations.

Fixed in separate functions to avoid breaking backward compatibility.

- - -
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/6128)

### CODE REVIEW

**Review by bernatx — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/6128)* status: all files reviewed, 8 unresolved discussions (waiting on @Axel1092 and @LuisPoveda)

___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/FrameData.cpp` line 142 at r4](https://reviewable.io/reviews/carla-simulator/carla/6128#-NMSqr5zA7xifbShlYJZ:-NMSqr5zA7xifbShlYJ_:b-k4f916) ([raw file](https://github.com/carla-simulator/carla/blob/505599a41a53a49cb13bd7b1dcefd50cfed1d44d/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/FrameData.cpp#L142)):*
> ```cpp
>   for (const CarlaRecorderAnimWheels &AnimWheel : Wheels.GetVehicleWheels())
>   {
>     CarlaRecorderAnimWheels Wheel = AnimWheel;
> ```

can we called in plural, as it is for all the wheels and not just one :)



_Code quote:_
```cpp
Wheel
```
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/FrameData.cpp` line 259 at r4](https://reviewable.io/reviews/carla-simulator/carla/6128#-NMSqke01FdOMjyKf4uE:-NMSqke01FdOMjyKf4uF:b97dadv) ([raw file](https://github.com/carla-simulator/carla/blob/505599a41a53a49cb13bd7b1dcefd50cfed1d44d/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/FrameData.cpp#L259)):*
> ```cpp
>         Walkers.Read(InStream);
>         break;
>       
> ```

remove empty spaces please
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/FrameData.cpp` line 429 at r4](https://reviewable.io/reviews/carla-simulator/carla/6128#-NMT0CxO9klb2FciLO8V:-NMT0CxO9klb2FciLO8W:b-3obznt) ([raw file](https://github.com/carla-simulator/carla/blob/505599a41a53a49cb13bd7b1dcefd50cfed1d44d/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/FrameData.cpp#L429)):*
> ```cpp
>   FL.Location = EVehicleWheelLocation::FL_Wheel;
>   FL.SteeringAngle = CarlaVehicle->GetWheelSteerAngle(FL.Location);
>   FL.TireRotation = WheeledVehicleMovementComponent->Wheels[(uint8)FL.Location]->GetRotationAngle();
> ```

better use the more modern cast like static_cast<uint8>(FL.Location)



_Suggestion:_
```cpp
(uint8)FL.Location
```
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorder.h` line 139 at r4](https://reviewable.io/reviews/carla-simulator/carla/6128#-NMT0hjOBCEXYiLBGkKE:-NMT0hjOBCEXYiLBGkKF:b-605xso) ([raw file](https://github.com/carla-simulator/carla/blob/505599a41a53a49cb13bd7b1dcefd50cfed1d44d/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorder.h#L139)):*
> ```objc
> 
>   void AddActorBones(FCarlaActor *CarlaActor);
>   
> ```

remove spaces there



_Code quote:_
```objc
··
```
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorderAnimBiker.h` line 39 at r4](https://reviewable.io/reviews/carla-simulator/carla/6128#-NMT0yu9ArRWdbOE0AA3:-NMT0yu9ArRWdbOE0AA4:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/505599a41a53a49cb13bd7b1dcefd50cfed1d44d/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorderAnimBiker.h#L39)):*
> ```objc
> 
>   const std::vector<CarlaRecorderAnimBiker>& GetBikers();
>   
> ```

remove spaces



_Code quote:_
```objc
··
```
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayer.cpp` line 389 at r4](https://reviewable.io/reviews/carla-simulator/carla/6128#-NMT2nPt2OhdhMPj9oiR:-NMT2nPt2OhdhMPj9oiS:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/505599a41a53a49cb13bd7b1dcefd50cfed1d44d/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayer.cpp#L389)):*
> ```cpp
>           SkipPacket();
>         break;
>         
> ```

remove spaces



_Code quote:_
```cpp
········
```
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayer.cpp` line 565 at r4](https://reviewable.io/reviews/carla-simulator/carla/6128#-NMT2rEVAH7xl4PPhRoe:-NMT2rEVAH7xl4PPhRof:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/505599a41a53a49cb13bd7b1dcefd50cfed1d44d/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayer.cpp#L565)):*
> ```cpp
> {
>   uint16_t i, Total;
>   
> ```

remove spaces



_Code quote:_
```cpp
··
```
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayerHelper.h` line 57 at r4](https://reviewable.io/reviews/carla-simulator/carla/6128#-NMT3Io2Eo9fD72CuLYI:-NMT3Io2Eo9fD72CuLYJ:b-750vq4) ([raw file](https://github.com/carla-simulator/carla/blob/505599a41a53a49cb13bd7b1dcefd50cfed1d44d/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayerHelper.h#L57)):*
> ```objc
>   // set the animation for Vehicles
>   void ProcessReplayerAnimVehicle(CarlaRecorderAnimVehicle Vehicle);
>   
> ```

remove spaces



_Code quote:_
```objc
··
```

**Review by LuisPoveda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/6128)* status: 7 of 15 files reviewed, 8 unresolved discussions (waiting on @Axel1092 and @bernatx)

___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/FrameData.cpp` line 142 at r4](https://reviewable.io/reviews/carla-simulator/carla/6128#-NMSqr5zA7xifbShlYJZ:-NMTxjlS-SnxN9xD9UYu:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/505599a41a53a49cb13bd7b1dcefd50cfed1d44d/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/FrameData.cpp#L142)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

can we called in plural, as it is for all the wheels and not just one :)
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/FrameData.cpp` line 259 at r4](https://reviewable.io/reviews/carla-simulator/carla/6128#-NMSqke01FdOMjyKf4uE:-NMTxlG6-isMenx3MsGQ:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/505599a41a53a49cb13bd7b1dcefd50cfed1d44d/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/FrameData.cpp#L259)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

remove empty spaces please
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/FrameData.cpp` line 429 at r4](https://reviewable.io/reviews/carla-simulator/carla/6128#-NMT0CxO9klb2FciLO8V:-NMTxloKAhIlI3V16n35:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/505599a41a53a49cb13bd7b1dcefd50cfed1d44d/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/FrameData.cpp#L429)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

better use the more modern cast like static_cast<uint8>(FL.Location)
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorder.h` line 139 at r4](https://reviewable.io/reviews/carla-simulator/carla/6128#-NMT0hjOBCEXYiLBGkKE:-NMTxnA5BqBmSfWHKmtQ:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/505599a41a53a49cb13bd7b1dcefd50cfed1d44d/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorder.h#L139)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

remove spaces there
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorderAnimBiker.h` line 39 at r4](https://reviewable.io/reviews/carla-simulator/carla/6128#-NMT0yu9ArRWdbOE0AA3:-NMTxnyBEvR2JW-31F4q:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/505599a41a53a49cb13bd7b1dcefd50cfed1d44d/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorderAnimBiker.h#L39)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

remove spaces
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayer.cpp` line 389 at r4](https://reviewable.io/reviews/carla-simulator/carla/6128#-NMT2nPt2OhdhMPj9oiR:-NMTxocp87cEvySIUpd5:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/505599a41a53a49cb13bd7b1dcefd50cfed1d44d/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayer.cpp#L389)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

remove spaces
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayer.cpp` line 565 at r4](https://reviewable.io/reviews/carla-simulator/carla/6128#-NMT2rEVAH7xl4PPhRoe:-NMTxpJP29NjheDg-tIb:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/505599a41a53a49cb13bd7b1dcefd50cfed1d44d/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayer.cpp#L565)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

remove spaces
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayerHelper.h` line 57 at r4](https://reviewable.io/reviews/carla-simulator/carla/6128#-NMT3Io2Eo9fD72CuLYI:-NMTxpvw7PIYDrUURmqH:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/505599a41a53a49cb13bd7b1dcefd50cfed1d44d/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayerHelper.h#L57)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

remove spaces
</blockquote></details>

Done.

**Review by bernatx — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/6128)* status: all files reviewed, 1 unresolved discussion (waiting on @Axel1092 and @LuisPoveda)

___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorderAnimBiker.h` line 1 at r6](https://reviewable.io/reviews/carla-simulator/carla/6128#-NMU1oSd6yfHfjqVGYBM:-NMU1oSd6yfHfjqVGYBN:b-pmg20n) ([raw file](https://github.com/carla-simulator/carla/blob/6184697587f085faf2fe9398dad939d616793c06/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorderAnimBiker.h#L1)):*
> ```objc
>           // Copyright (c) 2017 Computer Vision Center (CVC) at the Universitat Autonoma
> ```

There is an extra TAB here

**Review by LuisPoveda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/6128)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @Axel1092 and @bernatx)

___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorderAnimBiker.h` line 1 at r6](https://reviewable.io/reviews/carla-simulator/carla/6128#-NMU1oSd6yfHfjqVGYBM:-NMUZQpcDxCAVehrZYP1:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/6184697587f085faf2fe9398dad939d616793c06/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorderAnimBiker.h#L1)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

There is an extra TAB here
</blockquote></details>

Done.

**Review by bernatx — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/6128)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Axel1092)

**Pull request merged**
