### PR TITLE
Automatic calculation of vehicle's BB

### PR DESCRIPTION
**Pull request by doterop**
#### Description

Added a helper function to the BaseVehiclePawn constructor to calculate automatically the bounding box of the vehicle.

The changes are directly applied to the VehicleBounds Box Collision Component.
The new function is called AdjustVehicleBounds.
This feature affects both 4 wheeled and 2 wheeled vehicles. Everything that inherits from BaseVehiclePawn.

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04
  * **Python version(s):** 2, 3
  * **Unreal Engine version(s):** 4.24

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3267)

### CODE REVIEW

**Review by bernatx — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3267)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Axel1092, @bernatx, @doterop, and @marcgpuig)

___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp, line 125 at r2](https://reviewable.io/reviews/carla-simulator/carla/3267#-MGcKfxU1t9JT9oy8rdB:-MGcKfxU1t9JT9oy8rdC:bjgelsx) ([raw file](https://github.com/carla-simulator/carla/blob/be3a467246aa61309ed9de961a2fa8cf0cac8f4b/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp#L125)):*
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
> // Calculate middle point
>   FVector Origin (
>     (MaxVertex.X + MinVertex.X) * 0.5f,
>     (MaxVertex.Y + MinVertex.Y) * 0.5f,
>     (MaxVertex.Z + MinVertex.Z) * 0.5f
>   );
>   // Calculate box extent
>   FVector Extent (
>     (MaxVertex.X - MinVertex.X) * 0.5f,
>     (MaxVertex.Y - MinVertex.Y) * 0.5f,
>     (MaxVertex.Z - MinVertex.Z) * 0.5f
>   );
> ```
</details>

If speed matters here, we could optimize like this. First calculate the extension as it is now, and then get the middle point using the minimum point plus the extension, so we remove three products from the calculation :)

// Calculate box extent
FVector Extent (
  (MaxVertex.X - MinVertex.X) * 0.5f,
  (MaxVertex.Y - MinVertex.Y) * 0.5f,
  (MaxVertex.Z - MinVertex.Z) * 0.5f
);

FVector Origin (
  (MinVertex.X + Extent.X),
  (MinVertex.Y + Extent.Y),
  (MinVertex.Z + Extent.Z)
);

**Review by bernatx — DISMISSED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3267)* status: all files reviewed, 1 unresolved discussion (waiting on @Axel1092, @doterop, and @marcgpuig)

**Review by doterop — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3267)* status: all files reviewed, 1 unresolved discussion (waiting on @Axel1092, @bernatx, and @marcgpuig)

___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp, line 125 at r2](https://reviewable.io/reviews/carla-simulator/carla/3267#-MGcKfxU1t9JT9oy8rdB:-MGiNEsc7ophjV1-2pYh:beip5m1) ([raw file](https://github.com/carla-simulator/carla/blob/be3a467246aa61309ed9de961a2fa8cf0cac8f4b/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp#L125)):*
<details><summary><i>Previously, bernatx (bernat) wrote…</i></summary><blockquote>

> ```
> // Calculate middle point
>   FVector Origin (
>     (MaxVertex.X + MinVertex.X) * 0.5f,
>     (MaxVertex.Y + MinVertex.Y) * 0.5f,
>     (MaxVertex.Z + MinVertex.Z) * 0.5f
>   );
>   // Calculate box extent
>   FVector Extent (
>     (MaxVertex.X - MinVertex.X) * 0.5f,
>     (MaxVertex.Y - MinVertex.Y) * 0.5f,
>     (MaxVertex.Z - MinVertex.Z) * 0.5f
>   );
> ```
If speed matters here, we could optimize like this. First calculate the extension as it is now, and then get the middle point using the minimum point plus the extension, so we remove three products from the calculation :)

// Calculate box extent
FVector Extent (
  (MaxVertex.X - MinVertex.X) * 0.5f,
  (MaxVertex.Y - MinVertex.Y) * 0.5f,
  (MaxVertex.Z - MinVertex.Z) * 0.5f
);

FVector Origin (
  (MinVertex.X + Extent.X),
  (MinVertex.Y + Extent.Y),
  (MinVertex.Z + Extent.Z)
);



</blockquote></details>

Done! Well spotted.

**Review by bernatx — DISMISSED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3267)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Axel1092 and @marcgpuig)

**Pull request merged**
