### PR TITLE
Remove duplicated instance variable `is_junction`

### PR DESCRIPTION
**Pull request by Kim-mins**
#### Description

Hi team, this pr is minor I think, but can be important for better documentation.

While I was reading the python api documentations, I just found a duplicated instance variable is written.
You may see the image below contains two `is_junction`s.

image

#### Where has this been tested?

I just updated a document for python api.

#### Possible Drawbacks

- - -
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/6702)

### CODE REVIEW

**Review by bernatx — APPROVED** [review]

**Comment by bernatx** [comment]
Thanks

**Comment by bernatx** [comment]
To properly remove that method you should remove that part from the .yml file from where the .md is built.
Do you mean to remove that part from the **carla\PythonAPI\docs\map.yml** file also?
Thanks

**Comment by Kim-mins** [comment]
Hi @bernatx! Thank you for the response!
Well, I also saw the map.yml file you mentioned, but I checked that there's no duplication.
It seems that only the .md file has the duplication.
So I think there's no need to change map.yml file.

**Comment by bernatx** [comment]
But I can see the duplication in the .yml file. Maybe you already removed that? lines 338 and 355, right?

**Comment by Kim-mins** [comment]
Oh, sorry. I checked the map.yml in another branch.
I saw there's a duplication in map.yml file, and I removed it.
Thank you!

**Comment by bernatx** [comment]
Perfect, thank you

**Pull request merged**
