### PR TITLE
Basic build system for Windows

### LINKED ISSUE #976: make PythonAPI error win10
dependencies/include\carla/Buffer.h(325): warning C4267: “参数”: 从“size_t”转换到“carla::Buffer::size_type”，可能丢失数据
source/libcarla/libcarla.cpp(116): warning C4101: “e”: 未引用的局部变量
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.15.26726\include\type_traits(16707566): note: 参见对正在编译的函数 模板 实例化“void MakeCallback::<lambda_95b4ba70dbee63f70695d6205b045391>::operator ()<_Ty>(_Ty) const”的引用
        with
        [
            _Ty=boost::shared_ptr<carla::sensor::SensorData>
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.15.26726\include\functional(1279): note: 参见对正在编译的 类 模板 实例化 "std::_Is_invocable_r<_Ret,_Fx,boost::shared_ptr<T>>" 的引用
        with
        [
            _Ret=void,
            _Fx=MakeCallback::<lambda_95b4ba70dbee63f70695d6205b045391> &,
            T=carla::sensor::SensorData
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.15.26726\include\functional(1277): note: 查看指向正在编译的变量模板“const bool conjunction_v<std::negation<std::is_same<<lambda_95b4ba70dbee63f70695d6205b045391>,std::function<void __cdecl(boost::shared_ptr<carla::sensor::SensorData>)> > >,std::_Is_invocable_r<void,<lambda_95b4ba70dbee63f70695d6205b045391> &,boost::shared_ptr<carla::sensor::SensorData> > >”的引用
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.15.26726\include\functional(1499): note: 参见对正在编译的 别名 模板 实例化 "_Enable_if_callable_t<MakeCallback::<lambda_95b4ba70dbee63f70695d6205b045391>&,std::function<void (boost::shared_ptr<T>)>>" 的引用
        with
        [
            T=carla::sensor::SensorData
        ]
dependencies/include\boost/bind/placeholders.hpp(54): note: 参见对正在编译的 类 模板 实例化 "boost::arg<9>" 的引用
dependencies/include\boost/bind/placeholders.hpp(53): note: 参见对正在编译的 类 模板 实例化 "boost::arg<8>" 的引用
dependencies/include\boost/bind/placeholders.hpp(52): note: 参见对正在编译的 类 模板 实例化 "boost::arg<7>" 的引用
dependencies/include\boost/bind/placeholders.hpp(51): note: 参见对正在编译的 类 模板 实例化 "boost::arg<6>" 的引用
dependencies/include\boost/bind/placeholders.hpp(50): note: 参见对正在编译的 类 模板 实例化 "boost::arg<5>" 的引用
dependencies/include\boost/bind/placeholders.hpp(49): note: 参见对正在编译的 类 模板 实例化 "boost::arg<4>" 的引用
dependencies/include\boost/bind/placeholders.hpp(48): note: 参见对正在编译的 类 模板 实例化 "boost::arg<3>" 的引用
dependencies/include\boost/bind/placeholders.hpp(47): note: 参见对正在编译的 类 模板 实例化 "boost::arg<2>" 的引用
dependencies/include\boost/bind/placeholders.hpp(46): note: 参见对正在编译的 类 模板 实例化 "boost::arg<1>" 的引用
dependencies/include\carla/image/ImageIOConfig.h(81): error C2338: No image format supported, please compile with at least one of LIBCARLA_IMAGE_WITH_PNG_SUPPORT, LIBCARLA_IMAGE_WITH_JPEG_SUPPORT, or LIBCARLA_IMAGE_WITH_TIFF_SUPPORT
dependencies/include\carla/image/ImageIOConfig.h(299): error C2338: Default IO needs to be supported.
dependencies/include\carla/image/ImageIOConfig.h(320): note: 参见对正在编译的 类 模板 实例化 "carla::image::io::detail::io_any<carla::image::io::detail::io_jpeg>" 的引用
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

### LINKED ISSUE #1000: [0.9.1 & 0.9.0] still build error on win10
```
 "C:\carla91\carla\Unreal\CarlaUE4\CarlaUE4.sln" (Standardziel) (1) ->
       "C:\carla91\carla\Unreal\CarlaUE4\Intermediate\ProjectFiles\CarlaUE4.vcxproj" (Standardziel) (2) ->
       (Build Ziel) ->
         c:\program files\epic games\ue_4.19\engine\source\runtime\rhi\public\RHIResources.h(59): error C2039: "_Interl
       ockedCompareExchange": Ist kein Element von "FWindowsPlatformAtomics" [C:\carla91\carla\Unreal\CarlaUE4\Intermed
       iate\ProjectFiles\CarlaUE4.vcxproj]
         c:\program files\epic games\ue_4.19\engine\source\runtime\rhi\public\RHIResources.h(59): error C2665: "_Interl
       ockedCompareExchange": Durch keine der 4 Überladungen konnten alle Argumenttypen konvertiert werden. [C:\carla91
       \carla\Unreal\CarlaUE4\Intermediate\ProjectFiles\CarlaUE4.vcxproj]
         c:\program files\epic games\ue_4.19\engine\source\runtime\rhi\public\RHIResources.h(78): error C2039: "__fasts
       torefence": Ist kein Element von "FWindowsPlatformMisc" [C:\carla91\carla\Unreal\CarlaUE4\Intermediate\ProjectFi
       les\CarlaUE4.vcxproj]
         c:\program files\epic games\ue_4.19\engine\source\runtime\rhi\public\RHICommandList.h(282): error C2039: "_Int
       erlockedIncrement": Ist kein Element von "FWindowsPlatformAtomics" [C:\carla91\carla\Unreal\CarlaUE4\Intermediat
       e\ProjectFiles\CarlaUE4.vcxproj]
         c:\program files\epic games\ue_4.19\engine\source\runtime\rhi\public\RHICommandList.h(282): error C2665: "_Int
       erlockedIncrement": Durch keine der 4 Überladungen konnten alle Argumenttypen konvertiert werden. [C:\carla91\ca
       rla\Unreal\CarlaUE4\Intermediate\ProjectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\Engine\Classes\Engine/Scene.h(1689): error C2039: "G
       etObjectW": Ist kein Element von "TScriptInterface<IBlendableInterface>" [C:\carla91\carla\Unreal\CarlaUE4\Inter
       mediate\ProjectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\Engine\Classes\Engine/Scene.h(1709): error C2039: "G
       etObjectW": Ist kein Element von "TScriptInterface<IBlendableInterface>" [C:\carla91\carla\Unreal\CarlaUE4\Inter
       mediate\ProjectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\CoreUObject\Public\UObject/UObjectIterator.h(37): er
       ror C2660: "GetObjectW": Funktion akzeptiert keine 0 Argumente [C:\carla91\carla\Unreal\CarlaUE4\Intermediate\Pr
       ojectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\CoreUObject\Public\UObject/UObjectIterator.h(45): er
       ror C2660: "GetObjectW": Funktion akzeptiert keine 0 Argumente [C:\carla91\carla\Unreal\CarlaUE4\Intermediate\Pr
       ojectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\CoreUObject\Public\UObject/UObjectIterator.h(128): e
       rror C2660: "GetObjectW": Funktion akzeptiert keine 0 Argumente [C:\carla91\carla\Unreal\CarlaUE4\Intermediate\P
       rojectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\CoreUObject\Public\UObject/UObjectIterator.h(137): e
       rror C2660: "GetObjectW": Funktion akzeptiert keine 0 Argumente [C:\carla91\carla\Unreal\CarlaUE4\Intermediate\P
       rojectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\CoreUObject\Public\UObject/UObjectIterator.h(37): er
       ror C2660: "GetObjectW": Funktion akzeptiert keine 0 Argumente [C:\carla91\carla\Unreal\CarlaUE4\Intermediate\Pr
       ojectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\CoreUObject\Public\UObject/UObjectIterator.h(45): er
       ror C2660: "GetObjectW": Funktion akzeptiert keine 0 Argumente [C:\carla91\carla\Unreal\CarlaUE4\Intermediate\Pr
       ojectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\CoreUObject\Public\UObject/UObjectIterator.h(128): e
       rror C2660: "GetObjectW": Funktion akzeptiert keine 0 Argumente [C:\carla91\carla\Unreal\CarlaUE4\Intermediate\P
       rojectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\CoreUObject\Public\UObject/UObjectIterator.h(137): e
       rror C2660: "GetObjectW": Funktion akzeptiert keine 0 Argumente [C:\carla91\carla\Unreal\CarlaUE4\Intermediate\P
       rojectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\Core\Public\Async/AsyncFileHandle.h(103): error C203
       9: "__faststorefence": Ist kein Element von "FWindowsPlatformMisc" [C:\carla91\carla\Unreal\CarlaUE4\Intermediat
       e\ProjectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\Core\Public\Async/AsyncFileHandle.h(154): error C203
       9: "__faststorefence": Ist kein Element von "FWindowsPlatformMisc" [C:\carla91\carla\Unreal\CarlaUE4\Intermediat
       e\ProjectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\Core\Public\Async/AsyncFileHandle.h(159): error C203
       9: "__faststorefence": Ist kein Element von "FWindowsPlatformMisc" [C:\carla91\carla\Unreal\CarlaUE4\Intermediat
       e\ProjectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\Core\Public\Async/AsyncFileHandle.h(165): error C203
       9: "__faststorefence": Ist kein Element von "FWindowsPlatformMisc" [C:\carla91\carla\Unreal\CarlaUE4\Intermediat
       e\ProjectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\Engine\Classes\Engine/Scene.h(1689): error C2039: "G
       etObjectW": Ist kein Element von "TScriptInterface<IBlendableInterface>" [C:\carla91\carla\Unreal\CarlaUE4\Inter
       mediate\ProjectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\Engine\Classes\Engine/Scene.h(1709): error C2039: "G
       etObjectW": Ist kein Element von "TScriptInterface<IBlendableInterface>" [C:\carla91\carla\Unreal\CarlaUE4\Inter
       mediate\ProjectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\CoreUObject\Public\UObject/UObjectIterator.h(37): er
       ror C2660: "GetObjectW": Funktion akzeptiert keine 0 Argumente [C:\carla91\carla\Unreal\CarlaUE4\Intermediate\Pr
       ojectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\CoreUObject\Public\UObject/UObjectIterator.h(45): er
       ror C2660: "GetObjectW": Funktion akzeptiert keine 0 Argumente [C:\carla91\carla\Unreal\CarlaUE4\Intermediate\Pr
       ojectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\CoreUObject\Public\UObject/UObjectIterator.h(128): e
       rror C2660: "GetObjectW": Funktion akzeptiert keine 0 Argumente [C:\carla91\carla\Unreal\CarlaUE4\Intermediate\P
       rojectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\CoreUObject\Public\UObject/UObjectIterator.h(137): e
       rror C2660: "GetObjectW": Funktion akzeptiert keine 0 Argumente [C:\carla91\carla\Unreal\CarlaUE4\Intermediate\P
       rojectFiles\CarlaUE4.vcxproj]
         UnrealBuildTool : error : UBT ERROR: Failed to produce item: C:\carla91\carla\Unreal\CarlaUE4\Plugins\Carla\Bi
       naries\Win64\UE4-Carla.lib [C:\carla91\carla\Unreal\CarlaUE4\Intermediate\ProjectFiles\CarlaUE4.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targ
       ets(44,5): error MSB3075: Der Befehl ""C:\Program Files\Epic Games\UE_4.19\Engine\Build\BatchFiles\Build.bat" Ca
       rlaUE4 Win64 Development "C:\carla91\carla\Unreal\CarlaUE4\CarlaUE4.uproject" -WaitMutex -FromMsBuild" wurde mit
        dem Code 5 beendet. Stellen Sie sicher, dass Sie zur Ausführung dieses Befehls berechtigt sind. [C:\carla91\car
       la\Unreal\CarlaUE4\Intermediate\ProjectFiles\CarlaUE4.vcxproj]
```

Still getting these build errors.
I read in Fix win32 compilation #988 that you have changed something.
But still, I'm getting these build errors on win10.
What shall I do?

### LINKED ISSUE #1155: Cannot launch on win10 with 0.9.2
I am using CARLA 0.9.2 on win10

I have read the post that some function is only working on Linux, so I am wondering if it is fixed right now.

when building the 0.9.2, I got the following errors
```
 "C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\CarlaUE4.sln" (default target) (1) ->
       "C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Intermediate\ProjectFiles\CarlaUE4.vcxproj" (default target) (2) ->
       (Build target) ->
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\Engine\Classes\Engine/Scene.h(1689): error C2039: 'GetObjectW'
       : is not a member of 'TScriptInterface<IBlendableInterface>' [C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Intermedi
       ate\ProjectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\Engine\Classes\Engine/Scene.h(1709): error C2039: 'GetObjectW'
       : is not a member of 'TScriptInterface<IBlendableInterface>' [C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Intermedi
       ate\ProjectFiles\CarlaUE4.vcxproj]
         c:\program files\epic games\ue_4.19\engine\source\runtime\rhi\public\RHIResources.h(59): error C2039: '_InterlockedCompa
       reExchange': is not a member of 'FWindowsPlatformAtomics' [C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Intermediate
       \ProjectFiles\CarlaUE4.vcxproj]
         c:\program files\epic games\ue_4.19\engine\source\runtime\rhi\public\RHIResources.h(59): error C2665: '_InterlockedCompa
       reExchange': none of the 4 overloads could convert all the argument types [C:\Users\heyd0\Desktop\carla\carla\Unreal\Carla
       UE4\Intermediate\ProjectFiles\CarlaUE4.vcxproj]
         c:\program files\epic games\ue_4.19\engine\source\runtime\rhi\public\RHIResources.h(78): error C2039: '__faststorefence'
       : is not a member of 'FWindowsPlatformMisc' [C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Intermediate\ProjectFiles\
       CarlaUE4.vcxproj]
         c:\program files\epic games\ue_4.19\engine\source\runtime\rhi\public\RHICommandList.h(282): error C2039: '_InterlockedIn
       crement': is not a member of 'FWindowsPlatformAtomics' [C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Intermediate\Pr
       ojectFiles\CarlaUE4.vcxproj]
         c:\program files\epic games\ue_4.19\engine\source\runtime\rhi\public\RHICommandList.h(282): error C2665: '_InterlockedIn
       crement': none of the 4 overloads could convert all the argument types [C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4
       \Intermediate\ProjectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\CoreUObject\Public\UObject/UObjectIterator.h(37): error C2660:
        'GetObjectW': function does not take 0 arguments [C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Intermediate\Project
       Files\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\CoreUObject\Public\UObject/UObjectIterator.h(45): error C2660:
        'GetObjectW': function does not take 0 arguments [C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Intermediate\Project
       Files\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\CoreUObject\Public\UObject/UObjectIterator.h(128): error C2660
       : 'GetObjectW': function does not take 0 arguments [C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Intermediate\Projec
       tFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\CoreUObject\Public\UObject/UObjectIterator.h(137): error C2660
       : 'GetObjectW': function does not take 0 arguments [C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Intermediate\Projec
       tFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\CoreUObject\Public\UObject/UObjectIterator.h(37): error C2660:
        'GetObjectW': function does not take 0 arguments [C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Intermediate\Project
       Files\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\CoreUObject\Public\UObject/UObjectIterator.h(45): error C2660:
        'GetObjectW': function does not take 0 arguments [C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Intermediate\Project
       Files\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\CoreUObject\Public\UObject/UObjectIterator.h(128): error C2660
       : 'GetObjectW': function does not take 0 arguments [C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Intermediate\Projec
       tFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\CoreUObject\Public\UObject/UObjectIterator.h(137): error C2660
       : 'GetObjectW': function does not take 0 arguments [C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Intermediate\Projec
       tFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\Core\Public\Async/AsyncFileHandle.h(103): error C2039: '__fast
       storefence': is not a member of 'FWindowsPlatformMisc' [C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Intermediate\Pr
       ojectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\Core\Public\Async/AsyncFileHandle.h(154): error C2039: '__fast
       storefence': is not a member of 'FWindowsPlatformMisc' [C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Intermediate\Pr
       ojectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\Core\Public\Async/AsyncFileHandle.h(159): error C2039: '__fast
       storefence': is not a member of 'FWindowsPlatformMisc' [C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Intermediate\Pr
       ojectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\Core\Public\Async/AsyncFileHandle.h(165): error C2039: '__fast
       storefence': is not a member of 'FWindowsPlatformMisc' [C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Intermediate\Pr
       ojectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\Engine\Classes\Engine/Scene.h(1689): error C2039: 'GetObjectW'
       : is not a member of 'TScriptInterface<IBlendableInterface>' [C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Intermedi
       ate\ProjectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\Engine\Classes\Engine/Scene.h(1709): error C2039: 'GetObjectW'
       : is not a member of 'TScriptInterface<IBlendableInterface>' [C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Intermedi
       ate\ProjectFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\CoreUObject\Public\UObject/UObjectIterator.h(37): error C2660:
        'GetObjectW': function does not take 0 arguments [C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Intermediate\Project
       Files\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\CoreUObject\Public\UObject/UObjectIterator.h(45): error C2660:
        'GetObjectW': function does not take 0 arguments [C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Intermediate\Project
       Files\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\CoreUObject\Public\UObject/UObjectIterator.h(128): error C2660
       : 'GetObjectW': function does not take 0 arguments [C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Intermediate\Projec
       tFiles\CarlaUE4.vcxproj]
         C:\Program Files\Epic Games\UE_4.19\Engine\Source\Runtime\CoreUObject\Public\UObject/UObjectIterator.h(137): error C2660
       : 'GetObjectW': function does not take 0 arguments [C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Intermediate\Projec
       tFiles\CarlaUE4.vcxproj]
         UnrealBuildTool : error : UBT ERROR: Failed to produce item: C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Plugins\
       Carla\Binaries\Win64\UE4-Carla.lib [C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Intermediate\ProjectFiles\CarlaUE4.
       vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5):
        error MSB3075: The command ""C:\Program Files\Epic Games\UE_4.19\Engine\Build\BatchFiles\Build.bat" CarlaUE4 Win64 Develo
       pment "C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\CarlaUE4.uproject" -WaitMutex -FromMsBuild" exited with code 5.
       Please verify that you have sufficient rights to run this command. [C:\Users\heyd0\Desktop\carla\carla\Unreal\CarlaUE4\Int
       ermediate\ProjectFiles\CarlaUE4.vcxproj]

    0 Warning(s)
    27 Error(s)
```

### PR DESCRIPTION
**Pull request by marcgpuig**
#### Description
A basic build system for Windows.

**This PR provides**
- Support for Python3 (`make PythonAPI`)
- Automated download and build of `zlib` and `libpng` needed in Win
- Now Boost is downloaded from `https` and not from git

**This PR does NOT provides**
- Support for Python2 (not tested really)
- Support for Google Test

Fixes #1000 
Fixes #1155
Fixes #976

#### Full test of functionalities
1. Open a `Visual Studio x64 Native Tools Command Prompt` and navigate to the project folder
1. Remove `carla/Build` folder (if exists)
1. Run `make clean launch`
1. Make a package using the Editor (`File > Package Project > Windows > x64`) and close it
1. Run the generated package (`CarlaUE4.exe`)
1. Run `make PythonAPI`
1. Navigate to the PythonAPI dir (`cd PythonAPI`)
1. Run `python manual_control.py` and record some images (using `r`) to test that everything works as expected

#### Where has this been tested?

  * **Platform(s):** Windows10
  * **Python version(s):** 3.7
  * **Unreal Engine version(s):** 4.21

#### Possible Drawbacks
Credentials problem using `https` (see #647)
I hope this does not break anything on Linux :)

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/1241)

### CODE REVIEW

**Comment by dnovillo-CVC** [comment]
Once I follow all the steps, I receive a message telling me that the Python script cannot find Carla's module. I've double checked everything and it doesn't work either in the UE4 Editor.

**Comment by kedar123pro** [comment]
> 
> 
> Once I follow all the steps, I receive a message telling me that the Python script cannot find Carla's module. I've double checked everything and it doesn't work either in the UE4 Editor.

Same issue

**Comment by ddnnaadna** [comment]
Hi,
I'm trying to build carla-0.9.3 on windows10 platform.
First, I run the "make PythonAPI" command, and get my "carla-0.9.3-py3.6-win-amd64.egg" correctly.
Then,  I try to run "python manual_control.py" and i got the following error message:
Traceback (most recent call last):
  File ".\manual_control.py", line 75, in <module>
    import carla
  File "D:\carla-0.9.3\PythonAPI\carla\__init__.py", line 7, in <module>
    from .libcarla import *
ImportError: DLL load failed: 找不到指定的模块。
Any suggestions?

**Comment by marcgpuig** [comment]
Some people are experiencing the same issue, but nobody found a solution.
It's hard for me to solve the issue without being able to reproduce it. Luckily, in a couple of weeks, @dnovillo-CVC will let me test a bit on his computer and try to solve this.

**Comment by vishal-prgmr** [comment]
What should be the game mode in the worldsettings ? Packaging to Win64 binray just gives a blank screen. Should anything else be done before packaging?

**Comment by vishal-prgmr** [comment]
Make sure to also do the changes discussed in this issue. #1655

**Comment by xwnb** [comment]
> @marcgpuig has come up with a solution temporary by including a zlib.dll into the PythonAPI folder. Everything else works!
> 
> > Reviewed 21 of 21 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/1241#-:-LZfCs625YpqKWO7VnYR:bhxtkwc)_ status: :shipit: complete! all files reviewed, all discussions resolved

When I run spawn_npc.py it also occured the same problem. I have tried clean and relaunch carla that still does not worked. Then I copy zlib.dll to the folder where .py files in. Wow, it works!!!

Platform(s): Windows 10
Python version(s): 3.7
Unreal Engine version(s): 4.24
Carla: 0.9.9

**Pull request merged**
