### PR TITLE
Fix import pipeline crashes and missing semantic tagging

### PR DESCRIPTION
**Pull request by Jazzinghen**
#### Description

 * Changed the import python script to avoid running commands that would crash if no pedestrian navmesh is available.
 * Changed the Move assets commandlet to properly recognize the static meshes and put them in the right folder
 * Changed the Prepare assets for cooking commandlet to not overwrite the correct map with one without the semantic lane data

#### Fixes  

The import pipeline: 

 * Made assumptions on the optional data structures
 * Didn't properly place the static meshes for semantic tagging
 * Generated semantic information, saved the map, deleted the info from the map and then saved the map again

Fixes issues https://github.com/carla-simulator/carla/issues/2332 and https://github.com/carla-simulator/carla/issues/2340

#### Where has this been tested?

  * **Platform(s):** Windows 10 64 bits, Ubuntu Linux 18.04 64 bits
  * **Python version(s):** Python 3.7
  * **Unreal Engine version(s):** 4.22

#### Possible Drawbacks

 * A potential side effect is that the import process now doesn't treat pedestrian nav meshes as necessary, meaning that if someone is expecting it to crash when they are not available the script won't stop.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/2390)

### CODE REVIEW

**Comment by Jazzinghen** [comment]
Branch needed to be synchronized with master and I updated the CHANGELOG as requested.

**Comment by bernatx** [comment]
Thanks Jazzinghen for this Pull Request. I will take a look and review it as soon as I get some time.

**Comment by jeffreykxiao** [comment]
@bernatx I can confirm this fix works for me with RoadRunner. Technically this doesn't change the lack of Windows support for the new importing features, but before I had this fix, I was unable to import opendrive into 0.9.7. I don't know who else on the carla team worked on the import pipeline, maybe @manishthani? If there's anyone else who can help review I would tag them but I don't know 😅

**Comment by bernatx** [comment]
Thanks for the Pull Request.
I have made a commit with some fixes because the Road elements need to be placed in a folder called 'Road' instead of 'Roads', and also I have added the sidewalks elements to be placed on the 'Sidewalk' folder to be semantic.

**Comment by Jazzinghen** [comment]
> Thanks for the Pull Request.
> I have made a commit with some fixes because the Road elements need to be placed in a folder called 'Road' instead of 'Roads', and also I have added the sidewalks elements to be placed on the 'Sidewalk' folder to be semantic.

Oh, great! This allows for even more tagging then?
That's awesome!

**Comment by germanros1987** [comment]
guys!! @bernatx @marcgpuig, did this PR fall through the cracks? I saw a clear LGTM, then why the PR wasn't merged? Please, let's merge this ASAP.

**Pull request merged**
