### PR TITLE
Added lane offset parameter to the TrafficManager

### PR DESCRIPTION
**Pull request by joel-mb**
#### Description

Added `vehicle_lane_offset(actor, offset)` and `global_lane_offset(offset)` methods to the traffic manager.

These methods allow to set a lane offset displacement from the centre line. Positive values imply a right offset while negative ones mean a left one. Default is `0`. Numbers high enough to cause the vehicle to drive through other lanes might break the controller.

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04
  * **Python version(s):** 3.7
  * **Unreal Engine version(s):** CARLA

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5601)

### CODE REVIEW

**Review by joel-mb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5601)* status: 15 of 16 files reviewed, 2 unresolved discussions (waiting on @glopezdiest and @MattRowe18)

___
*[`LibCarla/source/carla/trafficmanager/MotionPlanStage.cpp` line 163 at r1](https://reviewable.io/reviews/carla-simulator/carla/5601#-N7LQBuZ1VjIGJD7XEP7:-N7M-yU2E8MDE5X4sHX0:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/778f6708319816c91f789ead5d407bac5d4a591c/LibCarla/source/carla/trafficmanager/MotionPlanStage.cpp#L163)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

whitespaces
</blockquote></details>

Done.
___
*[`LibCarla/source/carla/trafficmanager/MotionPlanStage.cpp` line 168 at r1](https://reviewable.io/reviews/carla-simulator/carla/5601#-N7LQEP50bot0hLrkxcc:-N7M-ymw3D3jCuCVjX3_:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/778f6708319816c91f789ead5d407bac5d4a591c/LibCarla/source/carla/trafficmanager/MotionPlanStage.cpp#L168)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

whitespaces
</blockquote></details>

Done.

**Review by glopezdiest — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5601)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MattRowe18)

**Review by glopezdiest — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5601)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MattRowe18)

**Review by MattRowe18 — APPROVED** [review]

**Review by glopezdiest — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5601)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @joel-mb)

**Pull request merged**
