### PR TITLE
sergi-e/python2-note

### PR DESCRIPTION
**Pull request by sergi-e**
#### Description

- Added prerequirement on ROS bridge installation. Python2 compilation will be needed in CARLA 0.9.10 and later if using ROS Kinetic or Melodic. 
- Added notes in Quickstart and build installation pages for optional Python2 compilation.

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04.4
  * **Python version(s):** 3.6.9
  * **Unreal Engine version(s):** 4.24

#### Possible drawbacks

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3309)

### CODE REVIEW

**Review by joel-mb — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3309)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @joel-mb and @sergi-e)

___
*[Docs/build_windows.md, line 57 at r1](https://reviewable.io/reviews/carla-simulator/carla/3309#-MHWRCWh6DOlLHSuFKBH:-MHWRCWi5m8RL9cQnPZ3:b-hswmfj) ([raw file](https://github.com/carla-simulator/carla/blob/5da13986b727ed6953d249f5bbbe5d5451ab2b6f/Docs/build_windows.md#L57)):*
> ```
> make PythonAPI ARGS="--python-version=2"
> ```
This is not working on Windows. The PythonAPI will be built based on the installed Python version. @axel1092 can you confirm that this is correct?
___
*[Docs/build_windows.md, line 168 at r1](https://reviewable.io/reviews/carla-simulator/carla/3309#-MHWRm6X7qpAkw74YOlS:-MHWRm6X7qpAkw74YOlT:bji21ee) ([raw file](https://github.com/carla-simulator/carla/blob/5da13986b727ed6953d249f5bbbe5d5451ab2b6f/Docs/build_windows.md#L168)):*
> ```
> make PythonAPI ARGS="--python-version=2"
> ```
same as above
___
*[Docs/ros_installation.md, line 26 at r1](https://reviewable.io/reviews/carla-simulator/carla/3309#-MHWQdYJ2pVX6Clgu-dq:-MHWQdYJ2pVX6Clgu-dr:b-5w0zuk) ([raw file](https://github.com/carla-simulator/carla/blob/5da13986b727ed6953d249f5bbbe5d5451ab2b6f/Docs/ros_installation.md#L26)):*
> ```
> In order to compile the necessary `.egg` file of the PythonAPI for Python2, run the following command in the root CARLA directory.
> ```
We should state that they need to compile CARLA from source. For packages or deb packages, the command is not working.
___
*[Docs/start_quickstart.md, line 52 at r1](https://reviewable.io/reviews/carla-simulator/carla/3309#-MHWSZ043gUJJNbBnjjG:-MHWSZ043gUJJNbBnjjH:bbu1uq3) ([raw file](https://github.com/carla-simulator/carla/blob/5da13986b727ed6953d249f5bbbe5d5451ab2b6f/Docs/start_quickstart.md#L52)):*
> ```
> # Optionally, to compile the PythonAPI for Python2, run the following command in the root CARLA directory.
> make PythonAPI ARGS="--python-version=2"
> ```
This is only working when building from source. For debian packages and packages this doesn't work. This should be removed.
___
*[Docs/start_quickstart.md, line 160 at r1](https://reviewable.io/reviews/carla-simulator/carla/3309#-MHWSlEc0pXUkIQZ9ZOW:-MHWSlEc0pXUkIQZ9ZOX:bxks4bk) ([raw file](https://github.com/carla-simulator/carla/blob/5da13986b727ed6953d249f5bbbe5d5451ab2b6f/Docs/start_quickstart.md#L160)):*
> ```
> Optionally, to compile the PythonAPI for Python2, run the following command in the root CARLA directory.
> ```sh
> make PythonAPI ARGS="--python-version=2"
> ```
same as above.

**Review by sergi-e — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3309)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @joel-mb and @sergi-e)

___
*[Docs/build_windows.md, line 57 at r1](https://reviewable.io/reviews/carla-simulator/carla/3309#-MHWRCWh6DOlLHSuFKBH:-MHe_umFBvpitYYrWOYj:bn7qusn) ([raw file](https://github.com/carla-simulator/carla/blob/5da13986b727ed6953d249f5bbbe5d5451ab2b6f/Docs/build_windows.md#L57)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> make PythonAPI ARGS="--python-version=2"
> ```
This is not working on Windows. The PythonAPI will be built based on the installed Python version. @axel1092 can you confirm that this is correct?
</blockquote></details>

Deleted for now and added a note
___
*[Docs/build_windows.md, line 168 at r1](https://reviewable.io/reviews/carla-simulator/carla/3309#-MHWRm6X7qpAkw74YOlS:-MHe_x1453pPZvC_TTzP:bn7qusn) ([raw file](https://github.com/carla-simulator/carla/blob/5da13986b727ed6953d249f5bbbe5d5451ab2b6f/Docs/build_windows.md#L168)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> make PythonAPI ARGS="--python-version=2"
> ```
same as above
</blockquote></details>

Deleted for now and added a note
___
*[Docs/ros_installation.md, line 26 at r1](https://reviewable.io/reviews/carla-simulator/carla/3309#-MHWQdYJ2pVX6Clgu-dq:-MHegqMi2oThz_fhf6Rg:b-lx4f4g) ([raw file](https://github.com/carla-simulator/carla/blob/5da13986b727ed6953d249f5bbbe5d5451ab2b6f/Docs/ros_installation.md#L26)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> In order to compile the necessary `.egg` file of the PythonAPI for Python2, run the following command in the root CARLA directory.
> ```
We should state that they need to compile CARLA from source. For packages or deb packages, the command is not working.
</blockquote></details>

Fixed? 
___
*[Docs/start_quickstart.md, line 52 at r1](https://reviewable.io/reviews/carla-simulator/carla/3309#-MHWSZ043gUJJNbBnjjG:-MHe_XChAOylueL30gtw:bs7wubq) ([raw file](https://github.com/carla-simulator/carla/blob/5da13986b727ed6953d249f5bbbe5d5451ab2b6f/Docs/start_quickstart.md#L52)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> # Optionally, to compile the PythonAPI for Python2, run the following command in the root CARLA directory.
> make PythonAPI ARGS="--python-version=2"
> ```
This is only working when building from source. For debian packages and packages this doesn't work. This should be removed.
</blockquote></details>

Done! 
___
*[Docs/start_quickstart.md, line 160 at r1](https://reviewable.io/reviews/carla-simulator/carla/3309#-MHWSlEc0pXUkIQZ9ZOW:-MHe_Y6f8wfhLN2RJoVc:bs7wubq) ([raw file](https://github.com/carla-simulator/carla/blob/5da13986b727ed6953d249f5bbbe5d5451ab2b6f/Docs/start_quickstart.md#L160)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> Optionally, to compile the PythonAPI for Python2, run the following command in the root CARLA directory.
> ```sh
> make PythonAPI ARGS="--python-version=2"
> ```
same as above.
</blockquote></details>

Done!

**Review by joel-mb — COMMENTED** [review]
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3309)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @joel-mb and @sergi-e)

___
*[Docs/ros_installation.md, line 37 at r2](https://reviewable.io/reviews/carla-simulator/carla/3309#-MHqx_VY08s3hQlPYeXG:-MHqx_VY08s3hQlPYeXH:b276b6b) ([raw file](https://github.com/carla-simulator/carla/blob/c940cf8889fb0a42133daca6bb0802b0f079a8e2/Docs/ros_installation.md#L37)):*
> ```
> *   __Windows__ — The PythonAPI will be built based on the installed Python version. If the system runs with Python2, the PythonAPI will be compiled properly. ·
> ```
I would remove this. Although ros can be executed on windows is not the target platform.

**Review by sergi-e — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3309)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @joel-mb and @sergi-e)

___
*[Docs/ros_installation.md, line 37 at r2](https://reviewable.io/reviews/carla-simulator/carla/3309#-MHqx_VY08s3hQlPYeXG:-MHrCWOG4fanIqrKMdGt:b-h37b58) ([raw file](https://github.com/carla-simulator/carla/blob/c940cf8889fb0a42133daca6bb0802b0f079a8e2/Docs/ros_installation.md#L37)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> *   __Windows__ — The PythonAPI will be built based on the installed Python version. If the system runs with Python2, the PythonAPI will be compiled properly. ·
> ```
I would remove this. Although ros can be executed on windows is not the target platform. 
</blockquote></details>

I have mixed feelings about this. The major part of the CARLA users rely on Windows, don't they?

**Review by joel-mb — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3309)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @joel-mb)

**Pull request merged**
